espressif/arduino-esp32

tools/get.py

Added a new requirement ( pip install request ) and some logic to get it working, I won't blame you if you reject this PR but this is what made it work on my machine

(Real) fix for cygwinless win10 TLS error

---

doc/windows.md

Forgot to mention the extra `pip install requests` in the ReadMe and saw issue #134

Followup to PR #126

---

libraries/WiFi/examples/SimpleWiFiServer/SimpleWiFiServer.ino

I just ported the example from arduino to sparkfun esp 32

Add (ported) SimpleWiFiServer

---

libraries/SD/README.md

It's look more a practical guide "how to use SD lib"
Maybe host the images in github is a good idea
Feel free to edit anything

SD library explanation

---

libraries/ESP32/examples/AnalogOut/LEDCSoftwareFade/LEDCSoftwareFade.ino

Remove LEDC_BASE_FREQ to calculate duty

---

libraries/WiFi/examples/WiFiTelnetToSerial/WiFiTelnetToSerial.ino
libraries/WiFi/src/WiFiServer.cpp
libraries/WiFi/src/WiFiServer.h

WiFiTelnetToSerial is also a test for hasClient().

Add WiFiServer hasClient and WiFiTelnetToSerial example

---

doc/windows.md

As requested in #439 even if it is a rare occurrence that the user will have a custom sketchbook directory.

Add for if user has custom sketchbook directory

---

libraries/ESP32/examples/DeepSleep/ExternalWakeUp/ExternalWakeUp.ino
libraries/ESP32/examples/DeepSleep/TimerWakeUp/TimerWakeUp.ino
libraries/ESP32/examples/DeepSleep/TouchWakeUp/TouchWakeUp.ino

*Added a Timer wakeup example
*Added a Touch wakeup example
*Added an external source wakeup example

ESP32: Add DeepSleep examples

---

libraries/SimpleBLE/examples/SimpleBleDevice/SimpleBleDevice.ino

I was a little confused reading what this sketch did the first time so I attempted to edit these for clarity.

Edit comments for clarity

---

ISSUE_TEMPLATE.md

It suggests to the user fill some information that may help solve the issue.
For test, create an issue here: https://github.com/copercini/arduino-esp32/issues/new

Create Issue template

---

libraries/WiFi/src/WiFiScan.cpp

Fix for issue #573

---

cores/esp32/HardwareSerial.cpp
cores/esp32/HardwareSerial.h

usefull for ESP8266 compatibility

Add baudRate function

---

platform.txt

Link cxx_guards from IDF libcxx not from libstdc++

---

cores/esp32/Esp.cpp

https://www.esp32.com/viewtopic.php?f=2&t=1358&sid=f77cd62ec254317f3bbb30d8ab75ca2a&start=10

Chip revision fix

---

cores/esp32/Arduino.h
cores/esp32/esp8266-compat.h

As suggested in https://github.com/espressif/arduino-esp32/pull/760

Add compatibility macros with esp8266

---

variants/heltec_wifi_lora_32/pins_arduino.h

Based on http://esp32.net/images/Heltec/WIFI-LoRa-32/Heltec_WIFI-LoRa-32_DiagramPinoutFromBottom.jpg

Fix Heltec Wifi-LoRa kit pinout

---

libraries/WiFiClientSecure/src/ssl_client.cpp

This reduce net_would_block calls and CPU utilization

Reduce net_would_block calls in handshake verification

---

libraries/HTTPClient/src/HTTPClient.cpp

fix for https://github.com/espressif/arduino-esp32/issues/740

Feed WDT in HttpClient

---

cores/esp32/esp32-hal-gpio.c

fix enable ADC on gpio37,38
gpio37,38 will enable when make this change.

fix enable ADC on pin37,38

---

variants/nina_w10/pins_arduino.h

This fixes the compile error when we include SPI.h

Added missing include stdint.h for NINA W10 

---

libraries/WiFi/src/WiFiGeneric.cpp

fix event reason logging > 176

---

boards.txt

Should we add this declaration option for all boards?

Add Core Debug Level for WeMosBat

---

boards.txt

Changed Flashmode to DIO due board only supports DIO

Corrected Flash Mode

---

boards.txt

Add upload.maximum_size directives to boards.txt

---

cores/esp32/esp32-hal-i2c.c

incorrect optimization for debugging tick markers.

fix debug optimization

---

variants/esp32-gateway/pins_arduino.h

Added IIC pins. I can confirm that this is working!

Added IIC pins

---

tools/platformio-build.py

See http://docs.platformio.org/en/latest/platforms/espressif32.html#partition-tables

Custom Partition Tables for @PlatformIO

---

tools/platformio-build.py

Calculate an absolute path for a custom partitions table

---

variants/esp32-gateway/pins_arduino.h

Added SPI bus pins and tested them as well
@me-no-dev

Added SPI bus pins

---

libraries/ESP32/examples/ESPNow/Basic/Master/Master.ino
libraries/ESP32/examples/ESPNow/Basic/Slave/Slave.ino
libraries/ESP32/examples/ESPNow/Multi-Slave/Master/Master.ino
libraries/ESP32/examples/ESPNow/Multi-Slave/Slave/Slave.ino

Added WiFi.disconnect to ESPNow examples. Fixes https://github.com/espressif/arduino-esp32/issues/1425

Added WiFi.disconnect to ESPNow examples.

---

tools/build-release.sh
tools/deploy.sh

fixes and updates for better cooperation with GHUI

Arduino-Esp32 release deployment comprehensive update

---

docs/arduino-ide/debian_ubuntu.md

Changed Adruino direcgtory path because it was explanation directory for mac

Update Arduino/hardware path

---

libraries/WiFi/examples/WiFiClientEnterprise/README.md

Short document - instructions about  WifiClientEnterprise.ino sketch

Informations about WifiClientEnterprise.ino sketch

---

variants/bpi-bit/pins_arduino.h

our board hardware have changed and Fixed previous error

Fixed previous error

---

libraries/HTTPClient/src/HTTPClient.cpp

Getting weather data from wunderground, I got stuck in an endless loop in HTTPClient.getString()
Others seem to have the same problem:
https://forum.arduino.cc/index.php?topic=533282.0

leave possible endless loop

---

libraries/WiFiClientSecure/examples/WiFiClientSecureEnterprise/WiFiClientSecureEnterprise.ino

Hello, I have tested connection to Eduroam and connection to HTTPS webserver on internet over WifiClientSecure example. Worked fine, no problem.
Tested under Devkit DOIT v1 and Devkitc v4.

Working example for HTTPS over Eduroam network - WifiClient secure library

---

libraries/HTTPClient/examples/HTTPClientEnterprise/HTTPClientEnterprise.ino

Working example for HTTPClient library on Enterprise network.
Worked for HTTP and HTTPS connections too with Root CA certificate.
Tested under Eduroam network with board Devkit v1 DOIT, Devkitc v4.
Arduino core from June 2018.

HTTPClientEnterprise example

---

cores/esp32/HardwareSerial.cpp

Resolves https://github.com/espressif/arduino-esp32/issues/2100

Prevent ESP-IDF component compilation errors

---

libraries/WiFi/src/WiFiMulti.cpp

My mistake , I should not use copy and paste...

Use right function for BSSID

---

libraries/HTTPUpdate/examples/httpUpdate/httpUpdate.ino
libraries/HTTPUpdate/src/HTTPUpdate.cpp

Abort update if http.begin() returns false. 
Fix a typo in httpUpdate.ino

Small improvements on HTTPUpdate

---

cores/esp32/Esp.cpp
cores/esp32/Esp.h
libraries/HTTPUpdate/src/HTTPUpdate.cpp

Replaces #2164. Review comments by @me-no-dev processed.

Add MD5 to Esp and MD5 request header to HTTPUpdate

---

platform.txt

update platform.txt for Arduino IDE issue

---

libraries/WiFi/src/WiFiGeneric.cpp

Fixes https://github.com/espressif/arduino-esp32/issues/1595

Increase _network_event_task priority

---

boards.txt
variants/turta_iot_node/pins_arduino.h

Added support for Turta IoT Node board. https://www.turta.io/iotnode

Add Turta IoT Node Board

---

variants/t-beam/pins_arduino.h

DAC2 is not wired, only DAC1 is -> corrected
LORA pins 27 + 19 are only wired on pcb, but not connected to header -> deleted
Button and LED added

Board T-Beam: Update pins_arduino.h

---

libraries/WebServer/examples/FSBrowser/FSBrowser.ino

default FORMAT_FILESYSTEM to false in FSBrowser.ino

---

cores/esp32/esp32-hal-i2c.c

@tread-Qualitrol discovered this error.

Fix compile warning, esp32-hal-i2c.c

---

libraries/WiFi/src/WiFiMulti.cpp

Disconnect WiFi if it is connected to network other than the given APlist .

connect only to provided creds

---

boards.txt
variants/frog32/pins_arduino.h

[FrogBoard](https://www.tindie.com/products/fred_IOT/esp32s-esp-wroom32-frogopins-development-board/)
We know its bare ESP32 module development board, but lot of user (mostly newbies) started asking how to work with it and they are little confused what board they should select in Arduino IDE, so having "own" definition would be nice especially for less experienced users.
BTW is there support to add own Example sketches to the definitions? 
Thank you in advance!

Frog Board ESP32 definition

---

boards.txt

Also works for the ESP-EYE v2.1

Add ESP32-CAM board

---

cores/esp32/esp32-hal-rmt.h

Added rmtDeinit to header. Fixes #2585

Added rmtDeinit to header. Fixes #2585

---

boards.txt
variants/m5stick_c/pins_arduino.h

Added support for M5Stick-C board, Change upload Speed
Project link https://docs.m5stack.com/#/en/core/m5stickc

Add M5Stick-C Board

---

libraries/FS/src/vfs_api.cpp

https://github.com/espressif/arduino-esp32/issues/1293

workaround for FS implementations that do not support fflush()

---

libraries/HTTPClient/src/HTTPClient.cpp
libraries/HTTPClient/src/HTTPClient.h

In addition to the existing GET, POST, PUT,... methods, I have added a PATCH call, so that RESTful APIs with the respective functionality can be accessed more easily.

Added PATCH request to HTTPClient

---

boards.txt
variants/sparkfun_lora_gateway_1-channel/pins_arduino.h

See also: https://learn.sparkfun.com/tutorials/sparkfun-lora-gateway-1-channel-hookup-guide/all

Add board "SparkFun LoRa Gateway 1-Channel".

---

boards.txt

Added Flash mode and Flash speed menu settings for TinyPICO
Also set Flash mode default to QIO

Added more menu settings for TinyPICO

---

docs/platformio.md

[doc] links http -> https

---

cores/esp32/esp32-hal-uart.c

Uart HAL flush is inconsitent. It misses RX Queue flush. Fix dat

Flush UART RX queue too

---

cores/esp32/Client.h

Fixes https://github.com/espressif/arduino-esp32/issues/2755

Remove extra connects from Client.h

---

libraries/SPI/src/SPI.cpp
libraries/SPI/src/SPI.h

fixes: https://github.com/espressif/arduino-esp32/issues/3241

Change the first argument of SPI::wrteBytes to be const

---

libraries/WiFi/src/WiFiScan.h

Add an accessor function for the useful wifi data

Allow access to useful information in WiFiScan.h

---

libraries/ESP32/examples/Camera/CameraWebServer/CameraWebServer.ino
libraries/ESP32/examples/Camera/CameraWebServer/camera_pins.h

Added pinout for TTGO T Journal device and improved the intent of comments.

Add TTGO T Journal Camera module & improve commenting

---

libraries/WiFi/src/WiFiClient.cpp

Reverts espressif/arduino-esp32#3680

Revert "std::shared_ptr Memory Leak"

---

boards.txt
variants/handbit/pins_arduino.h

Handbit is made by Labplus ,it's a useful ESP32 board for students and teachers to make  anything.
Here is more info about  Handbit
[Handbit wiki](https://mpython.readthedocs.io/zh/master/board/index.html)

add new board Handbit 

---

variants/m5stack_atom/pins_arduino.h

Update atom board pins_arduino.h

---

libraries/WiFi/src/WiFiMulti.cpp

Fixes #3729 typo in WifiMulti log message.

fix typo in WiFiMulti

---

cores/esp32/Arduino.h

F_CPU is fixed at 240MHz.
In the case of other frequencies, the pulseIn function, etc. is not right.
```c
#define clockCyclesPerMicrosecondFix() ( (long int)getCpuFrequencyMhz() )
#define clockCyclesToMicrosecondsFix(a) ( (a) / clockCyclesPerMicrosecondFix() )
#define microsecondsToClockCyclesFix(a) ( (a) * clockCyclesPerMicrosecondFix() )
void setup() {
delay(100);
// It's OK
setCpuFrequencyMhz(240);
Serial.printf("clockCyclesPerMicrosecond() : %ld\n", clockCyclesPerMicrosecond() );
Serial.printf("clockCyclesToMicroseconds(240) : %ld\n", clockCyclesToMicroseconds(240) );
Serial.printf("microsecondsToClockCycles(1) : %ld\n\n", microsecondsToClockCycles(1) );
// NG
setCpuFrequencyMhz(160);
Serial.printf("clockCyclesPerMicrosecond() : %ld\n", …
```

Fix clockCyclesPerMicrosecond Change from fixed value to current value

---

variants/honeylemon/pins_arduino.h

Update HONEYLemon -> pins_arduino.h

Update HONEYLemon -> pins_arduino.h 

---

boards.txt
variants/esp32thing_plus/pins_arduino.h

Please add the [SparkFun ESP32 Thing Plus](https://www.sparkfun.com/products/15663) board.
Thanks! :D

Added SparkFun ESP32 Thing Plus board

---

libraries/WiFi/src/ETH.cpp

I know you will port this esp32-s2 fork to ESP32 IDF v4.2 too, so here is an Ethernet fix

Makes ethernet get an IP when connected

---

boards.txt
variants/micro_s2/pins_arduino.h

Added esp32s2 based microS2 dev board.

Added board - microS2

---

libraries/BLE/src/BLERemoteCharacteristic.cpp

Don't convert to null-terminated string prior to writeValue

---

libraries/SPI/src/SPI.h

Small description comment correction

---

libraries/WebServer/examples/PathArgServer/PathArgServer.ino
libraries/WebServer/src/Uri.h

Fixes #4374
Same as for ESP8622 https://github.com/esp8266/Arduino/pull/7105

Add flash helper constructor to Uri

---

cores/esp32/Udp.h

https://github.com/arduino/ArduinoCore-sam/pull/6/files
It is used here:
https://github.com/arduino-libraries/ArduinoMDNS/blob/master/MDNS.cpp#L150

Add virtual beginMulticast(...) stub to UDP class

---

libraries/HTTPClient/src/HTTPClient.cpp

..because a firstLine = false; is missing ;)

Fix BUG: Parsing of first line fails

---

libraries/HTTPClient/src/HTTPClient.cpp

HttpClient uses Serial.printf()

---

cores/esp32/Arduino.h

Fixes https://github.com/espressif/arduino-esp32/issues/4466

fixes #4466

---

boards.txt
variants/adafruit_magtag29_esp32s2/pins_arduino.h
variants/adafruit_metro_esp32s2/pins_arduino.h

add 2 variants

---

tools/platformio-build-esp32.py
tools/platformio-build-esp32s2.py

Propagate changes on master branch from https://github.com/espressif/arduino-esp32/pull/4538

Allow custom variants directory

---

libraries/SPI/src/SPI.cpp

Fix logic in SPIClass::setHwCs.

---

cores/esp32/esp32-hal-uart.c

Fixes #4568 .  I am unable to test, as I don't know how to create the race condition.

Possible race condition in uart_AttachRx

---

cores/esp32/Print.h

added availableForWrite to Print.h to make compatible with Arduino Print.h

availableForWrite

---

libraries/HTTPUpdate/src/HTTPUpdate.cpp
libraries/HTTPUpdate/src/HTTPUpdate.h

This is a mirror of a change in esp8266 needed to update with a url that redirects.

Update HTTPUpdate to add setFollowRedirects

---

libraries/WiFi/src/WiFiClient.cpp

Replace bzero and bcopy with memset and memcpy.

[2.0.0] Update WiFiClient.cpp

---

libraries/WiFiClientSecure/src/ssl_client.cpp

[2.0.0] Update ssl_client.cpp

---

boards.txt
tools/partitions/rainmaker.csv

It adds the **fctry** partition needed for ESP RainMaker.

[2.0.0] Add custom partition for ESP RainMaker.

---

boards.txt
variants/esp32s2thing_plus/pins_arduino.h

Dear Espressif,
Please accept our pull request to add Arduino IDE support for our new hardware, The SparkFun ESP32-S2 Thing Plus.
Let us know if there is anything more we can do to help.
Cheers and thank you very much!
Pete Lewis
SparkFun Electronics

[2.0.0] SparkFun ESP32-S2 Thing Plus support

---

boards.txt

Still finding missing bits for the tinys2 board definition :(

---

boards.txt

add board KB32-FT in boards.txt

---

CONTRIBUTING.rst

Adding of basic Contributing.rst file. Contributing file will be updated after adding more guides into docs folder.  (Example guide e.g)

Add files via upload - CONTRIBUTING.rst

---

boards.txt

Bugfix for Heltec boards definition.

Bug fix for Heltec boards definition

---

cores/esp32/Arduino.h
cores/esp32/WMath.cpp

Fix makeWord parameter types in Arduino.h and WMath.cpp

---

.github/stale.yml

Second Update stale.yml

---

cores/esp32/esp32-hal-uart.c

fix UART FIFO test for being full

---

cores/esp32/esp32-hal-uart.c

Fixes Serial.end() hanging on ESP32-S2

---

cores/esp32/esp32-hal-adc.c

Fixes: https://github.com/espressif/arduino-esp32/issues/5503

Fix wrong attenuation being set to pins

---

variants/ET-Board/pins_arduino.h

ET-Board
No internal LED pin
Missing internal LED pin have been added to this commit.

Add ET-Board BUILTIN_LED pin

---

boards.txt
variants/um_feathers2neo/pins_arduino.h

As title states, just adding my newest FeatherS2 Neo board to the boards list with the appropriate variants folder.

Added UM FeatherS2 Neo to boards.txt and variants folder

---

docs/source/getting_started.rst

Supported SoC table updated due the v2.0.0 release.
None.

Supported devices table updated due the 2.0.0 release

---

cores/esp32/Stream.cpp

Fix double promotion in Stream::parseFloat()

---

cores/esp32/esp32-hal-ledc.c
cores/esp32/esp32-hal.h

Add basic analogWrite support based on LEDC

---

platform.txt

https://github.com/espressif/arduino-esp32/pull/5854
I misplaced the additions.
----------------------------------------------------------------------------------------------------------------------------------------------------
This entire section can be deleted if all items are checked.
1. [x] Please provide specific title of the PR describing the change, including the component name (eg."Update of Documentation link on Readme.md")
----------------------------------------------------------------------------------------------------------------------------------------------------
Support the precompiled library
None. Empty …

Fix compiler.libraries.ldflags Option

---

boards.txt
libraries/RainMaker/examples/RMakerSonoffDualR3/RMakerSonoffDualR3.ino
variants/sonoff_dualr3/pins_arduino.h

Added [Sonoff DUALR3](https://sonoff.tech/product/diy-smart-switch/dualr3/) support with RainMaker example.
None

[Feature] Added Sonoff DUALR3 support with RainMaker example

---

boards.txt
variants/um_feathers3/pins_arduino.h
variants/um_pros3/pins_arduino.h
variants/um_tinys3/pins_arduino.h

Added board definitions for my new ESP32-S3 based development boards
Should have no impact on development
There are my new boards...
https://youtu.be/bIm1ofpL6FY

Added my new Unexpected Maker ESP32-S3 boards

---

libraries/WebServer/src/WebServer.h

I have added a comment and changed a confusing argument name in WebServer.h after lots of research to understand what it is.
Briefly,
server.on(url, func1, func2) takes two function. I wrote purpose of the second function.
onFileUpload(func2) takes only a function. But to be consistent with first change, I changed its name.

added explanatory comments to WebServer.h

---

tools/platformio-build-esp32s3.py

Bootloader is at 0x0000 for S3

---

libraries/WiFiClientSecure/src/ssl_client.cpp

Info: https://github.com/espressif/arduino-esp32/commit/b69b44a93d80deb5f489b8782dd1f9168ab5edd6#commitcomment-66165077

Support the updated MbedTLS in ESP-IDF v4.4

---

docs/source/installing.rst

This PR is deleting outdated note about chips support.
Link to Soc's support page is provided to make maintaining of Installing.rst page more easy.
N/A
N/A

Installing.rst_update

---

boards.txt
variants/lolin_s2_mini/pins_arduino.h

add lolin s2 mini board def

---

docs/source/api/dac.rst

Documentation for DAC peripheral.

[Docs] DAC API documentation

---

boards.txt
variants/deneyapkart1A/pins_arduino.h

1. [ ] Please provide specific title of the PR describing the change, including the component name (eg. *„Update of Documentation link on Readme.md“*)
2. [ ] Please provide related links (eg. Issue, other Project, submodule PR..)
3. [ ] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)
-----------

Add new board (Deneyap Kart 1A)

---

boards.txt
variants/lolin_s2_pico/pins_arduino.h

add lolin s2 pico board def

---

boards.txt
libraries/WiFi/examples/WiFiScanDualAntenna/WiFiScanDualAntenna.ino
libraries/WiFi/src/WiFiGeneric.cpp
libraries/WiFi/src/WiFiGeneric.h
variants/esp32da/pins_arduino.h

Added the ESP32-WROOM-DA module to the `boards.txt`
None

Added ESP32-WROOM-DA module to boards.txt

---

.github/workflows/publish.yml

Remove the debug job and fix an error in the workflow.
No impact on any of the working workflows.
N/A

publish.yml: Remove the debug job and fix an error in the workflow.

---

variants/adafruit_feather_esp32s2_tft/variant.cpp

add some power pin setups for adafruit feather esp32s2 tft
only affects adafruit hardware board :)

add variant init code for the feather s2 tft

---

libraries/WebServer/examples/SDWebServer/SdRoot/edit/index.htm

Fixing path to the files in edit mode.
Needs to be changed according to SD changes from 1.0.6 to 2.0.0.
None.
Closes #6488

SDWebServer example fix for 2.x.x versions

---

libraries/Update/src/HttpsOTAUpdate.h

Error on compile Arduino as an ESP-IDF component
1. [x ] Please provide specific title of the PR describing the change, including the component name (eg. *„Update of Documentation link on Readme.md“*)
2. [ x] Please provide related links (eg. Issue, other Project, submodule PR..)
3. [ x] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)
-----------
coude not compile on esp-idf
add #ifndef and #endif

Compiler error

---

cores/esp32/esp32-hal-i2c-slave.c

Fixes: https://github.com/espressif/arduino-esp32/issues/5907

Fix onRequest being called for every slave address

---

.github/workflows/upload-idf-component.yml

Fix the upload-idf-component workflow.
CI
PRs are having the following error: https://github.com/espressif/arduino-esp32/actions/runs/2344218674
Full list: https://github.com/espressif/arduino-esp32/actions/workflows/upload-idf-component.yml

workflows/upload-idf-component.yml: Fix the wildcard.

---

cores/esp32/esp32-hal-i2c-slave.c

Fixes: https://github.com/espressif/arduino-esp32/issues/6677

Fix fail to set single byte that contains the slave address

---

.github/ISSUE_TEMPLATE/Issue-report.yml

Added 2.0.4 version to Issue template.

Add 2.0.4 version to Issue report template

---

boards.txt
variants/Bee_Motion/pins_arduino.h
variants/Bee_Motion_Mini/pins_arduino.h
variants/Bee_Motion_S3/pins_arduino.h
variants/Bee_S3/pins_arduino.h

tested all boards in 2.0.4 and working as intended.

Added Smart Bee Design Boards

---

boards.txt
variants/m5stack_station/pins_arduino.h

M5Station related [documents](https://docs.m5stack.com/en/core/station_485)

Create M5Station pins_arduino.h and M5Station Board

---

.github/scripts/on-push.sh

to complete the test of Esptool v4.2.1 for all scenarios.
@me-no-dev 
-----------
Please describe on what …

Esptool v4.2.1 for CI Platformio

---

boards.txt
variants/wifiduino32s3/pins_arduino.h
variants/wifiduinov2/pins_arduino.h

add boards WiFiduinoV2&WiFiduino32S3
can compiles and build projects.

add boards WiFiduinoV2&WiFiduino32S3

---

.github/ISSUE_TEMPLATE/Issue-report.yml

Update of Issue template with addition of new version 2.0.5.
N/A
N/A

Add v2.0.5 into Issue Template

---

libraries/WiFi/examples/SimpleWiFiServer/SimpleWiFiServer.ino

-----------
Removed unused variable.
(*eg. I have tested my Pull …

[SimpleWiFiServer] Remove unused variable

---

docs/source/conf.py

This PR will be necessary for the 2.0.6 release and update the core version in the documentation.
N/A
N/A

Release version update to 2.0.6 in the Docs

---

.github/ISSUE_TEMPLATE/Issue-report.yml

----------
Add v2.0.6 into Issue Template

Add v2.0.6 into Issue Template

---

libraries/ESP32/examples/Template/ExampleTemplate/README.md

Added the link to the ESP32-S3 datasheet
N/A
#7665

Added ESP32-S3 link to the datasheet

---

libraries/Ethernet/src/ETH.cpp

Minor fix based on observation done in https://github.com/espressif/arduino-esp32/issues/7795#issuecomment-1416868611
No Need
Minor fix based on observation done in https://github.com/espressif/arduino-esp32/issues/7795#issuecomment-1416868611

Fix commentary in code

---

libraries/Update/src/Update.h

-----------
Please describe on what Hardware and Software combinations you have tested this Pull Request and …

Change header gaurd name

---

docs/source/api/sigmadelta.rst

fixed the function header ftom ledcSetup to  sigmaDeltaSetup
I have tested my Pull Request on Arduino-esp32  with ESP32-S3 Board

fixed the function header

---

boards.txt
variants/lilygo_t_display_s3/pins_arduino.h

New variant LilyGO T-Display-S3.
https://github.com/Xinyuan-LilyGO/T-Display-S3

new variant LilyGO T-Display-S3

---

variants/redpill_esp32s3/pins_arduino.h

Update definition for RedPill+ ESP32-S3.
I have tested my Pull Request on RedPill+ ESP32-S3 and Arduino IDE v2.
None.

Update definition for RedPill+ ESP32-S3.

---

.github/ISSUE_TEMPLATE/Issue-report.yml

Adding version 2.0.7 into issue-report.yml
N/A
N/A

Add v2.0.7 in issue template

---

libraries/ESP32/examples/Camera/CameraWebServer/app_httpd.cpp

Issue and solution as described by user @mondolirondo in #7742

Swapped enable_led() and isStreaming setup; solving #7742

---

boards.txt
variants/m5stack_stamp_s3/pins_arduino.h

Stamp-S3 [Related links](https://docs.m5stack.com/en/core/StampS3)

Create Stamp-S3 pins_arduino.h and Stamp-S3 Board

---

libraries/WiFi/src/WiFiGeneric.cpp
libraries/WiFi/src/WiFiGeneric.h

Applies same changes in PR #8043 to branch v5.1-libs

WiFiGeneric CrashFix 5.1-libs

---

.github/scripts/find_new_boards.sh
.github/workflows/boards.yml

Fixed empty result from `find_new_boards.sh` script.
Removed unnecessary brackets for `IF` condition in yaml.

[CI] Boards test fix

---

boards.txt
variants/lolin_s3_mini/pins_arduino.h

Add LOLIN S3 Mini board based ESP32-S3FH4R2.
I have tested my Pull Request on Arduino-esp32 core with ESP32-S3 Board with this scenario
https://www.wemos.cc/en/latest/s3/s3_mini.html

Add LOLIN S3 Mini board def

---

.github/ISSUE_TEMPLATE/Issue-report.yml

Added version 2.0.8 into issue-report.yml

Add v2.0.8 into Issue Template

---

.github/workflows/lib.json

Added 2 libraries to the External library testing proposed by #8108.

Add MFRC522 and WS2812FX library to External library testing

---

package/package_esp32_index.template.json

esp-idf: release/v5.1 2004bf4e11
esp-dl: master 0632d24
esp-insights: main d8b2dfc
esp-rainmaker: master cc861bf
esp-sr: master 6109ee3
esp32-camera: master e689c3b
esp_littlefs: master aeb9858
espressif__esp-dsp: master bbb9ccc
tinyusb: master 5e023fa2c

IDF release/v5.1

---

cores/esp32/esp32-hal-spi.c
cores/esp32/esp32-hal-spi.h
libraries/SPI/src/SPI.cpp

Implemented peripheral manager into SPI driver.
Tested using SPI Class and SD card.

SPI - Peripheral manager implementation 

---

.github/ISSUE_TEMPLATE/Issue-report.yml

Just adding v2.0.10 into issue template.
No need to test.
N/A

Add v2.0.10 into issue template

---

.github/workflows/hil.yml
tests/democfg/cfg.json
tests/nvs/cfg.json
tests/requirements.txt

Fixing hw tests to contain all needs for C6/H2 SoC.

HW Testing -  ESP32-C6 + ESP32-H2 fixes

---

tools/platformio-build.py

This PR adds special handling of the `ARDUINO_BUILD_CORE` macro introduced in v2.0.10.

Sync PlatformIO build script

---

.github/workflows/allboards.yml

Checkout action was not correctly set for all jobs in the workflow file to use the branch name passed the the curl command.
Tested on forked repo.

[CI] Fix allboards.yml workflow to use selected branch

---

.github/scripts/on-release.sh
cores/esp32/esp_arduino_version.h
package.json
platform.txt

Update Arduino Core version to reflect latest 2.0.12
None
Fixes #8612

Set ref to 2.0.13

---

libraries/SD/README.md

-----------
Fix Mardown table format error in SD library
None
None

Fix Mardown table format error in SD library

---

README.md

Update README.md to add C6 and H2
None
None

Update README.md to add new SoCs

---

.github/scripts/on-release.sh

Some include paths in the RV32 toolchain on Windows end up too long for GCCs 200 char limit and compilation fails. While a fix is provided upstream, we workaround this issue by shortening the tool name and version, thus saving 26 chars of the path.

Rename the RV32 toolchain on release to fit paths in GCC limit

---

README.md

Fixing the readme file.
Realese supported schedule will be added in another commit later.

Fix of Readme

---

idf_component.yml

Fix path of IDF Component examples.

Fix IDF component examples path

---

variants/sensebox_mcu_esp32s2/variant.cpp

Updates the initialize script of the 3rd Party Board "senseBox MCU-S2 ESP32-S2" in the corresponding variants.cpp file. 
I have tested my Pull Request on Arduino-esp32 core v2.0.14 with 3rd Party Board "senseBox MCU-S2 ESP32-S2".
Somehow related to #8999 but does not fix the mentioned issue.
Are you planning to do a v2.0.15 release? If so we would really like to add the our board (and this change to it) also to the release/v2.x branch.

Update initialize script of 3rd Party Board "senseBox MCU-S2 ESP32-S2" 

---

libraries/LittleFS/src/LittleFS.cpp

-----------
Added missing identifiers to match new version of littlefs component.
LittleFS_Test.ino
Fixes #9044

Added missing identifiers in esp_vfs_littlefs_conf_t

---

docs/source/api/preferences.rst

PR created at @Xylopyrographer request here https://github.com/espressif/arduino-esp32/pull/9111
Commits were cherry picket from the main branch.
Thank you guys for all the work you're putting in for us! I'm glad to be contribution a little :)

Added isKey documentation for the Preferences library

---

docs/requirements.txt

Changes on the requirements file to remove dependencies
Run docs build
N/A

[Docs] Change/clean the requirements file

---

libraries/ArduinoOTA/src/ArduinoOTA.cpp

Backport: ArduinoOTA upload intermittent failure fixed

---

cores/esp32/Esp.cpp
libraries/Update/src/Updater.cpp

Backport: Fix ESP32-Solo WDT on HTTP OTA update

---

variants/Geekble_ESP32C3/pins_arduino.h

-----------
Update LED_BUILTIN pin
Arduino blink …

fix: Geekble mini board pin fix

---

libraries/BluetoothSerial/examples/DiscoverConnect/DiscoverConnect.ino

Fixing typo in DiscoverConnect.ino BluetoothSerial example

---

variants/esp32s3_powerfeather/pins_arduino.h

Define Wire1 pins for ESP32-S3 PowerFeather.

Define Wire1 pins for ESP32-S3 PowerFeather

---

docs/en/migration_guides/2.x_to_3.0.rst

mention WiFiServer channges  in the migration guide

migration guide: WiFiServer changes

---

libraries/Update/src/Updater.cpp

arguement -> argument
5. [ ] Please **confirm option to "Allow edits and access to secrets by maintainers"** when opening a Pull Request
-----------
Please describe on what Hardware and Software combinations you have tested this Pull Request and …

Fix typo in Updater.cpp

---

libraries/WiFi/examples/WiFiUDPClient/udp_server.py

Convert all remaining Python 2 scripts to Python 3

Convert script from Python 2 to 3

---

variants/unphone9/pins_arduino.h

This change only affects a single board variant, the unPhone. As co-designer of the board I confirm that this change will allow users to work with our hardware using this codebase more easily. No restrictions are imposed on the use of this code.
We have sucessfully tested this change on an unPhone9.
unphone description can be found at [unphone.net](https://unphone.net/)

change(variant): add additional pin mappings and #define to variant/unphone9

---

docs/en/installing.rst

Just one typo fix at Installing guide.
N/A

Docs: Typo fix in installing guide

---

.gitignore
docs/en/lib_builder.rst

Add documentation for the Lib Builder Docker Image.

docs(lib-builder): Add docker image documentation

---

.github/workflows/hil.yml
.github/workflows/publish.yml
.github/workflows/wokwi.yml

Fix wokwi concurrency.
CI will fail on PR as the correct file will only be run after merge.
CI on fork

ci(wokwi): Fix concurrency

---

boards.txt

Added extra options in the UI for the ESPDuino board as CPU freq and Partition was missing. Now it better mirrors its source board, the WeMos D1 R32.

Update(3rd_party_board): Updated ESPDuino with extra options

---

boards.txt
variants/weact_studio_esp32c3/pins_arduino.h

Add support for [WeAct Studio ESP32C3](https://github.com/WeActStudio/WeActStudio.ESP32C3CoreBoard) board
Related: https://github.com/platformio/platform-espressif32/pull/1381

feat (3rd_party_board): add support for WeAct Studio ESP32C3

---

libraries/Ethernet/src/ETH.cpp

fix(eth): Fix ETH.stop() with IDF SPI

---

.github/ISSUE_TEMPLATE/Issue-report.yml

Adding missing versions from Issue Report form

feat(reports): Update Issue-report.yml with new versions

---

README.md

Update C6 and H2 support status for Stable version in the README.

change(readme): Update C6 and H2 support

---

.github/workflows/release.yml

Necessary to combine the json files

fix(release): install missing 'packaging' package

---

.github/workflows/publishlib.yml
.github/workflows/publishsizes.yml

This PR fixes incorrect name of the artifact in comparison to sort in sub folders.

fix(ci): Compare correct name of the artifact

---

cores/esp32/Esp.cpp
cores/esp32/chip-debug-report.cpp

Fixes: https://github.com/espressif/arduino-esp32/issues/9748
Fixes: https://github.com/espressif/arduino-esp32/issues/9618

Fix getFlashChipMode breaking on S3 and C3

---

boards.txt

updated boards.txt for Smart Bee Boards for IDE2 and CLI

Updated Smart Bee Boards for IDE2 & CLI

---

README.md

Fix readme badge after new CI refactoring

fix(readme): Fix tests badge

---

idf_component.yml

feat(crypto): Add libsodium to the included components

---

libraries/Network/src/NetworkClient.cpp

It was returning zero, because it was not able to handle IPv4 mapped address into IPv6 address
Fixes: https://github.com/espressif/arduino-esp32/issues/9843

fix(client): Fix NetworkClient::localIP()

---

boards.txt
variants/lilygo_t_eth_lite/pins_arduino.h

Adds board support for Lilygo T-ETH Lite

add(board): Add LILYGO T-ETH-Lite

---

docs/en/api/preferences.rst

This PR fixes `getBool` function in preferences.rst
Closes #9887

docs(preferences): Fix getBool function

---

.github/workflows/tests_results.yml

Make sure that the caches are cleaned when not necessary anymore

ci(tests): Fix cache cleaning

---

boards.txt
variants/lilygo_t3_s3_lr1121/pins_arduino.h
variants/lilygo_t3_s3_sx1262/pins_arduino.h
variants/lilygo_t3_s3_sx127x/pins_arduino.h
variants/lilygo_t3_s3_sx1280/pins_arduino.h
variants/lilygo_t3_s3_sx1280pa/pins_arduino.h

This topic submitted a request https://github.com/espressif/arduino-esp32/issues/9927

Added LilyGo T3S3 variants

---

libraries/HTTPClient/src/HTTPClient.cpp

fix(httpc): Fix data read was less than expected

---

.github/ISSUE_TEMPLATE/Issue-report.yml

add(template): Add version 3.0.3 to the Issue template

---

README.md

Update Readme with correct badge and link to build tests.

fix(readme): Update badge for Build status

---

.github/scripts/on-release.sh

Add test to check if the generated JSON files can be properly installed.
Local and CI

ci(release): Add JSON install test

---

boards.txt
variants/lilygo_twatch_s3/pins_arduino.h
variants/lilygo_twatch_ultra/pins_arduino.h

Added LILYGO's currently available T-Watch-S3 and the new T-Watch-Ultra variant that will soon be out

Added LILYGO T-Watch-S3 & T-Watch-Ultra variants

---

docs/requirements.txt
tests/requirements.txt
tools/pre-commit/requirements.txt

Fix requirement versions so they don't conflict when installed together
Tested locally

fix(requirements): Avoid version conflicts

---

tools/get.py

This PR makes sure that #10160 works properly when switching to the `release/v2.x` branch.
Tested locally
Requirement of #10160

fix(get.py): Clear old files before extracting

---

libraries/Network/src/NetworkEvents.cpp

Fixes: https://github.com/espressif/arduino-esp32/issues/10316

fix(events): Fix crash in getStdFunctionAddress

---

.pre-commit-config.yaml
tests/performance/fibonacci/test_fibonacci.py
tests/validation/gpio/test_gpio.py
tests/validation/nvs/test_nvs.py
tests/validation/periman/test_periman.py
tests/validation/wifi/test_wifi.py

Fix leftover formatting and disable JSON formatting to avoid issues

fix(formatting): Fix formatting and disable JSON hook

---

platform.txt

This will help external library developers
Fixes: https://github.com/espressif/arduino-esp32/issues/8815

fix(arduino): Move extra_flags to flags

---

.github/scripts/find_new_boards.sh
.github/workflows/boards.yml

Fixes broken boards test
Tested on GH CI in a fork

fix(ci): Boards test - get correct file for the diff

---

docs/en/lib_builder.rst

Improve Lib-Builder documentation by adding more info about the UI and the docker image

docs(lib-builder): Improve UI and Docker image sections

---

libraries/BLE/examples/BLE5_periodic_advertising/BLE5_periodic_advertising.ino

fix(example):Update comment in BLE5_periodic_advertising.ino

---

libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino

-----------
fix(Zigbee): Fix typo in Zigbee_Temp_Hum_Sensor_Sleepy.ino

fix(Zigbee): Fix typo in Zigbee_Temp_Hum_Sensor_Sleepy.ino

---

CMakeLists.txt
libraries/Matter/examples/MatterOccupancySensor/MatterOccupancySensor.ino
libraries/Matter/examples/MatterOccupancySensor/ci.json
libraries/Matter/keywords.txt
libraries/Matter/src/Matter.h
libraries/Matter/src/MatterEndpoints/MatterOccupancySensor.cpp
libraries/Matter/src/MatterEndpoints/MatterOccupancySensor.h

Adds a new Matter Endpoint for Occupancy Sensor.
ESP32-C6 using the provided example.

feat(matter): adds new Matter Occupancy Sensor endpoint

---

.github/workflows/upload-idf-component.yml

Fix uploading component to IDF registry.
CI
Fixes #10751

fix(component): Checkout proper branch for uploading component

---

.github/workflows/upload-idf-component.yml

fix(component): Add check for workflow_run

---

CMakeLists.txt
cores/esp32/esp32-hal-i2c-ng.c
cores/esp32/esp32-hal-i2c.c
libraries/Wire/src/Wire.cpp
libraries/Wire/src/Wire.h
variants/esp32c6/pins_arduino.h

Also adds support for LP I2C buses on some newer chips (C6, P4)

feat(i2c): Add support for the new I2C driver in IDF v5.4

---

libraries/ArduinoOTA/src/ArduinoOTA.cpp

fixes: https://github.com/espressif/arduino-esp32/issues/10930

fix(ota): Make sure that ArduinoOTA.end() is called in the destructor

---

.github/workflows/build_py_tools.yml
.github/workflows/push.yml

Bump version of ubuntu runners as the versions being used are flagged for removal.
CI

ci(runners): Bump runner images version

---

tests/validation/i2c_master/i2c_master.ino

Add scan test to `i2c_master`.
Local and CI
#10848

test(i2c): Add test to scan bus

---

variants/lilygo_tlora_pager/pins_arduino.h

Sorry, there was a small misunderstanding.
https://github.com/espressif/usb-pids/pull/231

Modify T-LoRa-Pager device PID

---

idf_component.yml

branch master has updates which needs esp_hosted >= 2.0.0
@me-no-dev

fix compile fail esp_hosted

---

idf_component.yml

recommended version from maintainer to use for IDF branch master
@me-no-dev

Update version for wifi remote

---

tools/gen_esp32part.py

Don't have write rights in the PR

fix flake8

---

variants/tamc_termod_s3/pins_arduino.h
variants/tamc_termod_s3/variant.cpp

This pull request makes small updates to the `tamc_termod_s3` variant files to fix compilation issues.

fix(tamc_termod_s3): Fix header includes

---

libraries/HTTPClient/examples/Authorization/Authorization.ino
libraries/HTTPClient/examples/BasicHttpClient/BasicHttpClient.ino
libraries/HTTPClient/examples/ReuseConnection/ReuseConnection.ino
libraries/HTTPClient/examples/StreamHttpClient/StreamHttpClient.ino

Replace USE_SERIAL macro with direct Serial calls in HTTPClient examples
Tested on master
https://github.com/espressif/arduino-esp32/pull/11768#discussion_r2310106793

refactor(http-client): Replace USE_SERIAL with direct Serial
