espressif/arduino-esp32

cores/esp32/Arduino.h

The defines are needed by library [Adafruit_SSD1306](https://github.com/adafruit/Adafruit_SSD1306/blob/master/examples/ssd1306_128x64_i2c/ssd1306_128x64_i2c.ino)

Add from original Arduino.h

---

libraries/Wire/src/Wire.h

Add to #55, We need `Wire.write(const char*)` for code compatibility. This PR adds `write(const char *)` to `TwoWire` class.
Thank you.

Add TwoWire::write(const char *)

---

libraries/WiFi/src/WiFiClient.cpp

Hi, it's needed close sockfd before sockfd = -1, and
_connected = false;
close(sockfd);
sockfd = -1;
this equals stop() function.

close sockfd before set -1

---

cores/esp32/IPAddress.cpp
cores/esp32/IPAddress.h

make IPAddress.toString() const method, it doesn't modify anything
within the class.

const correctness

---

tools/get.py

Added an Exception handling to the offending urlretrieve() call for the issue https://github.com/espressif/arduino-esp32/issues/108
It's not really a fix but the failure message is much more elegant than the initial stack trace as it hints at the solution to the setup problem rather than confusing the user into Windows problems.

Error Handling for Window10 without CygWin

---

cores/esp32/esp32-hal-spi.c
tools/sdk/include/esp32/soc/gpio_sig_map.h

Hi @me-no-dev,
esp-idf commit esp-idf/23455de4 renamed VSPICLK_OUT_MUX_IDX to VSPICLK_OUT_IDX. This PR updates the name to avoid compilation errors when using arduino as an esp-idf component.
FWIW I think this should be safe to change even without rebuilding the binary libraries, as there's no object file difference. But it will break anyone compiling arduino as a submodule in older esp-idf. 
Angus

SDK headers: Use new esp-idf signal name VSPICLK_OUT_IDX

---

cores/esp32/Arduino.h
cores/esp32/wiring_pulse.c

quick edit to make pulseIn() work.

Enable pulseIn()

---

libraries/WiFi/examples/WiFiUDPClient/WiFiUDPClient.ino
libraries/WiFi/examples/WiFiUDPClient/udp_server.py
libraries/WiFi/examples/WiFiUDPClient/udp_server.rb

Added a basic WiFi UDP client example: a sketch that sends random bytes over UDP. It uses the recently implemented UDP functionality.

Added a basic WiFi UDP client example

---

variants/esp320/pins_arduino.h
variants/esp32thing/pins_arduino.h
variants/espea32/pins_arduino.h
variants/hornbill32dev/pins_arduino.h
variants/lolin32/pins_arduino.h
variants/nano32/pins_arduino.h
variants/node32s/pins_arduino.h

**Sources:**
* esp320: http://wiki.sweetpeas.se/index.php?title=ESP320#Developing_using_the_Arduino_IDE
* esp32thing: https://cdn.sparkfun.com/assets/learn_tutorials/5/0/7/esp32-thing-schematic.pdf
* espea32: https://github.com/AprilBrother/ESPea32/blob/master/hardware/ESPea32-schematic.pdf
* hornbill32dev: https://github.com/ExploreEmbedded/Hornbill-ESP32-DEV/blob/master/Design%20Files/Schematic/Hornbill%20Devboard.pdf
* lolin32: values from existing header
* nano32: http://iot-bits.com/closer-look-esp32-nano32/
* node32s: https://github.com/lamloei/node32s-book/blob/master/ch01/node32s-schematic.pdf
_Note: Some board producers have not published schematics yet, so it was little digging work._

Added boards constants for LED_BUILTIN and KEY_BUILTIN

---

cores/esp32/Print.cpp
cores/esp32/Print.h
cores/esp32/WString.cpp
cores/esp32/WString.h
cores/esp32/pgmspace.h

Previous `__FlashStringHelper` implementation was defines as a `char` which brought problem in case the method with `char*` parameter used overloading with `__FlashStringHelper*` parameter (they was identical). Now `__FlashStringHelper` is defined as a `class` and all casts between `char*` and `__FlashStringHelper*` are made with `reinterpret_cast` sugar.

Fixes implementation of __FlashStringHelper

---

libraries/WiFi/src/WiFiUdp.cpp

Currently there is bug in WiFiUDP library when you want to use `beginPacket(...)` without listening on socket (without calling `begin(...)` first). You can't send any data because socket is not open and also `tx_buffer` is not allocated which cause crash while writing data to `tx_buffer`.
_**Note**: Tested with `WiFiUDPClient` example. For situation without listening on socket, just comment the line with `udp.begin(WiFi.localIP(),udpPort);` (line 67)._

beginPacket can be used without listening on socket

---

cores/esp32/esp32-hal-misc.c

This error occurs only when `CONFIG_ESP32_PHY_AUTO_INIT=y`.

Fix for implicit declaration of function nvs_flash_init error

---

libraries/WiFiClientSecure/src/WiFiClientSecure.cpp

When I tried to use WiFiClientSecure, I got an error: error return statement in function returning non-void.

Fix for WiFiClientSecure.

---

cores/esp32/Esp.cpp
cores/esp32/Esp.h

* fixed not working functions for flash chip size, speed and mode
* added function to retrieve chip revision from eFuse
* ~`flashRead` / `flashWrite` supports encrypted flash~ (reverted, see @igrr review)

Improvements in EspClass

---

libraries/WiFi/src/WiFiClient.cpp

The send call may return EAGAIN. This indicates a recoverable error and a retry should be attempted. The current implementation treats this as a fatal error. Further, the current implementation strips the error code, setting it to 0, which prevents the caller from handling it directly. 
This change utilizes select to verify the socket is available prior to calling send and will retry on an EAGAIN condition.

Revise WiFiClient::Write to handle EAGAIN

---

libraries/WiFi/src/WiFiClient.cpp
libraries/WiFi/src/WiFiClient.h

Rework WiFiClient to correct error where making a copy of a WiFiClient object resulted in the socket being closed prematurely.
Added loop and select to write to handle/prevent EAGAIN errors.

Rework WiFiClient

---

libraries/WiFiClientSecure/examples/WiFiClientSecure/WiFiClientSecure.ino
libraries/WiFiClientSecure/src/WiFiClientSecure.cpp
libraries/WiFiClientSecure/src/WiFiClientSecure.h
libraries/WiFiClientSecure/src/ssl_client.cpp
libraries/WiFiClientSecure/src/ssl_client.h

-Best MbedTLS error handling, returning the error code and translate it to a error message.
-Fix for the issue https://github.com/espressif/arduino-esp32/issues/223
-Partial fix for the issue https://github.com/espressif/arduino-esp32/issues/211  (avoid crashing, just return mbedtls error and close the connection), but still don't close in described situation.
-Add CA certificate in example, because SHA1 fingerprint is broken now, details in https://shattered.io/

WiFiSecureClient fixes and improvements

---

libraries/WiFi/src/WiFiMulti.cpp

Actually WiFiMulti is not working due some functions haven't equal comportment of ESP8266
Replace status == WL_DISCONNECTED => status != WL_CONNECTED
Replace scanComplete() => scanNetworks()
Maybe is more interesting, for keep the maximum compatibility, investigate why WL_DISCONNECTED and scanComplete() doesn't works in this case instead of just replace by this pull request.

Replace some WiFiMulti functions without equal comportment of ESP8266

---

libraries/WiFiClientSecure/src/ssl_client.cpp

Fix for https://github.com/espressif/arduino-esp32/issues/265
mbedtls_ssl_conf_authmode was defined before mbedtls_ssl_config_defaults causing several bugs when no CA certificate is defined.

Support self signed certificates

---

cores/esp32/esp32-hal-spi.c

It appears that the configurations for `ck_out_edge` were inverted for `SPI_MODE2` and `SPI_MODE3`. You can check the technical reference manual on page 76, table 23 "Clock Polarity and Phase, and Corresponding SPI Register Values for SPI Master".
I've check with my oscilloscope that the current configuration is wrong and this fix corrects the issue.
Here are some examples writing `0x8F` with the `SCK` line in red and the `MOSI` line in yellow
`SPI_MODE2` before the change:
`SPI_MODE2` after the change:
`SPI_MODE3` before the change:
`SPI_MODE3` after the change:

SPI_MODE2 and SPI_MODE3 configurations inverted

---

cores/esp32/Esp.cpp
cores/esp32/Esp.h
libraries/ESP32/examples/ChipID/GetChipID/GetChipID.ino

@me-no-dev 
Add ESP.getChipId() function to get ESP32's ChipID.

Add ESP.getChipId() function to get ESP32's ChipID.

---

libraries/HTTPClient/examples/Authorization/Authorization.ino
libraries/HTTPClient/examples/BasicHttpClient/BasicHttpClient.ino
libraries/HTTPClient/examples/ReuseConnection/ReuseConnection.ino
libraries/HTTPClient/examples/StreamHttpClient/StreamHttpClient.ino
libraries/HTTPClient/library.properties
libraries/HTTPClient/src/HTTPClient.cpp
libraries/HTTPClient/src/HTTPClient.h
libraries/WiFiClientSecure/examples/WiFiClientSecure/WiFiClientSecure.ino
libraries/WiFiClientSecure/src/WiFiClientSecure.cpp
libraries/WiFiClientSecure/src/WiFiClientSecure.h
libraries/WiFiClientSecure/src/ssl_client.cpp
libraries/WiFiClientSecure/src/ssl_client.h

Changed SHA1 fingerprint by Root CA verification
Changed log system
Some WiFIClientSecure fixes

HTTPClient Port

---

libraries/WiFi/src/WiFiClient.cpp
libraries/WiFi/src/WiFiServer.cpp
libraries/WiFi/src/WiFiServer.h

Fix WiFiClient::available() so it detects remote TCP disconnects. See #377 for discussion.

Remote tcp disconnect not detected

---

libraries/WiFi/src/WiFiClient.cpp
libraries/WiFi/src/WiFiClient.h

Implement methods from ESP8266WiFiClient but use sockets API. The methods are used in the DNSServer library CaptivePortAdvanced example as well as in the WiFiManager library.

Add WiFiClient localIP and localPort

---

libraries/WiFi/src/WiFiClient.cpp
libraries/WiFi/src/WiFiClient.h
libraries/WiFi/src/WiFiServer.cpp
libraries/WiFi/src/WiFiServer.h

Required for WebServer and DNSServer libraries. May be use by other libraries and apps.

Additions to WiFiClient and WiFiServer

---

cores/esp32/esp32-hal-uart.c

This incorporates a fix from the latest IDF for the two stop bit issue.
See:
https://github.com/espressif/esp-idf/blob/master/components/driver/uart.c  lines 118-127

Two Stop Bit Workaround

---

libraries/ESP32/examples/ResetReason/ResetReason.ino

Method:
--------
Added a verbose print method for ease.
Test Case:
-----------
Putting ESP32 to sleep will give a different reason on wake than the first
time power up.

ResetReason: Add an additional method and a test case

---

libraries/WiFiClientSecure/src/ssl_client.cpp

- Clear certificates just after the handshake:
Saving up to 7k of heap
Fix for https://github.com/espressif/esp-idf/issues/723
- Remove duplicated include

Heap optimization

---

libraries/SD/src/sd_diskio.cpp

The two functions sdcard_mount and ff_sd_ioctl had missed the begin/endTransaction calls. 
The change intrdocues a local RAII helper to simplify maintaining begin/end scopes
Signed-off-by: Andreas Pokorny <andreas.pokorny@siemens.com>

Bugfix: Put every SPI access between begin / end Transaction

---

libraries/SPI/src/SPI.cpp

Fixes problem where not enough data is sent when sending a repeating pattern via SPI that doesn't evenly divide into the hardware FIFO size (64 bytes).
For example, I was sending a 3-byte pattern (RGB data) for a 320 x 480 display, which fits 21 times into the hardware FIFO (3 * 21 = 63 bytes), and by the end of the routine 1/64th of the data (and therefore the image) was missing.  This happened because for every 63 bytes sent, this routine decremented the byte count by 64.

Spi pattern fix

---

libraries/WiFi/src/WiFiClient.cpp

send() can return a value > 0 but less than size indicating it was able to accept some of the data in buffer. The caller must try again after updating the buffer pointer and size remaining.
https://github.com/bbx10/WebServer_tng/issues/1

Handle partial socket send

---

libraries/WiFi/src/WiFiSTA.cpp

Current implementation does not disconnect the WiFi. Use of `esp_wifi_disconnect()` does.

Change disconnect function

---

libraries/Update/examples/AWS_S3_OTA_Update/AWS_S3_OTA_Update.ino

- 100ms is too low to get server response

Small improvements in update example

---

cores/esp32/esp32-hal-uart.c

This should solve the device freezing issue when Serial.end() is called

uartEnd: Unlock mutex before detaching rx and tx

---

platform.txt

Previously compiler.c.extra_flags was used in this recipe rather than compiler.S.extra_flags, which I believe to have been a typo.

Use correct extra_flags property in recipe.S.o.pattern

---

libraries/WiFiClientSecure/src/WiFiClientSecure.cpp
libraries/WiFiClientSecure/src/ssl_client.cpp
libraries/WiFiClientSecure/src/ssl_client.h

Server Name Indication (SNI) support for WiFiClientSecure
Fix https://github.com/espressif/arduino-esp32/issues/571 and https://github.com/espressif/arduino-esp32/issues/550

SNI support

---

docs/arduino-ide/mac.md

Had to run "xcode-select --install" before your script worked.
More info here: https://stackoverflow.com/questions/32893412/command-line-tools-not-working-os-x-el-capitan-macos-sierra

Missing xcrun fix.

---

component.mk

There are many libraries which don't put their source files under *src* directory.
For example, nearly all sensor libraries from Adafruit don't have a *src* directory.
In order to compile with these libraries, we should manually create a *src* directory and move all source files into it, which is really annoying.
If the library also includes source files under sub directories, it would result in linker errors.
**However, only changing a line in *component.mk* can solve all these issues.**

Fix support for some arduino libraries which don't put source files under a src directory

---

cores/esp32/Arduino.h
cores/esp32/esp32-hal-time.c

leave original configTime() intact, add ability to setup sntp using only TZ environment variable and ntp server.

add configTzTime() to setup sntp using TZ environment variable

---

variants/heltec_wifi_kit_32/pins_arduino.h

Looks like the LoRa kit pinout was copied in for the WiFi kit.
If you reference http://esp32.net/images/Heltec/WIFI-Kit-32/Heltec_WIFI-Kit-32_DiagramPinout.jpg, you'll see a few differences, this PR should address them.  I've only tested out the SPI pins and the LED_BUILTIN specifically.

Very slight difference between LoRa kit and WiFi kit.

---

libraries/WiFi/examples/WPS/README.md
libraries/WiFi/examples/WPS/WPS.ino

This example shows how WPS can be used to connect an ESP32 to a router that has the required functionality.

Add Example Code for WPS Functionality

---

cores/esp32/esp32-hal-i2c.c
cores/esp32/esp32-hal-i2c.h
libraries/Wire/src/Wire.cpp
libraries/Wire/src/Wire.h

Because of two situations, reboot and bus error, in which the ESP32 I2C state machine can get into a non-recoverable state where the busy flag remains set, potentially causing lockup or preventing I2C from running, the reset function has been added at the HAL layer and made available from Wire.
An attempt was made to time out operations and have i2cReset called internally, but that ended up creating more problems than it solved because the slave may need to release the line(s) first. At this point anyone who runs into bus errors that leave the I2C unusable after SDA and SCL go high can call the reset() function to reset the hardware I2C elements.

I2c reset functionality

---

libraries/Update/examples/SD_Update/SD_Update.ino

I saw that an update example got added, felt that the example could be made tidier when not using goto.

Changed update example to use different control flow structure

---

platform.txt

The arameter "-fno-rtti " is present two times
compiler.cpp.flags=-std=gnu++11 -fno-exceptions **-fno-rtti** -Os -g3 -Wpointer-arith -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib {compiler.warning_flags} -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare **-fno-rtti** -MMD -c

Second occurace of parameter -fno-rtti removed

---

cores/esp32/esp32-hal-i2c.c

The i2cWrite() function was returning to the app before the i2c transaction had completed.  This caused the next Wire() call to return a I2C_ERROR_BUSY.

Fix Early return when Address NAK is received

---

cores/esp32/esp32-hal-i2c.c
cores/esp32/esp32-hal-i2c.h

I wanted to make this available for  others before I run out of time on this activity for the short term. The same approach used for reads can be applied for writes to avoid the hardware END-handling state machine bug. The code incorporates the fix by @stickbreaker that I had previously injected (doh!).
The obvious next approach is to try using interrupts for handling the work currently being done on lines 336 to 365 since the current code can be starved of CPU time at points resulting in bus hangs when the state machine is not properly fed.

Add initial handling for long I2C reads.

---

cores/esp32/esp32-hal-i2c.c

The existing code did not follow protocol with 10bit addressed devices.  Per _Philps/NXP Semiconductors UM10204 I2C-bus specification and user manual Rev. 6 4April2014_ pg.15 3.1.11 10-bit addressing:
`The first seven bits of the first byte are the combination of 1111 0xx of which the last two bits (xx) are the two Most-Significant Bits (MSB) of the 10-bit address; the eighth bit of the first byte is the R/W bit the determines the direction of the message`

Correct 10bit Device address handling.

---

boards.txt
variants/nina_w10/pins_arduino.h

This was implemented according to section 1.3 and 2.4 of the system integration manual: 
https://www.u-blox.com/sites/default/files/NINA-W1_SIM_%28UBX-17005730%29_2.pdf
This target can for example be used on the following products:
- https://www.u-blox.com/en/product/evk-nina-w10
- https://www.u-blox.com/en/product/nina-w10-series

Add new target u-blox nina-w10

---

tools/get.py

Localized versions of Linux systems use Unicode characters in the names of standard directories like "Downloads".

Unicode support in get.py

---

libraries/ArduinoOTA/src/ArduinoOTA.cpp
libraries/ArduinoOTA/src/ArduinoOTA.h

Previously, ArduinoOTA would stop receiving any packets if the port received a zero-length UDP packet, commonly sent by network scanners like nmap. Fixed to flush() after every call to parsePacket(), even if read length is 0.
Additionally, added length checking to fix a potential buffer overflow in parseInt().
Finally, added an end() method that stops the OTA listener and releases resources.

Fixes for zero length packet bug, buffer overflow in parseInt(), added end() method

---

boards.txt
platform.txt

see also "fix NodeMCU-32S .build.board property" (https://github.com/espressif/arduino-esp32/pull/812#issuecomment-341990261)
`-DARDUINO_BOARD={build.board}` is missing
With this fix you get a macro `ARDUINO_BOARD` with the name of the selected board (e.g. `"NodeMCU-32S"`).
https://github.com/esp8266/Arduino/blob/master/platform.txt#L75
https://github.com/esp8266/Arduino/blob/master/platform.txt#L78
https://github.com/esp8266/Arduino/blob/master/platform.txt#L81

Fix compiler flags to be compatible with ESP8622/Arduino

---

boards.txt

The .build.board=xx proptery is used for generating a macro named "ARDUINO_xxx".
C macro names should never have a "-" sign.
* current: ARDUINO_NodeMCU-32S
* should be: ARDUINO_=NodeMCU_32S

fix NodeMCU-32S .build.board property

---

libraries/ArduinoOTA/examples/BasicOTA/BasicOTA.ino
libraries/ArduinoOTA/src/ArduinoOTA.cpp
libraries/ArduinoOTA/src/ArduinoOTA.h

This change allows chaining of methods for more concise code, similar like in most JavaScript Frameworks. Should not affect previous usage patterns, as the return type was `void`.
The BasicOTA example could look like this:
```
ArduinoOTA
.onStart([]() {
})
.onEnd([]() {
})
.onProgress([](unsigned int progress, unsigned int total) {
})
.onError([](ota_error_t error) {
});
```

Allow chaining of methods for more concise code

---

tools/platformio-build.py

Do you have ideas why `-fstack-protector` generates a warning? Should be it removed from platform.txt?
```
cores/esp32/IPv6Address.cpp:1:0: warning: -fstack-protector not supported for this target
```

Sync flags with platform.txt; Custom partitions per board

---

libraries/SPI/src/SPI.cpp
libraries/SPI/src/SPI.h

When user selected HSPI with SPIClass name(HSPI) ESP was, by default,
still using VSPI ports (the ones defined in pins_arduino.h).
With this change when user selects HSPI then HSPI default ports will be
used.
If user won't specify HSPI then VSPI default ports will be used.
If user will specify SCLK, MOSI, MISO and SS with SPI.begin() then user
defined ports will be used no matter if VSPI or HSPI is selected.
With this change fe. SD library can use default HSPI ports. It was
possible to
pass HSPI SPI instance to SD lib, however even then it was using VSPI
ports which were (probably) GPIO matrixed to HSPI.

Set HSPI ports by default when HSPI is selected

---

libraries/WiFi/src/WiFiSTA.cpp

Allow PSK, which generated by `wpa_passphrase` command or the PBKDF2 function.
I referred to the following the PR: https://github.com/esp8266/Arduino/pull/1850
> In WPA protocol, the maximum length of the passphrases is 64 characters in order to distinguish them from the actual PSK which is 64 ASCII characters long, so in most systems if a 64 chars string is passed, it is assumed to be a PSK, otherwise is treated as a passphrase and is used to compute the PSK.
To calc the PSK, please use http://jorisvr.nl/wpapsk.html

Allow PSK instead of passphrase in WiFiSTA::begin

---

libraries/HTTPClient/src/HTTPClient.cpp
libraries/HTTPClient/src/HTTPClient.h
libraries/WiFiClientSecure/src/WiFiClientSecure.cpp
libraries/WiFiClientSecure/src/WiFiClientSecure.h

Currently, the getStream() function on the httpClient will return the stream for the non-SSL without generating errors and this will cause problems when someone tries to read the stream as there is nothing to read. The changes check whether the SSL mode is in use or not and generate an error if the method is called while SSL is in use.

Ensure errors are generated if the wrong method is called to retrieve the SSL data stream.

---

libraries/Preferences/examples/StartCounter/StartCounter.ino

Just fixed some small grammar issues in the comments and clarified a few things that might seem confusing.

Small grammar fixes and clarifications

---

cores/esp32/pgmspace.h

Also added missing pgm_read_ptr define
See: https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/328511332 and https://github.com/PaulStoffregen/cores/commit/8a02ea67f577c1798b50c38da9b74296a861b45a#diff-6e1ff9551639ac89d99617863bf84e10

Workaround strict-aliasing warnings

---

libraries/Update/src/Update.h
libraries/Update/src/Updater.cpp

This is a more or less verbatim port from the ArduinoOTA library to the UpdateClass. Usage example:
```
Update.onProgress(
[](size_t current, size_t total) {
Serial.printf("\r  received %d of %d bytes           ", current, total);
}
);
```
Very useful for possible inclusion in the HttpUpdate library.

Add progress callback to Update::writeStream().

---

libraries/DNSServer/src/DNSServer.cpp
libraries/DNSServer/src/DNSServer.h

I had problem with the last version of the DNS server lib, there were lots of malformed packets on Wireshark and I could not get the library to work. So I checked what was done in the ESP8266 library, integrated some of it and prettified a bit the whole thing. Everything should be a little clearer for someone trying to integrate new functionalities. Tested it with success with WiFiManager.

DNS Server : bug fix and prettifying

---

docs/arduino-ide/debian_ubuntu.md

As discussed in #1042.
FIXED: The script currently tries to run Python 2 with the command `python`. To run Python 2, the command `python2` should be used.

Changed Python version in Debian/Ubuntu install instructions

---

boards.txt

It appears that all boards which use the current partition size of 0x140000 for apps should also have upload.maximum_size=1310720 in boards.txt
Also see: https://github.com/espressif/arduino-esp32/issues/339

Fix upload.maximum_size as current partition size 0x140000 for esp32vn-iot-uno & heltec boards

---

libraries/Ticker/examples/Arguments/Arguments.ino
libraries/Ticker/examples/Blinker/Blinker.ino
libraries/Ticker/keywords.txt
libraries/Ticker/library.properties
libraries/Ticker/src/Ticker.cpp
libraries/Ticker/src/Ticker.h

Add Ticker library

---

cores/esp32/Esp.cpp

esp_efuse_mac_get_default() only stores into the bottom 6 bytes of it's 8-byte argument, so must initialize the arg to zero to avoid trash on the stack.

FIX: getEfuseMac can return random data

---

tools/get.py

See  https://stackoverflow.com/questions/6812031/how-to-make-unicode-string-with-python3
May unicode an alias for str()

Python 3 fails,  unicode is not needed or supplied

---

libraries/ESPmDNS/src/ESPmDNS.cpp

The ESP8266 version of the mDNS library expected service name and protocol **without** leading `_` (underscore). The ESP32 version expected service name and protocol **with** leading `_` (underscore).
This small change makes the ESP32 version compatible with the ESP8266 version and keeps backward compatibility with existing code by accepting service name and protocol either **with or without** leading `_` (underscore).
See issues #962 #387
Tested with following combinations:    
```cpp
MDNS.addService("test1","tcp",9998);
MDNS.addServiceTxt("test1", "tcp", "id", "mDNS-Test");
MDNS.addService("_test2","tcp",9998);
MDNS.addServiceTxt("_test2", "tcp", "id", "mDNS-Test");
MDNS.addService("test3","_tcp",9998);
MDNS.addServiceTxt("test3", "_tcp", "id", "mDNS-Test"); …
```

Make ESPmDNS compatible to ESP8266mDNS

---

libraries/HTTPClient/src/HTTPClient.cpp

If the unread data is very large, cleaning up byte by byte will take a long time.
on a http radio stream easily >=60s observed.
so just flush tcp buffer instead of reading it byte by byte.
thanks to @xiruilin and @Uksa007

HTTPClient: make clean up faster (fixes #828)

---

cores/esp32/esp32-hal-spi.c

Fixes SPI mode setting (Issue #1094)

---

libraries/SPIFFS/examples/SPIFFS_Test/SPIFFS_Test.ino

Update SPIFFS test to show more detail to help for checking for poor/inconsistent FLASH operation.

Add additional SPIFFS test detail

---

tools/get.py

Simple fixes - found when passing the code through pylint.
* fix typos
* fix docstring format

Fix coding stype as per PEP8

---

libraries/WiFi/src/WiFiGeneric.cpp

fixes
#1081 
#1086 
(to be merged into master as soon as possible please)

fix issue 1081 and 1086 Wifi connection error when using STATIC IP settings

---

package/package_esp32_index.template.json

Updated the package template (used by tools/get.py) to download the new mkspiffs tool. This is in reference to https://github.com/espressif/arduino-esp32/issues/1022,  and is necessary because of a change implemented in Dec 2017. Currently, the mkspiffs that is installed by get.py does not work with arduino-esp32, causing problems for https://github.com/me-no-dev/arduino-esp32fs-plugin.

Updated to download mkspiffs 0.2.2

---

cores/esp32/esp32-hal-misc.c

The cycle count that micros() is using to report timing is a PER Task value.  When micros() or delayMicroseconds() is called from different Tasks, the lastCycleCount value may have no relationship to the current Task specific cycleCount. If the current cycleCount is less than the saved lastCycleCount a rollover condition is assumed. This erroneous conditions results in incorrect delays and reported microseconds.  This fix creates thread local storage so that each Task will have accurate microsecond reporting and delays.  The reported microseconds are not real time, they are microseconds of the current Task execution.

micros() returning inconsistent values when call from different tasks

---

libraries/ArduinoOTA/keywords.txt
libraries/ESPmDNS/keywords.txt
libraries/Ticker/keywords.txt
libraries/Update/keywords.txt

The Arduino IDE currently requires the use of a tab separator between the name and identifier. Without this tab the keyword is not highlighted.
Reference:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keywords

Use correct separator in keywords.txt

---

libraries/WiFi/src/WiFiAP.cpp

same as esp8266 PR I submitted.
`esp_wifi_set_config(WIFI_IF_AP, &conf)`  returns blank error code, if authmode is not open when password is not set. 
NOT documented anywhere I can tell.

fixes #1249 softApDisconnect fails always

---

cores/esp32/HardwareSerial.cpp
cores/esp32/HardwareSerial.h

I am in trouble because I can not disable instances of wide area serial
This implementation was included in ESP 8266, so I ported it

Can not invalidate global serial instance

---

libraries/Wire/src/Wire.cpp

This code allows Wire.begin() to assign the default values of SDA, and SCL only if they have not been previously configured.  Arduino libraries that use Wire() usually re-init the I2C interface in their initialization code with a call to Wire.begin().  If a user app sets custom pins assignment in setup(); These assignments will be overwritten with the default values  whenever Wire.begin() is called.

Preserver custom pin assigments with Wire.begin(custom_sda,custom_scl)

---

cores/esp32/esp32-hal-log.h

I'm trying to build the IDF A2DP source example, and the Arduino core is getting pulled in.
BluetoothSerial uses ESP_LOGI/E/W but esp32-hal-log.h doesn't define those because esp_log.h is hidden behind an #ifdef.
```
/Users/george/esp/esp-idf/components/arduino/libraries/BluetoothSerial/src//BluetoothSerial.cpp: In function 'void esp_spp_cb(esp_spp_cb_event_t, esp_spp_cb_param_t*)':
/Users/george/esp/esp-idf/components/arduino/libraries/BluetoothSerial/src//BluetoothSerial.cpp:48:45: error: 'ESP_LOGI' was not declared in this scope
ESP_LOGI(SPP_TAG, "ESP_SPP_INIT_EVT");
^
/Users/george/esp/esp-idf/components/arduino/libraries/BluetoothSerial/src//BluetoothSerial.cpp:69:111: error: 'ESP_LOGV' was not declared in this scope
ESP_LOGV(SPP_TAG, "ESP_SPP_DATA_IND_EVT len=%d handle=%d", …
```

fix Arduino component build when CONFIG_ARDUHAL_ESP_LOG is turned off

---

cores/esp32/HardwareSerial.cpp
cores/esp32/HardwareSerial.h
cores/esp32/esp32-hal-uart.c
cores/esp32/esp32-hal-uart.h

Implementation for availableForWrite() for HardwareSerial.
I have used this for doing non-blocking updates on a Nextion HMI display.

HardwareSerial - availableForWrite() support

---

docs/arduino-ide/windows.md

In order to execute ```git submodule update --init --recursive```  `Git Bash` session must be pointing to ```[ARDUINO_SKETCHBOOK_DIR]/hardware/espressif/esp32```

Corrected Instructions for Windows typo error

---

Kconfig.projbuild
boards.txt
tools/partitions/min_spiffs.csv

with minimal SPIFFS partition size for bigger apps and OTA support 
useful for problems:
https://github.com/espressif/arduino-esp32/issues/1194
https://github.com/espressif/arduino-esp32/issues/1282
but leaving the OTA functionality available (unlike no_ota scheme)
addition for:
https://github.com/espressif/arduino-esp32/pull/1296/commits/535a55dd4ca19d7fa10d10e47367ed8edd7b866b
https://github.com/espressif/arduino-esp32/pull/1296/commits/75b08d542f560d1b588f47a43100acd43a869064
P.S. is there a possibility to add partitions select for all available boards? (not only for esp32 dev board)

Additional partition scheme min_spiffs

---

libraries/WiFi/src/WiFiGeneric.cpp

This PR calls `esp_wifi_set_storage(WIFI_STORAGE_RAM);` when persistent WiFi configuration is not desired.
according to the ESP32 API reference guide the default is to store WiFi configuration in NVS.
esp_err_t esp_wifi_set_storage(wifi_storage_tstorage)
Set the WiFi API configuration storage type.
Attention
1. The default value is WIFI_STORAGE_FLASH

Fix WiFi.persistent(false); having no effect.

---

libraries/WiFiClientSecure/src/WiFiClientSecure.cpp
libraries/WiFiClientSecure/src/WiFiClientSecure.h
libraries/WiFiClientSecure/src/ssl_client.cpp
libraries/WiFiClientSecure/src/ssl_client.h

This PR ports `verify` function from ESP8266 WiFiClientSecure which verifies remote certificate fingerprint.
Since sha1 is no longer secure, I switched to sha256.
Fixes #278

Port SSL fingerprint checking from ESP8266 WiFiClientSecure to ESP32

---

libraries/WiFi/src/WiFiClient.cpp

`WiFiClient::connected()` incorrectly checks `errno`. If any other function before this call sets `errno`, the `connected()` returns false even though `recv()` result was 0. This is because `recv` function does not reset `errno` variable on successful operation and old unknown value is used in switch.
This behaviour can be observed when using multiple `WiFiClient` objects and one of them disconnects with an error. Subsequent `connected()` call on a healthy connection would return false due to a previous set `errno`.
I propose a change to only check for `errno` if `recv()` call fails.

Fix WiFiClient error handling

---

docs/arduino-ide/mac.md

I had no idea what `~/Documents/Arduino` represents as _my_ sketch book location is different. Also fixed a list formatting glitch.

Add note about sketch book location

---

cores/esp32/pgmspace.h
libraries/WiFi/examples/WiFiClientEvents/WiFiClientEvents.ino
libraries/WiFi/src/WiFiGeneric.cpp
libraries/WiFi/src/WiFiGeneric.h
libraries/WiFi/src/WiFiType.h

+ Fix for WiFi onEvent std::functional #1174
+ Minor fix for #1185 strcat_P
I couldnt work out how to remove the wifif event like how the other functions do, using a std::functional since i cant equate functionals as the same (ie the == operater doesnt work), thus i had to use an id work around, which IMHO isnt a bad thing, Please review and tell me how i can improve :) (my fist PR here....)

std::functioanl for WFIF event + Minor fix

---

boards.txt

`build.board` is used to define a macro but `-` is not a permitted character in macro names. This causes the macro name to actually be only everything up to the first `-` and also many warnings when compiling for one of these boards:
```
<command-line>:0:14: warning: ISO C++11 requires whitespace after the macro name
<command-line>:0:14: warning: ISO C99 requires whitespace after the macro name
```
I have followed the convention of the other `build.board` names by replacing `-` with `_`.
Related:
https://github.com/espressif/arduino-esp32/pull/812
https://github.com/espressif/arduino-esp32/pull/1187

Change - to _ in build.board names

---

cores/esp32/esp32-hal-sigmadelta.c

The esp-idf expects duty values for the the sigma delta modulator in the range of -128 to 127
The arduino framework is supposed to use the range 0-255 thus the offset calculation was wrong.

Fix wrong range for sigma delta duty cycle

---

docs/esp-idf_component.md

resolves espressif/arduino-esp32#1434

Added link to compilation issues for arduino as esp-idf component

---

.gitmodules

This library is a port of the Microsoft Azure IoT device SDK for C to Arduino for esp32 devices. It allows user to use several Arduino compatible ESP32 boards with Azure IoT Hub.

Add submodule of Azure IoT library

---

tools/espota.py

In our case the timeout is too small for the device to accept the invitation as it might be busy processing the loop. So the ability to specify timeout for the invitation is a nice to have feature for us.
And the second part of the pull request is to verify the last few responses from device to check for `OK` result as you can't guarantee the order of responses.
We noticed several times that the result is coming after 2nd or 3rd response in the while loop. This will avoid wrong results - showing error even when the OTA update is successful.

[OTA] Add UserSelectable timeout for invitation to device 

---

libraries/ESPmDNS/src/ESPmDNS.cpp
libraries/ESPmDNS/src/ESPmDNS.h

This patch is for adding methods which get TXT record values from mDNS result.

add support for TXT records in mDNS query responses

---

cores/esp32/esp32-hal-dac.h

Missing include gpio.h in esp32-hal-dac.h. Fixes https://github.com/espressif/arduino-esp32/issues/1500

Missing include gpio.h in esp32-hal-dac.h

---

package/package_esp32_index.template.json
platform.txt

Requires get.py/get.exe to be run again. On Mac, you need to manually delete `tools/esptool` prior to running get.py

Update esptool to be compatible with the packager

---

tools/build-release.sh
tools/deploy.sh

Arduino-esp32 release mgmt. improvements and fixes

---

cores/esp32/esp32-hal-i2c.c

If Core Debug Level is at DEBUG, a confusing debug message will be emitted if the I2C transaction takes longer complete than the  calculated minimum time.  This original debug message was just to prove that this new i2c code could correctly handle SCL stretching or interrupt latency issues. This delay is not a problem, or an error.  Usually it is caused by a higher priory interrupt starving the i2c ISR.  Usually WiFi is the culprit.  As long of this delay is within the configured timeout (by default 50ms, or can be set with Wire.setTimeOut(milliseconds);) no problem will occur and the transaction will successfully complete.
Chuck.

Remove confusing Debug output.

---

cores/esp32/esp32-hal-uart.c

`uartFlush()` does not work after soft reset due to a hardware bug in ESP32. This was fixed in ESP-IDF by reading out all data from the buffers instead of using reset bits.
Using reset bits on UART1 also corrupts data in UART2. From technical reference manual:
> UART2 doesn’t have any register to reset Tx_FIFO or Rx_FIFO, and the UART1_TXFIFO_RST and UART1_RXFIFO_RST in UART1 may impact the functioning of UART2. Therefore, these two registers in UART1 should only be used when the Tx_FIFO and Rx_FIFO in UART2 do not have any data. (R/W)
Hence UART should only be flushed by reading out.
ESP-IDF commits:
https://github.com/espressif/esp-idf/commit/4052803e161ba06d1cae8d36bc66dde15b3fc8c7
https://github.com/espressif/esp-idf/commit/492db0591d0c5643cb863b76600ab0bf5a204b64
Fixes: #662

Port UART reset fix from ESP-IDF

---

tools/build-release.sh
tools/deploy.sh

* rel.notes handling improved
* script exec fails on curl error

Arduino ESP32 release management update

---

libraries/EEPROM/EEPROM.cpp

EEPROM.readstring was returning an extra character

---

boards.txt
variants/xinabox/pins_arduino.h

We have a product based off the ESP32 WROOM-32 module.  
Information of the product can be found on our [store](https://xinabox.cc/products/cw02).
Additional info can be found on our [wiki](https://wiki.xinabox.cc/CW02_-_Wi-Fi_%26_Bluetooth_Core).

Add XinaBox CW02 to supported boards

---

cores/esp32/esp32-hal-i2c.c

the 'eject' ERROR is and indication of an interrupt triggering without an source.  I am working to eliminate these unserviceable interrupts.  This update increase stability on a HelTek Wifi Lora 32 board. with a SSD1306 OLED.  This update fixes a glaring error in the interrupt allocation code, the Interrupt mask was wrong.  I also dynamically adjust the FiFo thresholds based on Bus clockrate. The change to FiFo thresholds has reduced the number for 'eject' events.  I also change 'eject' from and ERROR to DEBUG.  An 'eject' event does not compromise i2c transmissions. It happens after a transaction has completed. 
Chuck.

Spurious Interrupts Temporary fix 20180711

---

libraries/EEPROM/EEPROM.cpp
libraries/EEPROM/EEPROM.h

EEPROM.h uses data types which are declared through Arduino.h but that file does not contain an `#include` directive for Arduino.h. This does not cause any problems when the EEPROM library is `#included` from a .ino file because the Arduino IDE automatically adds an `#include` directive for Arduino.h but this is not the case for .cpp files. If a .cpp file has an `#include` directive for EEPROM.h that does not follow an `#include` directive for Arduino.h then compilation fails:
```
E:\arduino\hardware\espressif\esp32\libraries\EEPROM/EEPROM.h:91:5: error: 'float_t' does not name a type
float_t readFloat(int address);
^
E:\arduino\hardware\espressif\esp32\libraries\EEPROM/EEPROM.h:92:5: error: 'double_t' does not name a type
double_t readDouble(int address);
^ …
```

EEPROM library: Move #include of Arduino.h to header file

---

tools/build-release.sh
tools/deploy.sh

- better merging of user/generated release notes (EOL processing)
- whole string escaped through JSON-encoding (python) - all UNICODE chars allowed now

Release notes formatting update

---

libraries/WebServer/src/Parsing.cpp
libraries/WebServer/src/WebServer.cpp
libraries/WebServer/src/WebServer.h

Currently post args are only available at the end of upload but they are already listed - this PR just expose them with minimal changes
It also set a define for post args array size originaly set to 32

expose post args during upload

---

libraries/ArduinoOTA/src/ArduinoOTA.cpp
libraries/ArduinoOTA/src/ArduinoOTA.h

Currently the timeout for OTA packets is set as 1 sec, which is not good enough in a slower connection. This PR enables the clients to set custom timeout for OTA packets.

[OTA Timeout] Added ability set OTA timeout in the OTA client

---

cores/esp32/esp32-hal-i2c.c

This version no longer needs an interrupt for each byte transferred. It only needs interrupts for START, STOP, FIFO empty/Full or error conditions.  This dramatically reduces the interrupt overhead.  I think the prior version was causing an interrupt overload condition where the ISR was not able to process every interrupt as they happened.

Fix for spurious interrupts during I2C communications

---

libraries/WiFi/src/WiFiUdp.cpp

If you receive a package with a data length of zero, parsePacket returns zero, but rx_buffer will be created. So if you perform another parsePacket you will get a zero, even if something could be read. This example would not work: https://www.arduino.cc/en/Reference/EthernetUDPParsePacket
Also I added a check if rx_buffer exist when you try to flush it.

UDP Packet with zero data length

---

boards.txt
variants/m5stack_fire/pins_arduino.h

Add M5Stack-FIRE board 16MB FLASH, 4MB PSRAM.

Add M5Stack-FIRE board

---

libraries/WiFi/src/WiFiUdp.cpp

When a package of size 0 arrives, "buf" is created, but never released. (Sorry, that was my mistake in the last patch)

Memory leak

---

libraries/WebServer/src/Parsing.cpp
libraries/WebServer/src/WebServer.h

Functions _uploadReadByte and _parseForm were modified in order to speed up uploading data. 
Now there is no need to call time consuming client.connected() method.

WebServer Speed Up

---

README.md
docs/arduino-ide/boards_manager.md

Removed links to releases page from boards_manager.md to make it less confusing.  They are on the main README.md now.

Cleanup on README and boards_manager

---

tools/espota.py

Using OTA with platformio, I sometimes get an error like this:
20:14:21 [DEBUG]: Options: {'timeout': 10, 'esp_ip': '192.168.178.45', 'host_port': 44255, 'image': '.pioenvs\\d1_mini\\spiffs.bin', 'host_ip': '0.0.0.0', 'auth': '', 'esp_port': 8266, 'spiffs': True, 'debug': True, 'progress': True}
20:14:21 [INFO]: Starting on 0.0.0.0:44255
20:14:21 [INFO]: Upload size: 1028096
Sending invitation to 192.168.178.45
20:14:21 [INFO]: Waiting for device...
Uploading: [============================================================] 100% Done...
20:14:39 [INFO]: Waiting for result...
20:14:39 [INFO]: Result:
20:14:39 [INFO]: Result:
20:14:39 [INFO]: Result:
20:14:39 [INFO]: Result:
20:14:39 [INFO]: Result:
20:14:39 [ERROR]: Error response from device
*** [uploadfs] Error 1
On investigation I found …

[OTA] Fix "Error response from device" if OK response comes to early

---

cores/esp32/esp32-hal-i2c.c
cores/esp32/esp32-hal-i2c.h
libraries/Wire/src/Wire.cpp
libraries/Wire/src/Wire.h

pr #1665 introduce a problem with ReSTART, when solving this problem I found an interaction between the TxFifo refill, RxFifo empty and CMD[] fill.  during certain sequences a dataqueue command would be skipped, this skipping resulted in a mismatch between the contents of the TxFifo and the i2c command sequence.  The problem manifested as an ACK error. 
In addition to this required bug fix I propose:
* `Wire.begin()` be changed from a `void` to a `bool` this will allow the reset functionality of `Wire.begin()` to be reported.  Currently `Wire.begin()` attempts to reset the i2c Peripheral, but cannot report success/failure.
* `Wire.busy()` be added. this `bool` function returns the hardware status of the bus. This status can be use in multi-master environments for application level …

ReSTART fix, with others

---

cores/esp32/esp32-hal-i2c.c

If the esp32 is reset during a i2c read cycle the slave device may be in control of the SDA line.  
If the SDA line is held low, the esp32 cannot issue a START or STOP to recover the bus. 
The previous code did not correctly configure the SCL output pin, and it cycled SCL 9 times with SDA Low.  Since the slave device was in a READ cycle, it just continued outputting the bits of the current byte.  When the ACK/NAK bit space occurred, The low output value of SDA was interpreted as ACK so the slave device continued with the next byte.  It never terminated the READ cycle. 
This new code will correctly recover from an interrupted READ

Improve I2C bus recovery of Interrupted READ cycle

---

variants/heltec_wifi_lora_32/pins_arduino.h

The original pins_arduino.h did not correspond to the actual hardware.

Correct pins for actual hardware

---

libraries/BluetoothSerial/src/BluetoothSerial.cpp

- Delete queue at end
- Close BT connection before end
- DeInit SPP
Fix https://github.com/espressif/arduino-esp32/issues/1798

Fix BTserial memory leaks

---

cores/esp32/HardwareSerial.cpp
cores/esp32/HardwareSerial.h
cores/esp32/esp32-hal-uart.c
cores/esp32/esp32-hal-uart.h

This adds functionality analogous to the ESP8266's Arduino core's `HardwareSerial::setRxBufferSize`, providing users functionality allowing them to increase the size of the rx buffer as a way of preventing lost characters when using high baud rates.  Given that the queue size is only 256 characters by default, it is terribly easy for fast serial connections to exceed the default buffer length.

Adds functionality allowing size of HardwareSerial's RX buffer to be changed at runtime.

---

cores/esp32/esp32-hal-uart.c

This is a possible fix for uart fifo problem.

_uart_isr use wr_addr != rd_addr as test for internal queue not empty

---

libraries/ESP32/examples/DeepSleep/TimerWakeUp/TimerWakeUp.ino

Flush serial in DeepSleep example to allow print before sleep

---

cores/esp32/Arduino.h
libraries/WiFi/src/WiFiClient.h
libraries/WiFi/src/WiFiGeneric.cpp
libraries/WiFi/src/WiFiMulti.h

cores: replace max and min macros with imports from std

---

libraries/WiFi/examples/WiFiClientEnterprise/WiFiClientEnterprise.ino

Few testers let me know, they were unable with connection to Eduroam network under PEAP+MsCHAPv2 methods.
They were trying many modifications. Solution is very absurd. 
Use function Wifi.mode(); with parameter WIFI_STA for init hardware!
One tester from Italy was able to connect to Eduroam network under TTLS + MsCHAPv2 with that sketch too!
Sketch was tested and worked almost for all testers with that problem (Doesn't worked for EAP-TLS --> where system want certificate from client).
Refer to: 
https://github.com/espressif/arduino-esp32/issues/1381#issuecomment-412073401
https://github.com/espressif/arduino-esp32/issues/1381#issuecomment-414174639
https://github.com/espressif/arduino-esp32/issues/1744#issuecomment-411974121

Fix WifiClientEnterprise - STA mode set

---

cores/esp32/esp32-hal-gpio.c
cores/esp32/esp32-hal-gpio.h

@bertmelis 
When working on an example for the FunctionalInterrupt, I took yours from GPIOInterrupt as base.
However, could not get it to run correctly.
I think the signature of attachInterruptArg is wrong.
With the patch from this PR it works as expected.
Can you take a look ? 
PS : Did not notice when creating FunctionalInterrupt as that implements it's own attach.

attachInterruptArg should take voidFuncPtrArg as argument

---

cores/esp32/esp32-hal-i2c.c

#1869 exposed a resource exhaustion issue. The current HAL layer for I2C support is designed to use a shared interrupt, But, during debugging to solve the interrupt overloading condition identified in #1588, and the generation of pr #1717, the interrupt allocation parameters were changed.  This change was unnecessary, the code will work successfully with shared interrupts.  So, there is no need to assign a private interrupt for each I2C peripheral.

Reduce resource requirements, Share Interrupt

---

cores/esp32/esp32-hal-rmt.c

Small fix to esp32-hal-rmt.c allows as-component projects to compile with locks disabled.

allow component projects to compile with CONFIG_DISABLE_HAL_LOCKS

---

libraries/Wire/library.properties
libraries/Wire/src/Wire.cpp
libraries/Wire/src/Wire.h

This patch will fix issue #1725 
There is no need to have the uint8_t version of the endTransmission() function.
Having both endTransmission(uint8_t) and endTransmission(bool) creates problems. The biggest problem being that endTransmission(0) and endTransmission(1) won't compile like it does on all the other cores.
Simply removing endTransmission(uint8_t) solves the problem.

Wire endTransmission() fix for issue #1725

---

libraries/ESP32/examples/DeepSleep/ExternalWakeUp/ExternalWakeUp.ino
libraries/ESP32/examples/DeepSleep/TimerWakeUp/TimerWakeUp.ino
libraries/ESP32/examples/DeepSleep/TouchWakeUp/TouchWakeUp.ino

Incorrect values used, use the proper defines from header-files instead.

Deep-sleep example-sketches reported wrong wakeup-reason

---

libraries/WiFi/examples/WiFiClientEvents/WiFiClientEvents.ino

Previously, the `switch` statement covered only 2 different events. I took the time to add them all in here.

WiFiClientEvents.ino: Added a message for all event types

---

libraries/WiFi/examples/WiFiClientEvents/WiFiClientEvents.ino

WiFi: improve WiFiEvent list in WiFiClientEvents example

---

libraries/WiFi/src/WiFiAP.cpp

Make WiFi.softAP() fail less easily, attempt to fix #1924

make WiFi.softAP() more robust

---

libraries/WiFiClientSecure/src/WiFiClientSecure.cpp
libraries/WiFiClientSecure/src/WiFiClientSecure.h

Fixes #1957.
Allows a file object to be used as a certificate in WiFiClientSecure.

Added loadCert methods to WiFiClientSecure

---

libraries/WiFi/examples/WiFiClientEnterprise/README.md

Updated table of tested locations, provided table of frequent bugs/errors during authentization, etc

Updated table of tested locations - Enterprise wifi networks - WifiClientEnterprise 

---

libraries/WiFi/examples/WiFiClientEnterprise/WiFiClientEnterprise.ino

**Added to program:**
- counter
- auto restart on unsucessful connection or authentization timeout (30 seconds)
- changed HTTP GET connection
**Tested under boards:**
- ESP32 DevKit V1
- ESP32 DevKitc V4
- Lolin32
**Tested version of Arduino core**
- June 2018

updated WifiClientEnterprise example

---

boards.txt
variants/esp32-poe/pins_arduino.h

Added Olimex board ESP32-PoE. pins_arduino header file based on the ESP32-EVB with changed SS pin and removed BOARD_HAS_1BIT_SDMMC macro. Added the board description in boards.txt file in the same pattern like ESP32-EVB.

Added Olimex ESP32-PoE board definitions

---

cores/esp32/base64.cpp
cores/esp32/libb64/cencode.c

The calculation of the base64 encoded string length is incorrect as pointed out in #827. libbase64 already provides a macro that can be used to calculate the base64 encoded string length.
You also have to increment the calculated size by 1 for the trailing zero character.

use libbase64 macro to calculate base64 length

---

cores/esp32/esp32-hal-uart.c

wait for UART FSM to become idle before uart_flush() returns:
current situation:
new situation:
tested with a simple sketch:
```C++
void setup() {
Serial.begin(112500);
pinMode(26, OUTPUT);
}
void loop() {
static uint32_t lastMillis = 0;
if (millis() - lastMillis > 10000) {
lastMillis = millis();
digitalWrite(26, HIGH);
Serial.write("Hello World!");
Serial.flush();
digitalWrite(26, LOW);
}
}
```
Tested with Serial, Serial1 and Serial2.

fix uart_flush() returning early

---

libraries/BluetoothSerial/src/BluetoothSerial.cpp

BluetoothSerial misbehaves when a second device connects to ESP32 so this helps limit the connections to only 1.
It does not limit the number of devices that can be paired with ESP32 and it does allow any paired device to connect with ESP32 - just one at a time. Note that after the first device connects any following connection attempt is not refused, but it's immediately rejected after connection.

Limit the number of simultaneously connected devices to BluetoothSerial to only one

---

libraries/BluetoothSerial/src/BluetoothSerial.cpp
libraries/BluetoothSerial/src/BluetoothSerial.h

This allow to catch the events when connected /disconnected,, etc...
This also allow to get parameters of events like the remote address of connected devices, etc...
Small change but lot of flexibility

Allow to add custom callback in BT Serial

---

libraries/HTTPUpdate/src/HTTPUpdate.cpp

Remove F() macro's as @me-no-dev suggested in PR #2116.

Remove F() macro's from HTTPUpdate.cpp

---

.travis.yml

**git clone --depth** parameter removed not to limit working tree checkout (default is 50 commits). This is to fix automatic release management issue (missing tags)

Remove git clone --depth parameter

---

cores/esp32/Esp.cpp
cores/esp32/esp32-hal-i2c.c
libraries/SD/src/sd_diskio.cpp
libraries/WiFi/src/WiFiClient.cpp
libraries/WiFi/src/WiFiMulti.cpp
libraries/WiFi/src/WiFiSTA.cpp
libraries/WiFiClientSecure/src/WiFiClientSecure.cpp
tools/sdk/include/vfs/esp_vfs.h

Not used variables / functions due to debug log
Dual define with different values :
cores\esp32/binary.h
#define B110 6
#define B1000000 64
tools/sdk/include/newlib/sys/termios.h
#define B110        3
#define B1000000   23
Local variable returned in WiFiclient Secure

Clean warnings when all warning enabled

---

libraries/SPI/src/SPI.cpp
libraries/SPI/src/SPI.h

Hi,
implemented missing SPI.transfer, required to compile Arduino SPI based Ethernet (W5500)
Splitted the suggested change in Issue #1623, in a header and source part. It compiles, works, but i'm not completely confident with exact location, and if this would be the best solution.
Please review, and accept the proposal. 
Not completely feeling confident with providing the data parameter twice to the transferBytes function, please, just copied it form the suggested solution in #1623 . 
Regards,
Arjan

Fixed Arduino SPI/Ethernet compile issue as described in issue #1623

---

libraries/WiFi/src/WiFiClient.cpp
libraries/WiFi/src/WiFiMulti.cpp

fix https://github.com/espressif/arduino-esp32/issues/2139

 removing log

---

libraries/WiFiClientSecure/README.md
libraries/WiFiClientSecure/examples/WiFiClientPSK/WiFiClientPSK.ino
libraries/WiFiClientSecure/src/WiFiClientSecure.cpp
libraries/WiFiClientSecure/src/WiFiClientSecure.h
libraries/WiFiClientSecure/src/ssl_client.cpp
libraries/WiFiClientSecure/src/ssl_client.h

This PR adds support for using pre-shared keys in TLS connections. MQTT servers seem to start to support this, at least mosquitto does. This is an alternative to generating a self-signed cert and then distributing the cert to all mobile devices. With PSK one can now generate a long random hex string and simply use that as key. It also makes it easy to have multiple identity->key pairs, basically they act like passwords.
I would be happy to write some docs for this, but am not sure where to add given that WiFiClientSecure doesn't have any docs.

WiFiClientSecure: add support for PSK (pre-shared key) ciphers

---

libraries/WiFi/src/WiFiClient.cpp

If ::available() is called before ::connect() _rxBuffer is not initialised

Fix bug in PR #2148: correcting available() introduced an bug!

---

cores/esp32/Esp.cpp
libraries/HTTPUpdate/src/HTTPUpdate.cpp
libraries/HTTPUpdate/src/HTTPUpdate.h
libraries/WiFi/src/WiFiClient.cpp

HTTPUpdate checked if the new sketch would fit into the _current_ partition free space, which was wrong. Now it checks if it fits into the _next_ flash partition.
A size check for a SPIFFS update is added, this was stil 'to do' from the previous PR.
Still to do: the SHA256 hash could be checked if a server sends it in the request header.
This PR includes PR #2155.

Fix HTTPUpdate flash size check and add SPIFFS size check

---

cores/esp32/esp32-hal-misc.c

The file `cores/esp32/esp32-hal-misc.c` attempts to `#include "esp_bt.h"` regardless if Bluetooth is enabled or not (typically via sdkconfig) which causes a compilation error. The actual logic in `esp32-hal-misc.c` is guarded by the `CONFIG_BT_ENABLED` flag so all we have to do is wrap the include with the same flag.
Config with `CONFIG_BT_ENABLED` not set to true will fail compilation with the following error:
```
../components/arduino/cores/esp32/esp32-hal-misc.c:24:20: fatal error: esp_bt.h: No such file or directory
```
This is because `esp_bt.h` isn't added to the CMake includes unless the `CONFIG_BT_ENABLED` flag is set to true. https://github.com/espressif/esp-idf/blob/ae5df5d6ce7c9abd9c8c4731ced96031c29f7fc1/components/bt/CMakeLists.txt#L1-L4
Successful compilation with the …

Fix a esp32-hal-misc.c compilation error if Bluetooth not enabled

---

tools/espota.py

This PR piggybacks on #1695.  @Gei0r originally reported that while the update was successful, it was reported erroneous by espota.py.  I've run into another similar condition, where the expected "OK" is coming concatenated with another recv.
```
07:38:54 [DEBUG]: Options: {'timeout': 10, 'esp_ip': '10.4.20.20', 'host_port': 13414, 'image': '.pioenvs/esp12e_0/firmware.bin', 'host_ip': '0.0.0.0', 'auth': '', 'esp_port': 8266, 'spiffs': False, 'debug': True, 'progress': True}
07:38:54 [INFO]: Starting on 0.0.0.0:13414
07:38:54 [INFO]: Upload size: 293792
Sending invitation to 10.4.20.20
07:38:54 [INFO]: Waiting for device...
Uploading: [============================================================] 100% Done...
07:39:00 [INFO]: Waiting for result...
07:39:00 [INFO]: Result: 536
07:39:00 …
```

OTA success reporting fix

---

cores/esp32/Print.cpp

correct bounds checking in Print::printf to avoid corner case of len=64

---

libraries/HTTPClient/src/HTTPClient.cpp

This is necessary to avoid this log entry from being generated due to invalid usage of setTimeout:
[E][WiFiClient.cpp:236] setSocketOption(): 1006 : 9
This fixes #2213

move call to setTimeout() to after the client connects.

---

cores/esp32/esp32-hal-i2c.c

The I2C hardware has limitations on min and max bus frequency directly related to CPU frequency, bus speed cannot be greater than 1/100 CPU clock, nor less than CPU clock / 8192.

Support CPU frequency changes in I2C driver

---

cores/esp32/esp32-hal-uart.c

@felixstorm reported one more location where a buffer is created but not freed when the size is exactly 64 bytes.

fix #2232 and #2033

---

cores/esp32/HardwareSerial.cpp
cores/esp32/HardwareSerial.h

- This method will be useful for libraries that attempt to find current baud rate of device connected via Serial, for example GSM modems
- Please be aware that some garbage on Serial may occur(an most of times it does) after baud rate is changed
Fixes:
#441

HardwareSerial - add changeBaudRate method

---

variants/lopy/pins_arduino.h
variants/lopy4/pins_arduino.h
variants/t-beam/pins_arduino.h

small fixes in pin definitions:
- changed LORA_IO0 to LORA_IRQ
- added missing SS line for LoPy4
- added missing LORA_RST definition for LoPy4

update board files for LoPy, LoPy4, T-Beam

---

libraries/WiFiClientSecure/src/ssl_client.cpp

Since Mbedtls is running only on internal heap, show internal + PSRAM available memory on logs can confuse the users

[WiFiClientSecure] Shows only free internal heap on logs

---

libraries/WiFi/src/WiFiClient.cpp

Redo PR #2259 Fix WiFiClientRxBuffer::fillBuffer() error, likely solves issue #2212

---

cores/esp32/esp32-hal-i2c.c
libraries/Wire/src/Wire.h

**esp32-hal-i2c.c**
* add callback for cpu frequency changes
* adjust fifo thresholds based on cpu frequency and i2c bus frequency
* reduce i2c bus frequency if differential is too small
**Wire.h**
* version to 1.1.0

Update i2c to support CPU frequency changes

---

cores/esp32/esp32-hal-i2c.c

The i2c peripheral will hang if a READ request is issued with a zero data length.  The peripheral
drops into a continuous timeout interrupt response.  The STOP command can not be set out to the I2C
bus. The SLAVE device correctly ACK'd the address byte, with READ bit set, it has control of the SDA
pin.  The ESP32 send out the next SCL HIGH pulse but, since the SLAVE is in READ Mode, and the First
bit it is sending happened to be a ZERO, the ESP32 cannot send the STOP.  When it releases SDA during
the SCL HIGH, the pin does not change state.  The pin stays low because the SLAVE is outputing a LOW!
The ESP32 drops into a perminent WAIT state waiting for SDA to go HIGH (the STOP).
**esp32-hal-i2c.c**
* add databuff length checks to `i2cRead()` and `i2cWrite()`

I2C fix READ of zero bytes hardware hang

---

libraries/WiFi/src/WiFiGeneric.cpp

`err` is int32_t. `%d` is better

fix log error code format

---

libraries/WiFi/src/WiFiGeneric.cpp
libraries/WiFi/src/WiFiMulti.cpp

```
uint8_t run() {
if(status != WL_CONNECTED || status == WL_NO_SSID_AVAIL || status == WL_IDLE_STATUS || status == WL_CONNECT_FAILED) {
// ...
}
}
```
these code are equal to
```
uint8_t run() {
if(status != WL_CONNECTED) {
// ...
}
}
```
and equal to
```
uint8_t run() {
if(status == WL_CONNECTED) {
return status;
}
// ...
}
```

remove useless condition in if statement

---

libraries/WiFi/src/WiFiClient.cpp
libraries/WiFi/src/WiFiClient.h

Allows a timeout, in milliseconds, to be passed as an optional parameter to WiFiClient.connect().
Currently this is a blocking function which can take up to 20 seconds to return if the server isn't responding. 
- Incidentally, the 'normal' timeout will trigger an error at the usual time so behaviour is unchanged if a timeout isn't provided! (Unfortunately, it will also trigger if the provided timeout is longer; timeout duration is therefore effectively capped at whatever it is normally.) Ideally this would be overriden. Also, a defined default value might be more a better approach (see initial commit for eg.).
- Perhaps using setTimeout would be a better way to set the value. That would leave signatures unchanged and only require setting the value once, instead of tacking it on to every …

Add connect timeout to WiFiClient

---

libraries/WiFi/examples/WiFiClientBasic/WiFiClientBasic.ino

Made debug messages and comments easier to understand/grammatical fixes in WiFiClient example

Clarified comments and debug messages in WiFiClient Example

---

boards.txt
variants/esp32-gateway/pins_arduino.h
variants/esp32-poe/pins_arduino.h

In Board.txt file added board revision submenu for different revisions of the same board. By selecting different revision in the Arduino menu different value of the predefined macro will be applied which is used inside the pins_arduino.h file to make different defines and values for the specific revision.
Added PartitionScheme submenu to our 3 boards, similar to the other ESP32 boards.
In esp32-gateway pin defintions preprocessor conditions added to distingiush different revisions.
In esp32-poe pin definitions is added ethernet power enable pin and also defined macro: BOARD_HAS_1BIT_SDMMC.

New version of the Olimex boards ESP32-EVB/Gateway/PoE

---

variants/wesp32/pins_arduino.h

This sets the default pin assignments for Serial1 and Serial2 correctly for the wESP32.

Add default pin mapping for Serial1 and Serial2

---

cores/esp32/esp32-hal-misc.c

Corrects issue #2430, thanks to @stickbreaker for the very easy solution found! 
This solution is very different from the ESP8266 solution, because on that controller the micros() timer used to calculate millis() is a 32 bit wide counter. On the ESP32 the micros() base counter is 64 bits wide, allowing the solution to be both fast and simple. As I understand from reading topics on the internet, the division by 1,000 needed in this solution should be optimised by the gcc compiler using the same magic number method as in the ESP8266.
The new millis() function was tested (only) one loop of 72 minutes, without an issue.

Correct millis() error causes by micros() overflow every about 72 minutes

---

boards.txt
tools/partitions/default_8MB.csv
variants/heltec_wifi_kit_32/pins_arduino.h
variants/heltec_wifi_lora_32_V2/pins_arduino.h
variants/heltec_wireless_stick/pins_arduino.h

- Added Heltec Automation(TM) newest boards defintion, include WiFi_Kit_32, WiFi_LoRa_32, WiFi_LoRa_32_V2, Wireless_Stick defintions;
- Added 8MB SPI FLASH partition map;
- Update board menu chooices.

Heltec boards defintion and update board menu chooices

---

libraries/WiFi/src/WiFiMulti.cpp

When scanResult is 0 `no networks found ` is logged.

log "no networks found" when scanResult is 0

---

tools/platformio-build.py

Adding the -g3 flag that was omitted in the PIO build script but is present in Arduino IDE build scripts. This flag restores the ability to get line numbers from stack traces for elf files generated in PlatformIO IDE.

Adding debug flag to PIO build script

---

libraries/HTTPClient/src/HTTPClient.cpp
libraries/HTTPClient/src/HTTPClient.h

The existing setTimeout() function is effective only once the client is already connected to the server. Therefore, if there is a problem establishing a connection to the server in the first place (eg. it is offline), connect() will block for up to ~20 seconds regardless of the value passed to setTimeout. 
See https://github.com/espressif/arduino-esp32/issues/1433
This PR introduces a separate, self-explanatory function - setConnectTimeout(int32_t connectTimeout) - to HTTPClient, which simply takes advantage of the WiFiClient connect timeout functionality recently introduced here: https://github.com/espressif/arduino-esp32/pull/2383

Add server connect timeout to HTTPClient

---

libraries/WiFi/src/WiFiClient.cpp

Currently  WiFiClient::write is unable to send messages over 25Kb, because of the hard-coded retry limit of 10, that is getting decremented on every successful send. Since we cannot send more than 2*MTU bytes in one go, and have only 10 retries, write() is limited to approximately 25Kb. Technically it is not a bug, as it correctly returns the number of sent bytes and the caller can set up futher retries. But not all libs are aware of this behavior, for example, WebServer is not.
I suggest improving current behavior by resetting retry counter every time we had a successful write, so the limit of 10 retries will apply to Failed writes only, and will not apply to Successful writes. This will allow to write() blobs of arbitrary sizes.

Reset retry counter upon successful WiFiClient::write

---

cores/esp32/esp32-hal-i2c.c

@cyberman54 from #2250 recommended reducing unnecessary logging.  There have not been any reported problems with i2c and cpu frequency changes since it was implemented in the 1.0.1 release. This pr hides these verbose log reported behind the `ENABLE_I2C_DEBUG_BUFFER` define.  They will be available if necessary, but normally will not be included in compiled code.
Chuck.

Hide log_v behind conditional define, reduce excessive logging

---

boards.txt

Make all the partitions descriptions consistent, they now all show what space allocation you get.

Also show how space is allocated for the default partitions

---

libraries/AsyncUDP/src/AsyncUDP.cpp

If _handler is set, pbuf_free is not called. ~AsyncUDPPacket() calls pbuf_free once but only after calling pbuf_ref in it's constructor. The refcount never reaches zero and the memory allocated for pbuf is never released.

Fix AsyncUDP receive memory leak

---

libraries/Update/examples/AWS_S3_OTA_Update/AWS_S3_OTA_Update.ino

When the file.bin is more than 32767 characters. 
I change "int" in "long" for contentLength.

File with more than 32,767 characters

---

cores/esp32/Stream.cpp
cores/esp32/Stream.h
libraries/WebServer/examples/WebUpdate/WebUpdate.ino
libraries/WebServer/src/Parsing.cpp
libraries/WiFi/src/WiFiClient.cpp

This is a timeout based alternative to https://github.com/espressif/arduino-esp32/pull/2655. I haven't tested it yet.

Alternative Improve _uploadReadByte 

---

libraries/ESP32/examples/ESPNow/Basic/Slave/Slave.ino

The former way generates the following warning:
ISO C++ forbids converting a string constant to 'char*'
This change makes a character array the size of the string with null ending. It's clearer and gets rid of the warning.

Properly allocate string and remove warning

---

libraries/EEPROM/src/EEPROM.cpp

String EEPROMClass::readString (int address) returns **"0"** instead of empty string **""**
> ```String thisString = String(13);```
> gives you the String "13". 
[source](https://www.arduino.cc/reference/en/language/variables/data-types/stringobject/)

EEPROM return empty string instead of "0"

---

boards.txt

With a little bit of copy, paste and rename I added cpu frequency to the arduino IDE menu.
Tested with 240, 160 and 80 MHz.
I am not sure if the plan is to add this to all of the board definitions, so feel free to reject or close this PR.

add lolin32 CPU freq choice

---

libraries/WebServer/src/WebServer.cpp

This PR addresses the GCC `reorder` warning caused by [a recent commit that adds CORS support to `WebServer`](https://github.com/espressif/arduino-esp32/commit/672e4faa92b0560352f34fd99f67ff388e05d413). This error prevents compiling using the default `idf.py build` workflow which, for some reason, sets `-Werror`.

Fix Werror in WebServer that prevents compiling using idf.py

---

libraries/EEPROM/src/EEPROM.cpp
tools/platformio-build.py

Like #2700 except for https://github.com/espressif/arduino-esp32/commit/619568db5bcc219091c653a5ced5e378b3a5643b. Hopefully adding the CFLAG to CI will prevent this from happening (yet) again?

Fix Werror=reorder for idf.py build

---

cores/esp32/StreamString.cpp
cores/esp32/WString.cpp
cores/esp32/WString.h

I redid the ESP8266 WString library to enable small string optimization
(SSO) a while back, and think it would be helpful even on the ESP32 with
its higher memory complement.
SSO avoids lots of tiny mallocs() on the heap which cause fragmentation
by using the memory in the class object itself to store the actual
string and only mallocing() for buffers that are larger than what can
fit in thie class object.  Modern C++ std::string implementations have
this optimization as well, but since we're using Arduino strings we had
to roll our own.

Copy ESP8266 String w/SSO to ESP32 repo

---

boards.txt
package/package_esp32_index.template.json
variants/d1_mini32/pins_arduino.h
variants/mini32/pins_arduino.h

The "WEMOS D1 MINI ESP32" category of boards provide pin-out compatibility to the family of shields for the popular WEMOS/LOLIN D1 MINI series of ESP8266 boards. In order to make recompiling sketches as easy as possible, this board description includes definitions for the pins of the D1 MINI.
Among the other names for the same board layout are mini32, HW-665, WEMOS TTGO MINI32.

Add board "WEMOS D1 MINI ESP32".

---

cores/esp32/WString.h

Fixes Arduino.h redefinition errors, as found by @dok-net

Undo the redefinition of FPSTR from 8266 merge

---

libraries/BLE/src/BLEAdvertising.cpp
libraries/BLE/src/BLEAdvertising.h

Implemented the function used to change the advertised BLE address.
As per the specification, there are multiple address types that can be user set (Random, Static, etc.). Currently this library only uses the address issued to the device during manufacture. This pull request adds the functionality of user changeable BLE addresses.
There is currently no implementation of this function that I am aware of, so use in projects should be minimal, if at all. Changing the functions signature should not break any significant number of projects.

Defined BLE setPrivateAddress()

---

libraries/BLE/src/FreeRTOS.cpp

Fixes the problem of giving a mutex from a callback with the latest IDF. Also addresses an occasional assert that happens when the btc_task callback gives the semaphore and causes an assert due to both cores potentially writing m_owner concurrently.

Fix semaphores in IDF & std::string assert

---

cores/esp32/StreamString.cpp

Sorry, @me-no-dev, I thought we'd hammered out the issues in the SSO conversion, but there's one more but just found.
As found by @mongozmaki in https://github.com/esp8266/Arduino/pull/6035
With SSO implementation in String, StreamString::write generates wrong
strings under some circumstances.  Reason is that String::len() returns
strlen(sso_buf) if SSO=true but with newly written data
(in StreamString::write) the null-termination missing at the time len()
is called.
Furthermore, len() is called twice which is inefficient if SSO=true.

StreamString SSO fix

---

cores/esp32/Arduino.h

* Other Arduino cores uses a macro to redefine libc abs() to take any  type, meaning `abs(-3.3) == 3.3` not the normal libc result of 3.
* 1e4bf14a3 (#1783) replaced similar `min`, `max` macros with c++ stdlib. However this change includes `<algorithm>` after the line which defines the abs() macro. `<algorithm>` includes `<cstdlib>` which undefines `abs()` and re-defines it.
* As a result, current esp32 Arduino core has a bug compared to other Arduino cores: `abs()` is now the plain libc version which only takes integers, so `abs(-3.3) == 3`. As reported here: https://github.com/espressif/esp-idf/issues/3405
This fix tries to keep in the spirit of #1783 by using libstdc++ rather than a macro, for the same effect (abs can take any compatible type). The other option would be to include …

Use std::abs for a float-compatible abs() function

---

boards.txt
variants/ttgo-t1/pins_arduino.h

Fixes https://github.com/espressif/arduino-esp32/issues/2740
Default settings for SS/MISO/MOSI/SCK are set to avoid SPI.begin() with custom pin usage.

Adding TTGO T1 board definition

---

libraries/BLE/src/BLECharacteristic.cpp
libraries/BLE/src/BLECharacteristic.h

It's fixed that multi_heap_free failed like below. It sometimes happen when esp32 recevied ble data fast from another device so I added semaphore so It was fixed.
assertion "head != NULL" failed: file "/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/heap/multi_heap_poisoning.c", line 214, function: multi_heap_free
ELF file SHA256: 0000000000000000000000000000000000000000000000000000000000000000
Backtrace: 0x4008faf8:0x3ffd1d60 0x4008fd75:0x3ffd1d80 0x40157317:0x3ffd1da0 0x400954cd:0x3ffd1dd0 0x40085d82:0x3ffd1df0 0x4008c131:0x3ffd1e10 0x4000bec7:0x3ffd1e30 0x401889d5:0x3ffd1e50 0x4018c05e:0x3ffd1e70 0x400ddcb6:0x3ffd1e90 0x400d99ba:0x3ffd1ed0 0x400d9a5d:0x3ffd1ef0 0x400da2fd:0x3ffd21a0 0x400dd105:0x3ffd21c0 0x400dd539:0x3ffd2210 0x400dcaa2:0x3ffd2230 0x400dae35:0x3ffd2290 …

Fixed multi_heap_free failed during setting the value of the characteristic in BLE Library.

---

libraries/BLE/src/BLERemoteCharacteristic.cpp

When calling the function `BLERemoteCharacteristic::readValue()` sometimes it gave this error:
[D][FreeRTOS.cpp:158] take(): Semaphore taking: name: ReadCharEvt (0x3fff8f00), owner: <N/A> for readValue
[D][FreeRTOS.cpp:167] take(): Semaphore taken:  name: ReadCharEvt (0x3fff8f00), owner: readValue
[D][BLEDevice.cpp:154] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 4] ... Unknown
[D][BLEClient.cpp:158] gattClientEventHandler(): gattClientEventHandler [esp_gatt_if: 4] ... Unknown
assertion "heap != NULL && "free() target pointer is outside heap areas"" failed: file "/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/heap/heap_caps.c", line 267, function: heap_caps_free
abort() was called at PC 0x4016a1cf on core 0
Backtrace: 0x40093d80:0x3ffe2310 …

FIXED "heap != NULL && "free() target pointer is outside heap areas" on BLERemoteCharacteristic::readValue()

---

CMakeLists.txt

Ignore the error about a potentially uninitialized variable
in the Azure library that will occur when compiling as a component
in ESP-IDF.
See https://github.com/espressif/arduino-esp32/issues/2822

Ignore Werror-maybe-uninitialized from Azure IoT Library

---

libraries/HTTPClient/src/HTTPClient.cpp
libraries/HTTPClient/src/HTTPClient.h

HTTPClient's Persistence support does not follow the RFC 2068 standard for HTTP 1.1 but follows HTTP 1.0 instead. This [issue](https://github.com/esp8266/Arduino/issues/6152) was found by @jpboucher for the **ESP8266**. With this PR it is fixed for the **ESP32** too.

Fix HTTPClient persistance issue for HTTP1.1 see ESP8266 issue #6152

---

Kconfig.projbuild

I think FFat went into core at the same time as the selective menuconfig, so it did not get an option in there.

Make a selective menuconfig option for FFat

---

libraries/FFat/src/FFat.cpp

Fix : warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]
Fix : warning: unused variable 'res' [-Wunused-variable]

Fix warnings in platformio for FFat libary

---

libraries/WiFi/src/WiFiMulti.cpp
libraries/WiFi/src/WiFiMulti.h

First PR to esp32 - testing the waters with a simple clean-up. Four commits, most significantly using macros instead of magic numbers for case labels but also some smaller changes.

Cleanup WiFiMulti

---

libraries/WiFi/src/WiFiGeneric.cpp

This resolves the following build warning when using WiFi:
```
[...]\hardware\espressif\esp32\libraries\WiFi\src\WiFiGeneric.cpp: In static member function 'static esp_err_t WiFiGenericClass::_eventCallback(void*, system_event_t*)':
[...]\hardware\espressif\esp32\libraries\WiFi\src\WiFiGeneric.cpp:336:107: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
if(event->event_id < 26) log_d("Event: %d - %s", event->event_id, system_event_names[event->event_id]);
```

Fix warning -Wempty-body by adding braces to 'if' stmt body

---

libraries/BLE/src/BLEAdvertising.cpp

Simple fix for missing ';' in the file libraries/BLE/src/BLEAdvertising.cpp.

fix for BLE Library Compile Error #2866

---

tools/espota.py

Tidied up references to the ESP8266, and set the correct default port for the ESP32.
The latter point is the main reason for this PR - I discovered that when you run the `espota.py` tool from this repo against a ESP32 _without_ overriding the default port it would not work... but it was being overridden when run via the Arduino IDE. 
I'm hoping this is just leftovers, and can be corrected?

ESP8266 => ESP32 tidyup, set correct default port

---

cores/esp32/esp32-hal-i2c.c

Some Debugging variables were enabled at ERROR level instead of DEBUG.  Specifically `tAfter` and `tBefore`

Fix Unused Variable Warning in I2C code.

---

.gitignore

The Arduino IDE for Visual Studio in part uses the standard MS Visual Studio project layout.

Expand gitignore to cover files created by Visual Micro

---

libraries/BLE/src/BLEAddress.cpp
libraries/BLE/src/BLEAdvertisedDevice.cpp
libraries/BLE/src/BLECharacteristic.cpp
libraries/BLE/src/BLECharacteristicMap.cpp
libraries/BLE/src/BLEClient.cpp
libraries/BLE/src/BLEClient.h
libraries/BLE/src/BLEDescriptor.cpp
libraries/BLE/src/BLEDescriptorMap.cpp
libraries/BLE/src/BLEDevice.cpp
libraries/BLE/src/BLEEddystoneTLM.cpp
libraries/BLE/src/BLEExceptions.cpp
libraries/BLE/src/BLERemoteCharacteristic.cpp
libraries/BLE/src/BLERemoteDescriptor.cpp
libraries/BLE/src/BLERemoteService.cpp
libraries/BLE/src/BLEService.cpp
libraries/BLE/src/BLEServiceMap.cpp
libraries/BLE/src/BLEUUID.cpp
libraries/BLE/src/BLEUtils.cpp
libraries/BLE/src/FreeRTOS.cpp
libraries/BLE/src/GeneralUtils.cpp

This PR gets rid of stringstream and exception usage in @nkolban  BLE library. While stringstream itself is a good and safe thing on mature desktop platforms, using it in embedded world mostly for debugging purposes has its impact. In this case we can save about **214k**.
Here's a metrics of my test image build.
----
* Stringsream=y
* Exceptions in idf toolchain=y
* Exceptions in library=y
```
$ ls -al build/
-rw-r--r--   1 user  staff    628288 25 июн 16:45 firmware_.bin
```
-----
* Stringsream=n
* Exceptions in library=n
* Exceptions in idf toolchain=y
***Note**: by default exceptions seems to be enabled in Arduino build configuration. So, actual flash size benefit from this PR on most platforms can be about **137k**.*
-----
```
$ ls -al build/
-rw-r--r--   1 user  staff    491184 25 …
```

Reduce flash usage up to 214k in one click

---

libraries/WebServer/src/Parsing.cpp

This tiny PR fixes endless loop inside WebServer library if file upload is interrupted by the browser

Fix WebServer hang on client disconnect during upload

---

libraries/BLE/src/BLECharacteristic.cpp
libraries/BLE/src/BLEServer.cpp
libraries/BLE/src/BLEServer.h

`onRead` callback is called after the actual data is sent over BLE read response.
Possibly fix of #1982
Also brings useful capability to gracefully disconnect client from BLEServer

BLE Library onRead Callback fix and Client disconnect feature

---

libraries/ESPmDNS/examples/mDNS_Web_Server/mDNS_Web_Server.ino

The flush causes an empty response a client side.
see https://github.com/espressif/arduino-esp32/issues/2902

 fix empty reply from server error

---

boards.txt
variants/tinypico/pins_arduino.h

I have added support for the ESP32 PICO-D4 based TinyPICO in the boards list, so users can select that board when using their TinyPICO.

Added support for TinyPICO in the boards list

---

libraries/WiFi/src/WiFiSTA.cpp

This seems to finally fix/workaround the bug that has been plaguing WPA2 connections.
In my testing (home network, WPA2 Personal), connection time has improved from **~1200ms to ~300-350ms**.
The issue seems to be that the underlying WiFi API needs esp_wifi_set_config() to be explicitly called. Perhaps some lwIP settings aren't applied. It might even be a clash with the ARP check config specifically.
This is not specific to Arduino, but it is a band-aid for now. Also tested with esp-idf (PlatformIO) , esp-idf + Arduino component (PlatformIO), Arduino (IDE and PlatformIO). 
I'll create an issue on the esp-idf repo soon.
Hopefully helps with #1675, #2798, etc

WPA2 connection fix (significant improvement to connection time)

---

libraries/ESP32/examples/RMT/RMTWriteNeoPixel/RMTWriteNeoPixel.ino

Fixed bit shift in demo application of using RMT peripheral. Init data array to be transmitted was off by one, as for the first iteration (i==0) the mask was 1<<8, which resulted in shifted RGB value in `color[]` variable
Closes https://github.com/espressif/arduino-esp32/issues/2921

RMT: Fix in bitshift of NeoPixel example project

---

libraries/WiFi/src/ETH.cpp
libraries/WiFi/src/ETH.h
libraries/WiFi/src/WiFiAP.cpp
libraries/WiFi/src/WiFiAP.h
libraries/WiFi/src/WiFiGeneric.cpp
libraries/WiFi/src/WiFiGeneric.h
libraries/WiFi/src/WiFiSTA.cpp
libraries/WiFi/src/WiFiSTA.h

WiFiGeneric:
calculateNetworkID(IPAddress ip, IPAddress subnet) => Calculate the network id using the IP and subnet (e.g. 192.168.0.0)
calculateBroadcast(IPAddress ip, IPAddress subnet) => Calculate the broadcast IP using the IP and subnet (e.g. 192.168.0.255)
calculateSubnetCIDR(IPAddress subnetMask) => Calculate the subnet CIDR using the subnet (e.g. 24)
WiFiAP:
softAPBroadcastIP() => Retrieve the network id (e.g. 192.168.0.0)
softAPNetwrokID() => Retrieve the broadcast IP (e.g. 192.168.0.15)
softAPSubnetCIDR() => Retrieve the subnet CIDR (e.g. 28)
WiFiSTA:
broadcastIP() => Retrieve the network id (e.g. 192.168.0.0)
netwrokID() => Retrieve the broadcast IP (e.g. 192.168.0.255)
subnetCIDR() => Retrieve the subnet CIDR (e.g. 24)
ETH:
broadcastIP() => Retrieve the network id (e.g. …

Add generic IP utilities

---

libraries/BLE/src/BLEAdvertising.cpp

BLEAdvertising::handleGAPEvent -> ESP_GAP_BLE_ADV_STOP_COMPLETE_EVT should NOT call start()!

Fix BLE stop advertising not working

---

libraries/Update/src/Updater.cpp

The progress callback was only invoked with Update.writeStream before.

The progress callback is now correctly invoked with Update.write

---

cores/esp32/Esp.h

ESP.getCpuFreqMHz was returning the CONFIG_ variable.  Now calls the getCpuFrequencyMhz function.

ESP.getCpuFreqMHz fix

---

libraries/BLE/src/BLECharacteristic.cpp
libraries/BLE/src/BLECharacteristic.h
libraries/BLE/src/FreeRTOS.cpp
libraries/BLE/src/FreeRTOS.h

Sometimes it is useful to see if our BLE indication succeed or not. Current BLE implementation doesn't provide such functionality and has potential deadlock if indication confirmation response is not delivered to ESP by any reason. 
This PR adds:
* TimedWait to FreeRTOS abstraction layer
* Indication timeout (and fix possible deadlock on semaphore)
* Indication/Notification status callback, to give precise control over messages sent to BLE peer.
* Backward codebase compatibility with previous sketches.

Ble notification/indication status and timeout

---

libraries/BLE/src/BLERemoteService.cpp

This creates a warning instead of an error and is not ignored by the compiler.

Added the pragma line to the top

---

cores/esp32/WString.cpp
cores/esp32/WString.h

Pull in bugfixes from the ESP8266 repo for problems in the SSO
implementation of replace().  See the following patches for full
details:
https://github.com/esp8266/Arduino/commit/54240d2cc51e8b134fc6dc583f5a2b21f19755d8#diff-8d9e71e16d437343017df828f0528f63
https://github.com/esp8266/Arduino/commit/78a1a66e6dcd0437167869c363cd29160c35fe96#diff-8d9e71e16d437343017df828f0528f63
https://github.com/esp8266/Arduino/commit/4e9358445a161939f7d8246fbc365a035693749a#diff-8d9e71e16d437343017df828f0528f63
Fixes #3140

Pull in ESP8266 String::replace() fixes, others

---

libraries/Ticker/src/Ticker.cpp

Long duration was truncated when calculating milliseconds * 1000. ESP32 only: functions esp_timer_start_* require microseconds as uint64_t. ESP8266 is not affected as it uses a different API.

Fix long Ticker period conversion: cast ms to uint64_t when calculating us

---

cores/esp32/Print.cpp

Fix return of Print::print(timeinfo, format)

---

libraries/WiFi/src/WiFiScan.cpp
libraries/WiFi/src/WiFiScan.h

If you start a scan for networks if the esp is connecting to an ap the scan request is aborted by the sdk without returning an error. See here espressif/esp-idf#3044 for reference.
In my case the scan routine is running in its own thread so i can't assume when the scanNetworks is triggered. If it gets triggered while the esp is connecting the connect has priority and the SYSTEM_EVENT_SCAN_DONE event is never triggered. In that particular case the WIFI_SCANNING_BIT is never cleared and you're not able to scan for networks without a reset.
To prevent that case i modified the WiFiScan.ccp to include a timeout mechanism to reset a failed scan. So I added a define SCAN_ERROR_DELAY with a value of 10000 for 10s as timeout and the parameter _scanStarted.
If the SYSTEM_EVENT_SCAN_DONE event is …

Added timeout to WiFiScan.cpp to prevent getting stuck at WIFI_SCAN_RUNNING

---

libraries/FFat/src/FFat.cpp

this is due to usage of `esp_err_t result;` instead of boolean, ESP_OK = 0, so it is false

Fix F_Fat::format return false when succeed

---

boards.txt

The old version would crash the Stino plugin, which appears not to support quotes in board names

Changed WeMosBat.name

---

libraries/EEPROM/src/EEPROM.cpp

nvs_handle is an int, was assigning NULL.  Also cleaned up end to ensure no memory leak.
Fixes #3142

EEPROM compile warnings

---

boards.txt

The original boards.txt was missing a menu option to select the FLASH partitioning options.

Added partition size option for Pico Kit

---

libraries/FFat/src/FFat.cpp
libraries/FFat/src/FFat.h

_wl_handle was not being cleared properly

Fixed FFat::end. Fixes #3244

---

libraries/FFat/src/FFat.cpp

Better cleanup on mount failures, as the idf api now seems to assign handle and mountpoint before failing. Fixes #3265

FFat remount failure

---

libraries/BLE/src/BLEDevice.cpp

Pretty sure this was a typo as the deinit doesn't actually allow for reinit if that is an ifndef.  Changed in my local copy and can now deinit and reinit just fine.  Also, not sure why we are checking for the architecture here.  Just curious.

Non-functional deinit/init in BLEDevice.cpp

---

libraries/BLE/src/BLEUUID.cpp

Fix for https://github.com/espressif/arduino-esp32/issues/3153

Fixes issue-3153 - Allocating enough memory to construct the entire UUID as a String

---

libraries/BLE/src/BLEDevice.cpp

#include "esp32-hal-log.h" is mandatory is order to build BLEDevice.cpp.
It can't be left up to a compiler variable.

Fix for issue_3209.

---

cores/esp32/base64.cpp
cores/esp32/base64.h

Avoid passing String by-value, which is slightly less efficient
as it involves a full copy-constructor/tempstring creation.

Base64::encode : const correctness / String by reference passing

---

cores/esp32/HardwareSerial.h
cores/esp32/esp32-hal-misc.c
cores/esp32/main.cpp

Hi @me-no-dev!
As I've a fully portable co-op scheduler running on ESP8266, ESP32 and Arduino (physically the ATmega 328P - Arduino Pro or Pro Mini) now [https://github.com/dok-net/CoopTask], here is another request to allow nice integration into the loop() with `yield()` (and, later, optionally, `delay()`). AVR Arduino et cetera have this, because `yield()` is overridable and `delay()` cyclically calls `yield()`, but as you know, the scheduling on the Espressif SOC is different.
I just hope that this very small adjustment is agreeable to you, even if you don't think that cooperative MT is useful on FreeRTOS, but users should implement OS tasks instead...

Make yield() overridable

---

platform.txt

Add a file named `partitions.csv` to your sketch folder and define the partitions inside. In order to not get `Sketch too big`, please select appropriate partition scheme from the board menu

Allow sketches to have custom partitions

---

libraries/WebServer/src/WebServer.cpp

I compiled the sample "WebServer -> HttpAdvancedAuth". But the right username and password can not login in. I found the file "WebServer.c" may be have some problem. So I fix it. Please check it.

fix authrization problem

---

cores/esp32/esp32-hal-spi.c
cores/esp32/esp32-hal-spi.h
libraries/SPI/src/SPI.cpp
libraries/SPI/src/SPI.h

This changes all SPI functions that take data pointers which are
not modified so that the declaration is const. This allows them
to be used with const data (i.e. held in flash). No functional
changes are required.
The defnitions of spiWrite() and spiTransferBytes()  in
esp-hal-spi.h/c have been updated to be consistent.
Tests:
- Build a simple sketch using SPI.writePattern() and
SPI.transferBytes()  which uses const data and verify that the
attached device functions as expected.

SPI: Ensure all read-only data pointers are marked as const

---

boards.txt

Added partition size options for TinyPICO to the boards menu

Added partition size options for TinyPICO

---

libraries/WiFiClientSecure/src/ssl_client.cpp

Especially if the user wants to use the library as component in IDF,
there are some pitfalls while doing make menuconfig. One is this missing
dependency which will now fail with a better error message with a hint to
the user how to fix it.
refs #2154 #3215

Add an error message in case of invalid configured dependency mbedTLS.

---

libraries/WiFi/src/WiFiGeneric.cpp

Hi.
**Summary**
Currently `_network_event_cb` pass pointer to `system_event_t` into `_network_event_queue`, instead of value.
I think this wrong. And this pull request fix that.
**Description**
Method `esp_event_loop_task` that calls `_network_event_cb` stores `system_event_t` in stack:
```
static void esp_event_loop_task(void *pvParameters)
{
while (1) {
system_event_t evt;
if (xQueueReceive(s_event_queue, &evt, portMAX_DELAY) == pdPASS) {
esp_err_t ret = esp_event_process_default(&evt);
if (ret != ESP_OK) {
ESP_LOGE(TAG, "default event handler failed!");
}
ret = esp_event_post_to_user(&evt);
if (ret != ESP_OK) {
ESP_LOGE(TAG, "post event to user fail!");
}
}
}
}
```
So when `_network_event_cb` sent pointer in `_network_event_queue` it stores pointer to stack in queue. And if several …

Fix WiFiGeneric event handler

---

cores/esp32/HardwareSerial.cpp
cores/esp32/HardwareSerial.h
cores/esp32/esp32-hal-uart.c
cores/esp32/esp32-hal-uart.h

Second attempt to create a `Serial.flush()` that does not affect the rx data queue or rxFifo.
`Serial.flush(true);` will hang until all tx Data has been sent out the UART.  It will not clear the rx data queue.

Implement Tx only Flush

---

libraries/WiFiClientSecure/examples/WiFiClientSecureEnterprise/WiFiClientSecureEnterprise.ino

Root CA certificate of my webserver that was used in example for HTTPS connection with eduroam connectivity has changed.
There were deleted and added a few comments, added a new header  with info about example. Tested, under core 1.0.1 (currently using) working, screenshot attached.
Added anonymous identity option to set in variable.

Root CA of webserver has changed, minor changes

---

boards.txt

Add menu items Partition Schemes:
- Default
- No OTA (Large APP)
- Minimal SPIFFS (Large APPS with OTA)
and Debug Levels:
- None
- Error
- Warn
- Info
- Debug
- Verbose
for node32s board

Add menu items Partition Scheme and Debug Level for node32s board

---

libraries/BLE/examples/BLE_client/BLE_client.ino

fix typo BLE_client.ino

---

libraries/BluetoothSerial/src/BluetoothSerial.cpp

Fixed incorrect usage of xEventGroupWaitBits

---

cores/esp32/esp32-hal-spi.c

This fixes an error introduced with changeset b847f41 which
tightened the use of const for read-only data. The helper
function __transferBytes also requires the const qualifier on
outgoing data. Without this change a warning is displayed
when compiling with the Arduino IDE set to display "All"
compiler warnings.
Local functions __transferBytes() and __spiTranslate32() are now marked as static.
Unused local function __spiTranslate24() has been removed.
Tests:
- Build an ESP32 SPI sketch that uses static const data to send
to an SPI device using the SPI.transferBytes() API

SPI: Fix discarded-qalifiers warning when compiling with all warnings

---

cores/esp32/esp32-hal-bt.c

Fix **BluetoothSerial crash when restart** :  this is because the BT controller remains in state  ESP_BT_CONTROLLER_STATUS_INITED instead of state  ESP_BT_CONTROLLER_STATUS_IDLE after the end() method.
in file esp_bt.h it is specified
> @brief Enable BT controller.
>                Due to a known issue, you cannot call esp_bt_controller_enable() a second time
>                 to change the controller mode dynamically. To change controller mode, call
>                esp_bt_controller_disable() and then call esp_bt_controller_enable() with the new mode.
after **esp_bt_controller_disable()** the controller remains in state INITED so we do call the **esp_bt_controller_deinit()** function to put the controller into state IDLE.

Fix BluetoothSerial crash when restart

---

cores/esp32/esp32-hal-cpu.c
cores/esp32/esp32-hal-ledc.c
cores/esp32/esp32-hal-uart.c

* `ledcWriteTone()` added a `apbcallback()` evertime the tone value was non zero.  
* `addApbChangeCallback()` did not detect duplicate callbacks.
* changed the apbcallback list to a double link to support roll forward, roll back execution.  This made the sequences of clock change callback start with the newest registered -> to oldest on the `before` then oldest -> newest after the clock change.  This made the UART debug log output have minimal gibberish during the clock change.
* change how the UART callback handled the MUTEX because if any `apbchangeCallback()` executed a `log_x()` a deadlock would occur.
This fixes #3555

Fix Memory leak in addApbChangeCallback() 

---

boards.txt
variants/mgbot-iotik32a/pins_arduino.h
variants/mgbot-iotik32b/pins_arduino.h

Hi!
I added new Russian education boards IOTIK 32A and IOTIK 32B:
http://www.iotik.ru/iotik32a/
http://www.iotik.ru/en/iotik32b/
Thanks!

Added MGBOT IOTIK 32A and IOTIK 32B boards

---

libraries/SPI/examples/SPI_Multiple_Buses/SPI_Multiple_Buses.ino

The existing example contains some issues which could cause confusion. 
Looking at line #35 it is clear that the commented line should be calling the `begin` method of `vspi` and not `hspi`. By using preprocessor symbols it makes the code more readable, and being able to control whether the SPI bus standard pins are used or the alternate pins by setting a symbol makes it easier.
Also the setting of the SS pins to output now is easier, and also the raising and lowering of the SS lines during sending is a lot easier and clearer.
Please consider this PR for merging.

Cleanup SPI_Multiple_Buses

---

cores/esp32/HardwareSerial.cpp
cores/esp32/HardwareSerial.h

The ESP32 Arduino implementation of `HardwareSerial.h` is missing
```c++
write(const char * buffer, size_t size);
```
Additionally, this PR adds the `read(buffer, size)` extension from ESP8266, also in `EspSoftwareSerial`, that complements the inherited `Stream::readBytes()` with a non-blocking variant.

HardwareSerial::write(const char*, ...) API compatibility to AVR, ESP8266, et al

---

libraries/FFat/examples/FFat_Test/FFat_Test.ino
libraries/SPIFFS/examples/SPIFFS_Test/SPIFFS_Test.ino

Added file.close to examples

---

CMakeLists.txt

Fix recent commit d8b2098 (PR #3377) which includes `esp_adc_cal` component but does not update `CMakeLists.txt`.

Fix commit d8b2098 (PR #3377) which includes esp_adc_cal

---

cores/esp32/esp32-hal-rmt.c
cores/esp32/esp32-hal-rmt.h

Number of pulses is limited to the reserved RMT memory for the channel. Very useful for PWM, Servo and other repeatable signals.

Implement rmtLoop to be able to continuously send pulses

---

libraries/WiFi/src/WiFiClient.cpp

WiFiClient.connected() was hanging thinking there was still a connection when the remote had already closed. The one-liner in this patch addresses recv() returning 0 and errno==128. I couldn't find the corresponding errno for 128 but its caught by the case statement which includes EPIPE, ENOTCONN, ECONNRESET and ECONNABORTED so I assume its one of those. Broken pipe maybe?
```c
[D][WiFiClient.cpp:511] connected(): Disconnected: RES: 0, ERR: 128
```
EDIT: added comment to reflect that recv() can set errno when it returns 0.

fix WiFiClient.connected()

---

cores/esp32/esp32-hal-spi.c

spiStartBus() was using spiStopBus() to init the hardware, one of spiStopBus() functions is to unregister the runtime CPU clock speed change callback. But, spiStartBus() only wanted to init the hardware.  This patch separates the hardware init into a standalone function spiInitBus() that both spiStartBus() and spiStopBus() call.

fix removeApbChangeCallback() error in spiStopBus()

---

cores/esp32/esp32-hal-uart.c
cores/esp32/esp32-hal-uart.h

In current HardwareSerial/esp-uart-hal 
- on Transmit
In the uart configutarion setting there is a parameter tx_idle_num.
tx_idle_num is : idle interval after tx FIFO is empty(unit: the time it takes to send one bit under current baudrate)
This tx_idle_num is set to 256.
Resulting in a forced transmit idle time after txFifo empty to next.
This PR sets the tx_idle_num value to zero at uartBegin(). 
Result is an immediate start of transmission when a char is send.
- On Receive
The chars are first received in rxFifo buffer which is transfered to HardwareSerial Queue on either fifo filled with 112 chars or 2 bytes idle time. 
Resulting in a delay at application level processing the incoming messages.
This PR takes the characters in rxFifo into account when calling available(), read() and …

Minimize HardwareSerial Receive and Transmit delays

---

libraries/WiFi/src/WiFiClient.cpp

clientSocketHande and _rxBuffer are std::shared_ptr, the stop() call was not correctly releasing them and the operator= had similar problems fix for #3679

std::shared_ptr Memory Leak

---

libraries/ESP32/examples/Camera/CameraWebServer/app_httpd.cpp

The boundary delimiter (_STREAM_BOUNDARY) needs to be send before the body part (_STREAM_PART) too follow RFC2046. This caused `ffplay`/`ffmpeg` to fail to open the MJPEG stream.
[RFC2046: 5.1. Multipart Media Type](https://tools.ietf.org/html/rfc2046#section-5.1)
"... The body must then contain one or more body parts, **each preceded by a boundary delimiter line**, and the last one followed by a closing boundary delimiter line. ..."
After the change `ffplay`, `ffmpeg` and `mplayer` worked fine with the MJPEG stream.

Move _STREAM_BOUNDARY before _STREAM_PART

---

CMakeLists.txt
libraries/WiFi/examples/WiFiProv/README.md
libraries/WiFi/examples/WiFiProv/WiFiProv.ino
libraries/WiFi/src/WiFi.h
libraries/WiFi/src/WiFiGeneric.cpp
libraries/WiFi/src/WiFiGeneric.h
libraries/WiFi/src/WiFiProv.cpp
libraries/WiFi/src/WiFiProv.h

Here 1. WiFiProv.ino sketch is added that allows arduino users to do provisioning via SoftAP or BLE. WiFi.beginProvision( ) API is designed for provisioning in Arduino. 
2. In WiFiProv.h provisioning class is defined.
3. WiFiProv.cpp contains implementation for provisioning class.
4. README.md file is added which contains detail information for working.

Add support of unified provisioning to Arduino

---

libraries/WiFi/examples/WiFiProv/README.md
libraries/WiFi/src/WiFiProv.cpp

Minor modifications in provisioning

---

.github/scripts/install-platformio-esp32.sh
boards.txt
variants/m5stack_atom/pins_arduino.h

Please add support for M5Stack-ATOM board
Project link https://docs.m5stack.com/#/en/core/atom_matrix

Add M5Stack-ATOM Board

---

tools/platformio-build.py

This will allow users to set any linker script from `platformio.ini` file using the following syntax:
```ini
[env:esp32dev]
platform = espressif32
framework = arduino
board = esp32dev
board_build.ldscript = custom_ldscript.ld
```
This is a more correct way of specifying it in comparison with using the `-Wl,-T` flag.

Allow using custom linker scripts in PlatformIO build script

---

cores/esp32/esp32-hal-uart.c

This PR includes : 
Bugfix : Disable/enable uart interrupts during transfer from fifo to queue
Improvement : Remove unnecessary check for full queue in uart isr

HardwareSerial bugfix & improvement

---

CMakeLists.txt

This addresses issue #3971 where build failed when building as a component because the include directory for wifi_provisioning was missing.

Added missing wifi_provisioning dependency (#3971).

---

libraries/SD_MMC/src/SD_MMC.cpp

According to ESP-IDF API
https://github.com/espressif/esp-idf/blob/dc14d027cec49260b78efb1c3724b1710f2f3ec0/docs/en/api-reference/peripherals/sdmmc_host.rst :
"To configure the bus width, set the width field of :cpp:class:`sdmmc_slot_config_t`. For example, to set 1-line mode:
sdmmc_slot_config_t slot = SDMMC_SLOT_CONFIG_DEFAULT();
slot.width = 1;
"
E.g. necessary on Olimex ESP32-POE, because this board is using GPIO12 for other purpose (switching PoE power). GPIO12 ususally is used in 4 bit SDMMC interface. Thus, should be disabled in 1bit mode to avoid conflicts if GPIO12 is used for other purpose.

Make 1bit SDMMC interface work

---

libraries/BLE/src/BLEServer.cpp
libraries/BLE/src/BLEServer.h

There is no need to decrement if nothing was removed from removePeerDevice
Reference issue:
https://github.com/espressif/arduino-esp32/issues/3974

Fix for issue 3974 m_connectedCount incorrectly decremented when no connection exists

---

.gitignore
libraries/ESP32/examples/Camera/CameraWebServer/CameraWebServer.ino
libraries/ESP32/examples/Camera/CameraWebServer/camera_pins.h

M5Stack's product offering includes various ESP32-based camera devices. They are all broadly similar, all being based on the ESP32-D0WD core, but have some subtle differences between variants around PSRAM inclusion and camera pin mappings.
The ESP32CAM "unit" product (SKU: U007) has no PSRAM and maps the "Pixel Data 0" (Y2 GPIO/OV2640 D2) camera pin to IO17 rather than IO32 as is the case with most other M5Stack ESP32 camera devices.
The ESP32CAM also requires the "hmirror" and "vflip" camera configuration bits setting in order to capture a true image.
The relevant M5Stack pin configuration documentation can be found [here](https://docs.m5stack.com/#/en/unit/esp32cam?id=pinmap).

Camera pin mappings for the M5Stack ESP32CAM device

---

libraries/WiFi/src/WiFiGeneric.cpp
libraries/WiFi/src/WiFiSTA.cpp

Fixing static IP configuration so it doesn't get overwritten by DHCP as part of WiFi.begin().
Fixing DHCP client stop if WiFi.config() is called before WiFi.begin() (as done in WiFiClientStaticIP.ino)

ESP32S2: Static IP and DHCP stop fixes

---

boards.txt
variants/um_feathers2/pins_arduino.h
variants/um_pros2/pins_arduino.h
variants/um_tinypico/pins_arduino.h

Updated the name of TinyPICO to UM TinyPICO in boards.txt

Added UM FeatherS2 and UM ProS2 boards to boards.txt

---

libraries/WiFi/examples/WiFiProv/README.md
libraries/WiFi/examples/WiFiProv/WiFiProv.ino
libraries/WiFi/src/WiFiProv.cpp
libraries/WiFi/src/WiFiProv.h

Few fixes w.r.t the issue - https://github.com/espressif/arduino-esp32/issues/4125

Provisioning fixes for: 1.Space issue for BLE 2.When device is already provisioned.

---

.github/scripts/install-platformio-esp32.sh

This PR fixes broken CI build by adjusting the `version` and `owner` manifest fields.
cc @ivankravets

Update PlatformIO CI script

---

docs/esp-idf_component.md

This is a documentation improvement regarding #2981

Added documentation regarding delay() resolution in esp-idf component

---

cores/esp32/WMath.cpp

Half, or zero errors, depending on in/out…… ranges, for round-trip mapping at the same performance.
(Based on "improved_map" from ESP8266's Servo.cpp)

Greatly reduced error rate of WMath map() roundtrip

---

cores/esp32/Print.cpp
cores/esp32/Print.h

Port from ESP8266 (https://github.com/esp8266/Arduino/pull/7040), PR'ed for Arduino Core AVR as well (https://github.com/arduino/ArduinoCore-avr/pull/312).
Tuned for ESP32 32bit and 64bit modulo.

Extend Print class for 64bit integers.

---

libraries/WiFi/src/WiFiGeneric.cpp

Real DNS resolving timeout used by lwip library is 14[s] (7[s] for DNS1 + 7[s] for DNS2). Function WiFiGenericClass::hostByName() has timeout set to lower value (only 4[s]), so callback function may be called after this low timeout and it may overlappe stack memory used now by other function.
Fixes #3722

DNS resolving timeout change to prevent stack overlapping

---

libraries/Update/src/Update.h
libraries/Update/src/Updater.cpp

UpdateClass::printError now accepts the Print object

---

libraries/HTTPClient/src/HTTPClient.cpp

When connecting using transportTraits, the CA and client certificates are ignored after the initial _client->connect() is called. This is because on connect, WiFiClientSecure will call start_ssl_client with _CA_Cert and other cert options set to null unless setCACert, setCertificate etc. are called before connect. Running _transportTraits->verify after connect therefore does exactly nothing. It's easy to verify that this is the case by passing a CACert to HTTPClient with verbose logging enabled - the logs will say "WARNING: Use certificates for a more secure communication!" which is only present when both PSK and CA are null. This change fixes the issue. With it, passing a CA cert to HTTPClient's begin will make subsequent connections correctly fail on certificate mismatch and succeed on …

HTTPClient: Set TLS params before calling connect on client, so verify works

---

platform.txt

Add support for the v1.8.6 compiler.libraries.ldflags:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification
This fixes the issue reported here:
https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/BSEC-1-4-7-4-compilation-error-on-ESP32-1-0-3-rc1/td-p/9120

Process compiler.libraries.ldflags

---

libraries/EEPROM/examples/eeprom_class/eeprom_class.ino

Fixes #3785 - Use EEPROM writeString() for character arrays instead of .put(). Add a 1 second delay on startup to allow time to connect serial monitor.

fix EEPROM class example

---

libraries/BLE/examples/BLE_Beacon_Scanner/BLE_Beacon_Scanner.ino
libraries/BLE/examples/BLE_Beacon_Scanner/BLE_Beacon_Scanner.md
libraries/BLE/examples/BLE_EddystoneTLM_Beacon/BLE_EddystoneTLM_Beacon.ino
libraries/BLE/examples/BLE_EddystoneTLM_Beacon/BLE_EddystoneTLM_Beacon.md
libraries/BLE/examples/BLE_EddystoneURL_Beacon/BLE_EddystoneURL_Beacon.ino
libraries/BLE/examples/BLE_EddystoneURL_Beacon/BLE_EddystoneURL_Beacon.md
libraries/BLE/src/BLEEddystoneTLM.cpp

Fix issue #3833, data parsing of Eddystone TLM data frame    
Add Beacon scanner example to show usage of BLEEddystoneTLM class and  BLEEddystoneURL class     
Add EddystoneTLM beacon example    
Add EddystoneURL beacon example

Fix issue #3833, data parsing of Eddystone TLM data frame

---

cores/esp32/esp32-hal-uart.c

Fixed bug where uartResizeRxBuffer() did not unlock mutex if creation of queue failed.

Fixed bug where mutex would not be unlocked

---

libraries/BLE/src/BLEClient.cpp

By default the disconnect is broadcasted to every clients. So if you call disconnect on one connected client, they'll all be disconnected if we don't filter the event by conn_id.
I'm not sure if other esp_gattc_cb_event_t events should do the same thing to prevent similar bugs.

Fix BLEClient disconnect bug

---

cores/esp32/Esp.cpp
cores/esp32/Esp.h
libraries/Update/src/Update.h
libraries/Update/src/Updater.cpp

The current implementation of `Update()` uses the `spi_flash_*` api to write and read from flash. These functions ignore the `partition->encrypted` flag and always write raw data to flash even if the partition is marked as encrypted.
1. `Update()` now uses the `esp_partition_*` api.
2. Wrapper functions for `esp_partition_*` added to `ESP.cpp`. This was done to maintain a consistent approach to the way the `spi_flash_*` functions were used. I note though that not all of the esp-idf functions are used are wrapped, for example `esp_ota_get_next_update_partition()` so it may be that these should not be added?
3. The current implementation of Update() changes the first (magic) byte of firmware to `0xFF` on write, and then when the firmware is completely written changes it back to …

Updater.cpp support for encrypted flash

---

variants/firebeetle32/pins_arduino.h

Update in accordance with Firebeetle's official firebeetle32 pins_arduino.h. Without it, digital pins weren't definable, and analogue pins didnt line up.
Taken from http://download.dfrobot.top/FireBeetle/DFRobot_FireBeetle-ESP32-0.0.9.zip

Update pins_arduino.h for Firebeetle32

---

libraries/WiFiClientSecure/src/WiFiClientSecure.cpp

Static ptr meant any load would overwrite the first. Also ensured the buffer is null-terminated.

Fix to allow more than one certificate to be loaded (espressif#3248).

---

libraries/BLE/src/BLERemoteCharacteristic.cpp

Some devices (eg some cheap iTag buttons) don't have descriptor 0x2902. Make it optional instead. For these devices, notify still works.
Debugged with ESP Exception Decoder:
```
PC: 0x400d56ff: BLERemoteDescriptor::writeValue(unsigned char*, unsigned int, bool) at /home/bb/Desktop/Arduino/libraries/ESP32_BLE_Arduino/src/BLERemoteDescriptor.cpp line 40
EXCVADDR: 0x00000030
Decoding stack results
0x400d56ff: BLERemoteDescriptor::writeValue(unsigned char*, unsigned int, bool) at /home/bb/Desktop/Arduino/libraries/ESP32_BLE_Arduino/src/BLERemoteDescriptor.cpp line 40
0x400d4d6f: BLERemoteCharacteristic::registerForNotify(void (*)(BLERemoteCharacteristic*, unsigned char*, unsigned int, bool), bool) at /home/bb/Desktop/Arduino/libraries/ESP32_BLE_Arduino/src/BLERemoteCharacteristic.cpp line 485 …
```

Fix handling of registerForNotify in BLERemoteCharacteristic.cpp

---

libraries/BLE/src/BLECharacteristic.cpp
libraries/BLE/src/BLECharacteristic.h

Informed by the discussion in the bug and the code in 'that other branch'
the fix was clear.  Just set a flag if we start handling a write, and
use that flag to guard the long write complete call.

Fix #4046 Details below:

---

libraries/WebServer/src/Parsing.cpp

Successful exploitation could lead to arbitrary code execution.
The bug can be reproduced by running the following in a browser
```js
const formData = new FormData();
for (let i = 0;i < 33;++i) { formData.append("foo", i.toString()); }
await fetch("http://esp.local", { method: 'POST', body: formData });
```

WebServer: Fix OOB write

---

libraries/WiFi/src/WiFiMulti.cpp

Fix for https://github.com/espressif/arduino-esp32/issues/3914 by syncing with https://github.com/espressif/arduino-esp32/blob/esp32s2/libraries/WiFi/src/WiFiSTA.cpp#L161

Correct PSK length check in WiFiMulti

---

libraries/WiFi/src/WiFiGeneric.cpp

This commit fixes issue https://github.com/espressif/arduino-esp32/issues/3522 where WiFi service fails to start after a WiFi.disconnect(true) or a WiFi.mode(WIFI_OFF).
I'm just doing the PR. Initial fix found by @rob58329 and modified by @lbernstone.

Fix issue #3522 (WiFi does not restart after stopped)

---

libraries/BLE/src/BLEScan.cpp

This value is uninitialised and as such can be a random (and invalid) value. It's needs to be set per the espressif documentation here:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/esp_gap_ble.html#_CPPv4N21esp_ble_scan_params_t14scan_duplicateE
This PR sets it to DUPLICATE_DISABLE. Chosen as this is needed to ensure all scan data is populated in the scan callback, per this comment in the IDF:
https://github.com/espressif/esp-idf/blob/master/components/bt/host/bluedroid/stack/btm/btm_ble_gap.c#L3591
"//if scan duplicate is enabled, the adv packet without scan response is allowed to report to higher layer"
We **don't** want it to report to the higher layer (ie BLEScan.cpp) **unless** it has the active scan response.
Seems to resolve #3770 #3677 and …

Set scan_duplicate in BLE scan params

---

libraries/FS/src/vfs_api.cpp

SPIFFS causes crashes if you attempt to rmdir. Since there are no true directories in spiffs, this ought to be a noop. It looks like @me-no-dev worked around this by using unlink instead of rmdir, which works in fatfs and doesn't panic spiffs. This behavior is not universal. In order to get littlefs working, it would be good to get this back to conformity. Rather than digging deep into the upstream spiffs, I just check the mountpoint and noop if it is "/spiffs". So, if the user has changed the mountpoint, this will not work, but I think it's a pretty good tradeoff.

rmdir causes issues in SPIFFS. Fixes #4138, albeit not very cleanly

---

cores/esp32/HardwareSerial.cpp
cores/esp32/HardwareSerial.h
cores/esp32/esp32-hal-uart.c
cores/esp32/esp32-hal-uart.h

This code exposes the ESP32's UART facility to invert input bits, which can resolve issues with bipolar receivers (e.g., RS-422) with user-error in hardware connections.  Adding this allows user code to detect reversed polarity inputs, and swap the bits in software to accommodate.

Added facility to invert the polarity of input UART bits.

---

variants/firebeetle32/pins_arduino.h

Source: https://wiki.dfrobot.com/FireBeetle_ESP32_IOT_Microcontroller(V3.0)__Supports_Wi-Fi_&_Bluetooth__SKU__DFR0478

Added firebeetle32 D pin numbers

---

libraries/HTTPClient/src/HTTPClient.cpp
libraries/HTTPClient/src/HTTPClient.h

Ported from ESP8266 . Fixes issue #3374 
The user can use HTTPClient::setFollowRedirects with HTTPC_DISABLE_FOLLOW_REDIRECTS, HTTPC_STRICT_FOLLOW_REDIRECTS or HTTPC_FORCE_FOLLOW_REDIRECTS to enable and disable this feature. Responds to codes 301, 302, 303, 307.

Add support for following redirects in HTTPClient

---

docs/arduino-ide/mac.md

shallow clone (board and submodules) to make installation faster

shallow clone to make installation faster

---

libraries/Update/src/Update.h
libraries/Update/src/Updater.cpp

Reinit updater md5 related fields for cleanup

---

libraries/SD/src/sd_diskio.cpp

SD is left in an active state if you simply detach the device.  Set into idle first, this reduces power consumption by ~12mA.  See #2958

Set SD state to idle before unregister (reduces power)

---

variants/m5stack_atom/pins_arduino.h

G22 was defined twice, changing the first one to G21

Fix duplicated pin constant

---

libraries/HTTPClient/src/HTTPClient.cpp

Currently when getString() is called when content-length is not set (for example for 204 no-content http code) program execution freezes.
I found similar problems mentioned in https://github.com/espressif/arduino-esp32/issues/2667 and https://github.com/espressif/arduino-esp32/issues/3586  but no fix to date.

Fix HTTPClient::getString() freeze on empty responses

---

cores/esp32/esp32-hal-i2c.c

I have run into a Problem where my ESP32 would crash with this error message: `[E][esp32-hal-i2c.c:1013] i2c_isr_handler_default(): unknown int=4`
It turns out `i2c_isr_handler_default()`does not handle `I2C_RXFIFO_OVF_INT_ST` at all which ultimately leads to a crash. Handling it the same way as a I2C_RXFIFO_FULL_INT_ST fixes the crashing and only leads to gracefully handled errors in the I2C transaction.

add I2C_RX_FIFO_OVF_INT_ST handling to i2c_isr_handler_default

---

libraries/WebServer/src/WebServer.cpp
libraries/WebServer/src/WebServer.h

If WebServer.handleClient is run in a tight loop, it will starve other processes.  So, if there is no connection, throw in a delay(1).  Fixes #4348

WebServer.handleClient delay

---

libraries/ESPmDNS/src/ESPmDNS.cpp
libraries/ESPmDNS/src/ESPmDNS.h

I was playing with the mDNS service and noticed the method `MDNSResponder::addService` could return a Boolean with the way it is implemented just like other functions in this library.
This would be handy to know at a higher level weather or not the service was added correctly to the mDNS server of the ESP32.

Update MDNSResponder::addService to return a boolean

---

CMakeLists.txt

* HttpsOTAUpdate introduced new IDF component requirements.
These have been added to CMakeLists.txt to correct compilation errors when using Cmake.

Fix missing headers when compiling as IDF component with Cmake

---

libraries/HTTPUpdate/examples/httpUpdate/httpUpdate.ino
libraries/HTTPUpdate/examples/httpUpdateSecure/httpUpdateSecure.ino

I spent quite a while today figuring out how to get an OTA update over HTTPS on a custom port working. A part of my problem was not putting a slash before the .bin filename, since it wasn't there in the example. This produced invalid HTTP requests. Adding the slash would make it clear that it needs to be there.

Add missing slashes in HTTPUpdate examples

---

libraries/WiFiClientSecure/src/ssl_client.cpp

I met problem while I was working with the WiFiClientSecure.
I tried to found the source of the problem, and I found it in the sll_client.cpp.
Please check my contribution.
I've open this problem in #4335 but received no response.

Certificate isn't be free in case parse failure.

---

libraries/HTTPClient/src/HTTPClient.cpp

ee88c42c3b5e87a2fc09303f9e82dd8172e99990 added support for following redirects  (#4240)
However I couldn't make it work because of 2 issues in HTTPClient.cpp:
1) in the newly added setURL() we do "_canReuse = true" which means we preserve the client but kill the connection. The latter invalidates some of the memory which means that later _client.available() or similar blow up completely
2) getString() doesn't deal with when _size == -1  which can be a valid state (see existing comment re "Server not sending Content-Length header"). I've changed that condition to how it was in one of the previous versions and removed the optimisation around reserving memory upfront, as this seems to be done later on just fine..
It's my first time I contribute to this project so please bear with me if I got …

Fix support for following redirects added by previous merge

---

platform.txt

This is in line with the [arduino platform specification](https://arduino.github.io/arduino-cli/platform-specification/#recipes-for-extraction-of-executable-files-and-other-binary-data).
specifies that the file extension after `recipe.objcopy` is arbitrary. The AVR platform uses `eep` & `hex`, while the esp32 platform seems to have file extensions `partition.bin` & `bin`.
Note: I ran into this using the [arduino platform specification to generate makefiles](https://gitlab.com/mjsir911/makeduino), this PR lets other software know about the dependency tree better.
Tested on Arduino 1.8.7

Rename eep -> partitions.bin & hex -> bin

---

cores/esp32/esp32-hal-rmt.c
cores/esp32/esp32-hal-rmt.h
libraries/ESP32/examples/RMT/RMTCallback/RMTCallback.ino
libraries/ESP32/examples/RMT/RMTReadXJT/RMTReadXJT.ino
libraries/WiFiClientSecure/src/ssl_client.cpp

Add an aditional (void *) arg to the RMT callback - to allow more flexible handling of the callback (e.g. by passing a private struct or a class pointer).
Same pattern as used by the Ticker() and many others. Example updated & new example with a trapoline added.
This lets you handle multiple RMT handlers with ease & without many global variables or tricks (as the current API does not provide access to the channel).

Add an aditional (void *) arg to the RMT callback (much like Ticker() et.al.).

---

cores/esp32/esp32-hal-tinyusb.h

Without this, the build fails unless tinyusb happens to be enabled.

Make esp32-hal-tinyusb.h conditional on tinyusb

---

tools/platformio-build.py

Fixes possible issues with assembly files in external libraries

Add missing "-mlongcalls" flag to PlatformIO build script

---

libraries/WiFi/src/WiFiClient.cpp

WiFiClient improperly treats zero data available for read as an error.
Allows multi-byte read() to return 0.

Fixes espressif#4435 - 

---

libraries/BLE/src/BLERemoteCharacteristic.cpp
libraries/BLE/src/BLERemoteDescriptor.cpp
libraries/BLE/src/BLERemoteDescriptor.h

These commits fix some issues with GATT Characteristic and Characteristic Descriptor issues.

Fixing BLE GATT Characteristic notification and Characteristic Descriptor read

---

libraries/ArduinoOTA/src/ArduinoOTA.cpp
libraries/ArduinoOTA/src/ArduinoOTA.h
libraries/Update/src/Update.h
libraries/Update/src/Updater.cpp

The UpdateClass in the Updater component has the ability to update data to
a SPIFFS partition. It selects the first available partition using the
ESP-IDF esp_partition_find_first() function.
That behaviour is problematic if one has multiple SPIFFS partitions.
This change allows a user to pass the label argument (defaults to NULL)
to UpdateClass::begin() so a specific SPIFFS partition can be updated.
Additionally, ArduinoOTA can set this partition label using the
new method ArduinoOTAClass::setPartitionLabel which is optional.
This change does not break compatibility.

Add partition label argument to Update and ArduinoOTA class

---

docs/arduino-ide/boards_manager.md
package/package_esp32_index.template.json

Closes #4111.
gcc: I was not able to find an arm64 build on espressif's website so I choosed to put the armhf version, even if this should works this is only ok as temporary, arm64 runs better on arm64 than armhf :)
esptool: being interpreted python its ok
mkspiff: need igrr/mkspiffs#74 to be merged and artifacts added in [/package/package_esp32_index.template.json](https://github.com/espressif/arduino-esp32/blob/master/package/package_esp32_index.template.json).

Add support for arm64 linux toolchain for the board manager.

---

cores/esp32/pgmspace.h

pgmspace.h missing 'pgm_get_far_address'

Fix issue 4095

---

libraries/BLE/src/BLEHIDDevice.cpp

In order for the host device to be able to update the battery level, a notification is needed.
This way, Windows wil automatically update the battery level of connected devices

Notify the batteryLevel change

---

libraries/WiFi/src/WiFiProv.cpp

Do not pollute the global namespace with generic names like 'config' by declaring global variables 'static'.

Update WiFiProv.cpp: make globals static

---

tools/platformio-build.py

The goal is to allow custom configuration for `variants_dir` to define our own board variant directly in the project.
With this functionnality, we are now allowed to define in our projects a custom board **AND** a custom variant.
https://docs.platformio.org/en/latest/platforms/creating_board.html#custom-embedded-boards
Here is an example of how to define a custom board with custom variant:
```
my_project
├── boards
│   └── custom_esp32dev.json
└── variants
└── custom-esp32dev
└── pins_arduino.h
```
custom_esp32dev.json
```json
{
"build": {
"arduino":{
"ldscript": "esp32_out.ld"
},
"core": "esp32",
"extra_flags": "-DARDUINO_ESP32_DEV",
"f_cpu": "240000000L",
"f_flash": "40000000L",
"flash_mode": "dio",
"mcu": "esp32",
"variants_dir": "variants",
"variant": "custom-esp32dev"
}, …
```

Allow custom variants directory

---

libraries/SD_MMC/src/SD_MMC.cpp

sd_mmc_host_t was changed to add a union on one of the elements.  So, the c-style initialization needed to be changed to verbose style.

Updated SD_MMC init to match changes upstream

---

libraries/WiFiProv/library.properties

Set the category to silence this warning in the Arduino IDE:
```
WARNING: Category '' in library WiFiProv is not valid. Setting to 'Uncategorized'
```

Set WiFiProv category to silence a warning in Arduino IDE

---

variants/m5stack_timer_cam/pins_arduino.h

- M5Stack timercam has a builtin LED on pin 2
- SS/MOSI/MISO/SCK is available internal as on any ESP32

M5TimerCam: add LED_BUILTIN & SS/MOSI/MISO/SCK

---

cores/esp32/main.cpp

Added guarded define to set the stacksize on the main looptask.
Advantage of this is that build_flags can be used to provide a different value for the stack size should it be neccessary
default behaviour is unaffected

[1.0.5] Make looptask stack size configurable

---

cores/esp32/esp32-hal-timer.c

Hi folks,
As seen in https://github.com/crankyoldgit/IRremoteESP8266/issues/1350 and https://github.com/taligentx/dscKeybusInterface/issues/80, the Arduino/esp32 hardware timer functions are currently not in IRAM and cause crashes when called from an ISR:
```
Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed)
Core 1 register dump:
PC      : 0x400d6838  PS      : 0x00060034  A0      : 0x80081aa8  A1      : 0x3ffbffa0  
A2      : 0x3ffc1be0  A3      : 0x20000000  A4      : 0x00000400  A5      : 0x00000000  
A6      : 0x3ffc7458  A7      : 0xffffffff  A8      : 0x800812ff  A9      : 0x00000001  
A10     : 0x3ffbdcb8  A11     : 0x00000000  A12     : 0x3ffba264  A13     : 0x0000abab  
A14     : 0x3ffc7058  A15     : 0x00000000  SAR     : 0x00000012 …
```

Resolve hardware timer functions not in IRAM, crashes when called from ISR

---

libraries/BLE/src/BLERemoteService.cpp

Compiler complains on unused parameter pCharacteristicMap:
framework-arduinoespressif32\libraries\BLE\src\BLERemoteService.cpp: In member function 'void BLERemoteService::getCharacteristics(std::map<short unsigned int, BLERemoteCharacteristic*>*)':
\framework-arduinoespressif32\libraries\BLE\src\BLERemoteService.cpp:246:89: warning: parameter 'pCharacteristicMap' set but not used [-Wunused-but-set-parameter]
void BLERemoteService::getCharacteristics(std::map<uint16_t, BLERemoteCharacteristic*>* pCharacteristicMap) {

Sanitize compiler warning in BLERemoteService.cpp (issue #4660)

---

libraries/BLE/src/BLERemoteCharacteristic.cpp
libraries/BLE/src/BLERemoteCharacteristic.h

**Background**
I have an iTag that I'm wanting to use as a BLE button to control an application on my ESP32.
**Problem**
The iTag doesn't require explicit registration for a client to be able to listen to `notify` events. Currently, the `BLERemoteCharacteristic::registerForNotify` function tries to update the remote descriptor at `0x2902` and register/unregister the client as required.
As the iTag doesn't have this descriptor, it causes an unhandled exception error and crashes the application.
**Changes**
To support devices that don't require you to explicitly register to follow such events, I've added a simple `descriptorRequiresRegistration` flag to the `BLERemoteCharacteristic::registerForNotify` function. This defaults to true, for backward compatibility.
Thanks!

Permit `notify` event subscription when BLE servers don't require registration

---

libraries/BluetoothSerial/examples/SerialToSerialBT_SSP_pairing/SerialToSerialBT_SSP_pairing.ino
libraries/BluetoothSerial/src/BluetoothSerial.cpp
libraries/BluetoothSerial/src/BluetoothSerial.h

Added authentication callbacks and example, resolves #4622.

BluetoothSerial SSP Authentication with callbacks

---

libraries/WiFi/src/ETH.cpp
libraries/WiFi/src/ETH.h

Add support for the IP101 chip to be able to use the Espressif Ethernet Kit. Based on this issue: https://github.com/espressif/arduino-esp32/issues/3554

Add IP101 support

---

libraries/BLE/src/BLERemoteCharacteristic.h

Provide access to characteristic's service, especially useful when receiving a notification registered via `BLERemoteCharacteristic::registerForNotify` as the callback only gets the characteristic as a parameter so you can't differentiate between multiple connected devices with multiple notification subscriptions.
More details in https://github.com/espressif/arduino-esp32/issues/3367 for use cases.

Make BLERemoteCharacteristic::getRemoteService() public #3367

---

cores/esp32/esp32-hal-rmt.c

I fixed the following compilation warning.
```
C:\Users\estshorter\.platformio\packages\framework-arduinoespressif32\cores\esp32\esp32-hal-rmt.c: In function 'rmtLoop':
C:\Users\estshorter\.platformio\packages\framework-arduinoespressif32\cores\esp32\esp32-hal-rmt.c:244:9: warning: unused variable 'channel' [-Wunused-variable]
int channel = rmt->channel;
^
```
Note: This is already fixed in the `idf-release/v4.0` and `idf-release/v4.2` branches.
https://github.com/espressif/arduino-esp32/blob/d011dd7ef5d26e7ba2c2c093f422c534bacf4661/cores/esp32/esp32-hal-rmt.c#L237-L249

Remove an unused variable 'channel'

---

tools/platformio-build.py

The default Arduino partitions are now moved to a separate section instead of global declaration. 
cc @ivankravets

Sync PlatformIO build script with changes in partitions processing

---

tools/platformio-build-esp32.py
tools/platformio-build-esp32s2.py

This PR fixes a possible issue when a user specifies an environment with a whitespace character in its name, e.g.:
```ini
[env:esp wrover kit]
platform = espressif32
framework = arduino
board = esp-wrover-kit
```
https://github.com/platformio/platform-espressif32/pull/483 depends on this fix.
cc @me-no-dev

Update PlatformIO build script to handle spaces in env names

---

libraries/WebServer/src/Parsing.cpp

Uploads are very slow because of an unnecessary "client.connected()" check in _uploadReadByte().
Here is what happens:
client.connected() is called for every byte read.  WiFiClient::connected() calls recv(fd(), &dummy, 0, MSG_DONTWAIT); which takes a relatively long time, so the optimized path of returning a buffered byte via client.read() is effectively nullified.
Removing the one line changed the upload speed for a 2 MB file (discarding the received data) from 22 KB/sec (before) to 367 KB/sec (after).
The change is safe in the face of disconnects because client.read(), when it no longer has buffered data, calls (WiFiClient)  fillBuffer(), which calls recv(), so the disconnection will be detected in due course.

Speed up upload by a factor of 17

---

libraries/BLE/src/BLEClient.cpp
libraries/BLE/src/BLERemoteCharacteristic.cpp

Apply the BLE memory leak fix reported in issue #4753.

Fixed a memory leak in BLE (issue #4753)

---

libraries/BLE/src/BLERemoteCharacteristic.h

Hello,
currently it is not possible to subscribe for the remote characteristic's notification with additional context. This way it's really hard to distinguish the source of callback in case if you are connected to multiple devices that shares the same callback function. Thanks to this pull request one can implement the BLERemoteCharacteristicCallbacks interface and then they can easily determine the device connected to particular notification. It is very useful for my case.
Let me know what do you think about it

Added callbacks to BLERemoteCharacteristic

---

boards.txt
variants/lolin32-lite/pins_arduino.h
variants/ttgo-t7-v13-mini32/pins_arduino.h
variants/ttgo-t7-v14-mini32/pins_arduino.h

Add the Wemos Lolin32 Lite (no longer being produced like the original Lolin32) and the TTGO T7 v1.3 and v1.4 boards (status unknown). All three are rather generic ESP32 boards the main difference being pin layouts and ESP32 module type.

Add Lolin32 Lite and TTGO T7 boards

---

libraries/WiFiClientSecure/src/WiFiClientSecure.cpp

The temp buffer serves no purpose here. Also mbedtls_strerror can be called with size == 0 safely.

Remove temp buffer in WiFiClientSecure::lastError

---

libraries/WiFiClientSecure/src/ssl_client.cpp

mbedTLS requires repeated calls to mbedtls_ssl_write() whenever it returns MBEDTLS_ERR_SSL_WANT_READ or MBEDTLS_ERR_SSL_WANT_WRITE. this happens when the client sends data faster then the server or the connection can handle.

Fix dropped SSL connection when buffer gets full.

---

libraries/BLE/src/BLEAddress.cpp
libraries/BLE/src/BLEAddress.h

Allows BLEAddress to be used as key in std::map etc

Added BLEAddress operator overload methods

---

CMakeLists.txt
cores/esp32/esp32-hal-log.c
cores/esp32/esp32-hal-log.h

With this PR user can select to use the original ESP-IDF log instead of the redefined one.
User can also redefine the log function as per [Logging Library](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/log.html#_CPPv419esp_log_set_vprintf14vprintf_like_t) so he can for example redirect logs to a file.
To enable this change just add -DUSE_ESP32_LOG to build flags.
User can also change the default TAG (that now is ES32) to whatever it wants adding '-DTAG="tag_value"' to build flags

Added possibility to use ESP32-IDF log insted of redefined one

---

cores/esp32/WMath.cpp

The check for divisor==0 was removed in last commit.  This is still necessary.

Add div by zero check back into WMath::map

---

libraries/FS/src/FS.cpp
libraries/SD/src/SD.cpp
libraries/SD/src/SD.h
libraries/SD/src/sd_diskio.cpp
libraries/SD/src/sd_diskio.h
libraries/SD_MMC/src/SD_MMC.cpp
libraries/SD_MMC/src/SD_MMC.h

- File might not eval to false if opened with write/append and SD is gone
- Allow card to be formatted if FAT partition was not found
- Mark card as gone in certain situations
- Fix several logic errors in low level SD API

Fix several SD card issues

---

cores/esp32/esp32-hal-bt.c

Fixed use of CONFIG_BLUEDROID_ENABLED instead of CONFIG_BT_ENABLED in HAL. This prevented compilation with Nimble-only configuration without apparent benefit.

Fixed use of Bluedroid instead of BT in HAL.

---

tools/platformio-build.py

For the PlatformIO build script. 
Per https://github.com/espressif/arduino-esp32/tree/master/tools/sdk/include this folder doesn't exist exist anymore, so users will see a warning in VSCode regarding this non-existent folder (see [here](https://community.platformio.org/t/fatal-error-pins-arduino-h-no-such-file-or-directory/19634/7?u=maxgerhardt) for example).
I don't know whether nimble has been removed or renamed, but this change just removes the reference to the folder in the platformio build script.
It looks like it's also gone from other branches (v4.0, v4.2), so.. it should also be merged there I guess.

Remove tools/sdk/include/nimble from include path

---

libraries/WebServer/examples/AdvancedWebServer/AdvancedWebServer.ino
libraries/WebServer/examples/FSBrowser/FSBrowser.ino
libraries/WebServer/examples/HelloServer/HelloServer.ino
libraries/WebServer/examples/HttpAdvancedAuth/HttpAdvancedAuth.ino
libraries/WebServer/examples/HttpBasicAuth/HttpBasicAuth.ino
libraries/WebServer/examples/PathArgServer/PathArgServer.ino
libraries/WebServer/examples/SDWebServer/SDWebServer.ino
libraries/WebServer/examples/SimpleAuthentification/SimpleAuthentification.ino
libraries/WebServer/examples/WebUpdate/WebUpdate.ino
libraries/WebServer/src/HTTP_Method.h
libraries/WebServer/src/Parsing.cpp

Fixes: https://github.com/espressif/arduino-esp32/issues/4884

Use HTTP method table from ESP-IDF's nghttp

---

tools/platformio-build.py

This PR adds PSRAM-specific libraries to the final linker command depending on the `BOARD_HAS_PSRAM` macro.
cc @me-no-dev

Add PSRAM-specific libs to PlatformIO build script

---

libraries/WiFi/src/WiFiSTA.cpp

In case you have multiple APs with the same SSID/password and WiFi.begin(ssid, pwd) is called, ESP32 defaults to connect to THE FIRST AP FOUND matching ssid - according to:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html#_CPPv418wifi_scan_method_t
This can cause situations that ESP32 is trying to connect to AP which is far away from it (weak signal) even there is AP close to it, just as in my house - I have AP on channel 6 which is in the 1st floor (quite far from room where I do the programming) and AP on channel 13 in the same room I do the programming (which is in the 2nd floor) - result: ESP32 is trying to connect to the AP on channel 6 because it finds it first and never try the AP on channel 13 in the same room, result of this is very …

WiFi.begin() should choose the nearest/strongest AP, not the first one found (which is default now)

---

libraries/BLE/src/BLEAdvertising.cpp
libraries/BLE/src/BLEAdvertising.h

In some use cases getting rssi signal from one channel is more stable (less variance) than rssi from the three advertising channels. 
This change allows you to specify which channels are used to advertise.

Allows you to specify which channels are used to advertise.

---

variants/twatch/pins_arduino.h

That solves
```
C:\Users\user\.platformio\packages\framework-arduinoespressif32@src-7a495aa357652c59e127d3388578e1f1\cores\esp32\esp32-hal-gpio.c: In function '__pinMode':
C:\Users\user\.platformio\packages\framework-arduinoespressif32@src-7a495aa357652c59e127d3388578e1f1\cores\esp32\esp32-hal-gpio.c:238:44: error: 'RX' undeclared (first use in this function); did you mean 'RX1'?
pinFunction |= ((uint32_t)(((pin)==RX||(pin)==TX)?0:1) << MCU_SEL_S);
^~
RX1
```

[2.0.0] Add missing default TX and RX for T-watch

---

libraries/SD/src/SD.cpp
libraries/SD/src/SD.h
libraries/SD/src/sd_diskio.cpp
libraries/SD/src/sd_diskio.h

This is added to easy use with usb msc.

[2.0.0] Add support to read/write raw sectors from/to sd card

---

libraries/WiFiClientSecure/src/ssl_client.cpp

mbedTLS requires repeated calls to mbedtls_ssl_write() whenever it returns MBEDTLS_ERR_SSL_WANT_READ or MBEDTLS_ERR_SSL_WANT_WRITE. this happens when the client sends data faster then the server or the connection can handle.
Fixes: https://github.com/espressif/arduino-esp32/issues/2494

[2.0.0] Fix dropped SSL connection when buffer gets full.

---

CMakeLists.txt

Made selective compile of ArduinoOTA and LITTLEFS libraries add necessary ESP-IDF components in priv_requires. If selective compilation is disabled the requirements will be added anyway.

[2.0.0] Made selective compile of ArduinoOTA and LITTLEFS libraries add requires

---

libraries/WiFiProv/src/WiFiProv.cpp

Use of BLE_SCHEME was protected with CONFIG_BLUEDROID_ENABLED except for this one place causing compliation errors when Bluedroid is disabled. A change to use other BLE hosts for BLE scheme is outside of the scope of this PR but should be considered.

[2.0.0] Fixed missing conditional around BLE_SCHEME.

---

libraries/WiFi/src/ETH.cpp
libraries/WiFi/src/ETH.h

This adds support for the KSZ8081 ethernet phy.
Only the IDF 4+ specific code is modified, as the phy support was only
added recently:
espressif/esp-idf@aecfbf96

Add KSZ8081 support.

---

cores/esp32/HardwareSerial.cpp

workaround for #5043.  There is a timing issue with HardwareSerial::end.  I'm not sure what is hung, but it should be possible to see this in jtag, as it does cause a reboot if you let it.  The delay needs to be before you detach the device!?

Serial::end hang

---

cores/esp32/esp32-hal-ledc.c
cores/esp32/esp32-hal-ledc.h

Currently there is no real option to change the pwm frequency programmatically. The only "hack" solution is to use the `ledcWriteTone(uint8_t chan, double freq)` method.
But there is problem with this hack. Inside this method the bit resolution value is hard coded to 10. Which means if you had a different bit resolution inside your setup it would be overrided here.
So I added a simple method to change the pwm frequency programmatically. This method takes three parameters:
`uint8_t chan, double freq, uint8_t bit_num`

Added method to change the ledc PWM frequency programmatically

---

libraries/WiFiClientSecure/examples/WiFiClientSecure/WiFiClientSecure.ino
libraries/WiFiClientSecure/examples/WiFiClientSecureEnterprise/WiFiClientSecureEnterprise.ino

The key and cert were flipped. It's just in the comments, but might avoid confusion.

WiFiClientSecure fix flipped cert/key in comment

---

libraries/WiFi/src/WiFiAP.cpp

* AP with old WPA should not be used due security flaws.
* restore behavior from 1.0.6, see https://github.com/espressif/arduino-esp32/blob/46d5afb17fb91965632dc5fef237117e1fe947fc/libraries/WiFi/src/WiFiAP.cpp#L127

softAP should only start modern WPA2

---

CMakeLists.txt

Tinyusb was required on platforms where it was not available.

Added condition to only use tinyusb as needed

---

libraries/HTTPClient/examples/BasicHttpsClient/BasicHttpsClient.ino

Having two servers in the list implies that sntp will use the second if first is not available.  SNTP will only use one as compiled - [source](https://github.com/espressif/esp-lwip/blob/2c9c531f0a7e0ee536db9de4f9dc54e453712087/src/include/lwip/apps/sntp_opts.h#L61).

Removed second NTP server from configTime. SNTP only uses one

---

libraries/ESPmDNS/src/ESPmDNS.cpp
libraries/ESPmDNS/src/ESPmDNS.h

Add method `MDNSResponder::txtKey(int idx, int txtIdx)` aka `MDNS.txtKey(int idx, int txtIdx)` to be able to get mDNS TXT record name (key) and explore TXT records. Closes #5132

MDNSResponder: Add method to get TXT key values.

---

cores/esp32/main.cpp

This PR lets the user override the LOOP STACK SIZE set in sdkconfig (for example with -DARDUINO_LOOP_STACK_SIZE=12288).

Make LOOP_STACK_SIZE user configurable at compile-time.

---

libraries/ArduinoOTA/library.properties
libraries/AsyncUDP/library.properties
libraries/BLE/library.properties
libraries/BluetoothSerial/library.properties
libraries/DNSServer/library.properties
libraries/EEPROM/library.properties
libraries/ESP32/library.properties
libraries/ESPmDNS/library.properties
libraries/FFat/library.properties
libraries/FS/library.properties
libraries/HTTPClient/library.properties
libraries/HTTPUpdate/library.properties
libraries/HTTPUpdateServer/library.properties
libraries/LITTLEFS/library.properties
libraries/NetBIOS/library.properties
libraries/Preferences/library.properties
libraries/RainMaker/library.properties
libraries/SD/library.properties
libraries/SD_MMC/library.properties
libraries/SPI/library.properties
libraries/SPIFFS/library.properties
libraries/SimpleBLE/library.properties
libraries/Ticker/library.properties
libraries/USB/library.properties
libraries/Update/library.properties
libraries/WebServer/library.properties
libraries/WiFi/library.properties
libraries/WiFiClientSecure/library.properties
libraries/WiFiProv/library.properties
libraries/Wire/library.properties

There are conflicts with some arduino built-in libraries.  This should help resolve them, although it does not fix the underlying name conflicts.

Bump library versions to 2.0.0

---

cores/esp32/WString.cpp
libraries/HTTPClient/examples/StreamHttpClient/StreamHttpClient.ino

There was some typos in the example code, etc.

Fix length typo

---

libraries/WiFi/src/WiFiClient.cpp

Thi may happen if `read()` gets called repeatedly (such as in `HttpClient` to parse response headers) and the connection is closed unexpectedly or the remote peer may have unexpected behavior that causes the underlying socket to report an error. In that case `read()` itself calls `stop()`, which invalidates the receive buffer object. Then when `read()` is called again without checking, such as inside `readStringUntil()`, the `_rxBuffer` is null and ESP32 crashes.
See also #3659

Fix crash in WiFiClient when read() called after stop()

---

CMakeLists.txt

Adding back missing dependency for wifi provisioning.
This has been removed in https://github.com/espressif/arduino-esp32/commit/5502879a5b25e5fff84a7058f448be481c0a1f73#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a but does not describe why or whether this was an oversight.
It was also missing in 2020 and has been previously added in https://github.com/espressif/arduino-esp32/commit/934841e2360e3f3c87354fd5bf9d5789308bf9a8#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a.
Without this, compiling this library as part of an esp-idf component fails as the compiler cannot find `#include "wifi_provisioning/manager.h"` in WifiProv.h

Add missing Wifi Provisioning dependency

---

libraries/WiFiClientSecure/src/ssl_client.cpp

`_handle_error`'s parameter is a function name, not a file name. See:
```
#define handle_error(e) _handle_error(e, __FUNCTION__, __LINE__)
```

ssl_client.cpp: Fix parameter name in _handle_error.

---

libraries/BLE/LICENSE

The code in the BLE library originates from https://github.com/nkolban/esp32-snippets/tree/master/cpp_utils as well as https://github.com/nkolban/ESP32_BLE_Arduino
The original code in the esp32-snippets library is apache-2.0 licence'ed.
In addition when Neil Kolban stopped maintaining this library he made it available with the express requirement that the licence stays as apache-2.0
(Please see: https://github.com/nkolban/esp32-snippets/issues/813)
"... I do require that it continue to be Apache Licensed and free of charge for any and all uses (private or commercial)."
This change is to clarify the licence of this library.

restore apache-2.0 licence to to BLE library

---

variants/doitESPduino32/pins_Arduino.h

The doitESPduino32/pins_Arduino.h lacks definitions for the common SPI pins names: SS, MOSI, MISO, SCK
This breaks compatibility with Arduino libs, including SPI.h/.cpp
This PR solves the issue while maintaining compatibility with previous pin naming (IO5/23/19/18), and ensures consistency with other boards variants.

doitESPduino32 - Add definitions for SPI pins names

---

cores/esp32/esp32-hal-adc.c

Convert hall read to use hal/idf

---

cores/esp32/Esp.cpp

original PR #5278 from @s-hadinger, which is not accepted because of failure of CLAassistant
`ESP.getFlashChipSize()` always returns `0` on Esp32c3 due to a change in the Flash layout. It looks like to Espressif documentation was not updated accordingly.
https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-reference/storage/spi_flash.html#spi-flash-size
- Esp32 and Esp32s3 have the flash information update by esptool.py
and decribed here
- https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/spi_flash.html
Esp32c3 has no image information at 0x0000 and contrary to the docu
this information is at offset 0x0000

Fix incorrect Flash Size in Esp32c3

---

CMakeLists.txt

Fix for the issue  #5293 `/components/arduino/libraries/WebServer/src/HTTP_Method.h:4:10: fatal error: http_parser.h: No such file or directory
#include "http_parser.h"`

Fix #5293 by adding missing dependency to nghttp

---

cores/esp32/WString.cpp

This patch removes the unneeded call to `strlen()` when concatenating some types to a `String`. Additionally it fixes some whitespace for consistency.

Make String::concat() faster for some types.

---

cores/esp32/esp32-hal-uart.c

This solves issue #5112
Call to pinMatrixInDetach() was changed from version 1.0.6 in version 2.0.0 injecting a bug as seen in cores/esp32/esp32-hal-uart.c
https://github.com/espressif/arduino-esp32/commit/80418fadcfb91c75d5100a8fddeb9318a8ef7d42

pinMatrixInDetach() has wrong parameter

---

CMakeLists.txt

arduino-esp32 has to depend on main in autostart mode, for setup() and loop(),
but this can be done with undefined symbol entries to avoid a large dependency
cycle and other linker errors.
Closes https://github.com/espressif/esp-idf/issues/6968

arduino as component: Remove circular dependency around 'main'

---

cores/esp32/esp32-hal-adc.c
cores/esp32/esp32-hal-adc.h

Fix pin attenuation being overwritten

---

CMakeLists.txt

Same as https://github.com/espressif/arduino-esp32/pull/5401 but targeting idf-master branch.

add optional component dependencies after Kconfig options are known (idf-master)

---

cores/esp32/Arduino.h

Added definitions of direct GPIO access macros for SOC_GPIO_PIN_COUNT <= 32.
Closes https://github.com/espressif/arduino-esp32/issues/5378

fix port{Input,Output,Mode}Register macros for chips with <=32 pins

---

.github/scripts/install-platformio-esp32.sh
.github/workflows/push.yml
package.json

This PR is an initial attempt to switch the CI to the latest toolchains 8.4.0 for ESP32, ESP32S2, ESP32C3 from Espressif. Additionally, updated the CI to install PlatformIO from master branch for better robustness and freshened `package.json`.
cc @me-no-dev

PlatformIO updates for CI

---

libraries/BLE/src/BLECharacteristic.cpp
libraries/BLE/src/BLECharacteristic.h

Is there a specific reason for it not to be included for the end user? The code should be self explanatory.

Added function to retrieve the amount of data received from an BLECharacteristic

---

libraries/WiFi/src/WiFiAP.cpp

backport from v2 to v1 of fix #5121
fixes #5038

[backport-v1] Fix softap_config_equal compare auth_mode/cipher

---

README.md

Links updated due the new ReadTheDocs branch (master/latest).
- ReadTheDocs badge link updated.
- Documentation reference links updated.

Links to the new docs updated and new docs build badge added

---

libraries/SD/src/sd_diskio.cpp

Fixes SD begin() end() memory leak #2897

---

libraries/WiFiClientSecure/src/ssl_client.cpp

Closes #5398
Using the same non-blocking socket connect pattern for respecting connection timeout, copied from [WiFiClient::connect](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiClient.cpp#L212).
`WiFiClient::connect` uses `lwip_connect_r`, whereas [start_ssl_client](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/src/ssl_client.cpp#L54) uses `lwip_connect`. I haven't found what is the difference between them. I tested both, both work ok, so I kept `lwip_connect`.

fix: Respecting connection timeout in WiFiClientSecure

---

cores/esp32/stdlib_noniso.c

This fixes the integer to string conversion functions broken in dd25e2b. (See #5423 )
It would be nice if someone using the ESP-DSP lib (https://github.com/espressif/esp-dsp ) could test whether it still compiles.

Unbreak integer to string conversion functions. (#5423)

---

cores/esp32/esp32-hal-ledc.c

Fixes ESP32-S2 LEDC PWM #5375 #5050

---

cores/esp32/esp32-hal-tinyusb.c

Weaken tinyusb callbacks to allow other libraries to coex with hal library.

Weaken tinyusb callbacks

---

libraries/BLE/src/BLEDevice.cpp

CLASSIC_BT_ENABLED never worked as was incorrectly named, e.g. see
https://github.com/nkolban/esp32-snippets/issues/890#issuecomment-521520934
Now corrected to the update-to-date name CONFIG_BT_CLASSIC_ENABLED.

Fixed CLASSIC_BT_ENABLED to CONFIG_CLASSIC_BT_ENABLED.

---

libraries/HTTPClient/src/HTTPClient.cpp

In [HTTPClient](https://github.com/espressif/arduino-esp32/tree/master/libraries/HTTPClient), if the `Transfer-Encoding` header is set to `identity`, an error (Transfer-Encoding not supported) will occur.
HTTPClient will consider the request as `identity` if the `Transfer-Encoding` header is not set. But it is also defined a response with `identity` explicitly set in the `Transfer-Encoding` header (ref:[MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding)).
This pull request will allow the request to be processed normally even when `identity` is explicitly set. Please consider this fix.

HTTPClient: Support for Transfer-Encoding headers that specify "identify"

---

libraries/WiFi/src/WiFiClient.cpp

WiFiClient's connect method variant where no timeout is passed can block esp32 MCU and may then cause watchdog to kick in and reset the device. This behavior is different from that, what is in arduino-esp8266 core.
Some cross-esp libraries (working both on esp32 and 8266), like PubSubClient simply call connect method on WiFiClient, to get connected to remote server. However, connect behavior varies betwen esp arduino 8266 and esp arduino 32 cores. This pull request tries introduce same behavior - to make connect method non-blocking on esp32, like it is with 8266 arduino core.
Introduce default fixed timeout that can be changed by #define - by default set to 3 seconds.
WiFiClient
```c++ 
int connect(IPAddress ip, uint16_t port);
int connect(const char *host, uint16_t port);
```
May impact …

[WiFiClient] Default connection timeout, when no timeout provided

---

cores/esp32/esp32-hal-uart.c

Fixes: https://github.com/espressif/arduino-esp32/issues/5513
Can still race if Serial.begin() is not called in setup()

Fix race in log_printf

---

libraries/WiFi/src/WiFiClient.cpp

https://github.com/espressif/arduino-esp32/pull/5487 introduced a default timeout for WiFiClient, however the default was specified in milliseconds instead of seconds, see https://github.com/espressif/arduino-esp32/commit/be84c8219c251210afd87cac71b8ef3527b601b3#commitcomment-54358731
This 3ms timeout breaks OTA when the processor is busy.
Sets the default to a saner value, fixes OTA.

Increase default timeout for WiFiClient from 3ms to 3s

---

cores/esp32/esp32-hal-i2c.c

Thanks @chegewara
I2C Scan was failing because `i2c_master_write` does not accept size of 0. This change checks and skips that call if no length is provided (usually when scanning)

Fix I2C Scan for S2 and C3

---

cores/esp32/esp32-hal-touch.c

Fixes #5493 
PR #4996 has broken Touch Interrupt functionality by removing a single line of code used to set a Register.
This PR fixes issue #5493 by reverting the removal of necessary code as described above.

Fixes Touchpad Interrupt

---

docs/source/boards/boards.rst

Closes: https://github.com/espressif/arduino-esp32/issues/5431
Added LOLIN boards D32 and D32 Pro links.
None

Added LOLIN dev kits to the boards list

---

docs/source/boards/boards.rst

This PR fix the link to the LOLIN boards to a new tab. All new links to external pages should be as this PR is.
None.

Fixed the external link to a new tab (LOLIN boards)

---

boards.txt
variants/franzininho_wifi_esp32s2/pins_arduino.h
variants/franzininho_wifi_msc_esp32s2/pins_arduino.h

This PR adds the support for the Franzininho WiFi board in CDC and MSC modes.
References: https://franzininho.github.io/docs-franzininho-site/docs/franzininho-wifi/franzininho-wifi/
https://github.com/Franzininho/imagens-franzininho/blob/main/franzininho_wifi/pinagem-franzininho-wifi.png
No impact.

Added Franzininho WiFi board support

---

cores/esp32/esp32-hal-timer.c

fix: timerRead() is returning the last read value, not the actual #3434

fix: timerRead() is returning the last read value, not the actual #3434

---

boards.txt
variants/esp32micromod/pins_arduino.h

Adds support for the [SparkFun ESP32 MicroMod microcontroller board](https://www.sparkfun.com/products/16781). Adds the relevant section to `boards.txt` and adds an `esp32micromod` folder with the proper `pins_arduino.h` to the `variants` folder.
Feedback is requested! I'm not sure if there's anything else required to add support for this microcontroller; let me know what needs doing and I'll figure out how to do it!
Allows users to compile code properly for the ESP32 MicroMod without having to use a similar board and manually entering pin numbers.
- [SparkFun Product Page](https://www.sparkfun.com/products/16781)
- [SparkFun Software Setup Guide](https://learn.sparkfun.com/tutorials/micromod-esp32-processor-board-hookup-guide/software-setup-and-programming)
- [SparkFun Board Manager …

Add SparkFun ESP32 MicroMod microcontroller

---

cores/esp32/HardwareSerial.cpp
cores/esp32/HardwareSerial.h
cores/esp32/esp32-hal-uart.c
cores/esp32/esp32-hal-uart.h

This PR is a complete reffactoring of UART Serial Hardware and respective HAL in order to use IDF instead of current Register manipulation approach. 
It  implements Arduino SerialEvent functionality. 
Fix #5287  
Fix #5273 
Fix #5519 
Fix #5247 
Fix #5403
Fix #5429
Fix #5047
Fix #5463
Fix #5362 
Fix #5112  
Fix #5443 
It solves many reported issues related to UART.
It was tested and works fine for ESP32, ESP-S2 and ESP32-C3.

Implements UART SerialHardware Refactoring on top of IDF

---

cores/esp32/HardwareSerial.cpp
cores/esp32/HardwareSerial.h

It adds HardwareSerial::setRxBufferSize() with default value of 256 bytes.
Fixes #5580 
It allows to define a Rx Buffer Size for UART, before begin().

Adds HardwareSerial::setRxBufferSize()

---

boards.txt

Fixes #5572.
There were several boards that were missing the _upload.flags_ and _upload.extra_flags_ fields, resulting in an error during upload of a sketch.

Add missing upload.flags on boards.txt

---

cores/esp32/WString.cpp
cores/esp32/WString.h

Applies the upstream changes here: https://github.com/arduino/ArduinoCore-API/compare/3b88acac8%5E...0d83f1afc3367037dbde5323c2abd0ae1bd2c583
Adds new String convenience methods that are now available in the mainline Arduino implementation, simplifying interoperability with C code that uses pointer+length strings rather than 0-termination. Also includes a change to avoid mutating the source string when taking a substring.

Add string constructor and concat routines taking explicit length args

---

libraries/BLE/src/BLEServer.cpp

Fix this issue: https://github.com/espressif/arduino-esp32/issues/5573
To reproduce:
1. Run any sample code that starts a BLE server, and does not call `setCallbacks`.
2. Connect to the device using the "LightBlue" app on iOS.
3. Observe crash shown in the issue linked above.
I'm not sure how often the MTU is updated, but the bug should cause a crash in any BLEServer instance, where `setCallbacks` was not called, if the MTU changes.
I haven't actually built and ran this locally, because I haven't had time to setup for local development. The change is tiny, and very simple, but it's probably always worth testing before merging.

BLEServer.cpp Fix: Crash on MTU change if m_pServerCallbacks not set.

---

cores/esp32/USBCDC.cpp
cores/esp32/USBCDC.h

Depending on `tud_cdc_tx_complete_cb` can cause in some cases the last packet to not be transmitted until more data is written and flushed. It's a rare case, but if the other end is expecting those last bytes, transmission will hang.
This PR also fixes debug output on CDC

[USB CDC] Fix data might not be transmitted until more is written

---

boards.txt
cores/esp32/HWCDC.cpp
cores/esp32/HWCDC.h
cores/esp32/esp32-hal-uart.c

This pull request contains a few fixes and improvements to the HWCDC implementation.
- Rework `HWCDC::write()` to accept unlimited data
- Add Semaphore to guard the TX Ring Buffer
- Add events support
- Remove unnecessary 1200bps touch for flashing over HWCDC
- Fix `HardwareSerial::setDebugOutput()` not resetting `putc` if the port is already selected, causing debug output to also show on HWCDC even when not selected.

[HWCDC] Improve HW CDC Implementation

---

libraries/SD_MMC/src/SD_MMC.cpp

I noticed that `max_freq_khz` was set twice to different values; I picked the last one. I made a fix because previously `SDMMC_FREQ_DEFAULT` was used in the host initialization, and some users elsewhere suggest lowering `SDMMC_FREQ_DEFAULT` from 20_000 to 5_000. Now it's clearly seen that changing `SDMMC_FREQ_DEFAULT` won't affect the initialization of an SD card with the SD_MMC driver.
It has no impact other than improving code clarity.
------
BTW, I don't understand why `host` initialization has been changed from
```c
sdmmc_host_t host = {
.flags = SDMMC_HOST_FLAG_4BIT,
.slot = SDMMC_HOST_SLOT_1,
.max_freq_khz = SDMMC_FREQ_DEFAULT,
.io_voltage = 3.3f,
.init = &sdmmc_host_init,
.set_bus_width = &sdmmc_host_set_bus_width,
.get_bus_width = &sdmmc_host_get_slot_width,
.set_bus_ddr_mode = …
```

SD_MMC max_freq_khz is set to HIGHSPEED by default

---

libraries/HTTPClient/src/HTTPClient.cpp

Append '/' to an URL with empty path in HTTPClient::begin. For example, `http.begin("http://example.com")` is the same as `http.begin("http://example.com/")`.
~Add an error check for empty path of HTTPClient::begin. For example, `http.begin("http://example.com")` returns false because the path of it is empty (`http.begin("http://example.com/")` returns true).~
RFC2616 and RFC2396 say this url is invalid. Furthermore, most servers return `400 Bad Request`.

Append '/' to an URL with empty path in HTTPClient::begin

---

cores/esp32/HardwareSerial.cpp

Fix compilation in case NO_GLOBAL_INSTANCES || NO_GLOBAL_SERIAL is defined.

Fix compilation of HardwareSerial.cpp

---

platform.txt
tools/espota.py

See #5656
Enabling the progress bar on OTA upload.
Instead of showing
`Uploading...........................................................................................`
and nothing when finished, a progress bar is shown:
`Uploading: [============================================================] 100% Done...`

Enable progress bar on ArduinoOTA upload (platform.txt)

---

libraries/SD_MMC/src/SD_MMC.cpp
libraries/SD_MMC/src/SD_MMC.h
variants/esp32-evb/pins_arduino.h

On Olimex ESP32 EVB I/O operations with SD card can cause error when LAN is used in same time.
Problem is disappearing if SD MMC frequency lower down from SDMMC_FREQ_HIGHSPEED to SDMMC_FREQ_DEFAULT.
No problem if WiFi used instead LAN.
For issue https://github.com/espressif/arduino-esp32/issues/5682

SDMMC frequency selection based on board type

---

cores/esp32/libb64/cdecode.c

This commit fixes a logic error / off-by-one error in [cores/esp32/libb64/cdecode.c at lines 15+16](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/libb64/cdecode.c#L15).
An if-condition bounds the value of 'value_in' which is used for array-indexing.
The array is 80 elements long, and the if-condition checks if value_in < 0 || value_in > decoding_size (80).
However accessing an array at index sizeof(array) is invalid - the condition should have been 'value_in < 0 || value_in >= decoding_size' instead.
```C
11	static int base64_decode_value_signed(int8_t value_in){
12	  static const int8_t decoding[] = {62,-1,-1,-1,63,52,53,54,55,56,57,58,59,60,61,-1,-1,-1,-2,-1,-1,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,-1,-1,26,27,28,29,30,31, …
```

fix off-by-one error in cores/esp32/libb64/cdecode.c

---

cores/esp32/esp32-hal-adc.c

Potential fix for #5691 and #5658.
Sets a different default value for `analogWidth` in `esp32-hal-adc.c` for ESP32S2 based boards. This fixes issue with performing `analogRead` on that platform.
Test sketch run on an [Adafruit FunHouse](https://www.adafruit.com/product/4985) which has an analog light sensor attached to `A3`:
```cpp
void setup() {
Serial.begin(9600);
}
void loop() {
Serial.println(analogRead(A3));
delay(100);
}
```

Fix analogWidth for ESP32S2 in esp32-hal-adc.c

---

cores/esp32/USB.cpp

add `pin_arduino.h` include in core's USB.cpp. This allows macro defined by variant e.g USB_VID, USB_PID to be used correct per board.
Correct the USB defines such as VID/PID, manufacturer in usb descriptor. Following is `lsusb` output with Adafruit Metro ESP32-S2 board before and after the PR
Before
```
Bus 003 Device 094: ID 303a:0002 Espressif Systems METRO_ESP32S2
```
After
```
Bus 003 Device 096: ID 239a:80df Adafruit Metro ESP32-S2
```
@ladyada

include pin_arduino.h for variant USB defines

---

libraries/FFat/src/FFat.cpp
libraries/FS/src/FS.cpp
libraries/FS/src/FS.h
libraries/FS/src/FSImpl.h
libraries/FS/src/vfs_api.cpp
libraries/FS/src/vfs_api.h
libraries/LittleFS/src/LittleFS.cpp
libraries/SPIFFS/src/SPIFFS.cpp

This PR adds to the SD.open() function option to create all folders to the file.
SD.open(const char* path, const char* mode, const bool **create**)
Default value of create is false.
When **true** folders are created.
From issue #5019
Should not have any impact.

SD.open() new feature for creating all folders in path

---

libraries/WebServer/examples/SDWebServer/SDWebServer.ino

Struggled myself trying to access content on SD card with SDWebserver.ino example, finally figured that I need to pass argument via HTTP Get request. Added that in the comment section of the example to increase user clarity.
Improved comment and usage clarity of an example.

Added comment for user clarity in SDWebserver example

---

cores/esp32/esp32-hal-rmt.c

fix double promotions in rmtSetTick()

---

libraries/HTTPClient/src/HTTPClient.cpp
libraries/HTTPClient/src/HTTPClient.h

The client always appends "Basic" to the authorization header, however there are other auth schemes that can be used: https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
For example "Bearer" when using OAuth.
This PR adds a `setAuthorizationType` method to the HTTPClient which allows this scheme to be configured by the caller. Authorization type is set to "Basic" by default so this will have no impact on existing usecases.
This PR will allow callers to specify the authorization type when making requests, and will not impact any existing usecases as the default is "Basic".

Support additional authorization schemes

---

cores/esp32/esp32-hal-log.h

if (1) log_e("error") produces a warning ("missing braces") and probably wrong code if no log level is defined.
This fixes that.

Allow use of log_x() in if

---

docs/source/libraries.rst

Added supported peripherals list on libraries section.
None.
Closes https://github.com/espressif/arduino-esp32/issues/5785

[Docs] Added supported peripherals list on libraries section

---

docs/source/api/wifi.rst

Added `useStaticBuffers` function description on the documentation.
None.

[Docs] Added useStaticBuffers function description

---

libraries/WiFi/src/WiFiGeneric.h

When using the [FTM examples])https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFi/examples/FTM/) I got an error in the Serial Monitor for FTM_Initiator.ino:
*"wifi:channel=0 is invalid"*
I solved it for myself by simply passing the channel argument to be 1 in *WiFi.initiateFTM*. However, a better fix would be to directly change the default channel [here](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFiGeneric.h).
channel=0 seems to be invalid for initiateFTM, i.e. we get the error message "wifi:channel=0 is invalid". The proposed fix changes the default channel in initiateFTM from 0 to 1.
The example codes for FTM will work out of the box ;)

Solving "wifi:channel=0 is invalid" when using FTM example code by adjusting default channel in WiFiGeneric.h

---

platform.txt

Added an option for using precompiled libraries.
Empty if there is no precompilation.
```
compiler.libraries.ldflags=
```
Compiler Message when there is precompilation.
```
Compiling libraries...
Compiling library "aquestalk-esp32"
Library aquestalk-esp32 has been declared precompiled:
Using precompiled library in C:\Users\tanaka\Documents\Arduino\libraries\aquestalk-esp32\src\esp32
```
The precompiler cannot be used because it is not set up now.
----------------------------------------------------------------------------------------------------------------------------------------------------
This entire section can be deleted if all items are checked.
1. [x] Please provide specific title of the PR …

Add precompiled

---

README.md
docs/source/getting_started.rst

Added the link to the supported SoCs on README file.
Added the link to the ESP32-S3 datasheet to the Getting Started page.
Closes: https://github.com/espressif/arduino-esp32/issues/5890
None.

[Docs] Add link to supported soc list on README and ESP32-S3 datasheet

---

boards.txt

The compilation error of the Deneyap Mini board has been resolved via minor changes in board.txt.
There was a compilation error due to newly released **"arduino-esp32 2.0.0 library"** and it's been fixed.

Fix  compilation error of Deneyap Mini Board

---

cores/esp32/cbuf.h

Changes "private" vars to "protected" so that descendants are allowed to access them.

cbuf: allow inheritance

---

cores/esp32/esp32-hal-i2c-slave.c
cores/esp32/esp32-hal-i2c.c

It was found that when I2C device is holding the clock LOW, ESP32 master is failing to wait for the clock to be released.
Fixes: https://github.com/espressif/arduino-esp32/issues/5875
Fixes: https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/issues/77

Fix I2C clock stretching issue with ESP32

---

docs/source/installing.rst

Update on the Windows install procedure.
None

[Docs] Update on the Windows install procedures

---

libraries/SD/src/sd_diskio.cpp

Edited sd_diskio to work the same as SD_MMC. The ff_sd_status function send command to card to check its status.
If card is disconnected, command will fail.
Fix for #3603
Might have very low impact on speed.

SD Card status check fix

---

.github/workflows/test_selfhosted_runner.yml

Run jobs that require self hosted runners only on the main repository.
https://github.com/espressif/arduino-esp32/pull/5521#issuecomment-986145419
https://github.com/adafruit/arduino-esp32/pull/11
Forks only.

Prevent self hosted jobs to run on forks.

---

libraries/WiFi/src/WiFiSTA.cpp

1.0.6 changed scanning method to always scan all available channels during connect. This results in results in connect taking about ~3 seconds instead of ~1. This patch changes the behavior to use WIFI_FAST_SCAN if client used a specific channel.
Fixes #1675

Use WIFI_FAST_SCAN if a specific channel was used

---

libraries/HTTPClient/src/HTTPClient.cpp

Current implementation clears _headers when request was sent. If the user added custom request headers, they will be lost and the redirected request will not contain them. This commit changes the scope of cleanup (moved from beginInternal() to begin(), changed the amount of data cleared in handleHeaderResponse()), so that the headers survive redirects but don't survive connection reuse.
Possible impact on connection reuse. Tested manually to behave properly.

Don't clear custom HTTP headers on redirect in HTTPClient

---

boards.txt
variants/wt32-eth01/pins_arduino.h

This pull request adds support for the Wireless-Tag WT32-ETH01 board based on the WT32-S1 module and a LAN8720A Ethernet PHY. Reference documentation available at http://www.wireless-tag.com/portfolio/wt32-eth01/
- adds a new board definition
- adds a new pin definition for corresponding variant
- no further changes to existing code base

add board variant for WT32-ETH01 (wt32-eth01) from Wireless-Tag

---

cores/esp32/esp32-hal-timer.c
cores/esp32/esp32-hal-timer.h

This PR is refactoring of TIMER HAL in order to use IDF instead of current Register manipulation approach.
I will do more tests, but everything seems to be working on all chips.
None.

Implement Timer based on ESP-IDF API

---

cores/esp32/MD5Builder.cpp
cores/esp32/MD5Builder.h

Fixes https://github.com/espressif/arduino-esp32/issues/5925 which is failing due to `CONFIG_WPA_MBEDTLS_CRYPTO` being enabled by default which omits the functions: `MD5Init`, `MD5Update`, `MD5Final`.
Migrates to use esp_rom_md5.h directly rather than rely on sdkconfig entries to enable usage.

MD5Builder update for esp_rom API usage

---

libraries/WiFiClientSecure/src/ssl_client.cpp

This should fix issue #5781 and possibly others related to the same problem: the function `start_ssl_client()` does not free memory allocated by mbed-tls library for data structures holding CA certificate, client certificate and private key, in case of early failures (handshake, verification, etc.), but only when the connection is successful.
The proposed fix adds some cleanup code to `stop_ssl_socket()` so that `WiFiSecureClient` does not leak memory when it finally calls `stop()`.

Fix WiFiSecureClient memory leaks when SSL/TLS connection fails

---

libraries/Ethernet/src/ETH.cpp

The previous assertion only considerate the existence of ESP-IDF 4.3, but with the ESP-IDF 4.3.1 release this assertion would generate errors. Now only includes from ESP-IDF 4.4 onwards.
Now don't generate esp_eth_phy_new_ksz8081 not included error

using ksz8081 only from ESP-IDF 4.4 onwards

---

libraries/Wire/src/Wire.cpp
libraries/Wire/src/Wire.h

----------------------------------------------------------------------------------------------------------------------------------------------------
This entire section can be deleted if all items are checked.
1. [x] Please provide specific title of the PR describing the change, including the component name (eg."Update of Documentation link on Readme.md")
----------------------------------------------------------------------------------------------------------------------------------------------------
Changing the header so the main TwoWire::requestFrom() definition uses a `size_t` instead of a `uint8_t`, removing the 255 …

Refactoring TwoWire::requestFrom() headers in Wire.cpp

---

libraries/WiFi/src/WiFiSTA.cpp

Fixes: https://github.com/espressif/arduino-esp32/issues/6020

Change default WiFi STA encryption to WIFI_AUTH_WPA2_PSK

---

cores/esp32/esp32-hal-dac.c
cores/esp32/esp32-hal-dac.h

This PR is refactoring of DAC HAL in order to use IDF instead of current Register manipulation approach.
Edited dacWrite() to use ESP-IDF api.
Added dacDisable() so there is an option to disable dac channel.
None.

Implement DAC based on ESP-IDF API

---

cores/esp32/esp32-hal-uart.c

HardwareSerial flush() was returning before all data was sent out through serial port.
This is a problem to some RS485 libraries that depend on it to signaling.
This PR solves the issue by forcing it to block flush() until all data is sent.
None, just fixes an issue.
fix #5877

Forces UART Flush() to wait until all bits are sent

---

cores/esp32/Arduino.h
cores/esp32/main.cpp
libraries/ESP32/examples/ArduinoStackSize/ArduinoStackSize.ino

Arduino ```setup()``` and ```loop()``` run under a Task with a fixed Stack size of 8KB.
Users may want to change this size.
This PR adds this possibility by just adding a line of code, as for example:
``` dart
ESP_LOOP_TASK_STACK_SIZE(16384);
void setup() { 
}
void loop() { 
}
```
None. It adds a new functionality to ESP32 Arduino.
If ```ESP_LOOP_TASK_STACK_SIZE(newSize);``` is not declared/used, it will compile the sketch with the default stack size of 8KB.
fix #6010 
https://github.com/espressif/arduino-esp32/issues/6010#issuecomment-992701658
Thanks @igrr for the suggestion!

Adds support to change LoopTask Stack size

---

docs/source/installing.rst

Related to:
https://github.com/espressif/arduino-esp32/issues/6012
#5994
#5991
None

[Fix] Added the Win32 not supported notice/warning

---

variants/wt32-eth01/pins_arduino.h

This is the subsequent patch to the previous commit, wich introduced some errors (`error: initializer element is not constant`) due to the initialization of const vars using other const vars.
The PR fixes a build error in variant wt32-eth01.

fix variant wt32-eth01 (initializer not constant)

---

libraries/BLE/src/BLEHIDDevice.h

23 Braille Display Page (0x41)
Braille display allow visually impaired computer users to read out text using raised pins. The pins are electro-mechanically
activated. These devices also have support for controls that help navigate the computer screen. Typically, braille displays
interface with software known as a screen reader in order to perform this navigation.
None
#5978

HID_BRAILLE_DISPLAY

---

cores/esp32/esp32-hal-ledc.c

This PR is refactoring of LEDC HAL in order to use IDF instead of current Register manipulation approach.
Fixing duty -> if all bits in resolution are set -> FULL ON
None
Fixed #5089

Implement LEDC based on ESP-IDF API

---

libraries/README.md

README revision to include missing and remove old entries
None

[Examples] README revision to include missing and remove old entries

---

cores/esp32/esp32-hal-rmt.c

Fixes warnings and an error when compiling RMT with Arduino Lib Builder
None
https://github.com/espressif/arduino-esp32/pull/6024#issuecomment-999137002
```
2021-12-21T13:42:08.4507786Z FAILED: esp-idf/arduino/CMakeFiles/__idf_arduino.dir/cores/esp32/esp32-hal-rmt.c.obj 
2021-12-21T13:42:08.4596147Z /home/runner/.espressif/tools/riscv32-esp-elf/esp-2021r2-8.4.0/riscv32-esp-elf/bin/riscv32-esp-elf-gcc -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -I/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/build/config -I/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/components/arduino/variants/esp32c3 -I/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/components/arduino/cores/esp32 …
```

Fixes Lib Builder compiling errors

---

cores/esp32/esp32-hal-sigmadelta.c
cores/esp32/esp32-hal-sigmadelta.h
libraries/ESP32/examples/AnalogOut/SigmaDelta/SigmaDelta.ino

This PR is refactoring of SigmaDelta HAL in order to use IDF instead of current Register manipulation approach.
**Change in API:**
* `uint32_t sigmaDeltaSetup(uint8_t channel, uint32_t freq);`
changed to -->
`uint32_t sigmaDeltaSetup(uint8_t pin, uint8_t channel, uint32_t freq);`
* `void sigmaDeltaAttachPin(uint8_t pin);` removed, no longer needed. Pin is attached in `sigmaDeltaSetup()`

Implement SigmaDelta based on ESP-IDF API

---

cores/esp32/WString.cpp
cores/esp32/WString.h
cores/esp32/stdlib_noniso.c
cores/esp32/stdlib_noniso.h

The PR fixes an issue related to Stack Smashing when trying to execute this sketch:
``` dart
void setup() {
String s = String(1e32f, 0);
Serial.println(s);
Serial.println(String(-1.0f, 30));
Serial.println(String(0.0f, 31));
}
void loop() {
// put your main code here, to run repeatedly:
}
```
The wrong output is:
```
Stack smashing protect failure!
abort() was called at PC 0x400d74a0 on core 1
Backtrace:0x40082e19:0x3ffb26800x40087a21:0x3ffb26a0 0x4008c465:0x3ffb26c0 0x400d74a0:0x3ffb2740 0x400d1731:0x3ffb2760 0x400d0f73:0x3ffb27c0 0x400d17de:0x3ffb2820 
```
Expected correct output is:
```
100000003318135366470187364029698
-1.000000000000000000000000000000
0.0000000000000000000000000000000
```
None.
Fixes #5873

Fixes String(float) issue with Stack Smashing

---

cores/esp32/Arduino.h
cores/esp32/esp32-hal-misc.c
cores/esp32/esp32-hal-psram.c
cores/esp32/esp32-hal.h

Users have requested a way to make the WROVER module to boot faster.
It takes about 1 second to boot in a 4MB PSRAM configuration because of SPI RAM Test routine.
This PR adds a function to ESP32 Arduino that allows the user to programmatically tell Arduino not to spend time on PSRAM test. The default behavior is to test it.
The API is ```BYPASS_SPIRAM_TEST(bool)```
Example:
``` dart
BYPASS_SPIRAM_TEST(true);  // not declaring it or using BYPASS_SPIRAM_TEST(false) will run SPI RAM Test
void setup() {
Serial.println("\n --- SPIRAM test bypass!");
Serial.println("Check how long does it take to boot in a WROVER module.");
}
void loop() {
static uint8_t count = 0;
Serial.print("-");
delay(500);
if (++count == 32) {
count = 0;
Serial.println();
}
}
````
The user decides …

Allows user to bypass PSRAM test and boot faster with WROVER

---

cores/esp32/esp32-hal-uart.c

This PR fixes an issue created by #6026 not allowing UART loopback to work correctly.
It fixes both at the same time:
- makes flush() to wait up to the end of UART transmission before returning, fixing issue related to MODBUS #5877 
- solves the UART loopback issue in https://github.com/espressif/arduino-esp32/pull/5549#issuecomment-1009642889 and #6126
None.
Fixes #6126 
https://github.com/espressif/arduino-esp32/pull/5549#issuecomment-1009642889
#5877 
#4603

Fixes UART MODBUS and Loopback issue

---

cores/esp32/HardwareSerial.cpp
cores/esp32/HardwareSerial.h
cores/esp32/esp32-hal-uart.c
cores/esp32/esp32-hal-uart.h

This PR adds a new feature to UART / Arduino Serial API.
Users have requested a feature related to UART ISR that allow a callback function to be executed as soon as data arrives to UART port. This PR adds ```Serial.onReceive()``` functionality to Arduino Hardware Serial.
Example:
``` dart
void UART_RX_IRQ() {
uint16_t size = Serial.available();
Serial.printf("Got %d bytes on Serial to read\n", size);
while(Serial.available())  {
Serial.write(Serial.read());
}
Serial.printf("\nSerial data processed!\n");
}
void setup() {
Serial.onReceive(UART_RX_IRQ);
Serial.println("Send data to UART0 in order to activate the RX callback");
}
void loop() {
Serial.println("Sleeping for 10 seconds...");
delay(10000);
}
```
Output of the example in the ESP32-C3 (```Hello World!``` sent …

Adds UART RX IRQ Callback with onReceive()

---

cores/esp32/esp32-hal-time.c
libraries/ESP32/examples/Time/SimpleTime/SimpleTime.ino
libraries/FFat/examples/FFat_time/FFat_time.ino
libraries/HTTPUpdate/examples/httpUpdateSecure/httpUpdateSecure.ino
libraries/LittleFS/examples/LITTLEFS_time/LITTLEFS_time.ino
libraries/SD/examples/SD_time/SD_time.ino
libraries/SD_MMC/examples/SDMMC_time/SDMMC_time.ino
libraries/SPIFFS/examples/SPIFFS_time/SPIFFS_time.ino

SNTP: revert comments for examples including configTime() call setup.
It's been obsolete since 2.0.2 build includes this PR espressif/esp32-arduino-lib-builder#51
Updated SimpleTime example with a bit more details regarding SNTP over DHCP use case and TimeZone env setup.
none
Obsoletes #5343

NTP Examples: revert obsolete comment and updated Time example

---

variants/adafruit_feather_esp32s2/pins_arduino.h
variants/adafruit_feather_esp32s2/variant.cpp
variants/adafruit_feather_esp32s2_reversetft/variant.cpp
variants/adafruit_feather_esp32s2_tft/variant.cpp
variants/adafruit_funhouse_esp32s2/variant.cpp
variants/adafruit_magtag29_esp32s2/variant.cpp
variants/adafruit_metro_esp32s2/variant.cpp
variants/adafruit_qtpy_esp32/pins_arduino.h
variants/adafruit_qtpy_esp32s2/variant.cpp

this will let us activate hardware on boot - avoid customer confusion :)

Add variantInit setups for adafruit boards

---

cores/esp32/Print.h
cores/esp32/Stream.h

In ARDUINO 1.0 (2011.11.30) Arduino changed Serial.flush() to "wait for outgoing data to be transmitted". In following years other classes derived from Stream (or Print) implemented flush() as "send the buffer out". In ARDUINO 1.8.4 (2017.08.23) they moved flush() from Stream to Print in the prominent Arduino AVR core. For backward compatibility of flush() in Print they changed the pure virtual function to empty implementation. The [ArduinoCore-API](https://github.com/arduino/ArduinoCore-API) recommended for new cores or major updates has flush() in Print too.
Most major cores already implemented this change. This PR moves flush() from Stream.h to Print.h in this core.

Print.flush() - Arduino API conformance

---

.github/ISSUE_TEMPLATE/Feature-request.yml
.github/ISSUE_TEMPLATE/Issue-report.yml

This PR includes 2 changes:
- add v2.0.2 into Issue template
- add confirmation Check Box into Feature request Template
By adding confirmation checkbox into Feature request template we will make sure that Users will really check list of already opened Feature requests.
N/A

Versions and feature Request Template updates

---

libraries/BluetoothSerial/src/BTScan.h
libraries/BluetoothSerial/src/BTScanResultsSet.cpp

Change device index consistently for getCount() parameter list to signed integer type.
Get rid of compiler warning as below and get parameter check work that won't work with unsigned type:
BTScanResultsSet.cpp:67:8: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
if (i < 0)
~~^~~
[ 83%] Linking C static library libarduino-esp32.a
This is related to discussion under:
https://github.com/espressif/arduino-esp32/pull/6091

Consistently change device index to singed integer in BluetoothSerial lib

---

libraries/WiFi/src/WiFiGeneric.cpp

Reliability fix for autoReconnect when assoc_fail, autoReconnect did not work before for these failures.
Changes behavior of WIFI_REASON_ASSOC_FAIL event when autoReconnect is set, removes WIFI_REASON_ASSOC_FAIL/WL_CONNECT_FAILED so retry waitforconnectresult loop stays active for the retry, was not working before.
Same behavior if autoReconnect is not enabled, suppress WL_disconnect when it is. 
Possible event loop, similar to other events, I see no special checks for avoiding, whole event method need a rewrite, currently prone to bugs
#2501

WIFI STA AutoReconnect fix for assocfail reason,  Proposed fix for #2501

---

boards.txt

Using an ESP32 board (namely an Olimex Gateway) I ran into an issue in an Ethernet library that could be debugged simply by setting the core debug level. Looking into it, most boards had this option configurable from the Arduino Tools menu, but a few (including mine) were missing that menu for some reason. I've added the menu for my board, but in addition I've added it for all boards in "boards.txt" because I couldn't think of a reason someone with any board wouldn't want this feature, but let me know if there is any reason to the contrary.
I also cleaned up some messy whitespace, sorry if that makes the commit harder to read.
All boards offered by the Arduino ESP32 library will now provide a "Core Debug Level" option under the Arduino Tools menu that can be set to "None", "Error", …

Add Core Debug Level option to Tools menu for all boards in boards.txt

---

libraries/Ticker/src/Ticker.cpp

Implement Ticker::active()

---

boards.txt
variants/lionbit/pins_arduino.h

Arduino pin definition of Lion:Bit Dev Board (https://lionbit.lk)
In order to use this dev board in all the available platform.
[Please provide links to related issue, PRs etc.
](https://github.com/LionBit-Sri-Lanka/lionbit_dev_board)

Add LionBit Dev Board.

---

boards.txt

Fixes: https://github.com/espressif/arduino-esp32/issues/6137

Fix variant definition for w32-eth01

---

cores/esp32/esp32-hal-ledc.c

Added `pinMode(pin,OUTPUT);` to ledcAttach function to ensure that GPIO pin interrupts will work again.
Fix for ledc output pin interrupt
Closes #6140

Fixing interrupts in LEDC

---

boards.txt
variants/watchy/pins_arduino.h

Arduino pin definitions for Watchy https://watchy.sqfmi.com
Support different Watchy board revisions with various pin definitions
https://github.com/sqfmi/Watchy

Add Watchy board

---

.github/scripts/install-arduino-core-esp32.sh
.github/scripts/install-arduino-ide.sh
.github/scripts/install-platformio-esp32.sh
.github/scripts/on-pages.sh
.github/scripts/on-push.sh
.github/scripts/on-release.sh

The shell scripts were using both tabs and spaces (2 & 4) for indentation.
This commit uses 4 spaces for indentation everywhere.

.github/scripts: Fix indentation and trailing spaces.

---

cores/esp32/Esp.cpp

fix S3 flash image base

---

cores/esp32/HardwareSerial.cpp

This PR fixes an issue with UART1 default pins.
When using pins RX_1 = 18 and TX_1 = 17, UART1 will display a Break Error on those pins when they are floting (not connected).
It also defines RX_2 = 19 and TX_2 = 20 as default pins for UART2.
The deaulf pins may look different from the original pinout diagram.
None

Fixes UART1 and UART2 default pins for ESP32-S3

---

libraries/SD/src/sd_diskio.cpp

On many issues with SD card mount, there is problem with sdWait() only before sending the 1st init cmd 0 = GO_IDLE_STATE. After this command sdWait() works as expected.
Edited GO_IDLE_STATE command:
-> sdWait() is ignored there, only warning message is logged.
Only in sdSelectCard timeout was 300 so added longer timeout as in other calls for sdWait.
According to issue #6107, making a timeout of 500 as in other calls should solve the issue.
Cannot reproduce issues with mounting SD cards.
Will appreciate someone to try this fix.
Fixing SD card mounting problems.
Closes #6143
Closes #6107 
Closes #5998

Fix - SD mount issue

---

libraries/WiFiClientSecure/src/ssl_client.cpp

Restoring handshake_timeout after clearing the whole instance.
Fix of regression.
Closes #6165

[SSL] fix: restoring handshake timeout 

---

cores/esp32/esp32-hal-uart.c

Fixes a problem with deadlock when using HardwareSerial::onReceive()
OnReceive() can use other HardwareSerial APIs and it can not have its execution Locked with semophore.
None
None

Fixes onReceive deadlock

---

libraries/WiFiProv/src/WiFiProv.h

Resolves issue #6171
Allows compiling WiFiProv.h if included in multiple files.
https://github.com/espressif/arduino-esp32/issues/6171

Add conditional include to WiFiProv.h

---

cores/esp32/WString.cpp

Resolve TODO (XXX) by logging warning message.
-----------
Replaces XXX comment with warning message.
Logs warning if there isn't enough buffer space for a replace.
NA

Resolve WString TODO

---

libraries/HTTPClient/src/HTTPClient.h

Allow a user to disable the HTTPCLIENT_1_1_COMPATIBLE flag from the command line, or whichever means available.

Allow HTTPCLIENT_1_1_COMPATIBLE to be disabled

---

libraries/WebServer/src/detail/RequestHandlersImpl.h

Using `serveStatic(...)` is broken when using folder names (not files) and LittleFS fil system.
This checks correctly for folders.
With LittleFS the `fs.exists(path)` returns true also on folders. A `isDirectory()` call is required to set _isFile to false on directories.
This enables serving all files from a folder like : `server.serveStatic("/", LittleFS, "/");`
serveStatic is partially broken

Update RequestHandlersImpl.h to enable serveStatic on folders with LittleFS. 

---

libraries/DNSServer/src/DNSServer.h

CaptivePortal.ino example did randomly crash for me ... so I start investigating ;-)
Decoding stack results
- 0x4016faea: WiFiUDP::write(unsigned char const*, unsigned int) at ...esp32\1.0.5\libraries\WiFi\src\WiFiUdp.cpp line 201
- 0x400d4a4a: DNSServer::replyWithIP() at ....\DNSServer\DNSServer.cpp line 187
- 0x400d4d01: DNSServer::processNextRequest() at ...\DNSServer\DNSServer.cpp line 117
- 0x400d3e81: loop() at  ....
- 0x400dd545: loopTask(void*) at  ...\esp32\1.0.5\cores\esp32\main.cpp line 37
- 0x4008a0de: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c line 143
I found with wireshark a possibility to trigger the crash on demand is:
nslookup 3.1o1osr0092ons87rp375p1pq8q066o8p56or1sqsps6rs17r4384q9748qr1r52 …

Fix random CaptivePortal.ino crashes

---

cores/esp32/WMath.cpp

(A) extra operation not needed and incorrect:
      wrong by 0.5 but happens to be thrown out   
      if someone needs a float version and based their code  
      from this, they will get the wrong result (by 0.5 or 1)  
      (don't ask me how I know...)
```
( delta * dividend + (divisor / 2) ) / divisor
delta * dividend   divisor
= ---------------- + -----------
divisor            2 * divisor
= delta * dividend / divisor + 1/2
```
(B) check error and exit, before doing other computations
(C) changed to rise/run, easier for future maintainer
       since it's closer to equation of a line
(D) before: mult, shift, add, div, add
       now: mult, div, add
(E) error message easier to trace where thrown
*By completing this PR sufficiently, you help us to improve the quality of Release …

Unnecessary operation removed from map() in WMath.cpp

---

libraries/ESP32/examples/Camera/CameraWebServer/CameraWebServer.ino

If board has no PSRAM, we need to set the framebuffer location to DRAM:
config.fb_location = CAMERA_FB_IN_DRAM;
It is just a minor change in an example. The "M5 esp32cam" board without PSRAM can run the example with this modification. Before, the example crashed.

Update of CameraWebServer example

---

cores/esp32/WString.cpp

This PR fixes a bug introduced by #6190
There was no braces after `if` so the `return` statement is taken every time, not just in case of failure.
String.replace is not doing an actual replacement most of the time.

Fix String.replace() broken by #6190

---

.github/workflows/upload-idf-component.yml
idf_component.yml

Add upload-idf-componen.yml file for Github Workflow. After each push on the master branch, the component will be uploaded to the component registry
After that PR users can use the Arduino-ESP32 component from the component registry.

Add Github action for uploading arduino-esp32 component. 

---

libraries/WiFi/src/WiFiGeneric.cpp
libraries/WiFi/src/WiFiGeneric.h

Added the dual antenna configuration for the ESP32-WROOM-DA module.
None
[ESP32-WROOM-DA](https://www.espressif.com/sites/default/files/documentation/esp32-wroom-da_datasheet_en.pdf)

Added dual antenna for WiFi (based on the ESP32-WROOM-DA module)

---

cores/esp32/esp32-hal-ledc.c

Fixing ledc is not working on ESP32C3, because of the pinMode.
Use pinMode only for ESP32 and ESP32S2 so attachInterrupt on ledc pin will be working.
After GPIO refactoring pinMode will be deleted.
Fix ledc
#6160

Remove pinMode in ledc for ESP32C3

---

idf_component.yml

Arduino Lib builder fails on branch esp32-s3-support since the s3 entry is missing
1. [ ] Please provide specific title of the PR describing the change, including the component name (eg. *„Update of Documentation link on Readme.md“*)
2. [ ] Please provide related links (eg. Issue, other Project, submodule PR..)
-----------

add missing S3

---

cores/esp32/esp32-hal-gpio.c
cores/esp32/esp32-hal-gpio.h

Refactoring of ```int8_t digitalPinToTouchChannel(uint8_t pin)``` based on IDF 4.4.
This fixes this function that doesn't work for ESP32-S3 and any other future SoC.
None
PR #6194

Fixes Touch Sensor for ESP32-S3 and any future SoC

---

libraries/HTTPClient/src/HTTPClient.cpp
libraries/HTTPClient/src/HTTPClient.h

This is a proposal to add cookie support in `HttpClient`. With this modification, the client is able to receive and store cookies and automatically send them in a subsequent request, if applicable as per `Domain` and `Path` attributes. Receiving multiple cookies in the same response (multiple `set-cookie` headers) is supported.
Cookie expiry (`Expires`and `Max-Age` attributes) is respected, but relies on RTC to be set properly. 
`Secure` is respected, `HttpOnly` is stored, but not used anywhere.
See [https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie](url) for a description of cookie attributes.
This proposal probably has room for additions, code style improvements whatsoever. I created this because I needed to handle cookies when dealing with AWS requests and thought …

HttpClient: Add cookie support (cookie jar)

---

libraries/ESP32/examples/RMT/RMTCallback/RMTCallback.ino
libraries/ESP32/examples/RMT/RMTWriteNeoPixel/RMTWriteNeoPixel.ino

Adds and fixes RMT examples to run with ESP32-S3 
None
None

Fixes RMT examples and adds ESP32-S3 config

---

libraries/WiFi/src/WiFiGeneric.cpp

Fixes: https://github.com/espressif/arduino-esp32/issues/6264
Thanks @Spritetm

Fix CDC+JTAG is disabled when WiFi is used on ESP32-C3

---

libraries/HTTPClient/src/HTTPClient.cpp

-----------
Fix nullptr in HTTPClient with _cookieJar
Fixes #6266

Fix Check for _cookieJar in HTTPClient (#6266)

---

libraries/WiFi/src/WiFiAP.cpp

This PR fixes the return of Static IP setup using ```softAPConfig()``` function.
```softAPConfig()``` returns always ```false``` even when the operation is successful.
This occurs because of a failure return code while trying to stop DHCP Client Service.
None, just fixes the function.
Fixes #6270

Fixes softAPConfig() return

---

CMakeLists.txt

It's a bug fix for `fatal error: ETH.h: No such file or directory` when building arduino as IDF component

Add Ethernet to CMakeLists

---

cores/esp32/esp32-hal-adc.c

Changed fixed DAC pins which are different for ESP32S2 to predefined DAC pins from SOC. 
None.

ADC esp32s2 attenuation fix for DAC pins

---

libraries/HTTPClient/src/HTTPClient.cpp

http end takes 20-30 seconds if there is a large amount of data
replacing this read loop with flush fixes that problem

fixed http.end taking too long

---

boards.txt
variants/lolin_c3_mini/pins_arduino.h

add lolin c3 mini board def

---

variants/m5stack_core2/pins_arduino.h

The M5Core2 and the very similar M5Tough have 40 digital pins
See reference here: https://docs.m5stack.com/en/core/core2 as well as the constant declarations in the bottom part of the file.
Without this, Code that needs the total number of pins (e.g. [firmata](https://github.com/firmata/ConfigurableFirmata)) doesn't show the higher pin numbers correctly.

The M5Core2 and M5Tough have 40 pins

---

libraries/USB/src/USBHIDKeyboard.h

Exposing this method makes it easier to integrate non-espressif USB-based projects (e.g. led/modifiers examples from USB Host Shield 2.0)

Make USBHIDKeyboard::sendReport() public

---

docs/requirements.txt
docs/source/api/adc.rst
docs/source/conf.py
libraries/ESP32/examples/AnalogRead/AnalogRead.ino

Added documentation for ADC peripheral.
Added example AnalogRead

Added ADC API doc + simple example

---

docs/source/guides/tools_menu.rst

Added more details about embedded FLASH and PSRAM on ESP32-S3.
None.
None.

[Docs] Added more details about embedded FLASH and PSRAM on ESP32-S3.

---

docs/source/api/ledc.rst
docs/source/api/sigmadelta.rst

Documentation for LEDC and SigmaDelta peripherals.

LEDC & SigmaDelta documentation

---

cores/esp32/esp32-hal-timer.h
docs/source/api/timer.rst

Documentation for Timer peripheral.
Edited one function input in esp32-hal-timer.h to match the .c file.

[Docs] Timer API documentation

---

libraries/Ethernet/src/ETH.cpp

this was not possible anymore since the GPIO refactoring.
This superseeds https://github.com/espressif/esp32-arduino-lib-builder/pull/60
(which works only for clock on GPIO17). A PR will provided to revert this.
@me-no-dev fyi
The fix is done from @arendst  Credits go to him!

fix to set ethernet clock at runtime

---

libraries/DNSServer/src/DNSServer.h

Because of the changes in #6206 it is necessary to change the QNameLength datatype to uint16_t, to be able to address the QName max. size of 256.
The problem appears int the following lines from the DNSServer.cpp if QNameLength is 255. The wrap around destroys the following memcpy.
https://github.com/espressif/arduino-esp32/blob/b254765ef81a2d80f498a8c22c7750152e3e68df/libraries/DNSServer/src/DNSServer.cpp#L88-L93

Fix DNSServer crash

---

libraries/WiFi/src/WiFiGeneric.cpp

This PR contains fix for wifiBegin works only every 2nd time. This happens when connecting to same AP without disconnecting first (eg. restarting board). Every AP works a bit different so results got from AP differs. 
Now wifi will ignore reason: 202 - AUTH_FAIL once and try to connect again.
None.
Closes #2501

FIX - wifiBegin works every 2nd time when connecting to same AP

---

docs/source/api/wifi.rst
libraries/WiFi/examples/WiFiScanDualAntenna/README.md
libraries/WiFi/examples/WiFiScanDualAntenna/WiFiScanDualAntenna.ino

* Added the Dual Antenna documentation.
* Added the DA example.
None.

WiFi DA: Added Dual Antenna to the docs and example created

---

cores/esp32/esp32-hal-log.h

#ifdef added, to avoid compiler redefinition warnings for `LOG_LOCAL_LEVEL` if defined by application, and we `USE_ESP_IDF_LOG`

[esp32-hal-log.h] add #ifdef for LOG_LOCAL_LEVEL

---

libraries/WiFi/src/WiFiSTA.cpp
libraries/WiFi/src/WiFiSTA.h

Implemented all types of Wifi SmartConfig. 
Function changed from:
`bool beginSmartConfig();`
to
`bool beginSmartConfig(smartconfig_type_t type = SC_TYPE_ESPTOUCH, char* crypt_key = NULL);`
If `WiFi.beginSmartConfig();` is called, ESPTOUCH is used as default type.
Or you can specify type nad crypt key (used for ESPTOUCH_V2 only):
```
char crypt_key[] = "ESPWIFISMARTCONF"; //should be 16 chars lenght
WiFi.beginSmartConfig(SC_TYPE_ESPTOUCH_V2, crypt_key);
```
| SmartConfig types | Protocol used |
| ------------- | ------------- |
| SC_TYPE_ESPTOUCH | ESPTouch |
| SC_TYPE_AIRKISS | AirKiss |
| SC_TYPE_ESPTOUCH_AIRKISS | ESPTouch and AirKiss |
| SC_TYPE_ESPTOUCH_V2 | ESPTouch v2 |
New types of WiFi SmartConfig supported.
Closes #5409 
Closes #5226

FEATURE: Implemented new types of Wifi SmartConfig

---

libraries/ESP32/examples/Camera/CameraWebServer/app_httpd.cpp

Simple delete of one duplicate line in CameraWebServer example which can bring some confusion.
N/A
Related discussion https://github.com/espressif/arduino-esp32/discussions/6289

CameraWebServer duplicate line fix

---

cores/esp32/esp32-hal-ledc.c
libraries/ESP32/examples/AnalogOut/LEDCSoftwareFade/LEDCSoftwareFade.ino

Fixing ledc issue when result of IDFs functions was not checked before calling next function causing core panic’ed.
Changed ledcSoftwareFade example to work on all SOCs.
Fix.

Fix ledc panic’ed when wrong setup of frequency and bit width

---

libraries/WiFi/examples/WiFiScanDualAntenna/WiFiScanDualAntenna.ino

Fix the GPIO number argument for the dual antenna selection function in the example.
The GPIO is the same for ANT1 and ANT2. This should not work as expected on the DA example.
N/A

Fixed the antenna GPIO argument on the DA example

---

cores/esp32/HardwareSerial.cpp

This PR allow users to start HardwareSerial setting just one pin (Rx or Tx) or both of them.
It allows these possible initial configurations:
```cpp
// In this case, Serial will configure rxPin and only be able to receive data
Serial1.begin(9600, SERIAL_8N1, rxPin);
```
```cpp
// In this case, Serial will configure txPin and only be able to send data
Serial1.begin(9600, SERIAL_8N1, -1, txPin);
```
```cpp
// In this case, Serial will configure rxPin and txPin with default pins for the chip (as in HardwareSerial.cpp)
Serial1.begin(9600, SERIAL_8N1);
```
```cpp
// In this case, Serial will configure rxPin and txPin as defined by the user
Serial1.begin(9600, SERIAL_8N1, rxPin, txPin);
```
None
This PR solves a discussion at https://github.com/espressif/arduino-esp32/discussions/6356
Fixes …

Allows setting only one pin (rx or tx) in the first begin()

---

CMakeLists.txt
cores/esp32/Arduino.h
cores/esp32/Tone.cpp

Issue #980 requested tone to be implemented.
[tone in Arduino documentation](https://www.arduino.cc/reference/en/language/functions/advanced-io/tone/)
[noTone in Arduino documentation](https://www.arduino.cc/reference/en/language/functions/advanced-io/notone/)
This PR provides new implementation of functions tone and noTone to be used with esp32.
New functions are written with almost the same API as Arduino original functions. This implementation adds the option to change duty (default is 50% the same as in Arduino).
Closes #980

Implemented tone and noTone; fixes #980

---

docs/source/lib_builder.rst

Update on the library builder procedures.
None
https://github.com/espressif/arduino-esp32/projects/5#card-63388323

[Docs] Added/Updated Lib builder docs

---

.github/workflows/publish.yml

1. Don't run the publish test result workflow on the master branch.
2. Run only on Pull Requests to be able to publish the result as a PR comment.
3. Avoid running when the triggering workflow was skipped, this will
cause a failure as no file will be uploaded.
Regarding running only on PRs and not on master branch or any other branch:  It's just that the results are kind of hidden.  One will need to check the output of the workflow the have a link to where the results are published.
Example for the schedule workflow: https://github.com/espressif/arduino-esp32/runs/5531527566
CI
https://github.com/espressif/arduino-esp32/actions

publish.yml:  Limit the running scope of the publish Workflow. 

---

libraries/AsyncUDP/src/AsyncUDP.h

In my project I'm getting the error 
```
In file included from lib/Discovery/Discovery.cpp:2:
C:/Users/David/.platformio/packages/framework-arduinoespressif32/libraries/AsyncUDP/src/AsyncUDP.h:47:1: error: expected class-name before '{' token
```
Adding a reference to Stream.h fixes it. …

Add missing include in AsyncUDP.h

---

variants/adafruit_feather_esp32_v2/pins_arduino.h
variants/adafruit_feather_esp32s2/variant.cpp
variants/adafruit_qtpy_esp32c3/pins_arduino.h

update some pins for adafruit board definitions. doesn't affect any other code :)

Some board variant fixes

---

libraries/SD_MMC/src/SD_MMC.cpp
libraries/SD_MMC/src/SD_MMC.h
variants/esp32s3box/pins_arduino.h

This PR adds SDMMC support for ESP32-S3.
Unlike ESP32, ESP32-S3 allows all SDMMC pins to be configured flexibly using GPIO matrix. A new function is added to SDMMC class to allow setting the pins.
SDMMC docs for S3: https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/sdmmc_host.html

ESP32-S3 SDMMC support

---

cores/esp32/esp32-hal-tinyusb.c

Fixes compile error of commit https://github.com/espressif/arduino-esp32/commit/2330e9992f46e265a34afafd1b14858d993e9621
1. [ ] Please provide specific title of the PR describing the change, including the component name (eg. *„Update of Documentation link on Readme.md“*)
2. [ ] Please provide related links (eg. Issue, other Project, submodule PR..)
-----------

Fix compile error of TinyUSB on ESP32-S3

---

docs/source/guides/docs_contributing.rst

Added the guideline for the documentation.
None.
None.

[Docs] Added the guideline for documentation

---

cores/esp32/HardwareSerial.cpp
cores/esp32/HardwareSerial.h
cores/esp32/esp32-hal-uart.c
cores/esp32/esp32-hal-uart.h

It adds HardwareSerial::setTxBufferSize() with default value of 0 bytes (like it is now by default).
No issue related. Just adds functionality to HardwareSerial. Allows non blocking writes when they exceed the TX FIFO.
None.
It allows to define a Tx Buffer Size for UART, before begin().

Adds HardwareSerial::setTxBufferSize()

---

platform.txt

First aid for ESP32 builds not passing in Arduino IDE on macOS Monterey 12.3 that obsolete "python2.7".
1. [ ] Please provide specific title of the PR describing the change, including the component name (eg. *„Update of Documentation link on Readme.md“*)
2. [ ] Please provide related links (eg. Issue, other Project, submodule PR..)
3. [ ] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)
-----------

Change "python" to "python3"

---

libraries/BluetoothSerial/examples/SerialToSerialBT/SerialToSerialBT.ino
libraries/BluetoothSerial/examples/SerialToSerialBTM/SerialToSerialBTM.ino
libraries/BluetoothSerial/examples/SerialToSerialBT_SSP_pairing/SerialToSerialBT_SSP_pairing.ino
libraries/BluetoothSerial/examples/bt_classic_device_discovery/bt_classic_device_discovery.ino
libraries/BluetoothSerial/examples/bt_remove_paired_devices/bt_remove_paired_devices.ino
libraries/README.md

This PR helps users that try to use BT SPP (BluetoothSerial), warning that it only works for the ESP32. 
None
Fix #6308 
Fix #6422

Warns about SPP only available for ESP32

---

libraries/FS/src/vfs_api.cpp

Edited VFSFileImpl::read to use read function instead of read when read size is bigger than 128 bytes.
There is check to FILEs internal buffer if there are some bytes read left. If yes, clear the buffer and set the pointer to deleted data, so it will read them again with read function.
Higher read speeds  on SD cards when reading more than 128bytes.

Edited VFSFileImpl::read to use both read/fread

---

README.md

add ESP32-S3 in Readme since it is supported now.
-----------

Add S3 in Headline

---

cores/esp32/HardwareSerial.h

Quick necessary fix in order to allow Lib Builder compilation.
None.
None.

Reordering - HardwareSerial Constructor

---

.github/scripts/on-push.sh

could be used for all. Nice would be releasing in Platformio registry.
-----------

use esptool v3.3 for S3 CI test

---

.github/scripts/on-release.sh

so it is directly useable from PlatformIO
-----------
With this change the releases can be directly used from Platformio
Just adding the package.json

add package.json to release zip

---

package/package_esp32_index.template.json

since it is missing in `package/package_esp32_index.template.json`
-----------

add S3 board in package_esp32_index.template.json

---

libraries/BLE/src/BLEAddress.cpp

Reversed the arguments to memcmp so that eg 'a4:...' > 'a3:...' is true
Lets Manufacturer ranges in bluetooth address space be filtered correctly

BLEAddress: Correct less- and greater-than operators

---

.github/scripts/update-version.sh
boards.txt
platform.txt
programmers.txt

Fixes some compatibility issues with Arduino IDE 2.0.0

Add better esptool support (ArduinoIDE 2.0.0)

---

cores/esp32/esp32-hal-gpio.h
libraries/Ethernet/src/ETH.cpp

The PR #6259 mentioned in this PR's subject line, broke the PHY8720(A). There have been a few issues posted regarding the timeouts. I have performed a git bisect to identify the offended PR, and reduced it to the lines that need to be considered for revert or otherwise, how the absense of this special mode handling causes the failure and where exactly would be the proper place to implement this oversight, after all. I am afraid I don't have the resources to hack the IDF, too. 
#5239
#6500
#6142
#5993
#

PHY8720(A) init timout failures: need to revert "GPIO refactoring (#6259)"

---

libraries/FS/src/FS.cpp
libraries/FS/src/FS.h
libraries/FS/src/FSImpl.h
libraries/FS/src/vfs_api.cpp
libraries/FS/src/vfs_api.h

1. Reverted changes #6456 that are breaking the FS reads.
2. Files internal buffer is now set to 4Kb by default where the recommended size cannot be read from _stat.
Fix FS issues in 2.0.3-RC1 release.
Improve SD reading speed (approx 40-50%)
Closes #6507 
Closes #6502 
Closes #6516

BUGFIX: FS read + speed improvements for SD

---

.github/scripts/sketch_utils.sh
.github/workflows/hil.yml
.github/workflows/publish.yml

- This prevents trying to run when the trigger was cancelled or skipped.
In these cases there will be no event file to upload and the workflow will fail.
- Update the runners' tags.  One of the available runners doesn't have an S2 board anymore.
Publish workflow.
https://github.com/Ouss4/arduino-esp32/actions/runs/2083991236
https://github.com/Ouss4/arduino-esp32/actions/runs/2087421730

workflows/publish.yml: Run the workflow on success and failure only.

---

.github/scripts/install-platformio-esp32.sh
tools/platformio-build-esp32.py
tools/platformio-build-esp32c3.py
tools/platformio-build-esp32s2.py
tools/platformio-build-esp32s3.py

This PR adds support for uploading additional flash images (e.g. Adafruit Tiny UF2 bootloader) specified in board manifests. 
Additionally, the PR switches the PlatformIO CI script to the upstream version of  the ESP32 dev-platform (basically reverts changes introduced in #5387 as they are no longer required).

PlatformIO minor updates

---

.github/workflows/publish.yml

Remove a leftover parenthesis that was making the workflow that was making the workflow invalid.
Github Workflow.
https://github.com/espressif/arduino-esp32/actions/runs/2213167501

publish.yml: Minor fix to the workflow syntax

---

libraries/LittleFS/examples/LITTLEFS_PlatformIO/platformio.ini

since it is outdated.
-----------
(*eg. I have tested my Pull Request on Arduino-esp32 core v2.0.2 with ESP32 and ESP32-S2 Board with this …

LittleFS Platformio example update

---

boards.txt
libraries/RainMaker/examples/README.md
libraries/RainMaker/examples/RMakerCustom/RMakerCustom.ino
libraries/RainMaker/examples/RMakerSwitch/RMakerSwitch.ino

This PR adds the needed configuration on `boards.txt` and examples files for the **ESP32-C3/S2/S3** support on RainMaker.
The ESP32-C3/S2/S3 does not work with RainMaker.
Closes https://github.com/espressif/arduino-esp32/issues/6573
Note related to the issue https://github.com/espressif/arduino-esp32/issues/6435

Added RainMaker support on Arduino IDE for ESP32-C3/S2/S3

---

cores/esp32/esp32-hal-touch.c

After touch has been refactored to use ESP-IDF API, its initialising all channels for touch loosing previously setup pins for different purposes. 
The change is that the `touchRead()` and `touchAttachInterrupt()` will initialise touch sensor, but will configure only the pad selected. Other pins will remain as was.
Sketch from issue #6443 tested on ESP32 and S2+S3 with different pins.
Closes #6443

Touch change to init only selected GPIO.

---

boards.txt
variants/AirM2M_CORE_ESP32C3/pins_arduino.h

Added support for the AIRM2M CORE-ESP32C3 board, which has already had a great impact and has excellent sales on Taobao in China (https://item.taobao.com/item.htm?spm=a1z10.1-c-s.w4004-24090382179.12.1ec655d0ILdwls&id=666974425430)
This pull request has been tested on CORE-ESP32C3

add AirM2M_CORE_ESP32C3 board

---

boards.txt
variants/um_rmp/pins_arduino.h

Added Unexpected Maker Reflow Master Pro (UM RMP) board (ESP32-S2FN4R2)
Fixed wrong SCK and MISO pins assigned for TinyS2 in pins_arduino.h
Changes tested locally on respective hardware
N/A

Added Unexpected Maker Reflow Master Pro (UM RMP) board + Fixed TinyS2 pins

---

docs/source/installing.rst

This PR updates PlatformIO doc page with extended info on using stable and upstream versions.
cc @pedrominatel @ivankravets

[Docs] Actualize PlatformIO installation instructions

---

libraries/HTTPClient/src/HTTPClient.h
libraries/WiFi/src/WiFiClient.cpp

Fix HTTP Client failing to connect because of wrong timeout

---

libraries/WiFi/src/WiFiSTA.cpp
libraries/WiFi/src/WiFiSTA.h
libraries/WiFi/src/WiFiScan.cpp
libraries/WiFi/src/WiFiScan.h
libraries/WiFi/src/WiFiType.h

Added options to WiFi STA for connect:
- setMinSecurity: default WIFI_AUTH_WPA2_PSK
- setScanMethod: default WIFI_FAST_SCAN
- setSortMethod: default WIFI_CONNECT_AP_BY_SIGNAL (required all channels scan method)
Added parameters for SSID and BSSID to WiFi.scanNetworks()
Fixes: https://github.com/espressif/arduino-esp32/issues/6485
Fixes: Any issue about WiFi connecting slower now than in 1.0.x

Add more controls over WiFi.begin and WiFi.scan

---

tools/platformio-build-esp32.py
tools/platformio-build-esp32c3.py
tools/platformio-build-esp32s2.py
tools/platformio-build-esp32s3.py

This fixes possible issues when developers specify arbitrary partition files using relative or absolute paths.
Additionally, hyphens in filenames are replaced with underscores to avoid compilation warnings like `ISO C++11 requires whitespace after the macro name`
Resolves platformio/platform-espressif32#787

Properly handle ARDUINO_PARTITION define in PlatformIO

---

boards.txt

The uploader tool for that ESPduino32 board and its clones was erroneous in boards.txt.
This triggered a java nullpointer exception when trying to upload.
Tested on an "AZ Delivery D1 R32" board which is a clone of the ESPduino32.
Tested by manually editing boards.txt in Arduino-esp32 core v2.0.3-RC1.

Fix uploader tool for ESPduino32 in boards.txt

---

.github/workflows/upload-idf-component.yml

`upload-idf-component.yml` action was only running for tags like `v*`, while in this project tags like `2.0.3` are used. With this change, the workflow will run for all tags.

Upload component to the registry on any tag

---

cores/esp32/esp32-hal-timer.c

In esp32-hal-timer.c fixed the timer_dev definition, where was timer 1 and timer 2 the same.
Now you can you all timers at the same time.
Thank you for reporting this issue [AkiHigashi](https://github.com/AkiHigashi)
Related PR with issue -> #5931

Fix TIMER timer_dev definition

---

cores/esp32/esp32-hal-gpio.c

pins default configuration has `intr_type =  GPIO_INTR_DISABLE`
With this implementation, it will set the intr_type to previously set intr_type. It will no longer disable interrupt, when pinmode is called multiple times on same pin with interrupt enabled.
There is no option to get pin config from ESP-IDF API, that's why I made this implementation.
```
//To trigger ISR, connect GPIO 19 to GND.
uint32_t interrupt_count = 0;
void IRAM_ATTR pin_interrupt(void *arg) {
interrupt_count++;
pinMode(19, INPUT);
//attachInterruptArg(19, pin_interrupt, 0, CHANGE);
}
void setup() {
pinMode(19, INPUT);
attachInterruptArg(19, pin_interrupt, 0, CHANGE);
}
void loop() {
ESP_LOGD("loop", "interrupt count %d", interrupt_count);
delay(500);
}
```
Closes #6669

Changed pinMode() default interrupt type DISABLED to previously set

---

cores/esp32/Tone.cpp
cores/esp32/esp32-hal-cpu.c

the compiler complains about these 2 places in `esp32-hal-cpu.cpp` of miss-matching %X to function & void pointers,
and x2 in `Tone.cpp` miss-matching `uint` with `long uint.
Sample warning messages:
```
.../framework-arduinoespressif32/cores/esp32/esp32-hal-cpu.c:132:9: note: in expansion of macro 'log_e'
log_e("not found func=%08X arg=%08X",cb,arg);
^~~~~
.../framework-arduinoespressif32/tools/sdk/esp32/include/log/include/esp_log.h:276:27: warning: format '%X' expects argument of type 'unsigned int', but argument 7 has type 'void *' [-Wformat=]
```
I believe the correct should be `%p`, but i preserved the 8-width in my PR.
(cannot really test the code, this fix just stops the compiler warnings).
To get those warnings, i had to enable `-Wformat` build-flag and define `DUSE_ESP_IDF_LOG …

fix: compiler warnings about printf-format for pointers in `esp32-hal-cpu.c`

---

cores/esp32/Arduino.h

This is a review of macro basic functions from Arduino.h that were missing from the original Arduino version.
This PR adds some missing functions to ESP32 Arduino.h
Tested using ESP32 and a few examples. The main target of testing was to make sure that there is no compiling conflicts.
Also searched for such macro on the source code to verify that those functions are not included anywhere else.
Closes #6623

Adds Arduino standard macro-functions

---

boards.txt

NINA series now has variants that support bigger flash sizes:
NINA-W106-00B : 32Mb / 4MB
NINA-W106-10B : 16Mb / 8MB
older NINA-W101/W102 : had 16Mb / 2MB only
Tested on different NINA variants
https://www.u-blox.com/en/product/nina-w10-series-open-cpu

Add support for NINA-W106 with bigger flash sizes

---

Kconfig.projbuild
cores/esp32/HardwareSerial.cpp

This is just a proposal so we can change on compile time the stack size and priority of the Serial Event Task.
On my current software, the serial part does not fit the current 2048 bytes of stack that the Serial Event Task offers me. So I'm forced to implement a binary semaphore for synchronization (the serial event task just gives a semaphore). This is a waste of resources because now I have two tasks (one for the serial event task and one for my actual routine) and a semaphore. Even worse, it's slower.
Thanks!

Adjustable Serial Event Task Stack Size And Priority

---

.github/workflows/hil.yml

I see that some of the test jobs in forks will get canceled. Although the reason reported by Github Actions is concurrency related, I believe they just couldn't find a runner since it's only in the Espressif organisation.
N/A
https://github.com/Ouss4/arduino-esp32/actions/runs/2325963816

workflows/hil.yml: Don't run the scheduled HIL workflow on forks.

---

cores/esp32/WString.cpp
cores/esp32/WString.h
cores/esp32/stdlib_noniso.c
cores/esp32/stdlib_noniso.h

This PR adds support to long long (64 bits) numbers to Arduino String Class.
Tested with this sketch:
``` cpp
void setup()
{
Serial.println();
// highest signed long long 2^63 - 1 = 9223372036854775807
// highest unsigned long long 2^64 = 18446744073709551615
signed long long ll = -9223372036854775807;
unsigned long long ull = 18446744073709551615;
String ss(ll);
Serial.println(ss);
String uss(ull);
Serial.println(uss);
String txt("This is the highest signed long long: ");
txt += -ll;
Serial.println(txt);
}
```
Fixes #5672

Extends String to print 64-bit integers

---

cores/esp32/esp32-hal-misc.c

Fixes: https://github.com/espressif/arduino-esp32/issues/5871

Add option to skip image verification after OTA

---

libraries/WiFi/src/WiFiGeneric.cpp

Just adds ouput messages for WPA3 WiFi for verbose debug.
Simple test with ESP32.
Fixes #6792

adds verbose message for WPA3

---

libraries/BluetoothSerial/src/BluetoothSerial.cpp

The BluetoothSerial library uses an internal _isRemoteAddressSet variable to track when a remote address has
been given. The connect() calls set this under certain circumstances, but fails to set it back to false if connection
fails. This causes subsequent calls to other functions such as discover() to fail without clear indications why.
I have tested this change on an Sparkfun ESP32 Thing Plus and connect() and subsequent discover() calls work as expected.

BluetoothSerial : Re-set _isRemoteAddressSet to false if connect() fails

---

libraries/SD/src/sd_diskio.cpp

The stack requirement of this library is huge due to a work buffer allocated for f_mkfs in sdcard_mount. The work buffer is only needed if argument format_if_empty is set true (which is by default false) and the card was empty. 
This change is quite important if you plan to use this library in a task. as now it increases the tasks stacks size by 4k, even this work memory is never used (due to format_if_empty is set false). If users are not aware of the large stack requirement during init this library they may have seen various side effects caused by the original code. the other variables in this function may have written addresses that were outside its valid stack range.
This issue was detected ESP32 when SD.begin was called from a task with a 2k stack (with format_if_empty set false). …

SD library: reduce stack size requirement by 4k by moving work buffer to heap

---

cores/esp32/Tone.cpp
cores/esp32/libb64/cdecode.c
cores/esp32/libb64/cencode.c
libraries/WiFi/src/WiFiGeneric.cpp

When building the core with `-Wextra` a few locations have `case:`
fall throughs or skipped field initializers.
Add proper comments for B64 cases to avoid GCC warnings
Initialized unused fields in Tone and WiFiGeneric to avoid missing
field initializer warnings.
Builds from the IDE with `File->Preferences->Compiler Warnings->All` show warnings shown below
````
2022-05-19T17:40:42.2280300Z /home/runner/arduino_ide/hardware/espressif/esp32/cores/esp32/libb64/cdecode.c: In function 'base64_decode_block_signed':
2022-05-19T17:40:42.2282122Z /home/runner/arduino_ide/hardware/espressif/esp32/cores/esp32/libb64/cdecode.c:42:23: warning: this statement may fall through [-Wimplicit-fallthrough=]
2022-05-19T17:40:42.2283247Z          *plainchar    = (fragment & 0x03f) << 2; …
```

Remove GCC -Wextra warnings from build process

---

tools/platformio-build-esp32.py
tools/platformio-build-esp32c3.py
tools/platformio-build-esp32s2.py
tools/platformio-build-esp32s3.py

The PlatformIO builder scripts attempt to include `tools/sdk/esp32/include/config` to the include path (and similiarly for the other MCU types), but this folder does not exist anymore.
VSCode emits a "Problem" warning for non-existing folders declared in the therefrom created `.vscode/c_cpp_properties.json`.
The fix trivially removes these folders from the include path. If the `include/config` folder was renamed and is not yet in the PlatformIO builder script, let me know.
Tested with PlatformIO using
```ini
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
platform_packages = 
framework-arduinoespressif32@https://github.com/maxgerhardt/arduino-esp32.git#patch-2
```
and the "Problems" view cleared out.
None.

Remove nonexisting folder from include path

---

tools/platformio-build-esp32.py
tools/platformio-build-esp32c3.py
tools/platformio-build-esp32s2.py
tools/platformio-build-esp32s3.py

The builder script compiles the sources of the variant folder to a `.a` library (`env.BuildLibary()`) which is then linked into the final `.elf` firmware in the order `<variant .a> <core .a>`. 
> -Wl,--start-group .pio\build\adafruit_feather_esp32_v2\libFrameworkArduinoVariant.a .pio\build\adafruit_feather_esp32_v2\libFrameworkArduino.a 
This however prevents the `_weak` [initVariant()](https://github.com/espressif/arduino-esp32/blob/1a7962ece8a4c6ffa1d64c5a86ed8ee58dde10ba/cores/esp32/esp32-hal-misc.c#L197-L267) function to be linked properly and be executed. This effectively means that the initVariant() code of some boards, which is very critical for e.g. [powering up the I2C bus](https://github.com/espressif/arduino-esp32/blob/master/variants/adafruit_feather_esp32s2/variant.cpp#L32-L46 …

Fix linking to make initVariant() work

---

cores/esp32/esp32-hal-uart.c

espressif/esp-idf / components/driver/include/driver/uart.h defines the API:
esp_err_t uart_set_pin(uart_port_t uart_num, int tx_io_num, int rx_io_num, int **rts_io_num**, int **cts_io_num**);
uartSetPins uses that api but alls it with swapped CTS/RTS pins as its API uses a different pin ordering: 
uart_set_pin(uart->num, txPin, rxPin, **ctsPin**, **rtsPin**); 
This fixes the wrong order in the function uartSetPins
Users that have so far successfully used the API so far will need to change their code. Another possibility would be to swap the arguments in the functions uartSetPins of the cores/esp32/esp32-hal-uart.c driver and up in the HardwareSerial. But then the order of the arguments is less logic: as TX/RX is different in arduino and esp_idf but handled correctly in this function.

[UART/SERIAL] CTS / RTS pins were swapped in this API

---

boards.txt
variants/connaxio_espoir/pins_arduino.h

This PR adds support for Espoir, a mikroBUS PoE+ devboard, by Connaxio inc. However, the ESP32-MINI-1 is a single core CPU, so Connaxio will provide the builds for its devboard until single core CPUs are officially supported. Adding these modifications to the official repository will limit discrepancies between Connaxio's fork and the main repo.
Tests include Ethernet, SPI, USB, I2C, UART (1-wire).
More info: https://www.connaxio.com/electronics/espoir/

Add support for Connaxio's Espoir devboard

---

docs/source/tutorials/partition_table.rst
tools/partitions/bare_minimum_2MB.csv

This PR adds the partition table details and the steps for creating a custom one.
N/A
Closes #4551
Closes #6495

[DOCS] Added partition table tutorial

---

tools/get.py

When get.py is run in a script the percent-update printouts shown while
downloading the toolchain end up as 100s to 1000s of lines in log files.
When stdout is not a terminal, avoid printing these percentages and
shrink logfiles significantly.  Errors/etc. are still reported as normal.
*This is a "nice to have" and does not impact functionality.*
Run `cd tools; rm -f dist/*; python3 get.py > log` on a clean installation
and open the log in `vi log` and see:
````
M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M …
```

Hide get.py download percent when not interactive

---

libraries/WiFi/src/WiFiGeneric.cpp

- Issue background : https://www.youtube.com/watch?v=F0u5qIwwY1k
According to the schematics of ESP32-WROOM-DA, there is no inverter chip(SN74AUP1G04 is NC), which means that we should use two gpio(pin 2 & pin 25) to control RTC6603SP. 
While the true table of RTC6603SP shows that we only input with 1 & 0 or 0 & 1, 0 & 0 or 1 & 1 are invalid.
According to idf docs: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html?highlight=antenna#wi-fi-multiple-antennas , below sample code means(comments inline):
```
wifi_ant_gpio_config_t ant_gpio_config = {
// ESP32-WROOM-DA boards default antenna pins
.gpio_cfg[0] = { .gpio_select = 1, .gpio_num = 2 },
.gpio_cfg[1] = { .gpio_select = 1, .gpio_num = 25 },
};
wifi_ant_config_t ant_config = {
.rx_ant_mode = …
```

wifi: fix esp32 dual antenna issue

---

libraries/WiFi/src/WiFiSTA.cpp

Remove duplicate setting of SSID and password.
Done by function call of `wifi_sta_config`.
Normal WiFi connection example. 
None.

[WiFiSTA] Remove duplicate setting of SSID and password.

---

libraries/BLE/src/BLEHIDDevice.cpp

BLE HID uses GATT Service to send Battery Level Indication.
It works fine on first time pairing and bonding, but on reconnect it doesn't update the Battery Level characteristic anymore. 
It is fixed by setting the Notification to be ON, by default at the Service Creation. 
Tested with ESP32 using Bluedroid and NimBLE.
Fixes #6708

fixes BLE HID Battery Level Indicator

---

libraries/WiFi/src/WiFiGeneric.cpp

`PSK` can concern different ciphers. Make it clear that it belongs to `WPA`.
Renamed output `PSK` to `WPA_PSK`.
Enable debugging and check output.
None.

[WiFi] Clarify arduino wifi debug output

---

libraries/BLE/src/BLERemoteDescriptor.cpp

Fixes BLE client that could not read any descriptor.
This PR adds missing code necessary for reading BLE Remote Descriptors.
Tested with ESP32, ESP32C3 and ESP32S3.
Provides support in the investigation of other BLE issues such as:
#6863 
#6868

Fixes reading BLE Remote Descriptor

---

cores/esp32/Tone.cpp

In file Tone.cpp switched 2 lines with  `ledcWriteTone` and `ledcAttachPin` solving the issue #6877 
ESP32 with an oscilloscope connected. Before fix - no output, after fix outputting requested frequency.
Closes #6877

Fixing Tone; solving #6877

---

libraries/BLE/src/BLEUtils.cpp
libraries/BLE/src/GeneralUtils.cpp

Replaces IDF `CONFIG_LOG_DEFAULT_LEVEL` usage in BLE and WiFi debuging log messages by the correct Arduino structure in order to make it work with `log_d()` and `log_v()`.
It make logging work correctly with Arduino IDE.
Tested with ESP32 in different Core Debug Level modes.
This PR helps on the investigation of BLE issue such as
#6863
#6868

fixes BLE and WiFi Debug log messages

---

tools/platformio-build-esp32.py
tools/platformio-build-esp32c3.py
tools/platformio-build-esp32s2.py
tools/platformio-build-esp32s3.py
tools/platformio-build.py

This pull request includes the following two major improvements: 
- Refactored structure of the build scripts. Currently, the build scripts for each ESP32 family include a lot of duplicated code. Updating this code in four different places is tedious and error-prone. In this PR, the common code is moved to the generic `platformio-build.py` script.
- Updated process of searching for a proper partition table and bootloader image. It now behaves similarly to the Arduino IDE by searching in the variant directory in the first place.
I believe this PR shouldn't affect the autogeneration process implemented in the `esp32-arduino-lib-builder` script as only the common parts of the code were moved.

Refactor PlatformIO build scripts

---

libraries/WiFi/examples/SimpleWiFiServer/SimpleWiFiServer.ino

Update documentation:
* By default `WPA2` is minimum required. The old insecure encryption must be explicitly enabled.
* Avoid confusion of new user who tries to connect to old insecure `WPA` wifi. 
None.
None.

Doc: update wifi encryption description

---

libraries/Wire/examples/WireMaster/WireMaster.ino

- Created temporary variable, removing confusion with the reuse of "error". Where Wire.requestFrom() doesn't return an error itself.
- Added a cast to help clarify when and why bytes are being read.

WireMaster example clarity

---

libraries/SD_MMC/src/SD_MMC.cpp
libraries/SD_MMC/src/SD_MMC.h

Adds another parameter to SD_MMC.begin to change maximum open files.
Untested on any hardware, but compiles on esp32 dev board, latest master (2.0.4 pre)
Requested in #6911

Added maxOpenFiles to SDMMC

---

docs/source/api/wifi.rst
libraries/WiFi/src/WiFiSTA.cpp

The code marks `setAutoConnect`, etc to be deprecated, but the documentation does not reflect this. Therefore, the documentation was updated.
Generate doc.
No known.

Doc: Update deprecation of `setAutoConnect`, etc..

---

libraries/BLE/src/BLE2902.cpp
libraries/BLE/src/BLEDescriptor.cpp
libraries/BLE/src/BLEDescriptor.h

This PR fixes an issue related to BLE Server and Descriptors.
The issue:
If the BLE Server code changes its own descriptors, it is not reflected in the GATTS database.
BLE2902 CCCD also didn't reflect any changes to the GATTS database.
Because of this issue, the client could never read the real Descriptor values from the remote Server.
Tested with ESP32.
Fixes #6863 
Fixes #6868

Fixes BLE Server descriptor update

---

docs/source/api/wifi.rst
docs/source/troubleshooting.rst
libraries/WiFi/src/WiFiSTA.cpp

* Add doc about minimum security for connection to AP.
* Add troubleshooting to connect to WEP/WPA APs.
* Add troubleshooting about WPA3 support.
None.
Closes #6873

Doc: Add doc about minimum security for connection to AP

---

variants/adafruit_feather_esp32_v2/pins_arduino.h

Very simple fix regarding a possible typo/edit on a `#define BUTTON = 38;` declaration.
None
Fixes #6939

Fixes wrong #define for BUTTON

---

libraries/ESP32/examples/I2S/HiFreq_ADC/HiFreq_ADC.ino

Original code does not work (crashing) - related issue #6832 - now fixed.
Extended description to be more helpful.
Added options to modify the setup at the top of the code via constants.
Added option do plot with Arduino Serial plotter.
Even if the crashing was solved alone the ledc PWM would not output any signal.
Tested on ESP32 with oscilloscope and signal generator.
Closing #6832

WIP; Reworked HiFreq_ADC example; Closing #6832

---

libraries/LittleFS/src/LittleFS.cpp

-----------
With recent compiler update, the following warning is generated: 
packages/esp32/hardware/esp32/2.0.4/libraries/LittleFS/src/LittleFS.cpp:85:5: warning: …

Added dont_mount option to LittleFS conf initialization

---

.github/scripts/on-push.sh
.github/scripts/sketch_utils.sh
.github/scripts/tests_build.sh
.github/scripts/tests_run.sh
.github/workflows/hil.yml
tests/.gitignore
tests/democfg/cfg.json
tests/democfg/democfg.ino
tests/democfg/test_democfg.py

Add multiple options to the test scripts.
1. Add command line options for flash mode and parts of the FQBN (others or any required argument can be added in the future).
2. Add a way to have multiple FQBNs per test.  The FQBNs are stored in a JSON file. The test will be built and run for every FQBN.
3. Option to erase the flash before programming.  This is very hacky and shouldn't be here.  For one, in the CI, it will always erase the flash.  Locally one can omit the `-e` option.  Second, this belongs to `pytest-embedded`, and should be added there, tests that require to erase the flash will be parameterized something like:
```python
@pytest.mark.parametrize(
'erase_flash'=[True], indirect=True,
)
def test_hello_world()
...
````
There is a function already that does this but it's not …

tests: Add options.

---

libraries/ESP32/examples/Camera/CameraWebServer/app_httpd.cpp

Fixed error appearing on verbose core debug level
Fixed warnings (missing initializers)
@P-R-O-C-H-Y tested on ESP32S3-EYE
no related issue

CameraWebServer example fix

---

boards.txt

bootloader naming was changed in 2.0.4.  This matches the S3 boards up with the name change.
Untested, but should work.  Please look over to make sure I didn't completely overshoot the issue.
Fixes #6958

Fixed instances where qspi has been renamed to qio in boards.txt

---

docs/source/faq.rst

Added an FAQ entry about modifying the configuration options. This question seems to come up pretty often, so it's useful to have the answer ready.
Docs changes only, no tests performed.
* https://github.com/espressif/arduino-esp32/issues/6011#issuecomment-991888693
* https://github.com/espressif/arduino-esp32/issues/2830#issuecomment-496345988
* https://github.com/espressif/arduino-esp32/issues/1752
* and probably others

docs: add FAQ entry about modifying sdkconfig options

---

cores/esp32/HardwareSerial.cpp

`HardwareSerial::setPins()` shall issue a message in case it is used before initializing the UART with `HardwareSerial::begin()`
Tested with ESP32

Adds an error message to HardwareSerial::setPins()

---

libraries/WiFi/src/WiFiAP.h

The header for softAPConfig() uses INADDR_NONE symbol that may conflict with LWIP defenition for the same symbol depending on the order to files included in a sketch, as describer in #6981 
ESP32
Fixes #6981

Fixes LwIP INADDR_NONE conflict with softAPConfig()

---

boards.txt
tools/partitions/max_app_8MB.csv
variants/unphone8/pins_arduino.h
variants/unphone9/pins_arduino.h

Second time doing this - accidentally closed previous #7058 in error!
Is adding a new partition scheme acceptable? 
Please advise if any changes or clarification needed.
Thanks!
Description of Change:
Adds two new pin maps for the unPhone spin 8 and spin 9 to variants/unphone8 and variants/unphone9
Updated boards.txt to add definitions for unphone7 (based on Adafruit ESP32 feather) and unphone 8 and 9 (ESP32-S3)
Added a new partition scheme for 8MB flash variant of ESP32-S3 with maximum program size (7.9MB)
Tests scenarios:
Tested on our prototype hardware with a variety of test sketches, pin assignments seem correct.
Related links:
Hardware description at [unphone.net](https://unphone.net/the-unphone/) and software at https://gitlab.com/hamishcunningham/unphone

Add support for new unphone boards

---

cores/esp32/esp32-hal-touch.c

Fixes and improves the time it takes to set an interrupt with Touchpads in ESP32.
With ESP32 as reported in #7097 
``` cpp
long beginDur = 0;
void IRAM_ATTR gotTouch() {}
void setup() {
}
void loop() {
beginDur = millis();
touchAttachInterrupt(4, gotTouch, 30);
Serial.println("dur: " + String(millis() - beginDur));
}
```
Espected output shall report 0 as time.
Fixes #7097

Improves time for setting touch interrupt

---

libraries/HTTPClient/src/HTTPClient.cpp

Cookie Names and Value are case sensitive, but attibutes such as "Expires", "Max-Age", "Domain", "Path", "Secure", "HttpOnly" must be case insensitively matched. This PR fixes it in `HTTPClient::setCookie(String date, String headerValue)` function.
ESP32
Fixes #7076

Fixes Cookie Case Sensitivity

---

boards.txt

i somehow had duplicated the same name across all my boards for the PIDs and VIDs. the PID's and VID's themselves were correct, but the name was the same for all of them. that is fixed now.

fixed names on the VID and PID for my boards in boards.txt

---

.github/workflows/push.yml
CMakeLists.txt
cores/esp32/esp32-hal-misc.c
docs/source/esp-idf_component.rst

Since `delay()` won't work properly with `CONFIG_FREERTOS_HZ` not set to 1000, this adds a `_Static_assert` to verify that fact. (The standard Arduino build already sets the value properly; this is for people using the Arduino platform as a component within their own ESP-IDF build.)
Tested with a platformio build that left `CONFIG_FREERTOS_HZ` at the default (100) and verified build failure.
Then added `CONFIG_FREERTOS_HZ=1000` to `config.defaults`, erased `config.esp32` and built again, verifying success this time.
(This particular build happens to be for the OLIMEX ESP32-POE, but none of this has any impact on runtime-- runtime code is unchanged.)
Addresses https://github.com/espressif/arduino-esp32/issues/6946

Compile error if CONFIG_FREERTOS_HZ != 1000

---

boards.txt
variants/nora_w10/pins_arduino.h

Adding support for the small 10x14mm ESP32-S3 based u-blox NORA-W106 and NORA-W101 industrial module. 
- Default peripheral pins assignment is based on the EVK-NORA-W1 Arduino compatible board.
- NORA-W1 series has a 8MB flash, so therefore 16MB flash sizes removed from the menu.
Tested on EVK-NORA-W106 evaluation kit and USB-NORA-W1 USB stick breakout board. 
[u-blox NORA-W1 webpage and documentation](https://www.u-blox.com/en/product/NORA-W10-series)

Adding u-blox NORA-W10 series (ESP32-S3)

---

libraries/RainMaker/examples/RMakerSonoffDualR3/RMakerSonoffDualR3.ino
libraries/RainMaker/examples/RMakerSwitch/RMakerSwitch.ino

Fixed issue wherein changing the name of switches was not getting reflected in the phone app after the device reboots.
I have tested this on ESP32 using Arduino 2.0.3 and Rainmaker Android app
Closes espressif/esp-rainmaker#152

Fixed switch rename issue in examples espressif/esp-rainmaker#152

---

tools/platformio-build.py

This PR includes the following:
- Implemented an additional build step that produces an adjusted bootloader image with updated headers
according to  selected flash mode and size values. This step is only executed for debugging or uploading
via debug probes.
- Implemented a basic mechanism to dynamically add an extra UF2 bootloader image if corresponding
partition is selected (e.g. for Adafruit targets)
- Minor code formatting

Update PlatformIO build scripts

---

boards.txt
variants/tamc_termod_s3/pins_arduino.h
variants/tamc_termod_s3/variant.cpp

adding a new ESP32 S3 variant: TAMC Termod S3
I have tested my Pull Request on Arduino-esp32 core v2.0.4 with TAMC Termod S3 with this scenario
[Termod S3 Documentation](https://termod-s3.readthedocs.io/en/latest/index.html)

add TAMC Termod S3 board variant

---

variants/nora_w10/pins_arduino.h

- fixing the default pin assignment for the SPI peripheral for new NORA-W10 added recently.  So that they match the GPIOs connected to D10-D13 of the Arduino compatible pin headers on the EVK.
- tested on EVK-NORA-W10

[NORA-W1] Fix SPI pin assignments to match Arduino pinout.

---

cores/esp32/Esp.cpp

actually only the value from the IDE which has been set is read from magic header.
Now the real size is read from the flash chip.
Credits got to @Staars
Fixes #7157

Get real Flash Chip Size via API call

---

variants/ttgo-t-oi-plus/pins_arduino.h

The pins for LED_BUILTIN and battery voltage ADC are defined for TTGO T-OI-Plus
Tested on TTGO T-OI-Plus, other boards are not affected
* https://github.com/Xinyuan-LilyGO/LilyGo-T-OI-PLUS/blob/main/example/battery_voltage/battery_voltage.ino

TTGO T-OI-Plus: pins LED_BUILTIN & BAT_ADC_PIN

---

libraries/ESP32/examples/ESPNow/Basic/Master/Master.ino
libraries/ESP32/examples/ESPNow/Basic/Slave/Slave.ino

Fixe the ability to change `CHANNEL` which was not actually working.
The missing piece was `esp_wifi_set_channel`
Tested on C3 DevkitC as Master and ESP32 DevkitC as Slave
Issue reporting the problem of nonfunctional `CHANNEL` change #2653
Similar Issue in IDF https://github.com/espressif/esp-idf/issues/4311
New issue in IDF https://github.com/espressif/esp-idf/issues/9592

Fixed the ability to change CHANNEL

---

libraries/SPI/src/SPI.cpp
variants/d32_pro/pins_arduino.h
variants/metro_esp-32/pins_arduino.h
variants/wt32-eth01/pins_arduino.h

Added to some boards missing default pin declaration for SPI in `pins_arduino.h` + some I2C. Fixing SPI error in compilation.
Boards:
metro_esp-32
wt32-eth01
Variant [wt32-eth01](https://github.com/espressif/arduino-esp32/tree/master/variants/wt32-eth01)
Closes #7160

Add default SPI pin definitions if not defined in pins_arduino.h

---

libraries/WiFiClientSecure/src/ssl_client.cpp

Updated warning message displayed when building as IDF component.
The previous message was not helpful.
New message lead the user through `menuconfig`
none
none

Updated warning message displayed when building as IDF component

---

tools/platformio-build.py

Since it can be different and should be correct set like flash mode and flash size.
Same reasons why #7200 is made. [Align](https://github.com/espressif/arduino-esp32/blob/master/platform.txt#L214) Platformio with ArduinoIDE
Issues when target has a different flash frequency than guessed. 

add flash frequency to patched firmware

---

cores/esp32/Esp.cpp

replaces #7178 Fixes #7140
Tested with https://github.com/espressif/arduino-esp32/pull/7159#issuecomment-1238247300

Get correct (real) Flash mode via API 

---

libraries/RainMaker/src/RMaker.cpp

Fixed issue wherein device would crash after during OTA upgrade.
I've tested this using ESP32 on Arduino.
Closes #5420 and espressif/esp-rainmaker#161

Fixed issue of device crashing in Rainmaker OTA  #5420

---

docs/source/faq.rst
docs/source/guides/core_debug.rst

- Added new file `docs/source/guides/core_debug.rst` explaining in detail how to modify libuilder to compile with different log level.
- Added minimal tip + link into FAQ
Tested only an rst preview, but I don't know how will it actually draw on a web page.
https://github.com/espressif/esp32-arduino-lib-builder/issues/79

Doc addition: How to compile libs with different debug level

---

cores/esp32/Arduino.h

Adds noInterrupt() and interrupt() to Arduino. 
This must be used carefully because ESP32 Arduino runs under FreeRTOS and it is easy to get Watchdog Timeout error if it is no correctly used.
Tested with this sketch (as suggested in the issue)
``` cpp
//  To run the example sketch to demonstrate the issue, 
//  two digital pins need to be connected together somehow. 
//  This was done on a breadboard using a jumper wire.
#define OUT_PIN 14
#define IN_PIN 32
int count = 0;
void counter() {
count++;
}
void setup() {
pinMode(OUT_PIN, OUTPUT);
digitalWrite(OUT_PIN, LOW);
pinMode(IN_PIN, INPUT);
attachInterrupt(digitalPinToInterrupt(IN_PIN), counter, RISING);
for (int i=0; i<50; i++) {
digitalWrite(OUT_PIN, HIGH);
digitalWrite(OUT_PIN, LOW);
}
noInterrupts();
for (int i=0; …
```

Adds noInterrupt() and interrupt() functionality

---

cores/esp32/esp32-hal-cpu.c

-----------
Issue: Serial data sent during frequency change is corrupted. Fixes corrupt debug message by printing it after the frequency change has completed.
Tested fix on ESP32-WROOM-32UE
Closes #7250.

Fix corrupt debug message in esp32-hal-cpu.c

---

libraries/USB/src/USBHID.cpp

The HID semaphore allows `USBHID::SendReport()` to wait for the completion of
report sending. There seemed to be an extra call to `xSemaphoreTake()` of this
semaphore that served no purpose.
With this extra call, occasionally, the following would happening:
1. `USBHID::SendReport()` would send a report by calling `tud_hid_n_report()`.
2. The send would complete and (presumably on another thread)
`tud_hid_report_complete_cb()` would be called and it would `xSemaphoreGive()`
the semaphore.
3. In `USBHID::SendReport()`, the extra `xSemaphoreTake(sem, 0)` would succeed,
taking the semaphore.
4. On the next line, `xSemaphoreTake(sem, timeout_ms ...)` would timeout
because the semaphore was already taken by the previous line of code.
The result would be waiting `timeout_ms` for no reason.
The …

Remove unnecessary xSemaphoreTake() of USBHID semaphore

---

.github/workflows/upload-idf-component.yml

By default `actions/checkout@v2` makes a shallow clone and doesn't fetch tags. There are 2 ways to overcome it: 
- Fetch tags 
- Use `github.ref_name`  which will contain tag value if the workflow is started for a tag.
This PR uses the latter option. It also updates the action repo for proper action versioning.

Pass tag to the Github action uncomponent upload action

---

docs/source/esp-idf_component.rst

Added short note.
Web page display.
None.

Doc update: added note about global arduino component

---

boards.txt

Fix a typo in the name of the MiniMain ESP32-S2 board. The 't' is missing from the name 'Department'.
Visually inspected boards.txt to verify that "Department of Alchemy" is now spelled correctly.

Fix missing 't' in the name 'Department' for the MiniMain ESP32-S2 in boards.txt

---

boards.txt

-----------
This PR fix 2 errors so that we can upload the compiled firmware successfully to AirM2M_CORE_ESP32C3 board.
1. `Property 'upload.tool.serial' is undefined`
2.  esptool write_flash: error: argument <address> <filename>: Address "{upload.erase_cmd}" must be a number
Failed uploading: uploading error: exit status 2
I have tested my Pull Request on Arduino-esp32 core v2.0.5 with AirM2M_CORE_ESP32C3 Board with this scenario.

fixed AirM2M_CORE_ESP32C3 upload.tool.serial & write_flash error

---

libraries/ESP32/examples/FreeRTOS/FreeRTOS.ino

The original code assumes 100Hz FreeRTOS tick rate and just supplies vTaskDelay with the assumed number of ticks required for the wanted delay. This patch simply fixes it to use portTICK_PERIOD_MS, thereby working correctly regardless of what tick rate FreeRTOS has been configured to run at.
Signed-off-by: Nita Vesa <werecatf@outlook.com>

FreeRTOS.ino: fix usage of vTaskDelay

---

cores/esp32/HardwareSerial.cpp
cores/esp32/HardwareSerial.h
cores/esp32/esp32-hal-uart.c
cores/esp32/esp32-hal-uart.h

When `Serial.end()` is executed, the UART driver doesn't detach RX/TX/CTS/RTS pins.
As consequense, those pins pads connected using IOMUX by IDF layer will continue to send/receive data to/from the peripheral, causing the impression that Serial is still working.
This PR fixes it by adding a pin detach function used in `Serial.end()`.  
Tested using ESP32 and ESP32C3.
Necessary to use Arduino Serial Monitor for the default Board Serial port (Serial) and then some other UART<->USB converter board for reading the messages from pin 5 (new TX). 
```cpp
#define New_RX 4   // ESP32, S2, S3, C3
#define New_TX 5   // ESP32, S2, S3, C3
HardwareSerial NewSerial(0);
void setup() {
delay(2000);
Serial.println("\n\nStarting on Serial, default pins, and ending Serial"); …
```

Fixes UART pin detach on Serial.end()

---

libraries/WiFi/src/WiFiGeneric.cpp

Fixed #7406 . The "reason2str" macro in WiFiGeneric.cpp tries to read memory from index "-1"  in "system_event_reasons" array when handling STA_DISCONNECTED event with reason 0. Dealing with reason 0 as a reason 1 (WIFI_REASON_UNSPECIFIED) will solve the problem (the reason for this event to arrive with reason 0 is unknown).
This proposed change has succesfuly solved the ESP32 Guru Meditation Error when hanling STA_DISCONNECTED event with reason 0.
It has been tested on the ESP32 DevKitC V4 esp32-s3-devkitc-1 as well as the esp32-s3-devkitc-1, using PlatformIO with the Arduino-esp32 core v2.0.4.
Closes #7406 of issue.

Fixed #7406 crash on WiFi STA_DISCONNECTED event with reason 0

---

libraries/BLE/src/BLERemoteCharacteristic.cpp

Releases BLE read semaphore on BLE target disconnect to avoid deadlock on read process.
Tested with heltec_wifi_kit_32 and BLE target.
Fixes #7318

[BLE Client] Fix deadlock if connection loss while readValue

---

libraries/RainMaker/README.md
libraries/RainMaker/src/RMakerDevice.cpp
libraries/RainMaker/src/RMakerDevice.h

Update ESP Rainmaker RMakerDevice.h and .cpp to change spelling of addTemperatureParam
none
None found

Correct Spelling of addTemperatureParam in ESP Rainmaker

---

libraries/RainMaker/src/RMakerUtils.cpp

The Rainmaker C library went through changes that would improve user experience. The Rainmaker App will show the device status as offline immediately after a WiFi reset and remove the device from the app on a Factory Reset. The following changes in the Arduino core will bring these enhancements to Arduino developers.
I have tested this PR on Rainmaker Switch Example on ESP32.

Changed Rainmaker WiFi/Factory reset time.

---

libraries/ESP32/examples/TWAI/TWAIreceive/TWAIreceive.ino

Copy of https://github.com/espressif/arduino-esp32/pull/7430 but squashed and rebased.

TWAI: Add receive example (Copy of #7430)

---

.github/scripts/install-platformio-esp32.sh
.github/scripts/on-push.sh
tools/platformio-build.py

This PR brings updates according to the latest changes in the Arduino core:
- Bootloader binaries are now generated from elf files
- Updated CI scripts
- Updated esptoolpy to v4.2.1
- Minor clean-up by removing obsolete code
Resolves #7572

Update PlatformIO integration scripts

---

cores/esp32/esp32-hal-uart.c

ESP Insights wraps log functions for capturing errors/warnings. In the case of IDF, the application uses `esp_log_write()` and `esp_log_writev()` for logging. In Arduino, we use `log_printf()` so Insights cannot capture logs coming from the Arduino core.
I have tested this on esp32 using the [examples](https://github.com/espressif/arduino-esp32/pull/7566) created in the Insights library
Other Insights for Arduino PRs
https://github.com/espressif/arduino-esp32/pull/7566
Insights code for wrapping log methods
[Wrapping IDF log methods](https://github.com/espressif/esp-insights/blob/aa8beceb7385936710bb6d0ae9a86094dc8c8773/components/esp_diagnostics/src/esp_diagnostics_log_hook.c#L450)

log_printf: Restructured log_printf for wrapping

---

libraries/WiFi/src/WiFiGeneric.cpp

remove [deprecated](https://espressif-docs.readthedocs-hosted.com/projects/espressif-esp-faq/en/latest/software-framework/wifi.html#lwip-how-to-configure-the-option-contents-of-dhcp-server-in-esp-idf) `tcpip_adapter` calls,
replaced with [ESP-NETIF](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_netif.html) interface instead

WiFiGeneric: remove deprecated tcpip_adapter calls

---

docs/source/api/timer.rst

This PR fixes the description for the `countUp` argument in the Timer API `hw_timer_t * timerBegin(uint8_t num, uint16_t divider, bool countUp);` function.
N/A
Closes #7589

[Docs] Fixed the countUp description

---

libraries/LittleFS/examples/LITTLEFS_PlatformIO/littlefsbuilder.py

-----------
MKSPIFFSTOOL in PlatformIO has been changed to MKFSTOOL.
I have tested my Pull Request on PlatformIO Core, version 6.1.5 .

Fix wrong environment variable in libraries/LittleFS/examples/LITTLEFS_PlatformIO/littlefsbuilder.py.

---

libraries/BLE/src/BLEServer.cpp
libraries/BLE/src/BLEServer.h

-----------
This change adds a onDisconnect with parameters to BLEServerCallbacks, equivalent to onDisconnect, which allows the code to know which (of the multiple connections) is disconnecting. Similar to how onConnect can be used with esp_ble_gatts_cb_param_t now.
Tested on ESP32-S3-DevKitC-1, Platform-IO 5.1.1 (framework=Arduino), while connecting with 2 BLE devices (android and ios) simultaneous, reconnecting them one at a time.
Closes #6008

Added onDisconnect with gatt parameters to BLEServerCallbacks, equivalent to the existing onConnect

---

libraries/RainMaker/examples/RMakerCustom/RMakerCustom.ino
libraries/RainMaker/examples/RMakerCustomAirCooler/RMakerCustomAirCooler.ino
libraries/RainMaker/examples/RMakerSonoffDualR3/RMakerSonoffDualR3.ino
libraries/RainMaker/examples/RMakerSwitch/RMakerSwitch.ino

1. Changed default OTA type in examples.
2. Added patch that will prevent crashes during provisioning due to low memory.
I have tested all examples on esp32 using master branch.

Rainmaker Example Changes

---

libraries/FS/src/vfs_api.cpp

Performance improvements by replacing sprintf with strcpy/strcat. Additional avoid creating temporary String objects.

FS: Performance improvements in vfs_api

---

libraries/Ethernet/src/ETH.cpp
libraries/Ethernet/src/ETH.h

The variable `eth_link` was never updated, so it was always reporting link down.
Proposed fix is to use the status bits managed by WiFi callbacks, that are updated correctly.
Link duplex mode did not have an implementation for IDF versions > 3 and actually the version check was done incorrectly with the preprocessor.
Proposed fix is using the same ioctl mechanism as for the link speed.
Tested with PlatformIO and the latest stable release 2.0.5 on a custom hardware using LAN8710 and LAN8740.
Closes #6105

Fix Ethernet library link status and missing functionality with recent IDF versions

---

libraries/EEPROM/src/EEPROM.cpp

I had a hard time figuring out why EEPROM kept failing when I tried to commit, so I tried to make a small improvement by adding the error name to the err log, and I finally found my answer. With this change, I hope it'll make the debugging experience much better. 
I have tested this with ESP32
-

[Chore] Add error name to EEPROMClass commit method's error log

---

docs/source/api/ledc.rst

API has changed with https://github.com/espressif/arduino-esp32/pull/6570

Reflect ledc API changes in Docs

---

README.md

On last Community Meeting, we have noticed that some active contributors don't know about the Gitter channel. 
This PR replace Gitter badge button by simple web link so it's supposed to be more visible.

Gitter link update in Readme.md

---

variants/adafruit_feather_esp32s2_reversetft/pins_arduino.h
variants/adafruit_feather_esp32s2_tft/pins_arduino.h
variants/adafruit_feather_esp32s3_tft/pins_arduino.h
variants/adafruit_funhouse_esp32s2/pins_arduino.h
variants/adafruit_magtag29_esp32s2/pins_arduino.h
variants/adafruit_metro_esp32s2/pins_arduino.h

This PR add missing symbol TX1 and RX1 for Adafruit boards, which fixed issue reported by Adafruit user here https://forums.adafruit.com/viewtopic.php?p=954722
I have tested my Pull Request on Arduino-esp32 core (master branch 2.0.6) with Adafruit Feather ESP32-S2 TFT with SerialPassThrough example.
@ladyada

add mising TX1 RX1 for adafruit boards

---

libraries/BluetoothSerial/src/BluetoothSerial.cpp
libraries/BluetoothSerial/src/BluetoothSerial.h

Fixes: https://github.com/espressif/arduino-esp32/issues/7675
The signature of `esp_spp_cb_t` has changed in recent ESP-IDF v4.4.3, so this fix targets to accomodate that change in Arduino

Fix BluetoothSerial compilation caused by upstream change

---

libraries/ESP32/examples/Touch/TouchRead/TouchRead.ino

Match comments with code.
```c
Serial.println(touchRead(T1));  // get value using T0 
```
to
```c
Serial.println(touchRead(T1));  // get value using T1
```

TouchRead examples, Fix typo T0 -> T1

---

libraries/WiFi/src/WiFiAP.h

Adds API compatibility of WiFi.softAP() with ESP8266, by adding `String` as possible overload parameters.
Using ESP32 works correctly. 
Fix #7780

Adds softAp(String) to make it compatible with ESP8266

---

boards.txt
variants/adafruit_feather_esp32s2_reversetft/variant.cpp

This PR add new board from Adafruit: Feather ESP32-S2 Reverse TFT https://www.adafruit.com/product/5345 . This should have no impact to other core and other boards functionality.
Tested with master commit of arduino-esp32 and new board
@ladyada

Add Adafruit new board feather esp32s2 reserve tft

---

cores/esp32/FunctionalInterrupt.h

Fix compilation on latest Xtensa ESP32 GCC toolchain.
ESP32-WROOM-32U built on Windows 11 64bit PlatformIO, the MKS TinyBee V1.0

bugfix: add <stdint.h> for uint8_t in FunctionalInterrupt.h to avoid compilation failure (GCC 11.2.0)

---

.github/scripts/install-platformio-esp32.sh

to use the actual versions of the toolchains and esptool.py
Avoid issues generated by outdated tools used for CI. 
1. [ ] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
-----------
(*eg. I have …

Update Platformio CI

---

variants/heltec_wifi_lora_32_V3/pins_arduino.h

Heltec updated the I2C pins for the wifi_lora32_v3 in https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/commit/b10f4bf85d13fd01be80dcdb0eb59e6a8c8ba19a
This mirrors the commit over to this code.
It was tested on a wifi lora v3 32 with a few i2c periphreals.

Mirror I2C pin update from Heltec repository

---

boards.txt

1.) Added missing `menu.` options on top of board.txt causing issues with arduino-cli.
2.) Split `menu.` options on top of board.txt to 2 sections (Official Espressif options / Custom options) to be easier to manage.
3.) Fixed Heltec Wifi Lora 32 (V3) board to compile.
Tested by building simple sketch for Heltec Wifi Lora 32 (V3) board.
Closes #7684

Fix missing options in board.txt

---

libraries/WiFiClientSecure/src/WiFiClientSecure.cpp
libraries/WiFiClientSecure/src/WiFiClientSecure.h
libraries/WiFiClientSecure/src/ssl_client.cpp
libraries/WiFiClientSecure/src/ssl_client.h

This PR aims to improve the logic of host address parameter passing, taking into account the elimination of unnecessary conversions of the IP address into a string. Thanks to this contribution, it becomes possible to manually provide the IP address with any hostname.
- Added generic 'connect' variant that doesn't 'bind' hostname with IP address (user can provide IP manually).
- This generic variant is now called by all other functions. Hostname translation has been moved to WiFiClientSecure.
- This change also removes redundant hostByName calls (when IP address is passed).
Tested on custom board with ESP-WROOM-32 module without PSRAM. Latest master with applied changes.
Targeting: #7459
Related: #7350 #7356

Allow passing IP as connect method parameter in WiFiClientSecure

---

variants/AirM2M_CORE_ESP32C3/pins_arduino.h
variants/AirM2M_CORE_ESP32C3/variant.cpp

Add missing definitions for AirM2M CORE ESP32C3 onboard LEDs and initialize them to stop them floating and flickering.
LED D4 defined as LED_BUILTIN
LED D5 defined as LED_BUILTIN_AUX (per another dual LED board)
Tested with airm2m_core_esp32c3 using standard Arduino blink sketch.
LED GPIOs taken from here: https://wiki.luatos.com/chips/esp32c3/board.html

airm2m_core_esp32c3 board Add LED_BUILTIN* definitions and initialization for LEDs

---

cores/esp32/Print.cpp

1. [ ] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
-----------
Please describe on what Hardware and Software combinations you have tested this Pull Request and …

Remove (useless) trailing semicolon from Print.cpp

---

boards.txt
variants/Edgebox-ESP-100/pins_arduino.h

Hi, I would like to add [Edgebox-ESP-100](https://files.seeedstudio.com/wiki/edge_box_esp/EdgeBox-ESP-100-User_Manual.pdf) which is an PLC device equipped with ESP32-S3-WROOM-1U
1. added the Edgebox-ESP-100 board config setting to the end of the **"boards.txt"** file 
2. added Edgebox-ESP-100 folder in  **"/varient/Edgebox-ESP-100"**
3. added **"pin_arduino.h"** in  **"/varient/Edgebox-ESP-100"** folder for the pin configurations.
I have tested my Pull Request on Arduino-esp32 core v2.0.6 with Edgebox-ESP-100 with successful verify and upload example sketches by using a usb-to-serial tool and connected to the Serial Programming & Debugging port of the Edgebox-ESP-100, The reset button need to be pressed or GPIO0 of the Serial Programming & Debugging port need to be pull down before the …

ADD: New variant Edgebox-ESP-100

---

cores/esp32/WString.cpp
cores/esp32/WString.h

-----------
Changed function return values from unsigned char to bool. This makes our library consistent with ESP8266 (https://github.com/esp8266/Arduino/pull/7939) and ArduinoCore-API (https://github.com/arduino/ArduinoCore-API/pull/147).  It also makes comparisons easier.
Discussion:
To avoid bugs, this PR focuses ONLY on boolean returns.  It does consolidate the return value in `changeBuffer()` to match ESP8266.  I'm confident the functionality is the same.
The function `unsigned char String::equalsConstantTime(const String &s2) const` should likely be bool.  Not touching it because changing the implementation might affect constant timing.  This matches ESP8266.
Tested on arduino-esp32 v2.0.5 and hardware Adafruit Huzzah32 Feather.  This uses an ESP32-WROOM-32E.  Runs our custom code …

WString Return bool

---

README.md

I think "Arduino as an ESP-IDF component" or just "As ESP-IDF component" instead of  "ESP-IDF as Component" are a more correct ways to name [the link in the readme about Arduino as an IDF component.](https://docs.espressif.com/projects/arduino-esp32/en/latest/esp-idf_component.html)
1. "ESP-IDF as Component" would imply that ESP-IDF is some sort of library for Arduino, which is IMO misleading, because it's true the other way around.
2. It's written as "Arduino as an ESP-IDF component" on the webpage it points to as well.
Also I removed the capitalization from "Component" as I have not found a reason why is it capitalized.
[https://docs.espressif.com/projects/arduino-esp32/en/latest/esp-idf_component.html](https://docs.espressif.com/projects/arduino-esp32/en/latest/esp-idf_component.html)

Reword "ESP-IDF as Component" in readme link

---

cores/esp32/esp32-hal-timer.c
cores/esp32/esp32-hal-timer.h

Added function timerAttachInterruptFlag to timer api, which allows passing interrupt allocation flags. For example ESP_INTR_FLAG_IRAM for low latency application.
I have tested my Pull Request on Arduino-esp32 core v2.0.6 with ESP32

Added function timerAttachInterruptFlag to timer api

---

libraries/WiFi/examples/WiFiAccessPoint/WiFiAccessPoint.ino
libraries/WiFi/src/WiFiAP.cpp

Using Arduino 2.0.6 with the WiFiAccessPoint example, if the password is changed to have between 1 and 7 characters, an error message is sent, but even though the AP starts to work.
It will start with a different SSID and no password, which should not happen given that the `WiFiAPClass::softAP()` returned `false` and failed with an error message.
This PR fixes it by changing the order of the parameter verification to happen before setting the AP mode.
Tested with ESP32
Fix #7831

Avoid starting AP Mode even when the password is too short

---

libraries/BluetoothSerial/examples/GetLocalMAC/GetLocalMAC.ino
libraries/BluetoothSerial/src/BTAddress.cpp
libraries/BluetoothSerial/src/BTAddress.h
libraries/BluetoothSerial/src/BTAdvertisedDeviceSet.cpp
libraries/BluetoothSerial/src/BTScanResultsSet.cpp
libraries/BluetoothSerial/src/BluetoothSerial.cpp
libraries/BluetoothSerial/src/BluetoothSerial.h

It was not easy or obvious how to retrieve a MAC address of a local BT device.
There is an IDF function `esp_bt_dev_get_address` which accomplishes that and is used in this solution.
However, there was no `BluetoothSerial`method that would facilitate this.
This PR adds three new methods, slightly extends the `BTAddress::toString`, and adds a new example `GetLocalMAC` which demonstrates the usage of the new additions.

Added methods + example to retrive local MAC for BT

---

cores/esp32/esp32-hal-tinyusb.c

This PR fixes an issue when GPIO20 (USB D+) pull-up is not enabled for usb jtag when we switch from OTG to Jtag when reset to bootrom. Which renders upload with OTG-USB is not possible and require manual hold BOOT and reset. The issue is introduced with IDF 4.4.3 specially from this commit https://github.com/espressif/esp-idf/commit/01143bd732992c97d5f31d0875a1d4c4c3fd1227 . As mentioned in the commit message, USB D+ should be re-enabled when setup/install usb jtag.
This has been causing lots of confusion and frustration for our user.
- https://forums.adafruit.com/viewtopic.php?p=959504
- https://forums.adafruit.com/viewtopic.php?p=959702
Tested with Arduino core v2.0.6 on Espressif ESP32-S3 devkit (literally any S3 board). Steps to reproduce
- Open an Blink sketch/example
- Select …

Fix ESP32-S3 cannot reset to bootrom when using USB OTG

---

cores/esp32/esp32-hal-uart.c

Excludes ESP32S3 and ESP32C3 in the UART HAL code that detects baud rate.
This feature only works for ESP32 and ESP32S2
ESP32, ESP32S2 and ESP32S3.
``` cpp
// This sketch works correctly with ESP32 and ESP32S2 only, so far.
// ESP32C3 and ESP32S3 seems to fail with baud rate detection
void setup() {
Serial.println("\nTesting baud rate detection\n");
}
void loop() {
Serial.println("Started detection for next 20 seconds.");
Serial.println("Use the Serial Monitor. Change the baud rate in the botton of the window.");
Serial.println("Send characters using the Serial Monitor and get the detected baud rate.");
Serial.flush();
Serial.begin(0);
unsigned long detectedBaudRate = Serial.baudRate();
if (detectedBaudRate) {
Serial.printf("\nDetected baudrate is %lu\n\n", …
```

Sets correct code for UART baud rate detection

---

cores/esp32/Arduino.h
cores/esp32/WMath.cpp

Currently `radom()` uses a real hardware generator.
Arduino mainstream `random()` uses a software pseudo generator that always returns the same pseudo random sequence based on a seed defined with `randomSeed()`
This PR implements a similar behavior as the ESP8266 Arduino:
1) By default, `random()` will use the ESP32 Hardware real random generator
2) If the Sketch calls `randomSeed()`, the Arduino Core will understand that it wants to follow Arduino behavior and it will generate a Pseudo Random number based on that seed.
3) Adds a new function `void useRealRandomGenerator(bool useRandomHW)` that, at any time, tells Arduino if `random()` shall use Hardware or Software random generator.
Tested on ESP32 
testing sketch:
``` cpp
void printRandomSequence(int val1, int val2) {
// …
```

Adds pseudo random numbers generation

---

libraries/BLE/src/BLEServer.cpp

PR #7559 was incomplete when compared to issue #6008
This is pointed out in issue #7741
There is a missing call to `onDisconnect(this, param);`
Tested with ESP32-S3 sketch (below) and a mobile BLE APP (iOS or Android). 
``` cpp
#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>
#include <BLEAddress.h>
#define SERVICE_UUID        "4fafc201-1fb5-459e-8fcc-c5c9c331914b"
#define CHARACTERISTIC_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a8"
bool deviceConnected = false;
class MyServerCallbacks: public BLEServerCallbacks {
void onConnect(BLEServer* pServer) {
deviceConnected = true;
};
void onDisconnect(BLEServer* server, esp_ble_gatts_cb_param_t* param) {
BLEAddress remote_addr(param->disconnect.remote_bda);
Serial.printf("ble::onDisconnect reason: %s | Connection ID: %d | Link …
```

Adds onDisconnect() BLE param
