espressif/arduino-esp32

cores/esp32/WString.cpp, cores/esp32/WString.h
Fixed int64_t String support.
Background:
sprintf on esp32 doesn't support "%lld" parameter.  It's possible to recompile the underlying libraries to add that option. However this has already been solved in ESP8266 version of WString by replacing sprintf() with itoa/ltoa/lltoa.
This PR does the following:
Fixes integer print issues by replacing sprintf() with itoa/ltoa/lltoa
Moves concat(long long num), concat(unsigned long long num) location (match ESP8266)
Cleans up code formatting (matches ESP8266)
Tested on Arduino FeatherESP32 with v2.0.5 and current master.
Closes #7760
=> Fixed String(int64_t)

boards.txt, variants/dfrobot_firebeetle2_esp32e/pins_arduino.h
This PR adds support for the DFRobot FireBeetle 2 ESP32-E board. (https://wiki.dfrobot.com/FireBeetle_Board_ESP32_E_SKU_DFR0654) No impact to other boards.
I have tested my Pull Request on master with dfrobot firebeetle 2 esp32-e board. Successfully uploads sketches.
=> Add support for dfrobot firebeetle 2 esp32-e board

variants/heltec_wifi_kit_32_v3/pins_arduino.h, variants/heltec_wifi_lora_32_V3/pins_arduino.h
-----------
Update `heltec_wifi_kit_32_v3` and `heltec_wifi_kit_32_v3` pin headers. @smerkadidit noticed that the pins were not correct for V3. This PR fixes that.
This PR copies over changes from the upstream repo:
https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series
I have both Heltec boards, and checked that the new pins were correct.
I also read through the …
=> Update heltec_wifi v3 pins

libraries/WiFi/src/WiFiUdp.cpp
-----------
Resolves crash in WiFiUDP:parsePacket() where allocation of `new char[1460];` throws an exception under low memory conditions.
Tested on FeatherESP32 using UDP socket listener.  Using arduino-esp32 core v2.0.5.
Additional testing welcome!
Closes #4104 (stale/closed), #7558, #7845
=> WiFiUDP:parsePacket() Crashfix

platform.txt
to make use of `LTO` possible. Discussed here https://github.com/platformio/platform-espressif32/pull/702#issuecomment-1460519144
@me-no-dev 
-----------
=> use gcc-ar

libraries/WiFiClientSecure/README.md
Corrected Spelling mistake for the Documentation of the WiFiClientSecure library
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/README.md#L48
In the current documentation, Arduino has been written as Android.
=> corrected spelling mistake

libraries/HTTPClient/src/HTTPClient.cpp
Partial duplicate of https://github.com/espressif/arduino-esp32/pull/7638
=> Add support for large uploads to HTTPClient

docs/source/api/preferences.rst
The `getBytes` seems to return the number of bytes copied and not just 1.
n/a
Source file:
https://github.com/espressif/arduino-esp32/blob/0d84018d969309addacbcc3e3782c1fadc95fbc8/libraries/Preferences/src/Preferences.cpp#L509
=> Documentation update in `preferences.rst` : fix return value of `getBytes`

cores/esp32/HardwareSerial.cpp, cores/esp32/HardwareSerial.h, cores/esp32/esp32-hal-uart.c, cores/esp32/esp32-hal-uart.h
Used to set the esp32 uart mode for use with RS485 Half Duplex and the auto RTS pin mode. This will set/clear the RTS pin output to control the RE/DE pin on most RS485 chips.
To use the half duplex mode, you must disable the UART Hardware Flow Control and set the RTS pin to use with the following code:
```
Serial1.setPins(RS485RxPin, RS485TxPin, -1, RS485TxControl);
Serial1.setHwFlowCtrlMode(HW_FLOWCTRL_DISABLE, 64);
Serial1.setMode(MODE_RS485_HALF_DUPLEX);
```
The setMode parameters can be (defined in esp32-hal-uart.h):
```
MODE_UART (default)
MODE_RS485_HALF_DUPLEX
MODE_IRDA
MODE_RS485_COLLISION_DETECT
MODE_RS485_APP_CTRL
```
I have tested my Pull Request on Arduino-esp32 core v2.0.7 with ESP32-WROVER-IE Board with this scenario
=> Add setMode function HardwareSerial.c to set the esp32 uart mode for use with RS485 auto RTS

cores/esp32/esp32-hal-uart.h
C prepropressor macros are generally considered deprecated in C++, in this particular case, their use for the serial configuration breaks the enum from the EspSoftwareSerial library, release 8.0.0 onward.
This merge request provides the previous macro defines for C language builds, but replaces them functionally identical with a C++ enumeration for C++ builds, which is the default Arduino language anyway.
The ESP8266 Arduino Core uses a C++ enum already.
=> Use enum for C++ to avoid macro pitfalls in esp32_hal_uart.h

docs/source/api/espnow.rst, docs/source/api/rainmaker.rst, libraries/RainMaker/examples/RMakerSwitch/RMakerSwitch.ino, libraries/RainMaker/src/RMaker.cpp, libraries/RainMaker/src/RMaker.h
This PR creates a new API that will allow users to reboot and reset(Wi-Fi and Factory) from the Rainmaker app.
I have tested my Pull Request on Arduino-esp32 core v2.0.6 with ESP32C3 Board.
=> Rainmaker: Added enableSystemService API

cores/esp32/Esp.cpp
Tested on ESP32-D0WDR2-V3 chip. It is now correctly detected by `getChipModel()`.
=> missing ESP32-D0WDR2-V3 added to getChipModel()

libraries/BluetoothSerial/src/BluetoothSerial.cpp
In the BluetoothSerial.setTimeout function the setTimeout function of the parent Class Stream should also be called.
Without this it is not possible to set the timeout used in for example the ReadString function of an instance of BluetoothSerial. The ReadString function is not overwritten and uses the Stream timeout.
The error was discovered because something like the example Code below would just ignore the timeout and wait the default 1000 ms on readString()
```cpp
MyBluetoothSerial SerialBT;
...
SerialBT.setTimeout(5);
String temp = SerialBT.readString();
```
=> in BluetoothSerial.setTimeout also set timeout for parent class Stream.

variants/heltec_wifi_kit_32_v3/pins_arduino.h, variants/heltec_wifi_lora_32_V3/pins_arduino.h
This PR corrects the definitions for: `WIFI_LoRa_32_V3`, and `WIFI_Kit_32_V3` boards.
Without macros defined like `DISPLAY_HEIGHT`, `DISPLAY_WIDTH`, and `DIO0`, some features on the Heltec V3 boards won't initialize properly. This also makes these heltec boards more consistent with earlier board versions definitions.
Tested on the actual boards. These changes are necessary to make the display work.
Follow on to #7846 after further testing.
Thanks!!
=> Update heltec wifi v3 pin definitions

variants/heltec_wireless_stick_lite_v3/pins_arduino.h
Added the required pin out file for Heltec Wireless Stick Lite v3 (Board from November 2022).
Information gathered from the site:
https://heltec.org/project/wireless-stick-lite-v2/ (it shares url with v2)
And Esp32 s3 technical document when required (SPI/I2C pins).
=> ADD: heltec wsl v3 pinout information

cores/esp32/esp32-hal-cpu.c
Debug Level Verbose + log_d() was displaying APLL for any SoC, but S3 and C3 has not such option, causing compilation errors.
ESP32, ESP32C3, ESP32S2 and ESP32S3 with `esp-idf-v5.1-libs` branch.
Any sketch, including an empty one.
Fix #8024
=> Fixes APLL/PLL with RTC Frequency

libraries/WiFi/src/WiFiGeneric.cpp, libraries/WiFi/src/WiFiGeneric.h
This PR resolves crashes in WiFiGeneric.cpp.  The crashes can occur with `CORE_DEBUG_LEVEL` >= 2.
Targeting branch v2.x
Observed:
-    Crash due to bad index into system_event_reasons[].
Potential:
-  Crash on bad index into arduino_event_names[]. e.g. New entry added but string array not updated.
-  Crash if `event` is null.
Changelog:
- Replaced arduino_event_names[] with WiFi.eventName().
- Replaced system_event_reasons[] and reason2str() with WiFi.disconnectReasonName().
- Return if `event` is null.
Advantages:
- Easier to maintain string conversions when types are updated.
- Users can call WiFi.eventName() and WiFi.disconnectReasonName() for their own use.
- Codespace is only used if the function is called.
- Functions return blank strings rather than crashing when an unknown type is …
=> WiFiGeneric CrashFix v2.x

CMakeLists.txt, libraries/Insights/src/Insights.cpp, libraries/Insights/src/Insights.h, libraries/RainMaker/examples/RMakerSwitch/RMakerSwitch.ino, libraries/RainMaker/src/AppInsights.cpp, libraries/RainMaker/src/AppInsights.h
1. Enable ESP Insights in Rainmaker switch example. This will reuse the existing MQTT connection of rainmaker, thereby saving memory space.
2. Add option of enabling insights with custom transport.
I have tested this on esp32 wrover kit
=> Add Insights in Rainmaker Switch example

libraries/USB/examples/Gamepad/Gamepad.ino
Initial example code had no effect with Win10/11 because BUTTON_START was not recognized. 
This PR makes it visible in the Windows Game Controller Testing TAB.
ESP32-S2 and ESP32-S3 (OTG mode)
https://github.com/espressif/arduino-esp32/issues/6922#issuecomment-1500791745
https://github.com/espressif/arduino-esp32/issues/6922#issuecomment-1501858344
=> Makes Gamepad example able to be tested with Windows 10/11

libraries/WiFi/src/WiFiUdp.cpp
Fixed WiFiUDP crash on low memory where `new char[1460];` throws an exception.  `malloc` is a safe drop in replacement.
-----------
Subset of PR 7868 targeting v2.x branch. Resolves crash in WiFiUDP by replacing `new` (which can throw an exception) with malloc.
Closes #7558
=> WiFiUDF Low memory fix

.github/workflows/lib.yml, LIBRARIES_TEST.md, README.md, docs/source/external_libraries_test.rst
As the CI has no permissions to push directly to master branch, we decided to relocate the `LIBRARIES_TEST.md` file to the `gh-pages` branch.
=> [CI] External Libraries Test - Results file relocation

boards.txt, variants/lolin_s3_pro/pins_arduino.h
Add LOLIN S3 Pro board based ESP32-S3.
I have tested my Pull Request on Arduino-esp32 core with ESP32-S3 Board with this scenario
https://www.wemos.cc/en/latest/s3/s3_pro.html
=> Add LOLIN S3 Pro board def

.github/workflows/lib.yml
This PR fixes pushing the `LIBRARIES_TEST.md` file to the `gh-pages` branch.
Tested on forked repository.
=> [CI] External Libraries Test - Results file push fix

libraries/FS/src/FS.cpp, libraries/FS/src/FS.h, libraries/FS/src/FSImpl.h, libraries/FS/src/vfs_api.cpp, libraries/FS/src/vfs_api.h
re-submit #8068
1. [ ] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
-----------
Please describe on what Hardware and Software combinations you have tested this …
=> getNextFileName: Get info whether filename is a file or directory

tools/platformio-build.py
without the needed bootloader files are not found.
@me-no-dev 
Supporting development with Platformio is currently nearly impossible since the toolchains 12.2.0 are not available in Platformio registry. https://github.com/espressif/crosstool-NG/issues/41
=> fix path for bootloaders, changed from `sdk` to `esp32-arduino-libs`

libraries/ESP32/examples/Serial/Serial_All_CPU_Freqs.ino
New Example for using/testing Serial with any CPU/APB Frequency
Works fine with any SoC in Arduino Core 2.0.7+
There are issues with IDF 5.1 / Core 3.0.0 -- to be fixed in separated PR
None - just old issues, but it will be used as reference in a Core 3.0.0 issue.
=> [All Arduino Cores] Adds HardwareSerial Example

cores/esp32/esp32-hal-uart.c
Fixes HardwareSerial to work with IDF 5.1 on any CPU/APB Frequency (240MHz to 10MHZ)
UART in low APB Freq is used by potential user created low power modes.
Tested using Sketch from #8095 with ESP32, ESP32S2, ESP32C3 and ESP32S3
Related to #8095
=> [Arduino Core 3.0.0] Fixes UART to work with any APB Freq

.github/workflows/boards.yml, libraries/ESP32/examples/CI/CIBoardsTest/CIBoardsTest.ino
Renamed test from `New Board Test` to `Boards Test`
Fixed typo in `IF` condition of test-boards job in `boards.yaml`.
Added new sketch `CIBoardsTest.ino` in `ESP32/examples/CI` which is now used in the `Boards Test`
=> [CI] Boards test fix + sketch

libraries/ESP32/examples/Camera/CameraWebServer/camera_pins.h
it is planned to use the flash led but a normal led is configured instead
=> (Update camera_pins.h) Flash does not work on the esp32cam

cores/esp32/esp32-hal-ledc.c
If  `analogWrite(pin, val)`  is called a second time after a `pinMode()`, it doesn't work.
Tested with ESP32
``` cpp
#define PWM_PIN 2
void setup() {
pinMode(PWM_PIN, OUTPUT);
analogWrite(PWM_PIN, 255);
delay(2000);
pinMode(PWM_PIN, INPUT);
analogWrite(PWM_PIN, 64);
delay(2000);
pinMode(PWM_PIN, OUTPUT);
analogWrite(PWM_PIN, 16);
delay(2000);
pinMode(PWM_PIN, OUTPUT); // it goes to Low as default
}
void loop() {
delay(100);
}
```
Fixes #8106
=> Fixes analogWrite

.github/workflows/lib.json
Changed example for WS2812FX lib as the previous one used `#include <Adafruit_GFX.h>`
=> External library test - Example change for WS2812FX lib

libraries/ESP32/examples/Camera/CameraWebServer/CameraWebServer.ino
Resolves deprecation warnings in CameraWebServer.ino.
pin_sscb_sda -> pin_sccb_sda.  (note the change from `ss` to `sc`)
pin_sscb_scl -> pin_sccb_scl.
```
Building Sketch Index 16 - CameraWebServer ....
/CameraWebServer.ino:63:10: warning: 'camera_config_t::<unnamed union>::pin_sscb_sda' is deprecated: please use pin_sccb_sda instead ....
config.pin_sscb_sda = SIOD_GPIO_NUM;
....
/CameraWebServer.ino:64:10: warning: 'camera_config_t::<unnamed union>::pin_sscb_scl' is deprecated: please use pin_sccb_scl instead ....
config.pin_sscb_scl = SIOC_GPIO_NUM;
```
This is a simple variable rename.   The variables are in the same union and are identical.
"esp32/tools/sdk/esp32s2/include/esp32-camera/driver/include/esp_camera.h"
Helps advance PR #7060
=> Fix CameraWebserver.ino CI Warning

cores/esp32/WString.h
Revert to previous definition of `FPSTR` and `F` macros.
Tested on arduino-esp32 core v2.0.8 with Adafruit Huzzah32 (Feather ESP32).
Tested on Win11 computer with VSCode+PIO.
```
const __FlashStringHelper * testfunc(void)
{
return F("test");
}
void setup() {
}
void loop() {
String s;
// put your main code here, to run repeatedly:
delay(1000);
s = testfunc();
Serial.println(s);
}
```
Results:
```
ets Jul 29 2019 12:21:46
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00       
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:13220
ho 0 tail 12 room 4
load:0x40080400,len:3028
entry 0x400805e4
test
test
test
```
Closes #8108
=> Revert FlashStringHelper Macros

docs/source/getting_started.rst
This minimalistic PR simply adds a link to external examples to the doc.
Related "for reference" issue: https://github.com/espressif/arduino-esp32/issues/360
=> Added link to external examples to the doc

boards.txt
A new flexible and powerful ["pluggable discovery" system](https://arduino.github.io/arduino-cli/0.27/platform-specification/#pluggable-discovery) was added to the Arduino boards platform framework. This system makes it easy for Arduino boards platform authors to use any arbitrary communication channel between the board and development tools.
Boards platform configurations that use the old property syntax are automatically translated to the new syntax by Arduino CLI:
https://arduino.github.io/arduino-cli/latest/platform-specification/#sketch-upload-configuration
> For backward compatibility with IDE 1.8.15 and older the previous syntax is still supported
This translation is only done in platforms that use the old syntax exclusively. If `pluggable_discovery` properties are defined for the …
=> Add protocol-explicit upload.tool properties required for pluggable discovery compatibility

cores/esp32/esp32-hal-dac.c
Previous bus needs to be deinited before acquiring new bus.
=> DAC - Added missing deinit of previous bus

cores/esp32/esp32-hal-timer.c, tests/timer/timer.ino
Added timer_started flag to determine, if there is a need to call `gptimer_stop()` before `gptimer_disable()`.
Fixed `timerEnd()` by calling `gptimer_stop()` if needed.
Fixed HW timer test.
HW test tested on all supported chips.
=> TIMER - add timer_started flag, fix timerEnd() + timer HW test

docs/source/faq.rst, docs/source/tutorials/preferences.rst
**Preferences:**
A large block of code had lines beyond the visible edge and the reader was forced to scroll down to reach the vertical scroller, scroll up, see the hidden portion, then back down to scroll left and return to reading - this is unacceptable. I have folded those lines. Smaller blocks of code were left unchanged even when the code reached beyond the edge.
**FAQ:**
Added note about SPIFFS mount failed - based on "for reference" issue #638
=> Updated preferences and FAQ documentation (added SPIFFS)

cores/esp32/esp32-hal-periman.h, cores/esp32/esp32-hal-touch.c
Implemented peripheral manager into touch driver.
As touch is already using pins as input, there was no need to change any API, just added `touchDetachBus` function for the Peripheral manager, which now call `touch_pad_deinit()`, if no more touchpads are used.
Tested on ESP32-S3.
=> TOUCH - Peripheral manager implementation

cores/esp32/esp32-hal-periman.c
This PR prevents any way of setting or getting a Bus from a ESP32_BUS_TYPE_INIT table entry. This prevents future sort of inconsistencies.
Right after ESP starts, all the Buses are in `ESP32_BUS_TYPE_INIT` state, thus, if `perimanSetPinBus(pin, ESP32_BUS_TYPE_INIT, NULL)`  is executed, it will issue a debug message (`perimanSetPinBus(): Bus already set`) that doesn't make full sense.
Tested on ESP32/S2/S3 and C3
``` cpp
#include <esp32-hal-periman.h>
#define PIN 2
static bool anyDetachBus(void * bus){
log_e("This shall never happen...");
return true;
}
int myBus = 7;
void setup() {
// it is necessary to set debug level to INFO or higher.
if (perimanSetPinBus(PWM_PIN, ESP32_BUS_TYPE_INIT, NULL)) log_i("1- OK");
else log_i("1- Fail"); 
if …
```
=> Enforces more consistency into Peripheral Manager

cores/esp32/HardwareSerial.cpp
If the user supplied a wrong UART number, the `begin()` method would return without releasing the lock. Add missing `UNLOCK()` call.
No other unbalanced locks exist in this file.
=> HardwareSerial: fix begin() lock issue on error path

.github/scripts/install-platformio-esp32.sh, .github/workflows/push.yml, tools/platformio-build.py
This PR enables PlatformIO checks in CI and updates related scripts according to the changes planned for core v3.0:
- Added new package `framework-arduinoespressif32-libs` with prebuilt IDF libraries. In the current implementation the libraries are cloned directly from https://github.com/espressif/esp32-arduino-libs.git with a specific commit from that repository specified in the `FRAMEWORK_LIBS_REVISION` variable. 
- Updated toolchain and esptoolpy packages
- Minor changes according to recent updates in PlatformIO's `espressif32` dev-platform.
=> Update PlatformIO scripts for the upcoming 3.0 core

cores/esp32/esp32-hal-ledc.c
Added free() to the detach function to fix memory leaks.
```
void setup() {
}
void loop() 
{
ledcAttach(4,1000,8);
Serial.println((unsigned long)ESP.getFreeHeap());
pinMode(4,OUTPUT);
delay(1000);
}
```
```
OUTPUT before:
349512
349492
349472
349452
OUTPUT with fix:
349512
349512
349512
349512
```
#8126
=> LEDC - Memory fix

cores/esp32/HWCDC.cpp
If we call `serial.end()` followed by `serial.begin` using JTAG/CDC interface, it will never initialize the semaphore `tx_lock` and it will reset the board when data is written.
There is a missing `tx_lock = NULL;` in the `HWCDC::end()` function.
Tested with C3 and S3.
Fixes #8224
=> Fixes HWCDC::end()

cores/esp32/esp32-hal-bt.c, cores/esp32/esp32-hal-misc.c
This change is necessary within Arduino Core 2.0.x and 3.0.x.
When testing ESP32-C3 with WiFiProv.ino example to use Bluetooth provisioning, it fails because `btInUse()` returns false due to a weak/strong symbol resolving within the linker.
This PR sets the origin of the `btInUse()` function to be with `esp32-hal-bt.c` and its symbol is an external one for `esp32-hal-misc.c` making possible for the user to redefine it, is necessary. This solves the Core library C3 linker issue.
The PR is tested by using `WiFiProv.ino` example by removing the `#if CONFIG_IDF_TARGET_ESP32` in order to use it with the C3.
This shall use this call: `    WiFiProv.beginProvision(WIFI_PROV_SCHEME_BLE, WIFI_PROV_SCHEME_HANDLER_FREE_BTDM, WIFI_PROV_SECURITY_1, "abcd1234", "Prov_123");`
Tested with ESP32, ESP32-C3, …
=> fixes ESP32-C3 WiFiProv and btInUse()

boards.txt, libraries/ESP32/examples/Camera/CameraWebServer/CameraWebServer.ino, libraries/ESP32/examples/Camera/CameraWebServer/camera_pins.h, variants/dfrobot_romeo_esp32s3/pins_arduino.h
1. [ ] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
-----------
I have added support for the DFRobot Romeo ESP32-S3 board.
Please describe on what Hardware and …
=> I have added support for the DFRobot Romeo ESP32-S3 board.

libraries/WiFiProv/examples/WiFiProv/README.md, libraries/WiFiProv/examples/WiFiProv/WiFiProv.ino, libraries/WiFiProv/src/WiFiProv.cpp, libraries/WiFiProv/src/WiFiProv.h
Based on issue #7748
The main problem is simply case size for the device name:
The IDF example is using upper case: `const char *ssid_prefix = "PROV_";` [line 210](https://github.com/espressif/esp-idf/blob/54576b7528b182256c027de86eb605a172bc2821/examples/provisioning/wifi_prov_mgr/main/app_main.c#L210)
While the Arduino is using lower case (only the first letter is upper case):
https://github.com/espressif/arduino-esp32/blob/3ec5f4efa1de4342aaab742008dc630091e5e035/libraries/WiFiProv/examples/WiFiProv/WiFiProv.ino#L50
This PR changes the device name to the same as the IDF name and also to what is expected by the app on default settings.
This should remove the confusion for first-time users.
This PR also added function for printing QR code (simply copied from the IDF example)
This PR also …
=> Provisioning fix and upgrades

libraries/RainMaker/src/RMakerDevice.cpp, libraries/RainMaker/src/RMakerDevice.h
This PR fixes an issue of multiple device callbacks (one callback per device) were not getting registered and invoked.
Consider an example where I create two devices, a switch and a fan; each of them having their own write callbacks. On controlling either switch/fan through Rainmaker app, the callback that got registered at last gets invoked. This is also seen in the issue reported [here](https://github.com/espressif/arduino-esp32/issues/8231)
I have tested this PR by creating four devices; Switch, Lightbulb, Temp. sensor and Fan; each of them having their own callback. On controlling the device through app, respective callbacks were getting invoked.
Closes https://github.com/espressif/arduino-esp32/issues/8231
=> rainmaker: multiple device callbacks not getting registered

cores/esp32/esp32-hal-i2c-slave.c, cores/esp32/esp32-hal-i2c.c
Implemented peripheral manager into i2c master and slave driver.
=> I2C - Peripheral manager implementation

libraries/USB/examples/CompositeDevice/CompositeDevice.ino, libraries/USB/examples/Keyboard/KeyboardLogout/KeyboardLogout.ino, libraries/USB/examples/Keyboard/KeyboardReprogram/KeyboardReprogram.ino
The example code lacks a pinMode() to initialize the GPIO 0 (button). 
In Arduino Core 3.0.0, it can't read the button and also prints an error message when trying to read a not initialized GPIO.
`[E][esp32-hal-gpio.c:177] __digitalRead(): Pin is not set as GPIO.` 
This PR also adds `const int buttonPin = 0;` to some examples to keep a standard and make it more readable and clear.
ESP32S2/ESP32S3.
None
=> Adds missing pinMode

cores/esp32/esp32-hal-spi.c
Removed all new castings that were the source of issue and created separated calls for C6 target.
Tested SD example on ESP32, ESP32-C3 and ESP32-C6.
=> SPI fix for C6 branch

cores/esp32/esp32-hal-rmt.c, cores/esp32/esp32-hal-uart.c
Defines correct source clock for RMT and UART.
ESP32-C6 with basic examples
None
=> ESP32-C6 Fixes Settings for RMT and UART source clock 

cores/esp32/esp32-hal-ledc.c, cores/esp32/esp32-hal-ledc.h, docs/source/api/ledc.rst, libraries/ESP32/examples/AnalogOut/LEDCFade/LEDCFade.ino
Implemented LEDC Fade functionality into LEDC driver. 
There are 3 new APIs which can be used:
```
bool ledcFade(uint8_t pin, uint32_t start_duty, uint32_t target_duty, int max_fade_time_ms);`
bool ledcFadeWithInterrupt(uint8_t pin, uint32_t start_duty, uint32_t target_duty, int max_fade_time_ms, void (*userFunc)(void));
bool ledcFadeWithInterruptArg(uint8_t pin, uint32_t start_duty, uint32_t target_duty, int max_fade_time_ms, void (*userFunc)(void*), void * arg);
```
Added new example `LEDFade.ino` for demonstrating hardware LEDC fade.
Also updated documentation with these new APIs.
Tested on all supported chips.
Closes #7136
=> LEDC Fade implementation

cores/esp32/HWCDC.cpp
JTAG/CDC `Serial` interface crashes when `Serial.end()` is called twice. 
This PR shall be applied to Arduino Core 2.0.10 and 3.0.0.
Tested with ESP32-C3 and ESP32-S3.
``` cpp
// MUST USE USB Mode "CDC/JTAG" and "CDC on Boot: Enabled"
void setup() {
// No need to initialize the RGB LED
Serial.begin();
delay(500);
Serial.println("First Print Testing");
Serial.flush();
Serial.end();
Serial.end();  // Second end() causes crash.
Serial.begin();
log_d("LOG printing after end-begin");
Serial.println("Second Print Testing");
Serial.flush();
}
void loop() {
}
```
Fix #8326
=> Fixes crash when calling twice HWCDC::end()

cores/esp32/esp32-hal-periman.h, libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h
Implemented peripheral manager into ETHERNET class.
Not tested yet. Waiting to pickup board with Ethernet.
=> ETHERNET - Peripheral manager implementation

libraries/WebServer/src/WebServer.cpp
Removing client temporary variable. Arduino doesn't like copying objects. And for the logisch de class variable _currentClient can be used from the start of the method
My openHAB server calls 3 ESP32 devices every minute. In the openHAB log about 5-10% fails on a timeout (3000 ms is set timeout on openHAB). With above code modification none (running for 3 days now) of the calls failed.
https://github.com/espressif/arduino-esp32/issues/8318
(same issue and resolution for ESP8266, check https://github.com/esp8266/Arduino/issues/8941 )
=> Fix for timeout issues on WebServer.cpp

cores/esp32/HardwareSerial.cpp, cores/esp32/HardwareSerial.h, cores/esp32/esp32-hal-uart.c, cores/esp32/esp32-hal-uart.h
Adds UART to the Peripheral Manager. 
Moved all UART GPIO information to ESP32-HAL layer.
`Serial.end()` will detach all UART GPIOs.
When another Peripheral uses any UART GPIO (Rx/Tx/Rts/Cts), the UART driver is terminated and all the GPIOs are detached.
Tested with ESP32 and ESP32S3.
None.
=> Adds HardwareSerial to Peripheral Manager - Arduino 3.0.0

CMakeLists.txt, cores/esp32/Arduino.h, cores/esp32/chip-debug-report.cpp, cores/esp32/chip-debug-report.h, cores/esp32/main.cpp
When the user selects log level INFO or above, full chip data will be printed. Example data below:
```
=========== Before Setup Start ===========
Chip Info:
------------------------------------------
Model             : ESP32-S3
Package           : 0
Revision          : 0
Cores             : 2
Frequency         : 240 MHz
Embedded Flash    : No
Embedded PSRAM    : No
2.4GHz WiFi       : Yes
Classic BT        : No
BT Low Energy     : Yes
IEEE 802.15.4     : No
------------------------------------------
INTERNAL Memory Info:
------------------------------------------
Total Size        :   397676 B ( 388.4 KB)
Free Bytes        :   365332 B ( 356.8 KB)
Allocated Bytes   :    27328 B (  26.7 KB)
Minimum Free Bytes:   360352 B ( 351.9 KB)
Largest Free Block:   294900 B ( 288.0 KB) …
```
=> Print full chip report when log level is sufficient

.github/workflows/hil.yml, tests/requirements.txt
Updated pytest and its components to newest version in order to support C6 and H2.
~~DRAFT: Waiting for [patch](https://github.com/espressif/pytest-embedded/pull/220) to be merged and new version is released.~~
Patch merged and 1.3.4 released.
Tested locally on C6 - working
Tested locally on H2 - working ~~with local [patch](https://github.com/espressif/pytest-embedded/pull/220) of pytest-embedded~~
=> HW Testing - Pytest update

docs/source/api/gpio.rst
In the documentation of gpio-api, in section 'attachInterrupt' the function was wrongly named 'attachInterruptArg' in the descriptive sentence. Corrected to 'attachInterrupt'
=> Update gpio.rst Documentation: typo in function name 'attachInterrupt'

libraries/ESP32/examples/TWAI/TWAItransmit/TWAItransmit.ino
Example showing how to transmit messages using the TWAI interface and a CAN transceiver.
It also uses the alerts to show how to set them up and react to them.
This is based on the receive example, adopted with the example from the api-reference for transmission: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/twai.html#message-transmission
I used an esp32-c3-devkit (ESP32-D0WDQ6) with a SN65HVD230 CAN transceiver.
This was attached between 2 Arduino Nano´s with a MCP2515/MCP2562 CAN interface, whereby they replayed a recording from a quite busy CAN bus.
The ESP32 is used to additionally transmit messages with this example into the bus and the output was observed.
Caution, when only another ESP32 is used to receive by the TWAI receive example the …
=> Add TWAI transmit example

libraries/WiFiClientSecure/src/WiFiClientSecure.cpp
- A small change at the `WiFiClientSecure::setCACert` that will help improve security when using WiFiClientSecure library. 
- This change does not break any current code interface.
- I've just added `_use_insecure = false` at the end of the above method. It is neccessary to prevent _accidentlly insecure_ connection of the end user in case they use `wifiClientSecure.setInsecure()` then in other endpoint they need to use `setCACert`. 
The following test code (on ESP32 dev kit) will show potential security problem of using the library:
```cpp
#include "WiFiClientSecure.h"
#include "utils/WiFiFSM.h"
#include "utils/LED.h"
#include "root_ca.h"
#include "invalid_cert.h"
LED led(LED_PIN, LED_ACT);
WiFiFSM wifi(WF_SSID, WF_PASS, led);
WiFiClientSecure tlsClient;
void …
```
=> set `_use_insecure` back to `false` in `setCACert` method on WiFiClientSecure.cpp

cores/esp32/esp32-hal-matrix.c
The MATRIX_DETACH_* values vary by platform, which is not documented in the gpio_matrix_out or gpio_matrix_in functions (https://github.com/espressif/esp-idf/issues/11737).  Use the SDK macros that contain the correct values for all platforms.
Tested on an Adafruit Qt Py ESP32-C3 board.  
Tested `pinMatrixInDetach` by using `pinMatrixInAttach` to connect an input pin to the `cpu_gpio_in0` signal, then use `pinMatrixInDetach` with low and high values and verified that they propagated to `cpu_gpio_in0` read with the CSRR instruction on CSR 0x804.
Tested `pinMatrixOutDetach` on an output pin and verified that it was still driven.
Without this patch both tests fail.
Tested with ESP-IDF 4.4.3 and arduino-esp32 72c41d09538663ebef80d29eb986cd5bc3395c2d. …
=> Set MATRIX_DETACH_* values based on TRM

docs/source/api/wifi.rst, libraries/WiFi/src/WiFiAP.cpp, libraries/WiFi/src/WiFiAP.h
In WiFiSTA you can ask for the subnet mask, but not in WiFiAP. Only the subnet CIDR is reported.
Therefor the missing method is added to have the same features in softAP as well.
-----------
Have an equal API for WiFi STA and WiFi AP. In WiFiAP only the subnet CIDR is reported. To have the subnet mask one has to inverse the CIDR function.
I have tested my Pull Request on Arduino-esp32 core v2.0.9 with ESP32 Board with this scenario.
https://github.com/rstephan/ArtnetnodeWifi/issues/23
=> Soft-AP: get subnet mask

.github/workflows/docs.yml, .readthedocs.yaml, .readthedocs.yml
This PR adds the `.readthedocs.yaml` configuration file and updates the docs CI build.
https://blog.readthedocs.com/migrate-configuration-v2/
https://docs.readthedocs.io/en/stable/config-file/v2.html
=> Add .readthedocs.yaml configuration file

platform.txt
Fix escaping issues on 2.0.10 (Windows path and IDE 1.x). 
Tested on clean Windows 11 box, Arduino IDE 2.1.1, username with spaces, 2.0.10. The issue is present and is fixed by these commits.
Includes patch by @pennam fixing #8424 for IDE 1.8.x.  
Closes #8424 and fixes Windows path issues reported in Arduino forums e.g. [here](https://forum.arduino.cc/t/compilation-error-exit-status-1/1149342) and [here](https://forum.arduino.cc/t/compiling-for-esp32-fails-access-is-denied/1149574)
=> 2.0.10 escaping fix

cores/esp32/io_pin_remap.h, variants/arduino_nano_nora/io_pin_remap.cpp
@me-no-dev 
* dec6db6 fixes a minor issue: the pin-remapping macros force `tone()` to have 3 parameters, while the Arduino API dictates the third is optional.
* 9b402f0 adds an error and warnings to detect issues with bad or non-standard `#define` combinations for the variants with defined custom pin-mapping. No noticeable effects on a normal core build.
Applicable to Arduino Nano ESP32 board only (other variants not using custom pin numbering are unaffected).
Tested that now:
- Removing the `-DARDUINO_CORE_BUILD` lines in `platform.txt` stops the build with an error
- Removing the `-DBOARD_HAS_PIN_REMAP` macro in `boards.txt` triggers a warning
- Defining the `-DBOARD_USES_HW_GPIO_PIN_NUMBERS` macro at compile time triggers a warning
The changes have been discussed in the PlatformIO repo …
=> io_pin_remap fixes for the Arduino Nano ESP32

cores/esp32/MD5Builder.cpp
Fixes a memory leak in `MD5Builder::addStream()`.
None - simple fix.
Closes #8472
=> MD5 memory leak fix

libraries/WiFiProv/examples/WiFiProv/WiFiProv.ino
When using `#define USE_SOFT_AP` in the example it causes a compilation error. 
Changed `&& not USE_SOFT_AP` ==> `&& !defined(USE_SOFT_AP)`
Removed the ESP32-only restriction in the example. It works with any BLE SoC.
Teste with the ESP32, ESP32S3, ESP32C3 and ESP32S2.
ESP32S2 has only the SoftAP provisioning mode available.
The ESP32, S3 and C3 can work with BLE and SoftAP modes.
fixes #8483
=> fixes preprocessor test

.github/ISSUE_TEMPLATE/Issue-report.yml
Just adding v2.0.11 into issue template. 
N/A
N/A
=> Add v2.0.11 into issue template

cores/esp32/Esp.cpp
Currently the flash mode for the C6 always is `QOUT`. This is fixed by the PR. Now the correct flash mode is returned
@me-no-dev
=> fix flash mode read out for C6

libraries/HTTPUpdateServer/examples/WebUpdater/WebUpdater.ino
=> Removed duplicate MDNS.begin() call in example

.github/ISSUE_TEMPLATE/Issue-report.yml, cores/esp32/esp32-hal-spi.c
This PR fixes attaching/detaching some of the SPI pins for S3. Probably a leftover when new chip was added.
In 5.1-libs branch, this part of code no longer exists, so no issue there.
checked agains variant if pins are correct.
Closes #8508
=> SPI - fix attach pin for ESP32-S3

cores/esp32/HardwareSerial.cpp
Changing pins of UART1 to be consistent with C6 documentation, RX=GPIO4, TX=GPIO5.
See https://docs.espressif.com/projects/espressif-esp-dev-kits/en/latest/_images/esp32-c6-devkitc-1-pin-layout.png
Notice that existing pin configuration ALSO works, but requires wiring that is inconsistent with the official doc of the C6.
Tested on ESP32-C6-DevKitC-1 connected to a SP3485 used (and tested) for MODBUS communication.
[Please provide links to related issue, PRs etc.](https://github.com/espressif/arduino-esp32/issues/7713#issuecomment-1659866557)
=> Fixing UART1 pins for esp-idf-v5.1-libs 

cores/esp32/esp32-hal-bt.c, cores/esp32/esp32-hal-misc.c
This is related to a change done in PR #8243 to fix Arduino with RainMaker + BLE Provisioning.
The PR #8243 works correctly for the C3 and S3 with no side effects.
But for the ESP32, it causes a problem with the linker that never allows it to release the BT memory whenever the sketch doesn't use BT/BLE.
Therefore, this PR **_just reverts the PR#8243 for the ESP32_**, making it work fine as before.
Tested with ESP32, ESP32-S3 and ESP32-C3 within the following sketches:
``` cpp
void setup() {
Serial.printf("Total Heap Size: %d\n", ESP.getHeapSize());
Serial.printf("Available Heap: %d\n", ESP.getFreeHeap());
Serial.printf("Lowest level of heap since boot: %d\n", ESP.getMinFreeHeap());
Serial.printf("Largest block of heap that can be allocated at once: %d\n", …
```
=> Fixes ESP32 BT Memory Releasing

cores/esp32/HWCDC.cpp
This PR fixes HW CDC for the C3 and S3 in order to keep the buffer size already set after calling `HWCDC::begin()`. In case no size was set before `HWCDC:begin()`, it will use a default RX/TX buffer size of 256 bytes.
`HWCDC::setTxBufferSize()` and `HWCDC::setRxBufferSize()` will set the buffer size if called at any time and it won't change until a new call to this function.
`HWCDC:begin()` will only set a default buffer size if none has been set already. If `HWCDC::setTxBufferSize()` and/or `HWCDC::setRxBufferSize()` was called before, it won't change the buffer size as set by the user. If those functions are called after `HWCDC::begin()` a new buffer will be allocated with the proper new size.
Therefore, the RX/TX buffer size can be set at any time, after or before `HWCDC::begin()` is …
=> Allows changing HW CDC Buffer Size after or before begin()

libraries/WiFi/src/WiFiClient.cpp
The WiFiClient doesn't seem responsible for the actual reading, yet the function `WiFiClient::flush` was calling `recv()`.
This resulted in errors.
I have reimplemented the `WiFiClient::flush` functionality into the `WiFiClientRxBuffer` and the `WiFiClient::flush` simply calls that: `_rxBuffer->flush();`
Solves #6129
=> Reimplemented flush in WiFiClient

boards.txt, variants/lilygo_t_display/pins_arduino.h.txt
This change adds a new board lilygo-t-display based on esp32. Board variants have 4 MB or 16 MB flash memory. All boards come with a TFT display. This board is the predecessor to the already included lilygo-t-display-s3.
[Manufacturer Board webpage](https://www.lilygo.cc/products/lilygo%C2%AE-ttgo-t-display-1-14-inch-lcd-esp32-control-board)
[Pinmap](https://github.com/Xinyuan-LilyGO/TTGO-T-Display/blob/master/image/pinmap.jpg)
I have tested my pull request with a Lilygo TDisplay HW rev 1.1 by configuring PlatformIO to use the platform in https://github.com/PBrunot/arduino-esp32#feature-lilygo-tdisplay as framework for arduino-esp32, and uploading a sketch to a destination board successfully. Testing sketch is using serial, TFT display over SPI.
platformio.used for testing
``` …
```
=> added lilygo t-display (esp32-based) board definition

boards.txt, variants/esp32_s3r8n16/gen4esp32_16MBapp.csv, variants/esp32_s3r8n16/gen4esp32_2MBapp_2MBota_12MBspiffs.csv, variants/esp32_s3r8n16/gen4esp32_4MBapp_4MBota_7MBspiffs.csv, variants/esp32_s3r8n16/gen4esp32_8MBapp_8MBota.csv, variants/esp32_s3r8n16/pins_arduino.h
Adding new board range from 4D Systems
gen4-ESP32 Range, featuring ESP32-S3R8 SoC, 16MB Flash
Custom Partitions to suit our modules and 16MB Flash
=> New 3rd Party Boards - 4D Systems

libraries/SD/src/SD.cpp
Depending on filesystem init order, SD reports wrong usedBytes()/totalBytes() results.
The reason was a fixed drive id.
See:
https://github.com/espressif/arduino-esp32/issues/3546#issuecomment-1676429313
=> When FFat is mounted before SD, then filesystem reports wrong system sizes

libraries/Update/src/Update.h, libraries/Update/src/Updater.cpp
Saves 180 bytes of RAM if UpdateClass instance is not required in project
follows same semantics as for
`NO_GLOBAL_HTTPUPDATE`
`NO_GLOBAL_ARDUINOOTA`
P.S. I could come up with PR for refactored `UpdateClass` where `MD5Builder _md5` member is created on-demand allocating from a heap for the duration of update. Could save about 100 bytes for global UpdateClass instance. but I'm not sure it worth the efforts and would be accepted. Let me know.
=> add 'NO_GLOBAL_UPDATE' define to disable global UpdateClass instance

boards.txt, tools/partitions/large_fat_32MB.csv, tools/partitions/large_littlefs_32MB.csv
-----------
Please describe on what Hardware and Software combinations you have tested this Pull Request and …
=> Added a partition table for 32MB ESP32-S3 (4.8/4.8/24)

boards.txt
make following options available in the Tools menu for board M5stack-ATOM.
- Events Run On
- Loop Run On
Tested
- on M5Stack-ATOM 
- Arduino IDE 2.1.1
- Arduino-esp32 core v.2.0.11
Closes #8461
=> feature(m5stack-atom): allow events and loop on core0 in boards.txt

cores/esp32/esp32-hal-ledc.c
The last channel allocated is number 0, which conflicted with the value given to an uninitialized pin, giving the "No more analogWrite channels available!" error when trying to use it.
Pins are now given the value -1 to indicate that they are not used so channel 0 can be used without errors.
Tested on a custom board with ESP32-S3-WROOM-1 module (8 ledc channels available.)
=> ledc.c: Fix analogWrite() last channel available verification

boards.txt, cores/esp32/FunctionalInterrupt.h, cores/esp32/io_pin_remap.h, variants/arduino_nano_nora/io_pin_remap.cpp, variants/arduino_nano_nora/pins_arduino.h, variants/arduino_nano_nora/variant.cpp
This addresses issues faced by some Arduino customers when trying to use third party libraries designed for ESP32 targets with no pin remapping. 
This changeset introduces a Pin Numbering menu option and enables it for the Arduino Nano ESP32 only. The default keeps the current Arduino pin numbered API, but when users select the "By GPIO number" option, the API will revert to the ESP32 common GPIO-based numbering for maximum compatibility with existing projects and libraries. 
61d867bc also fixes some compile time issues when some specific functions are called while pin remapping is enabled. 
Tested with the Arduino Nano ESP32. Sketches where pins are used by symbol ("`D6`") access the same physical pins regardless of menu selection, even if  the symbols have different values (Arduino pin …
=> Nano ESP32: add pin numbering option

boards.txt, cores/esp32/FunctionalInterrupt.h, cores/esp32/io_pin_remap.h, tools/partitions/app3M_spiffs9M_fact512k_16MB.csv, variants/arduino_nano_nora/io_pin_remap.cpp, variants/arduino_nano_nora/pins_arduino.h, variants/arduino_nano_nora/variant.cpp
This addresses issues raised by several Arduino forum users about not being able to use SPIFFS-based projects on their Nano ESP32, introducing the choice of data partition file system between FAT and SPIFFS. 
2578081 properly implements (as other ESP32 targets) the "Burn Bootloader" action to mean "Erase Flash". This is required when switching between file systems to avoid mounting errors.
Tested on the Nano ESP32 with SPIFFS_Test and FFat_Test.
First three commits are from #8565 to avoid conflicts in `boards.txt`.
Closes #8553.
=> Nano ESP32 file system option

boards.txt, platform.txt, tools/ide-debug/esp32s3-arduino.json
This adds debugging capability to the Arduino Nano ESP32 board, by allowing the user to use the Hardware CDC USB peripheral.
* 5a48caa fixes a minor issue with the `build_opt.h` file.
* 4119409 makes the debug configuration file customizable by board, to allow special instructions on the Arduino Nano ESP32
* 53fc5f63 fixes the shared prefix in `platform.txt` (even though it is overwritten by `debug_custom.json`) 
* 1feca59c adds the actual menu and related options to the Nano ESP32. 
Tested with an Arduino Nano ESP32 on Mac, Windows and Linux with a recent Arduino IDE ([nightly builds](https://www.arduino.cc/en/software)). 
Includes commits from #8565 and #8566 to avoid conflicts on `boards.txt`.
=> Nano ESP32: add debug support

boards.txt, platform.txt, tools/ide-debug/esp32s3-arduino.json, variants/arduino_nano_nora/pins_arduino.h
-----------
Fix the Nano ESP32's version of `pins_arduino.h` following the same spirit of #8562.
Compiled for the Nano ESP32 both with and without pin mapping, no issues.
Integrates with #8562.
=> Nano ESP32: fix digital, analog and GPIO pin counts

boards.txt, variants/namino_arancio/pins_arduino.h, variants/namino_rosso/pins_arduino.h
Namino Boards: Namino combines the industrial world with the world of makers by making digital analog inputs, outputs and compatible Arduino shields available on the same board.
CPU: ESP32-S3-WROOM-1U-N4R8
```
NAMINO ROSSO provides the following input/output lines:
8 PNP digital inputs (up to 24Vdc)
1 knob input and button
8 PNP digital outputs (up to 24Vdc) of which 1 for stepper motor command with total current 200mA
1 SPDT relay output of 5A
8 single ended analog inputs (0-10V or 0-20mA) or 4 thermometric (NTC, PTC, PT1000) or 4 thermocouples (J, K, T) or 2 load cells, software configurable
1 analog output jumper configurable: 0-10V or 0-20mA
ARDUINO UNO compatible shield interface 
NAMINO ARANCIO provides the following input/output lines:
8 PNP digital inputs (up to 24Vdc)
1 knob …
```
=> new industrial boards namino rosso / namino arancio

boards.txt, variants/Aventen_S3_Sync/pins_arduino.h
Addition of Aventen S3 Sync
NA
=> Added support for the Aventen S3 Sync

cores/esp32/esp32-hal-gpio.h
Changed gpio `OUTPUT_OPEN_DRAIN` mode to act as input/output the same way, it have been changed for `OUTPUT` mode to have pin state readable by `digitalRead()`
Tested just on esp32s3, should not have any impact.
Close #8590 
Close #7022
=> GPIO - make pin mode output_open_drain state readable

libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h, libraries/WiFi/src/WiFiGeneric.cpp, libraries/WiFi/src/WiFiGeneric.h
When used in Platform IO in a combined `arduino, espidf` platform setting, and disabling ETH component, the ETH library generates a lot of error messages
Running previously running firmware that did not use Ethernet, but does use WiFi and BLE
Tested on esp32 pico d4 with Arduino 2.0.9, IDF 4.4.4
=> Disable Ethernet library if CONFIG_ETH_ENABLED not defined in sdkconfig.h

libraries/HTTPClient/src/HTTPClient.cpp
Same as #8630 but for branch `release/v2.x`.
=> v2.x - HTTPClient - Fix case sensitiveness for header keys

cores/esp32/HardwareSerial.cpp
Back in April, 2021, a workaround PR #5047 was merged to fix #5043 by adding a `delay(10)` into `HardwareSerial::end()`
This is useless as pointed in https://github.com/espressif/arduino-esp32/discussions/8627
This PR removes such `delay()`
Simple test with ESP32
Closes #8627
=> removes delay(10) from HardwareSerial::end()

libraries/WiFi/src/WiFiClient.cpp
Fixes `LoadProhibited` exception (introduced in #8541) by properly initializing and checking the `_rxBuffer` pointer in the WiFiClient.
Tested on ESP32-DevKitC using the following sketch:
```
#include <WiFi.h>
WiFiClient client;
void loop() {
delay(1000);
Serial.println(".");
}
void setup() {
Serial.println("READY");
delay(1000);
Serial.println("Flush WiFiClient client...");
client.flush();
delay(2000);
Serial.println("Setup complete");
}
```
Closes #8681
=> WiFiClient - Properly initialize and check _rxBuffer

docs/source/contributing.rst
The link to the "Arduino Style Guide for Writing Content" was changed in November 2021.
=> Update of "Arduino Style Guide" link on contributing.rst

libraries/BluetoothSerial/src/BTAdvertisedDeviceSet.cpp
Correctly prints the BT COD in hex without chopping the end of the number.
Closes #8684
=> Fix BTAdvertisedDeviceSet::toString() method output

variants/lolin_s3/pins_arduino.h
-----------
Corrected Analog I/O, BUILTIN_LED and added missing soc/soc_caps.h. (RMT CAPS)
https://www.wemos.cc/en/latest/s3/s3.html
The S3 MINI should also have the same problem, but I do not have this board to verify.
Before neopixelWrite(); on a Wemos Lolin_s3 end up in none working onboard RGB LED (aka NeoPixel).
```
E (31449) rmt: rmt_set_gpio(526): RMT GPIO ERROR
E (31450) rmt: rmt_config(686): set gpio for RMT driver failed
[ 31353][D][esp32-hal-rmt.c:615] rmtInit():  -- TX RMT - CH 1 - 1 RAM Blocks - pin 245
[ 31359][E][esp32-hal-rmt.c:631] rmtInit(): RMT failed to initilize.
[ 31365][E][esp32-hal-rgb-led.c:18] neopixelWrite(): RGB LED driver initialization failed!
```
After the change, the neopixel worked as expected.
[theelims/ESP32-sveltekit/issues/9 …
=> Corrected pins_arduino.h for Lolin_s3

boards.txt, variants/atd147_s3/pins_arduino.h, variants/ioxesp32/pins_arduino.h
Add IOXESP32 (no PSRAM, use ESP32-WROOM-32 module) and IOXESP32PS (has 4MB PSRAM, use ESP32-WROVER-IE module) if you stay in Thailand you can get it at https://www.artronshop.co.th/product/tag/ioxesp32
Add ATD1.47-S3 it use ESP32-S3 (ESP32-S3-WROOM-1U-N8R8) with TFT LCD 1.47 inch, We plan to release in next week.
Tested Blink code on hardware and it work !
for IOXESP32 board family you can get a lots of infomation at https://docs.ioxesp32.com
for ATD1.47-S3 now not release but we have demo video : https://www.facebook.com/100001449306817/videos/905405350650352/
=> Add IOXESP32 board family and ATD1.47-S3 board

libraries/SD_MMC/README.md
-----------
Fix Markdown table format error in SD_MMC's documentation
None
None
=> Fix Markdown table format error in SD_MMC's documentation

docs/source/installing.rst, docs/source/ota_web_update.rst
Update supported IDEs and add link to more information about OTA updates.
Closes #8101
=> Documentation - Update supported IDEs and general improvements

libraries/HTTPClient/src/HTTPClient.cpp
According to the [RFC](https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2), header keys for HTTP/1.x should be treated as case-insensitive.
`String HTTPClient::header(const char* name)` and `bool HTTPClient::hasHeader(const char* name)` will, incorrectly, perform case-sensitive comparisons.
This PR makes HTTPClient comparisons for header keys case-insensitive. 
Tested using the following sketch on ESP32:
```cpp
#include <WiFi.h>
#include <WiFiMulti.h>
#include <HTTPClient.h>
#define USE_SERIAL Serial
WiFiMulti wifiMulti;
void setup() {
USE_SERIAL.begin(115200);
USE_SERIAL.println();
USE_SERIAL.println();
USE_SERIAL.println();
for(uint8_t t = 4; t > 0; t--) {
USE_SERIAL.printf("[SETUP] WAIT %d...\n", t);
USE_SERIAL.flush();
delay(1000);
}
wifiMulti.addAP("myssid", …
```
=> HTTPClient - Fix case sensitiveness for header keys

cores/esp32/esp32-hal-uart.c
Fixes a lack of return value in the `uartSetPins()` function. It doesn't prevent to build the firmware, but prints a warning message. With this fix, the warning message won't be displayed anymore.
This issue doesn't affect the `uartSetPins()` function because it only happens in the case that the HAL level is used with a UART number higher than the limit, which is very improbable.
``` cpp
if(uart_num >= SOC_UART_NUM) {
log_e("Serial number is invalid, please use numers from 0 to %u", SOC_UART_NUM - 1);
return false;
}
```
Just compiling and checking that the warning message is gone.
Closes #8641
=> Fixes set pins return value in 2.0.13

cores/esp32/HardwareSerial.cpp
without compile will fail with newer GCC version. GCC v13.2 will not compile without
Currently not yet a problem ;-)
Replaces #8655 / target branch changed
=> include ctime

cores/esp32/HardwareSerial.cpp, cores/esp32/HardwareSerial.h, cores/esp32/chip-debug-report.cpp, cores/esp32/esp32-hal-periman.h, cores/esp32/esp32-hal-uart.c, cores/esp32/esp32-hal-uart.h
This PR implements the same changes as described in #8629 
It also adds to the UART Peripheral Manager the control over UART pin and sets default console UART0 RX/TX.
The `BareMinimum.ino` example (empty sketch) will report RX/TX correctly when Verbose/Debug mode are set by using the Chip Debug Report feature.
Summary of changes:
- It is now possible to dettach UART0 pins by calling Serial.end() with no previous begin()
- It is now possible to call setPins() before begin() or in any order
- setPins() will detach any previous pins that have been changed
- begin(baud, rx, tx) will detach any previous attached pins
- setPins() or begin(baud, rx, tx), when called at first, will detach console RX0/TX0, attached in boot
- any pin set as -1 in begin() or setPins() won't be changed nor detached
- …
=> 3.0.0 - UART Peripheral Manager + Detach UART pins on begin()/setPins()

cores/esp32/HardwareSerial.cpp, cores/esp32/HardwareSerial.h, cores/esp32/esp32-hal-uart.c, cores/esp32/esp32-hal-uart.h
This PR makes RS-485 Mode and  Flow Control Mode to be closer to the IDF HAL level in order to make it easier to maintain.
There is no change in its functionality.
It also moves SERIAL modes to `HardwareSerial.h`.
It helps the new Arduino IDE 2.0.x find the commentaries that allow Intellisense to display all the options for those functions.
ESP32 compilation testing.
None
=> Serial reorganization code for RS-485 Mode,  Flow Control Mode and Serial Mode

cores/esp32/esp32-hal-misc.c, cores/esp32/esp32-hal.h, platform.txt
redo for: https://github.com/espressif/arduino-esp32/pull/8574
=> Add support for custom panic handler

libraries/WiFiClientSecure/README.md
Fixes a broken link to the certificate bundle instructions in the documentation for the WifiClientSecure library.
N/A
N/A
=> Update of documentation link on readme.md for WifiClientSecure

cores/esp32/Print.cpp, cores/esp32/Print.h
Added `vprintf`, modified `printf` to use `vprintf` and added new `printf` overload that uses a `FlashStringHelper` argument (This doesn't support compile time checks. Idk if this is a good idea)
Tested using ESP32-DevKitC
Closes #7392
=> Add printf method with FlashStringHelper argument

docs/source/esp-idf_component.rst, tools/add_lib.sh
Redo of: https://github.com/espressif/arduino-esp32/pull/8115
This Doc update is based on "for reference" issue https://github.com/espressif/arduino-esp32/issues/7839
This update provides info on how to add Arduino library when using arduino-esp32 as an ESP_IDF component.
There is also new script in `tools/add_lib.sh` which helps with that. The script also creates the `CMakefileLists.txt`
Usage of the script:
```
This script help to add library when using arduino-esp32 as an ESP-IDF component
The script accepts up to three arguments:
-n  NEW: URL address to new library on GIThub (cannot be combined with -e)
-l  LOCAL: Path to the project where the library should be placed locally (must be paired with -e or -n)
-e  EXISTING: path to existing libary- this will simply skip the download …
```
=> Add Arduino lib to arduino as IDF component

libraries/BluetoothSerial/README.md, libraries/BluetoothSerial/examples/DiscoverConnect/DiscoverConnect.ino, libraries/BluetoothSerial/examples/GetLocalMAC/GetLocalMAC.ino, libraries/BluetoothSerial/examples/SerialToSerialBT/SerialToSerialBT.ino, libraries/BluetoothSerial/examples/SerialToSerialBTM/SerialToSerialBTM.ino, libraries/BluetoothSerial/examples/SerialToSerialBT_Legacy/SerialToSerialBT_Legacy.ino, libraries/BluetoothSerial/examples/SerialToSerialBT_SSP/SerialToSerialBT_SSP.ino, libraries/BluetoothSerial/examples/bt_classic_device_discovery/bt_classic_device_discovery.ino, libraries/BluetoothSerial/examples/bt_remove_paired_devices/bt_remove_paired_devices.ino, libraries/BluetoothSerial/src/BTScan.h, libraries/BluetoothSerial/src/BluetoothSerial.cpp, libraries/BluetoothSerial/src/BluetoothSerial.h
Redo of: https://github.com/espressif/arduino-esp32/pull/8453
Added missing events
Added method to remove cached devices.
Renamed, clarified, and extended usage of SSP API + example
Fixed support for legacy pairing (fixed PIN) - must use as IDF component and disable `CONFIG_BT_SSP_ENABLED`
related https://github.com/espressif/arduino-esp32/issues/4566
Including fix for #8448
=> BT serial: SSP improvements, added missing events

boards.txt
Fixed bug by adding upload.flags and upload.extra_flags to LilyGo T-display
Fixed same issue as #5589
=> Fixed bug for LilyGo T-display on boards.txt

platform.txt
This allow for example to have LVGL's config in the sketch folder and it to be project specific this way.
=> Add the sketch folder as the first include search path

cores/esp32/esp32-hal-i2c.c
When Wire.setClock() is called after Wire.begin() an assert is triggered due to changes in clock calculations
fixes: https://github.com/espressif/arduino-esp32/issues/8772
=> Fix Wire.setClock() causing assert

libraries/LittleFS/src/LittleFS.cpp
Latest LittleFS provides the feature `grow_on_mount`. This PR makes it possible to use.
Details https://github.com/joltwallet/esp_littlefs/pull/148
We are using in project Tasmota and it works well.
=> provide LittleFS feature `grow_on_mount`

cores/esp32/HardwareSerial.cpp, cores/esp32/esp32-hal-uart.c, libraries/ESP32/examples/Serial/BaudRateDetect_Demo/BaudRateDetect_Demo.ino
This PR removes UART pins detaching whenever it is used to detect baud rate.
Such feature only works with ESP32 and ESP32-S2. 
It also fixes error message when trying to use ESP32-S3, ESP32-C3, ESP32-C6 and ESP32-H2 with baud rate detection.
In addition the PR also add an example about how to use baud rate detection feature.
Tested with ESP32 and ESP32-S2 UART0 using the Example provided in this PR.
None
=> HardwareSerial::end(bool) review + Baud Rate detection review and example

libraries/BLE/examples/Beacon_Scanner/Beacon_Scanner.ino, libraries/BLE/examples/Scan/Scan.ino, libraries/BLE/src/BLEScan.cpp, libraries/BLE/src/BLEScan.h
A `BLEScanResults` object is returned from `BLEScan` methods, causing issues because its same copy is released more than one time, causing HEAP corruption. 
To fix it BLEScanResults should be used as a contained class, by reference and not copy.
This is the same done with `BLEScan*`, for instance.
Tested with ESP32 using this sketch that causes the issue, before the change is done (previous version):
```cpp
#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEScan.h>
#include <BLEAdvertisedDevice.h>
int scanTime = 5; //In seconds
BLEScan* pBLEScan;
void setup() {
Serial.println("Scanning...");
BLEDevice::init("");
pBLEScan = BLEDevice::getScan(); //create new scan
pBLEScan->setActiveScan(true); //active scan uses more power, but get results faster …
```
=> Fixes BLEScanResults to be used by reference 

libraries/FS/src/FSImpl.h
This fixes this linker error:
```
c:/users/david/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\esp-idf\framework-arduinoespressif32\libframework-arduinoespressif32.a(vfs_api.o):(.literal._ZN11VFSFileImplD2Ev+0x4): undefined reference to `vtable for fs::FileImpl'
```
It can be tested on any of the examples of SPIFFS or LittleFS. 
For some reason it only happens when using Arduino as component on the latest version which uses IDF 5.1, no idea why a normal Arduino project links fine, because we are declaring a virtual function on the base class, but not defining it in the same class, so we should create a empty definition or just make it pure-virtual.
```
if(!LittleFS.begin()){ …
```
=> Fix linker failure when using SPIFFS or LittleFS with Arduino as component

cores/esp32/chip-debug-report.cpp, cores/esp32/esp32-hal-periman.h, libraries/ESP_I2S/src/ESP_I2S.cpp
This PR fixes missing call to set peripheral managers detach bus function for I2S.
=> I2S fix missing perimanSetBusDeinit()

docs/requirements.txt, docs/source/conf.py
This PR fixes the RTD default theme.
Component `sphinx-copybutton` version update.
Version on the docs footer updated to `2.0.14`.
N/A
N/A
=> [Docs] Fixed the RTD theme and core version

CMakeLists.txt
according to https://docs.espressif.com/projects/esp-idf/zh_CN/v5.0/esp32/migration-guides/release-5.x/storage.html
=> Fix "fatal error: esp_partition.h: No such file or directory"

docs/source/common/datasheet.inc, docs/source/getting_started.rst
Added ESP32C6 and ESP32H2 to the getting started page of our docs, as they are now supported in the development releases.
=> [Docs] Add ESP32C6 + ESP32H2

boards.txt, variants/dfrobot_beetle_esp32c6/pins_arduino.h, variants/dfrobot_firebeetle2_esp32c6/pins_arduino.h
-----------
Add the DFRobot Beetle ESP32C6 and the DFRobot FireBeetle2 ESP32C6 as two development boards.
Compiles and can build projects.
The product link has not been released yet.
=> Add the DFRobot Beetle ESP32C6 and the DFRobot FireBeetle2 ESP32C6 as two development boards

cores/esp32/HWCDC.cpp, cores/esp32/HWCDC.h, cores/esp32/HardwareSerial.cpp, cores/esp32/HardwareSerial.h, cores/esp32/USBCDC.cpp, cores/esp32/USBCDC.h, libraries/ESP32/examples/Serial/Serial_STD_Func_OnReceive/Serial_STD_Func_OnReceive.ino, libraries/USB/examples/CompositeDevice/CompositeDevice.ino, libraries/USB/examples/ConsumerControl/ConsumerControl.ino, libraries/USB/examples/CustomHIDDevice/CustomHIDDevice.ino, libraries/USB/examples/FirmwareMSC/FirmwareMSC.ino, libraries/USB/examples/Gamepad/Gamepad.ino, libraries/USB/examples/HIDVendor/HIDVendor.ino, libraries/USB/examples/Keyboard/KeyboardLogout/KeyboardLogout.ino, libraries/USB/examples/Keyboard/KeyboardMessage/KeyboardMessage.ino, libraries/USB/examples/Keyboard/KeyboardReprogram/KeyboardReprogram.ino, libraries/USB/examples/Keyboard/KeyboardSerial/KeyboardSerial.ino, libraries/USB/examples/KeyboardAndMouseControl/KeyboardAndMouseControl.ino, libraries/USB/examples/Mouse/ButtonMouseControl/ButtonMouseControl.ino, libraries/USB/examples/SystemControl/SystemControl.ino, libraries/USB/examples/USBMSC/USBMSC.ino, libraries/USB/examples/USBSerial/USBSerial.ino, libraries/USB/examples/USBVendor/USBVendor.ino
The PR changes `Serial` to be a pre-processor symbol instead of a HardwareSerial/HWCDC/USBCDC object.
Therefore, UART0 is always the `Serial0` object.
If the sketch doesn't use `CDC on Boot`, `Serial` will defined to be `Serial0` by default.
Whenever the sketch is set to use `CDC on Boot`, `Serial` will defined to be `USBSerial` object, which in turn will point to a HWCDC or USBCDC object depending on how it is configured / which SoC is used.
The PR will make `Serial0`, `Serial1` and `Serial2` (if it exists) always available as UART0/1/2.
`USBSerial` will also always be available whenever the SoC has a CDC interface.
If necessary the sketch can change/force the redefinition of `Serial` symbol to whatever necessary.
The PR also adds a `HWCDCSerialEvent()` callback that is executed after …
=> Serial as a #define

cores/esp32/HardwareSerial.cpp, cores/esp32/HardwareSerial.h
This PR aims to change the default UART1 and UART2 pins to avoid conflicts and improve ease of use.
It also moves the pin definitions to the `HardwareSerial.h` file so they can be used in sketches.
The final pin assignments are:
|          |   Name  | ESP32 | S2 | S3 | C3 | C6 | H2 |
|:--------:|:-------:|:-----:|:--:|:--:|:--:|:--:|:--:|
| UART0 RX | SOC_RX0 |   3   | 44 | 44 | 20 | 17 | 23 |
| UART0 TX | SOC_TX0 |   1   | 43 | 43 | 21 | 16 | 24 |
| UART1 RX |   RX1   |   26  |  4 | 15 | 18 |  4 |  0 |
| UART1 TX |   TX1   |   27  |  5 | 16 | 19 |  5 |  1 |
| UART2 RX |   RX2   |   4   | -- | 19 | -- | -- | -- |
| UART2 TX |   TX2   |   25  | -- | 20 | -- | -- | -- |
Tested all chips using the (future) UART CI script.
=> UART: Change default Serial1/2 pins and move definition to header

libraries/BluetoothSerial/src/BluetoothSerial.cpp
This PR aims to fix the SPP service mode used in the SPP callback.
Closes #8748
=> BluetoothSerial: Fix SPP service mode

cores/esp32/esp32-hal-uart.c, tests/uart/test_uart.py, tests/uart/uart.ino
This PR aims to add UART tests to the CI. It also does some very small improvements to the UART HAL.
Tested locally with all standard devkits.
Requires #8800 and  #8805
=> CI: Add UART test

tools/espota.py
This PR is a redo of https://github.com/espressif/arduino-esp32/pull/8239
Replaced the deprecated optparse module with argparse.
Adjusted the code style to conform to PEP 8 guidelines.
Used with statement for file handling to ensure proper resource cleanup.
Incorporated exception handling to catch and handle potential errors.
Made variable names more descriptive for better readability.
Introduced constants for better code maintainability.
=> [REDO] Update espota.py

cores/esp32/esp32-hal-rmt.c
This PR aims to fix RMT failing to start due to the uninitialized interrupt value. This would cause the interrupt to be initialized with garbage memory values:
```
E (18193) rmt: rmt_new_tx_channel(210): invalid interrupt priority:-2113922172
```
Tested with ESP32-S3-DevKitC-1 using the BlinkRGB example.
=> RMT: Fix RMT TX interrupt level

cores/esp32/chip-debug-report.cpp, cores/esp32/esp32-hal-periman.c, cores/esp32/esp32-hal-periman.h
This PR aims to improve the Peripheral Manager log messages to help debugging processes.
=> PeriMan: Improve log messages

cores/esp32/HardwareSerial.cpp, cores/esp32/esp32-hal-uart.c, cores/esp32/main.cpp
Fixes the order that a UART pin attaching shall work when a previous peripheral has been already attached.
Using Serial as UART0, independently of using `USB CDC On Boot: "Enabled` + any Logging Level (None | Verbose)
``` cpp
#include <SPI.h>
#ifndef LED_BUILTIN
#define LED_BUILTIN 2
#endif
void setup() {
Serial0.begin(115200);
//Serial0.setDebugOutput(true);
Serial0.println("TESTING... 1 - UART0");
Serial0.flush();
log_v("12345567890");  // just testing logging
// initialize digital pin LED_BUILTIN as an output.
pinMode(LED_BUILTIN, OUTPUT);
const uint8_t testedPin = SOC_TX0; // works for any any SoC
//First testing is using TX0 as RMT channel
rmtInit(testedPin, RMT_TX_MODE, RMT_MEM_NUM_BLOCKS_1, 10000000);
Serial0.println("RMT tick set to: 100ns");  // not printed -- TX UART0 attached …
```
=> Fixes uart attach/detach

cores/esp32/esp32-hal-rgb-led.c, libraries/ESP32/examples/RMT/RMTWriteNeoPixel/RMTWriteNeoPixel.ino, libraries/ESP32/examples/RMT/RMT_CPUFreq_Test/RMT_CPUFreq_Test.ino
Based on issue #8841, it was clear that some improvements could be done to the `neopixelWrite()` function.
Changes:
1- All RMT examples use the `PIN_NEOPIXEL` defined in `pins_arduino.h` for the Espressif devkits
2- `neopixelWrite()` can be used with many GPIOs in the same sketch. Before this changes, the sketch could only use one GPIO with `neopixelWrite()`.
Tested with ESP32-C6:
``` cpp
void blinkRGBLED(uint32_t count, uint32_t time_ms) {
const uint8_t LED_Pin = 23;  // change it to any other valid GPIO
for ( ; count; count--) {
neopixelWrite(LED_Pin, 255, 255, 255);  // RGB = White (on)
Serial.println("HIGH");
delay(time_ms);
neopixelWrite(LED_Pin, 0, 0, 0); // RGB = Black (off)
Serial.println("LOW");
delay(time_ms);
}
}
void setup() {
// No need to initialize the RGB LED …
```
=> Neopixel fix

libraries/BluetoothSerial/src/BluetoothSerial.cpp
SerialBT interface uses a task to send and receive data using Bluetooth SPP. When the application wants to reach maximum performance, specially when reading from one peripheral and writing the stream of bytes to the SPP interface, it fails and losses some data.
In order to improve it and make it run in the best performance possible, its task priority shall be the highest possible.
Using ESP32 - example provided in the issue #8808
Closes #8808
=> Increase BT SPP task priority

idf_component.yml
Arduino I2S uses MP3 header file and it fails when Arduino is built as IDF component.
This fixes it by making it public and exporting its header files to the I2S code and examples. 
project/main/idf_component.yml:
```
dependencies:
idf: ">=5.1"
espressif/arduino-esp32:
version: "*"
git: https://github.com/espressif/arduino-esp32.git
require: public
```
Build any sketch using Arduino as IDF component and with Arduino as Managed Component in the `idf_component.yml` file.
None
=> Makes MP3 header files public for I2S code

boards.txt, variants/um_tinyc6/pins_arduino.h
Added Unexpected Maker TinyC6 development board to the boards list.
Renamed and re-ordered all UM boards in boards.txt to make them more identifiable. 
I've tested this on my TinyC6, and it's working as expected.
@me-no-dev Can you please tag this for 3.0.0? I'm not quite sure how this all works when doing a PR for a tag.
=> Add new UM TinyC6 board and re-ordered UM boards in boards.txt file.

libraries/WiFi/src/WiFiSTA.cpp, libraries/WiFi/src/WiFiSTA.h, libraries/WiFi/src/WiFiScan.cpp, libraries/WiFi/src/WiFiScan.h
Arduino doc on BSSID getters: https://www.arduino.cc/reference/en/libraries/wifi/wifi.bssid/
I [compared more than a dozen of Arduino Networking libraries](https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md) to find the common API for Arduino networking. Then I wrote [a test sketch](https://github.com/JAndrassy/NetApiHelpers/blob/master/examples/WiFiTest/WiFiTest.ino) which checks how a library complies to this common API.
ESP32 Arduino WiFi library was based on ESP8266 Arduino WiFi library which was based on the first WiFi library by Arduino. Arduino later created more WiFi libraries and the API diverged, but at least with the most recent library they looked at the ESP32 WiFi library for new method names (for example dnsIP(n)).
While doing the research and …
=> WiFi.BSSID and scan result BSSID with parameter as in WiFi libraries by Arduino

libraries/WiFi/src/WiFiSTA.cpp, libraries/WiFi/src/WiFiSTA.h
Arduino doc: https://www.arduino.cc/reference/en/libraries/wifi/wifi.setdns/
I write about the motivation for this in the other [PR](https://github.com/espressif/arduino-esp32/pull/8853)
=> WiFiSTA - method setDNS as in WiFi libraries by Arduino

docs/source/installing.rst
This PR change a warning note about PlatformIO not being maintained by Espressif Arduino Core ESP32 project.
The original note was bringing some confusion to some of the users.
This PR relates to discussion in #8606 and also this PIO issue: https://github.com/platformio/platform-espressif32/issues/1225
=> Update warning note about PlatformIO related issues

cores/esp32/Esp.cpp
Various ESP32-variants like the C6, H2, etc. differ in their used flash frequencies.
Also the maximum possible flash size wasn't handled in `magicFlashChipSize`
Used the info from [esptool.py](https://github.com/search?q=repo%3Aespressif%2Fesptool%20FLASH_FREQUENCY%20&type=code)
=> Add platform specific flash speed to magicFlashChipSpeed

libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h
Here to help https://github.com/espressif/arduino-esp32/pull/8881
=> Fully guard I2C Slave in preparation for C2 support

cores/esp32/esp32-hal-tinyusb.c
This PR fixes an issue when GPIO19/20 (USB D+/D-) pull-up is not enabled for usb jtag when we switch from OTG to Jtag when reset to bootrom. Making uploading via USB OTG not possible.
- usb_otg_deinit() return false cause the new `periman` abort the pinMode() and digitalWrite() on DP/DM which is required disconnect from USB bus and force PC host to re-enumerate USB OTG in bootrom.
https://github.com/espressif/arduino-esp32/blob/fbfcb802b62e551721d4194330f08744ec7cf08d/cores/esp32/esp32-hal-tinyusb.c#L433-L436
- without this fix, above pinMode()/digitalWrite() do nothing, device reset to bootrom but USB host won't re-enumerate USB OTG. This can be observed when enable verbose logging (I added pinMode(D-/D+) and digitalWrite(D-/D+) to make it easier to follow)
```
[ …
```
=> fix S3 cannot reset to bootrom with USB OTG due to new gpio deinit()

tools/partitions/tinyuf2-partitions-16MB-noota.csv, tools/partitions/tinyuf2-partitions-16MB.csv, tools/partitions/tinyuf2-partitions-4MB-noota.csv, tools/partitions/tinyuf2-partitions-4MB.csv, tools/partitions/tinyuf2-partitions-8MB-noota.csv, tools/partitions/tinyuf2-partitions-8MB.csv
TinyUF2 is gettting a bit more popular with ESP32 S2/S3, however, tinyuf2 partition is currently treated as custom paritions and stored in `variants/{board}` folder. All Adafruit S2/S3 boards make use of tinyuf2, this causes quite a bit of csv file duplication within the repo.
This PR adding commonly used tinyuf2 partitions will help to reduce csv duplication and make it easier to add new tinyuf2-enabled boards. 
Nothing to test, will update Adafruit to use these and removed all duplicated csv in adafruit boards as follow-up later on.
@ladyada
=> add tinyuf2 partitions csv

boards.txt, variants/esp32s3_powerfeather/pins_arduino.h
Adds a new `variant` directory for `esp32s3_powerfeather`, under which the `pins_arduino.h` is created.
Entries for `esp32s3_powerfeather` in `boards.txt` are added.
Website: https://www.powerfeather.dev/
Allocation for PID under Espressif VID used in this PR: https://github.com/espressif/usb-pids/pull/123
=> Add support for ESP32-S3 PowerFeather

docs/source/conf.py
This PR adds the Google Analytics ID to the `conf.py` file. This will be used for documentation analytics.
N/A
N/A
=> Added the Google Analytics ID in the configuration file

cores/esp32/esp32-hal-rmt.c
- Commented out setting interrupt priority for both TX and RX configurations in the RMT initialization code.
otherwise we get an Compile Error with esp-idf 5.1.1
=> Update RMT initialization code

.github/scripts/on-push.sh, platform.txt
Fixes: https://github.com/espressif/arduino-esp32/issues/8610
=> Support relative paths in UNIX search PATH

libraries/ESP_I2S/src/ESP_I2S.cpp, libraries/ESP_I2S/src/ESP_I2S.h
Needed for some setups, where only the right channel is being used.
=> Add support for I2S Slot Mask

cores/esp32/esp32-hal.h, cores/esp32/io_pin_remap.h, libraries/SD/src/sd_diskio.cpp
Disabling the periman APIs from remap has a negligible effect on the source: the core is already excluded from remapping, as are most of the libraries. It's also expected to be somewhat private, not exposed by default via `Arduino.h`.
This patch removes references to those APIs from both `esp32-hal.h` and `io_pin_remap.h`, adjusting the relevant libraries.
=> fix: pin_remap: make periman APIs private and non-remapped

package/package_esp32_index.template.json
```
lib-builder: master e2f746c
esp-idf: release/v5.1 3662303f31
arduino: master e97a5190
tinyusb: master 0877a486c
espressif__esp-dl:
espressif__esp-dsp: 1.4.9
espressif__esp-nn: 1.0.2
espressif__esp-sr: 1.6.0
espressif__esp-tflite-micro: 1.2.0
espressif__esp-zboss-lib: 1.0.5
espressif__esp-zigbee-lib: 1.0.5
espressif__esp32-camera:
espressif__esp_diagnostics: 1.0.1
espressif__esp_insights: 1.0.1
espressif__esp_rainmaker: 1.0.0
espressif__esp_schedule: 1.0.1
espressif__esp_secure_cert_mgr: 2.4.1
espressif__json_generator: 1.1.1
espressif__mdns: 1.2.1
espressif__qrcode: 0.1.0~1
espressif__rmaker_common: 1.4.3
joltwallet__littlefs: 1.10.2
```
=> IDF release/v5.1

.github/PULL_REQUEST_TEMPLATE.md
Adding a note to the Pull Request Template.
**Reason:**
Sometimes maintainers need to take over of opened Pull Requests and they are blocked by not provided permissions.
N/A
N/A
=> Adding a note to allow access to PR secrets into PR template

.github/workflows/boards.yml
Added automated check if boards_name.build.board is uppercase.
Tested locally
#7942
=> [CI] Add to Boards Test check if build.board is uppercase

boards.txt, cores/esp32/esp32-hal-cpu.c
Added 120 MHz option to `setCpuFrequencyMhz()` as ESP32-C6 and ESP32-C2 supports this frequency.
Also added 120 MHz option for ESP32-C6 in the tools menu.
Tested locally on ESP32-C6.
Closes #8955
=> Add 120Mhz cpu frequency option to setCpuFrequencyMhz() 

libraries/Update/src/Updater.cpp
As calculated MD5 checksum is always lowercase, force `UpdateClass::setMD5` to store the expected MD5 in lowercase as some servers may return the MD5 in uppercase.
Tested forcing Arduino OTA to receive Uppercase MD5 by espota.py. Working as expected with MD5 lowercase or uppercase.
Closes #8945
=> UpdateClass::setMD5 store expected md5 in lowercase

libraries/WiFi/src/WiFiGeneric.cpp
`dns_gethostbyname`, as used in `hostByName`, is required to run in lwIP’s TCP/IP context. This can be verified by enabling `LWIP_CHECK_THREAD_SAFETY` in the sdkconfig.
Calling `dns_gethostbyname` from the Arduino task can trigger race conditions in lwIP or lower layers. One possibility is a corruption of IDF's Ethernet buffers, causing an unstoppable flood of "insufficient TX buffer size" errors, effectively severing all Ethernet connectivity.
`hostByName` cannot be executed in the TCP/IP context because it blocks until completion, preventing the TCP/IP task from receiving the DNS response to unblock itself, causing a deadlock. Therefore, this PR patches `hostByName` to execute `dns_gethostbyname` in the TCP/IP context while still blocking only the Arduino task.
I have tested my PR on …
=> Fix race condition in WiFiGenericClass::hostByName

docs/source/api/reset_reason.rst
CI is failing due to a change in ResetReason.ino folder.
/home/runner/work/arduino-esp32/arduino-esp32/docs/source/api/reset_reason.rst:18:Include file '/home/runner/work/arduino-esp32/arduino-esp32/libraries/ESP32/examples/ResetReason/ResetReason.ino' not found or reading it failed
make: *** [Makefile:28: html] Error 2
Error: Process completed with exit code 2.
CI Testing only.
None
=> Fixes CI error in reset_reason.rst

cores/esp32/Esp.cpp, libraries/BLE/src/BLEAdvertising.cpp, libraries/WebServer/src/WebServer.cpp, libraries/WiFi/src/WiFiUdp.cpp
This PR resolves potential crashing issues when allocating memory using `new` keyword.  Will be replacing with `malloc` for non-class calls. Targeting 3.0.x branch.
arduino-esp32 core v2.0.7 with Adafruit Feather ESP32.
Started by issue #7558.  PR #8065 will fix the issue on 2.x branch.
=> Replace new with malloc for non-class calls

.github/scripts/on-push.sh, .github/scripts/sketch_utils.sh
This PR fixes CI build on Windows runners, which did not failed on compilation error.
Also replaced BLE example with the correct one + simplified example selection across multiple SOCs, as the sketch_utils.sh build() now checks for the skip file.
CI passes
=> [CI] ESP32 Arduino CI fixes for Windows runner

libraries/HTTPClient/src/HTTPClient.cpp, libraries/HTTPUpdate/examples/httpUpdateSecure/httpUpdateSecure.ino, libraries/WebServer/src/WebServer.cpp, libraries/WiFi/src/WiFiClient.cpp, libraries/WiFi/src/WiFiClient.h, libraries/WiFiClientSecure/src/WiFiClientSecure.cpp, libraries/WiFiClientSecure/src/WiFiClientSecure.h
Arduino Stream::settimeout() is not virtual so it cannot be virtual in ESPLwIPClient.
This change should fix this conflict.
Closes #5558
=> ESPLwIPClient::setTimeout conflict fix with Stream::setTimeout

libraries/WiFiClientSecure/src/WiFiClientSecure.cpp, libraries/WiFiClientSecure/src/WiFiClientSecure.h
This PR removes `setTimeout` from WifiClientSecure. This change should be part of #6676, but after rebasing this change was missing.
=> Remove setTimeout from WifiClientSecure

libraries/WiFi/src/WiFiClient.cpp, libraries/WiFi/src/WiFiClient.h
<del>`WiFiClient::setTimeout` now shadows `Stream::setTimeout` which has a different purpose and the unit of the parameter is different. Related [issue](https://github.com/espressif/arduino-esp32/issues/5558).</del>
<del>The solution is to rename `WiFiClient::setTimeout` to [Arduino standard](https://www.arduino.cc/reference/en/libraries/ethernet/client.setconnectiontimeout/) `WiFiClient::setConnectionTimeout`.</del>
EDIT: at the end most of this PR was done in https://github.com/espressif/arduino-esp32/pull/6676 and https://github.com/espressif/arduino-esp32/pull/8998
overview of Client API in Arduino networking libraries:
https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md#client-getters-and-setters
=> WiFiClients.setConnectionTimeout added

cores/esp32/esp32-hal-adc.c, cores/esp32/esp32-hal-adc.h
1. Add new __analogReadRaw function and move code from __analogRead without mapResolution part to __analogReadRaw.
2. Refactor __anlogRead to use analogReadRaw (and mapResolution).
3. Refactor __analogReadMilliVolts to always use default read resolution when reading adc value, as expected input by esp_adc_cal_raw_to_voltage is in default resolution (means replacing all calls of __analogRead with __analogReadRaw).
This shall avoid that a change of the resolution of analog readings leads to incorrect values when using the analogReadMilliVolts function, as this function always expects the resolution to be the default one. For more information see description in #8999. 
I have tested my Pull Request on Arduino-esp32 core v2.0.14 with UM FeatherS2 (ESP32-S2) board with an analog sensor …
=> fix(adc): Always use default read resolution in __analogReadMilliVolts

libraries/WebServer/src/WebServer.cpp
This fixes a wrong (but "valid") call for `malloc()`.
C:/Users/user/.platformio/packages/framework-arduinoespressif32/libraries/WebServer/src/WebServer.cpp:138:54: warning: pointer to a function used in arithmetic [-Wpointer-arith]
138 |       char *toencode = (char *)malloc[toencodeLen + 1];
|                                                      ^
cc1plus.exe: warning: pointer to a function used in arithmetic [-Wpointer-arith]
Just CI
Fixes #9007
=> Fixes Malloc call in WebServer code

cores/esp32/IPAddress.cpp, cores/esp32/IPAddress.h
-----------
Update the IPAddress class to support v6 addresses, using the same interface changes as …
=> Add v6 support to IPAddress to match ArduinoCore-API

cores/esp32/esp32-hal-gpio.c, cores/esp32/esp32-hal-gpio.h
This PR adds 2 simple methods to enable/disable GPIOs interrupt.
Tested on C6 and H2 using the Zigbee examples.
=> Add methods to enable/disable GPIOs interrupt

cores/esp32/esp32-hal-gpio.c
Improves the log messages by adding the GPIO number that has triggered the error message for better debugging.
Tested with ESP32-C3.
Fixes #9008
=> Improve Log Messages in GPIO HAL

libraries/WiFi/src/WiFiServer.h
Removes depricated message for WiFiServer::available() to follow Arduino upstream API.
None
None
=> undeprecate WiFiServer::available()

cores/esp32/WString.cpp
The `String::lastIndexOf` incorrectly finds character `\0` behind the string size, so extra check was added.
This pull request fixes the bug in `int String::lastIndexOf(char ch, unsigned int fromIndex) const` function. The bug itself 
is that if the character we are searching is `\0` this function returns an index behind bounds of the string itself.
For example the following code prints that it found it at 4th position (points after the end of the actual string):
```cpp
String test = "test";
int p = test.lastIndexOf('\0');
USBSerial.printf("lastIndexOf: %d\n", p);
```
output:
```
lastIndexOf: 4
```
but it must be `-1` because there is no `\0` character inside the string itself.
I've tested the code on M5Stack-CoreS3 hardware, Arduino-esp32 core v `3.20011.230801` …
=> Fixed the String::lastIndexOf bug

libraries/SD/src/sd_diskio.cpp
SD card formatting in the SD library was broken by #6745. The work buffer for `f_mkfs` was moved from the stack to the heap, but the length argument was not updated, instead it currently passes the size of a pointer (32 bits).
Before my change, `SD.begin` with `format_if_empty` set to true and an erased SD card will always fail with the error `[sd_diskio.cpp:824] sdcard_mount(): f_mkfs failed: (17) LFN working buffer could not be allocated`.
After my change `SD.begin` succeeds and creates a FAT filesystem on the card.
=> SD library: Fix format

cores/esp32/Esp.cpp, cores/esp32/Esp.h
`esp_deep_sleep(uint64_t time_in_us)` takes a 64 bit argument, but `void EspClass::deepSleep(uint32_t time_us)` allows only 32 bit.
This fixes it, for a sleep time over 2,147 seconds (over 36 minutes).
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html#_CPPv414esp_deep_sleep8uint64_t
Just CI.
Fixes #9074
=> Fixes EspClass::deepSleep(64 bits)

libraries/SD/src/sd_diskio.cpp
Fixes bad coding style, possibly due to cut'n paste.
=> sd_diskio.cpp: return 0 instead of false when return type != bool

libraries/ESP32/examples/AnalogRead/AnalogRead.ino
The 12-bit MAX is 4095, not 4096.
-----------
Fixed an incorrect comment.
Confirm that values from 0 to 4095 can be obtained.
=> fix(esp32): Set the maximum value of AnalogRead to 4095

variants/arduino_nano_nora/pins_arduino.h
This PR adds aliases to control the RGB led on the Arduino Nano ESP32 board. On other Arduino boards those pins are named LEDR, LEDG, LEDB. To improve portability amoung the Arduino boards the Arduino Nano ESP32 should support those names.
Tested on Arduino Nano ESP32
=> Add LED pin aliases to Arduino Nano ESP32 for portability

tests/periman/periman.ino, tests/periman/test_periman.py
This PR aims to implement a test for the peripheral manager on the CI.
Tested locally with all DevKits.
=> CI: Add peripheral manager test

docs/en/api/preferences.rst
Addition of documentation for the functions isKey and getType for the Preferences libraries.
These functions were added here https://github.com/espressif/arduino-esp32/pull/4441 but not documented.
I have not tested, no code change only a change in the rst file
Documents PR https://github.com/espressif/arduino-esp32/pull/4441
Adds documentation for issue https://github.com/espressif/arduino-esp32/issues/4440
=> Added isKey and getType methods to Preferences documentation

libraries/FS/src/FSImpl.h
Backport of https://github.com/espressif/arduino-esp32/pull/8768
=> Backport fix linker failure

libraries/LittleFS/src/LittleFS.cpp
when IDF LittleFS is built with Arduino Lib Builder latest LittleFS will be used.
This PR adds the new LittleFS options and inits them, so no warnings will be generated.
Backport from branch master
=> Add and init new LittleFS options

libraries/WebServer/src/WebServer.cpp
Backport of #8667 Saves a few bytes. The changes are minimal and tested over a few months.
=> WebServer: use MD5Builder instead of mbedtls

libraries/WiFi/src/WiFiSTA.cpp, libraries/WiFi/src/WiFiSTA.h
WiFi.disconnect() "aligned with Aduino.cc". 
`WiFi.disconnect` renamed to `disconnectAsync`
new `WiFi.disconnect` waits for `status` change
the WiFi library with async disconnect behaves very strange. after disconnect() and immediate WiFi.begin it can't connect. I had to add a wait for status change after disconnect in my [test sketch](https://github.com/JAndrassy/NetApiHelpers/blob/master/examples/WiFiTest/WiFiTest.ino).
So I think the blocking version of disconnect() is a better option for everybody. It is quick.
=> WiFi.disconnect() "aligned with Aduino.cc". waiting for status change.

cores/esp32/HashBuilder.h, cores/esp32/MD5Builder.cpp, cores/esp32/MD5Builder.h, cores/esp32/SHA1Builder.cpp, cores/esp32/SHA1Builder.h
Propagate 'const' of underlying esp_rom_md5_update() to MD5Builder::add().
Remove some unneeded methods.
=> change(MD5Builder): Const-correctness.

docs/en/api/preferences.rst
This PR to fix a mistake I made while adding documentation for the preference library.
This removes the duplicated getType reference.
See https://github.com/espressif/arduino-esp32/pull/9111 for more details.
=> Fixed duplicated getType documentation.

libraries/LittleFS/examples/LITTLEFS_PlatformIO/littlefsbuilder.py, libraries/LittleFS/examples/LITTLEFS_PlatformIO/platformio.ini
Actual Platformio Platform espressif32 do not need anymore the Python script to build the LittleFS image. 
Use custom partition scheme to guarantee to have a SPIFFS partition which works with the example code.
=> Update LittleFS Platformio example

idf_component.yml
This PR fixes: 
- adding IDF component example (Hello_world) to the ESP Registry.
- issue with no license provided
- adds ReadMe file
Tested by uploading component under personal namespace.
=> IDF Component YAML fixes - Add license, include example + readme in ESP Registry

libraries/WiFi/src/WiFiServer.h
This reverts commit 5d97e02ad777100430dd443ac3e3458e5d5f72df.
As a result of discussion on PR https://github.com/espressif/arduino-esp32/pull/9028 "WiFiServer - implementation aligned with Arduino.cc" this is a PR to mark `server.available` as deprecated.
I also recommend the  PR https://github.com/espressif/arduino-esp32/pull/8930 "WiFiServer - don't inherit from Print and Server"
=> Revert "undeprecate available() (#9027)"

boards.txt, variants/sparkfun_esp32c6_thing_plus/pins_arduino.h
Add new SparkFun ESP32-C6 Thing Plus variant.
Tested with [v3.0.0 Alpha 3 Release](https://github.com/espressif/arduino-esp32/releases/tag/3.0.0-alpha3).
Product is not live yet, but I can update with a link to the product page once it is live if requested!
=> Add SparkFun ESP32-C6 Thing Plus Variant

.github/workflows/allboards.yml, .github/workflows/boards.yml, .github/workflows/build_py_tools.yml, .github/workflows/docs_build.yml, .github/workflows/docs_deploy.yml, .github/workflows/gh-pages.yml, .github/workflows/hil.yml, .github/workflows/lib.yml, .github/workflows/push.yml, .github/workflows/release.yml, .github/workflows/upload-idf-component.yml
Node.js 16 actions are deprecated. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Following actions were updated:
- checkout@v3 -> v4
- cache@v3 -> v4
- setup-python@v4 -> v5
=> [CI] Update workflows actions to latest versions with Node.js 20

boards.txt, variants/nologo_esp32s3_pico/pins_arduino.h
Add board support for [Nologo ESP32S3 Pico](https://www.nologo.tech/product/esp32/esp32s3Pico/esp32S3Pico.html)
I have tested my pr on this board. Verified by compiling and uploading using PlatformIO, cherry-picking the changes onto the v2.0.11 branch.
- https://www.nologo.tech/product/esp32/esp32s3Pico/esp32S3Pico.html
=> Add board support for Nologo ESP32S3 Pico

libraries/WebServer/src/Parsing.cpp
~The form parser has been shown to have issues with files ending with "--\r\n".~ This commit replaces the form parser with the parser from ESP8266, which is simpler and easier to reason about.
=> fix(webserver): Proposal for simplifying webserver file uploads via form POST.

libraries/WiFi/src/WiFiMulti.cpp, libraries/WiFi/src/WiFiMulti.h
Adds the possibility of using hidden networks in WiFiMulti.
Tested using WiFiMulti example with hidden mobile hotspot:
```
[   715][V][esp32-hal-uart.c:396] uartBegin(): UART0 baud(115200) Mode(800001c) rxPin(3) txPin(1)
[   724][V][esp32-hal-uart.c:482] uartBegin(): UART0 not installed. Starting installation
[   734][V][esp32-hal-uart.c:527] uartBegin(): UART0 initialization done.
[   759][I][WiFiMulti.cpp:89] addAP(): [WIFI][APlistAdd] add SSID: Vans
Connecting Wifi...
[   782][D][WiFiGeneric.cpp:1055] _eventCallback(): Arduino Event: 0 - WIFI_READY
[   857][V][WiFiGeneric.cpp:345] _arduino_event_cb(): STA Started
[   864][D][WiFiGeneric.cpp:1055] _eventCallback(): Arduino Event: 2 - STA_START
[  2569][V][WiFiGeneric.cpp:388] _arduino_event_cb(): SCAN Done: ID: 128, Status: 0, Results: …
```
=> Add support for hidden networks in WiFiMulti

libraries/WebServer/src/Parsing.cpp
Backport of #9167
Replaces the form parser with the parser from ESP8266, which is simpler and easier to reason about.
=> Backport: simplifying webserver file uploads via form POST

platform.txt
The Arduino Platform Specification requires that the recipe hooks are distinguished by a number and does not endorse using text labels. Fix all the usages of recipe hooks to use numbers.
As discussed in #9150, closes [arduino/arduino-cli#2369](https://github.com/arduino/arduino-cli/issues/2369) for branch 2.x.
=> fix(platform): use numbers in all recipe hooks (on 2.x)

platform.txt
The Arduino Platform Specification requires that the recipe hooks are distinguished by a number and does not endorse using text labels. Fix all the usages of recipe hooks to use numbers.
As discussed in #9150, closes [arduino/arduino-cli#2369](https://github.com/arduino/arduino-cli/issues/2369) for the master branch (3.0).
=> fix(platform): use numbers in all recipe hooks (on master)

cores/esp32/esp32-hal-spi.h
ESP32-S2 has 3 SPI buses available.
It fixes names and definitons in order to add the 3rd SPI to the list.
It also adds some commentaries in order to help users.
CI Only
Closes #9210
=> SPI (fix): Adds SPI 3 to the ESP32-S2 and adds comments about it

libraries/WebServer/examples/AdvancedWebServer/AdvancedWebServer.ino
This PR resolves an insignificant bug in the `AdvancedWebServer.ino` example, where the uptime is converted from seconds to hours, minutes, seconds format.  
The changes do not affect the overall sketch nor its intended usage.  
Prior to the changes, the reported uptime would be incorrectly going over 60 seconds a minute, and minutes would increase incorrectly.  
For examples:  
```text
0:0:59
0:1:0
0:1:60
0:1:61
0:1:118
0:1:119
0:2:120
0:2:121
```
After these changes, minutes and seconds update as expected.
I have tested my Pull Request on Arduino-esp32 core `v2.0.14` with ESP32 on an `ESP32-Ethernet-Kit_A_V1.2` development board.
Thank you for your time,
Cyril :slightly_smiling_face:
=> Fix AdvancedWebServer.ino uptime conversion

libraries/Update/src/Update.h, libraries/Update/src/Updater.cpp
Fixes issue reported in https://github.com/espressif/arduino-esp32/pull/5807#issuecomment-1935770156
This will work exactly the same for all chips except C2, where it will use the mbedtls functions. In the future we will need to replace mbedtls with something simpler.
=> Fix C2 compilation for Updater.cpp

libraries/BluetoothSerial/src/BluetoothSerial.cpp, libraries/BluetoothSerial/src/BluetoothSerial.h
IDF has changed Serial BT Callback type definition. This PR fixes the Arduino SerialBT API to match new type and function signature.
ESP32 - CI
``` cpp
#include "BluetoothSerial.h"
BluetoothSerial SerialBT;
void callback(esp_spp_cb_event_t event, esp_spp_cb_param_t *param){
if(event == ESP_SPP_SRV_OPEN_EVT){
Serial.println("Client Connected");
}
if(event == ESP_SPP_CLOSE_EVT ){
Serial.println("Client disconnected");
}
}
void setup() {
SerialBT.register_callback(callback);
if(!SerialBT.begin("ESP32")){
Serial.println("An error occurred initializing Bluetooth");
}else{
Serial.println("Bluetooth initialized");
}
}
void loop() {}
```
Closes #9244
=> Fixes Pointer and Call using Serial BT callback

libraries/Ethernet/examples/ETH_LAN8720/ETH_LAN8720.ino, libraries/Ethernet/examples/ETH_TLK110/ETH_TLK110.ino, libraries/Ethernet/examples/ETH_W5500_Arduino_SPI/ETH_W5500_Arduino_SPI.ino, libraries/Ethernet/examples/ETH_W5500_IDF_SPI/ETH_W5500_IDF_SPI.ino
Added check for `ETH_PHY_TYPE` to avoid Ethernet pins redefinition in sketch, if ETH pins are defined in variants `pins_arduino.h`. Also renamed pins defines in examples, to match empales of defines in `ETH.h`.
Compiled all ETH examples + tested variant with ETH pins defined.
Closes #9241
=> Added pin check in ETH examples to avoid redefinition

boards.txt
5. [X] Please **confirm option to "Allow edits and access to secrets by maintainers"** when opening a Pull Request
-----------
The previous board definition `ESP32_DEV` …
=> feat: Rename Firebeetle ESP32 board definition

tools/platformio-build.py
fixes compile and flash of the esp32-h2 with Platformio. Issue #9237 
Needs PR https://github.com/platformio/platform-espressif32/pull/1308
@valeros @me-no-dev
=> Implement `get_board_f_image `

libraries/WebServer/src/Parsing.cpp
This Pull Request provides a fix for the WebServer library to ignore additional headers that may appear in `multipart/form-data` uploads. The current code assumes that `Content-Disposition` headers can only possibly be followed by a `Content-Type` header, and while that is what the standard (RFC7578) intends, it is also required that any other headers be ignored (see related link).
Currently, when extra header(s) are present the WebServer library will fail to properly locate the start of the submitted data. To fix this, the `Content-Type` check is simply wrapped in a `while` loop to skip over any additional headers.
I have tested my Pull Request on Arduino-esp32 core v2.0.11 with an ESP32C3 Dev Module with this scenario:
1. Create a file upload form with the WebServer.
2. Send a POST …
=> WebServer: Ignore extra headers within multipart forms

cores/esp32/io_pin_remap.h, docs/en/migration_guides/2.x_to_3.0.rst
This PR updates and adds the new RMT API `bool rmtSetEOT(int pin, uint8_t EOT_Level);` to the list of MACROS from `io_pin_remap.h`
It also include this new funtion to the Migration Guide documentation.
Just CI.
None
=> Update new RMT function rmtSetEOT(pin, EOT_Level) in the pin remap macros

libraries/ESP32/examples/Time/SimpleTime/SimpleTime.ino
As stated in https://github.com/espressif/arduino-esp32/issues/8661, we have to call `WiFi.mode` before networking.
I've tested my Pull Request on arduino-esp32 v2.0.14 with ESP32-DevKitC-32E Board.
- https://github.com/espressif/arduino-esp32/issues/8661
=> Fixed "Invalid mbox" error in SimpleTime example

cores/esp32/esp32-hal-sigmadelta.c
If a pin is attached to another peripheral and it is latter attached to SigmaDelta, it won't correctly detach the previous peripheral.
This PR fixes it, including when the DeltaSigma frequency is changed.
ESP32
``` cpp
#define PIN 2
void setup() {
// Peripheral Manager will attach pin 2 UART (RX) - TX is the UART0 default pin.
Serial.begin(115200, SERIAL_8N1, PIN);
Serial.println("Serial pins - RX (pin 2) and TX (default) are attached");
delay(1000);
//Peripheral manage will detach pin 2 from UART (TX) and attach it to LEDC
analogWrite(PIN, 100); // by default it will use 1KHz, 8 bits resolution
Serial.println("Pin 2 is attached to LEDC");
delay(5000);
// Peripheral manager will detach pin 2 from LEDC and attach it to SigmaDelta
sigmaDeltaAttach(PIN, 312500);
sigmaDeltaWrite(PIN, 10); …
```
=> Fixes sigmaDeltaAttach() when another peripheral is already attached using the same pin

boards.txt, variants/esp32-gateway/pins_arduino.h, variants/esp32-poe-iso/pins_arduino.h, variants/esp32-poe/pins_arduino.h, variants/esp32-sbc-fabgl/pins_arduino.h, variants/esp32h2-devkit-lipo/pins_arduino.h
Hello!
Olimex employee here.
I have added support for the boards: Olimex ESP32-H2-DevKit-LiPo and ESP32-SBC-FabGL. Added a "pins_arduino.h" files in the "variants" folder and in the board.txt. The boards are open-source hardware and info can be found at our website.
Also for 3 of our existing in your package boards (ESP32-POE, ESP32-POE-ISO, ESP32-Gateway) inside the pins_arduino.h files I added the ethernet macros to match the fix from https://github.com/espressif/arduino-esp32/pull/9242 . 
For ESP32-POE and ESP32-POE-ISO added extra menus and menu options for: PSRAM, Flash Size, Flash mode and Partition scheme.
I tested what I could but let me know if I have missed something and needs further changes.
Thanks espressif and Arduino team.
=> Added support for 2 new Olimex boards and updated 3 existing ones

boards.txt, variants/motorgo_mini_1/pins_arduino.h
Add support for MotorGo Mini 1 motor controller with ESP32-S3.
-----------
Adds a new variant for the MotorGo Mini with an onboard ESP32-S3. Updated boards.txt and created a new variants directory.
Tested the new variant with the Arduino-ESP32Core 2.0.14 running on the MotorGo Mini 1 board. 
[MotorGo Website](https://motorgo.net/)
=> Add support for the MotorGo Mini board

boards.txt
This PR changes default upload speed for NodeMCU32-S board, as the previous default value may not work.
Closess #8320
=> NodeMCU32-S Change default upload speed

libraries/Ethernet/src/ETH.cpp
Requires this commit from ESP-IDF to be cherry picked: https://github.com/espressif/esp-idf/commit/fd0a1dc53c4cff99f04dfe658047f7c2e3e6d8ad
Related discussion: https://github.com/espressif/esp-idf/issues/12682#issuecomment-1914807052
Fixes: https://github.com/espressif/arduino-esp32/issues/9246
=> [Enhancement] Support no-IRQ for SPI Ethernet W5500

idf_component.yml
Was fixed to 1.2.1 before, because of a bug in 1.2.2
=> Update mdns version.

variants/motorgo_mini_1/pins_arduino.h
Changed LED_STATUS pin number to match the latest MotorGo Mini 1 board revision. Due to a communication mistake between me and a teammate, the last PR adding support for the board targeted the wrong board revision. I apologize for the back-to-back PRs :(
Tested this pin definition with Arduino-ESP32Core 2.0.14 running on the MotorGo Mini 1 board (revision 3 - this is the one shipping to consumers). All LEDs turn on as expected.
[MotorGo Website](https://motorgo.net/)
Original PR for MotorGo Mini 1: #9269
=> MotorGo Mini 1 - Update LED_STATUS to match latest board revision

cores/esp32/HWCDC.cpp, cores/esp32/HWCDC.h, libraries/ESP32/examples/HWSerial_Events/HWSerial_Events.ino
Improves the functionality of HW CDC (HW Serial) when CDC is not connected to the Host side. At this point it solves the delay issue only when it is not plugged to the USB port. But even when plugged and the host enumerates it, it still delays when CDC is not connected, causing some side effect.
This PR fixes it and also adds 2 new APIs:
- HWCDC::isConnected() will return true when HWCDC has a CDC connection to an application in the host side (like a serial terminal) and false otherwise.
- HWCDC::isPlugged() will return true when USB is plugged to a USB host and it has enumarated the CDC class.
``` cpp
void setup() {
Serial0.begin(115200);
HWCDCSerial.begin();
Serial0.println("\n ==> Connect to the CDC Serial Terminal\n");
while(!HWCDCSerial) delay(100);
Serial0.println("CDC is connected. …
```
=> fixes default 100ms delay with HWCDC write() is CDC is not connected 

libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h
This PR changes ETH.begin's parameter `phy_addr` from `uint8_t` to `int32_t` to match the `eth_phy_config_t`.
This also enables using `ETH_PHY_ADDR_AUTO` as `phy_addr` in `ETH.begin()` to automatically get the phy address from the chip.
Tested only with SPI Ethernet for now. Will test next week with RMII Ethernet.
Closes #9311
=> ETH: Support physical address auto detection

cores/esp32/HardwareSerial.cpp, cores/esp32/esp32-hal-uart.c
When setting RX buffer, the `setRxBufferSize()` method would fail with values lower than 128 bytes. 
Although it seems what IDF requests, it is not the best way to execute it, because the return value would be zero and the buffer size would be kept the same, by default 256. Now it returns the size it has been set, defining a minimum of 128+1 bytes, as required by IDF UART driver.
By other hand, for TX buffer, the  `setTxBufferSize()` method also fails with less than 128 bytes, returning also 0.
With the change, it will return and set it to 128 (minimum), as requeired by IDF. 
It also changes `availableForWrite()` in order to return a value that matches `setTxBufferSize()` when there is no data to be written, making it possible for applications to better compare and decide when to write to …
=> HardwareSerial Available For Write

cores/esp32/esp32-hal-spi.c
This PR fixes #9221 by forcing SPI clock line to update within `spiTransaction`.
This is especially important when sharing a single SPI bus between devices with different SPI modes.
Notable use case is using SD card (SPI mode 0) and ST7789-based TFT display (mode 3).
Tested with ESP32-C3 SuperMini board.
- #9221
- https://github.com/moononournation/Arduino_GFX/issues/433
=> Fix spiTransaction not updating clock line immediately (#9221)

cores/esp32/esp32-hal-tinyusb.c
Since the include file name changed from `hal/usb_phy_ll.h` to `hal/usb_fsls_phy_ll.h` IDF commit https://github.com/espressif/esp-idf/commit/148cc6e75d6f131deb36bd0a4ffdfbaaa2520520
The PR code change checks if the old file is there if yes it is included else the new file is included.
@me-no-dev
=> Fix compile branch master as Arduino as component with latest IDF 5.1

README.md
This PR aims add a badge to the README file to report the status of the hardware tests
=> Add hardware tests results

cores/esp32/esp32-hal-spi.c
Follow-up PR for #9333 to fix the issue on all chips.
For ESP32 and S2 this fix is not needed.
Tested on all chips.
Related to #9221
=> Fix spiTransaction not updating clock line immediately (C2,C6,H2)

.github/workflows/docs_build.yml, .github/workflows/hil.yml, .github/workflows/lib.yml
V4 uses node 20 and solves the deprecation warning
=> Update upload and download artifact action to v4

libraries/BLE/examples/UART/UART.ino
Fix UART example indentation that was breaking the documentation.
Closes #9320
=> Fix indentation for UART BLE example

cores/esp32/HWCDC.cpp
Fixes (#9316) where ESP may not respond over the USB Serial/JTAG interface if bytes are sent before `HWCDC::begin(...)` is called. Clearing of the interrupt status has been removed from `HWCDC::begin(...)` so that if the `USB_SERIAL_JTAG_INTR_SERIAL_OUT_RECV_PKT` is already set, the isr handler can process the interrupt status correctly.
Tested with ESP32-S3:
``` c++
#include <HWCDC.h>
#include <hal/usb_serial_jtag_ll.h>
#include <string>
uint32_t prevTime = 0;
void setup() {
delay(5000);
Serial.println("begin");
}
void loop() {
if (millis() - prevTime > 500)
{
prevTime = millis();
std::string output;
output += "rxFifo: " + std::to_string(usb_serial_jtag_ll_rxfifo_data_available());
output += " Serial avaliable: " + …
```
=> fix: HWCDC removed clearing USB Serial/JTAG interrupts during begin (#9316)

cores/esp32/esp32-hal-uart.c
Begin() may "undo" a setpins() that has set RTS and/or CTS pin.
As consequence, RTS and CTS won't be detached with end(). 
This pins are only changed by using setPins() passing RTS and CTS.
setpins() can be called after or before begin()
when called before, begin() shall not change those pins.
This PR fixes it.
Tested with ESP32 just checking logs.
``` cpp
void setup() {
Serial.setPins(3, 1, 25, 26); // ESP32 RX, TX, CTS, RTS
Serial.end();  // only detaches RX and TX. CTS and RTS will be -1 after begin() and won't be detached!
}
void loop() {}
```
This changes has been backported to 2.0.15 by #9176
=> HardwareSerial:begin() changes RTS and CTS pins preventing detaching those pins 

cores/esp32/USB.cpp, docs/_static/webusb.html, docs/en/api/usb.rst, libraries/USB/examples/USBVendor/USBVendor.ino, libraries/USB/examples/USBVendor/index.html, libraries/USB/src/USBVendor.cpp, variants/esp32s2usb/pins_arduino.h
Improves USBVendor example by adding the flush method and adding WebUSB console hosted inside the documentation.
Tested with ESP32-S3 DevKit
Closes #8235
=> Improve USBVendor Example

docs/en/guides/docs_contributing.rst
This PR updates the documentation build instructions to the new ones.
=> Fix documentation build instructions

cores/esp32/HWCDC.cpp
Fixes:
- pin number error
- PHY initialization that prevented HW Serial to start correctly and get enumerated after end() or detaching pins
- crash after executing end() 
- force USB Host enumeration in order to set the right state to detect first time sending data to the HOST (CDC Connection) 
Tested with ESP32-C3, ESP32-S3, ESP32-C6, ESP32-H2
``` cpp
// HW Serial CDC mode with CDC on boot enabled
void setup() {
Serial.begin();
Serial.end();
Serial.begin();
// waits until Serial Monitor is open
while (!Serial) delay(100);
Serial.println();
Serial.println("Started!");
Serial.println("");
}
void loop() {
Serial.println("loop...");
delay(1000);
}
```
Fixes #9360
=> Fixes HW Serial attaching pins, PHY initialization, crash after end()

cores/esp32/esp32-hal-rgb-led.c
When writing to the same GPIO using RMT, like in a loop, it is necessary to use `rmtWriteBlocking()` instead of `rmtWrite()` to avoid issues with FreeRTOS and IDF 4.4.x.
This PR fixes `neopixelWrite()` (as well as digitalWrite(RGBLED, state)`) in order to avoid such issue.
Tested with ESP32-S3
``` cpp
void setup() 
{
Serial.println("");
Serial.println("");
}
void loop() 
{
Serial.println("blink slow");
for (auto i = 0; i < 10; i++)
{
digitalWrite( LED_BUILTIN, i & 1 );
//uint8_t color = i & 1 ? 32 : 0;
//neopixelWrite( 48, color, color, color);  // 47 is Lolin S3 onboard LED
delay(100);
}
Serial.println("blink fast");
for (auto i = 0; i < 10; i++)
{
digitalWrite( LED_BUILTIN, i & 1 );
//uint8_t color = i & 1 ? 32 : 0;
//neopixelWrite( 48, color, color, color);
}
} …
```
=> Fixes issue related to writing RGB LED fast in a row

cores/esp32/HardwareSerial.cpp
UART0 pins are set by ROM Boot to default values. 
This must be reflected into Arduino HardwareSerial in order to allow it to correctly detach it and then attach it to something else.
Summary:
UART0 constructor sets default RX/TX pins as done in boot time.
Tested with DevKits ESP32, ESP32-S3, ESP32-S2.
``` cpp
// necessary to crossconnect 
// TX0(4) <--> Original TX pin, in order to see the output in the Serial Monitor - testing TX0 pin
// RX0(2) <--> TX1(17) for testing RX0 pin
void setup() {
Serial.begin(115200, SERIAL_8N1, 2, 4); // rx0, tx0
Serial1.begin(115200, SERIAL_8N1, 16, 17); // rx1, tx1
}
void loop() {
Serial.println("Loop from UART0...");
delay(1000);
Serial1.println("Loop from UART1...");
delay(1000);
while(Serial.available()) Serial.write(Serial.read());
delay(1000);
}
``` …
=> fix: UART0 boot pin setup

tools/platformio-build.py
makes speed setting of 120Mhz possible. Needs Platformio PR https://github.com/platformio/platform-espressif32/pull/1331 merged first!
Edit: PR upstream is merged
Fixes https://github.com/espressif/arduino-esp32/issues/9351
=> Platformio add `f_boot` to build script

.github/scripts/find_all_boards.sh, cores/esp32/io_pin_remap.h, variants/imbrios-logsens-v1p1/pins_arduino.h
This PR contain fixes needed for CI to pass compilation test on all boards.
Test results: https://github.com/P-R-O-C-H-Y/arduino-esp32/actions/runs/8326763069 
Fixing:
- ESP32-C2 removed from all-boards-test
- IO remapping fixed for SPI, as the pin is no longer needed to detach pin
- #3880 collision of `SPI_SS1` with `#define SPI_SS1` in esp32-hal-spi.h. Renamed to `SS1`.
=> Fixes for some boards which are failing CI test.

cores/esp32/MacAddress.cpp, cores/esp32/MacAddress.h
Adds MacAddress object constructor from String.
Tested in future ESP NOW example
=> Add MacAddress string constructor

boards.txt, cores/esp32/HWCDC.cpp, variants/waveshare_esp32s3_touch_lcd_128/pins_arduino.h
Adding variant for Waveshare ESP32-S3-Touch-LCD-1.28 board containing MCU, LCD, and IMU.
Untested, pin definition is based on information in Waveshare wiki.
Link to board wiki: https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-1.28
=> Add variant for Waveshare ESP32-S3-Touch-LCD-1.28

libraries/WiFi/src/WiFiGeneric.cpp, libraries/WiFi/src/WiFiGeneric.h
Adds method to set the WiFi radio channel. This will be useful for applications that need to set the wifi channel without connecting to anything, like ESP-NOW.
=> Add method to set the WiFi radio channel

libraries/ESP32/examples/Serial/onReceiveExample/onReceiveExample.ino
Adds a new example that uses HardwareSerial::onReceive(). The example demosntrates how to read all the data sent to UART0, considering that the end of transmission is defined by a period of time with UART in idle state.
This PR adds a new example that uses HardwareSerial::onReceive().
The example demosntrates how to read all the data sent to UART0, considering that the end of transmission is defined by a period of time with UART in idle state.
This is based on a question from a user.
Tested using the code from the example with the ESP32, ESP32-S3 and ESP32-C3.
https://github.com/espressif/arduino-esp32/issues/6102#issuecomment-2009207450
=> Adds a new example: onReceiveExample.ino

libraries/WiFi/src/WiFiSTA.cpp
I have tests as examples in the NetAPIHelpers library. You can run them too to avoid these kind of simple bugs.
The NetAPIHelpers library is in the Library Manager.
=> WiFi BSSID getter fix

libraries/Network/src/NetworkInterface.cpp, libraries/WiFi/src/AP.cpp, libraries/WiFi/src/STA.cpp, libraries/WiFi/src/WiFiAP.h, libraries/WiFi/src/WiFiGeneric.cpp, libraries/WiFi/src/WiFiSTA.h
After the network refactoring, WiFi.mode would not properly init the interfaces and events would be lost.
cc @Jason2866 @s-hadinger
=> Use WiFi.mode to enable/disable the Network Interfaces

libraries/WiFi/src/WiFiSTA.cpp, libraries/WiFi/src/WiFiSTA.h
repeat of https://github.com/espressif/arduino-esp32/pull/8892 rebased after networking refactoring.
In WiFi libraries by Arduino `config` has parameters `ip, dnsIP, gatewayIP, subnet`. only ip is not optional. for unspecified subnet default is 255.255.255.0 and unspecified gateway and dns are based on IP with last number changed to 1.
the ESP8266WiFi library accepts the 'esp\ ordering ip, gw, subnet, dns and Arduino ordering ip, dns, gw, subnet. The detection is based on the position of the subnet mask which has 255 as first number.
This PR adds handling of Arduino ordering of parameters. Parameter subnet is on position of dns1 which is an optional parameter so default value is used if needed.
And this PR adds a second `config` with two parameters local_ip and dns IP. dns IP is optional. …
=> WiFi.config handle Arduino parameters ordering and auto dns,gw,mask

libraries/Ethernet/src/ETH.cpp, libraries/Network/src/NetworkInterface.cpp, libraries/Network/src/NetworkInterface.h, libraries/WiFi/src/STA.cpp, libraries/WiFi/src/WiFiSTA.cpp
Closes: https://github.com/espressif/arduino-esp32/issues/9435
=> Ensure that Static IP configuration for network interfaces is kept until STOP

cores/esp32/Server.h
the Server class is now not used in NetworkServer. it is in the core only for external libraries like the Arduino Ethernet library, so it should be compatible with them. (optionality of the parameter doesn't apply when matching implementation of virtual function )
https://github.com/arduino-libraries/Ethernet/issues/88
https://github.com/arduino/ArduinoCore-API/blob/master/api/Server.h
=> core Server class back to Arduino Core API version

libraries/Update/src/HttpsOTAUpdate.h, libraries/Update/src/Update.h, libraries/Update/src/Updater.cpp
Adjust Update Library license.
The same as #9446 but for 2.x release
N/A
Internal
=> Adjust Update Library license

libraries/Network/src/NetworkEvents.cpp, libraries/Network/src/NetworkEvents.h, libraries/Network/src/NetworkInterface.cpp, libraries/Network/src/NetworkManager.cpp, libraries/Network/src/NetworkManager.h, libraries/WiFi/src/WiFiGeneric.cpp, libraries/WiFi/src/WiFiGeneric.h
5. [X] Please **confirm option to "Allow edits and access to secrets by maintainers"** when opening a Pull Request
-----------
Allows dual-stack networks to connect to …
=> Network refactoring - fix some IPv6 DNS issues

libraries/Network/src/NetworkManager.cpp
Fixes "missing initializer" warnings for the NetworkManager
```
/home/lucassvaz/Arduino/hardware/espressif/esp32/libraries/Network/src/NetworkManager.cpp: In member function 'int NetworkManager::hostByName(const char*, IPAddress&)':
/home/lucassvaz/Arduino/hardware/espressif/esp32/libraries/Network/src/NetworkManager.cpp:73:5: warning: missing initializer for member 'addrinfo::ai_flags' [-Wmissing-field-initializers]
73 |     };
|     ^
/home/lucassvaz/Arduino/hardware/espressif/esp32/libraries/Network/src/NetworkManager.cpp:73:5: warning: missing initializer for member 'addrinfo::ai_protocol' [-Wmissing-field-initializers]
/home/lucassvaz/Arduino/hardware/espressif/esp32/libraries/Network/src/NetworkManager.cpp:73:5: warning: missing initializer for member 'addrinfo::ai_addrlen' …
```
=> Fix NetworkManager compilation warning

libraries/ESP_NOW/examples/ESP_NOW_Broadcast_Master/ESP_NOW_Broadcast_Master.ino, libraries/ESP_NOW/examples/ESP_NOW_Broadcast_Slave/ESP_NOW_Broadcast_Slave.ino, libraries/ESP_NOW/examples/ESP_NOW_Network/ESP_NOW_Network.ino, libraries/ESP_NOW/examples/ESP_NOW_Serial/ESP_NOW_Serial.ino, libraries/ESP_NOW/src/ESP32_NOW.h
Fixes issues in ESP-Now examples. Also improve log messages for the lib.
Tested all examples
Fixes for #9395
=> ESP-NOW: Fix examples and improve logging

libraries/WiFi/src/AP.cpp, libraries/WiFi/src/WiFiAP.cpp, libraries/WiFi/src/WiFiAP.h
For example to start the AP with WPA3 auth:
```cpp
WiFi.softAP(WiFi.getHostname(), "password", 1, 0, 4, false, WIFI_AUTH_WPA3_PSK, WIFI_CIPHER_TYPE_CCMP);
```
closes: https://github.com/espressif/arduino-esp32/issues/8451
=> Add option to specify AP auth mode and cipher

docs/en/migration_guides/2.x_to_3.0.rst, libraries/Network/src/NetworkClient.cpp, libraries/Network/src/NetworkClient.h, libraries/Network/src/NetworkUdp.cpp, libraries/Network/src/NetworkUdp.h, libraries/WiFi/examples/WiFiIPv6/WiFiIPv6.ino
this is a repeat of https://github.com/espressif/arduino-esp32/pull/8871 after networking refactoring.
With a major version release the `flush()` dilemma could be resolved for WiFiClient & co. as last on this platform.
I renamed the flush which cleared the rx buffer to `clear()`. but flush is pure virtual in Client so I had to add empty `flush()`
The position of the function in file is to group Print (write) related and Stream (read) related functions.
If Arduino adds to Stream class a method to clear the input buffer, it will be most probably named clear() because Stream is taken from Processing and there it has clear().
I [analyzed the API](https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md) of 18 Arduino networking libraries. ESP32 is the only one with …
=> WiFiClient - rename flush() to clear()

libraries/Network/src/NetworkInterface.cpp, libraries/Network/src/NetworkInterface.h
Provides better automation for setting IP/DNS
example `Serial.println(Network);`
```
sta: <UP,nbis-test,CH:8,RSSI:-50,N,WPA_WPA2_PSK> (DHCPC_OFF,GARP,IP_MOD,V6_REP)
ether 30:C6:F7:F4:2F:8C
inet 192.168.254.7 netmask 255.255.255.0 broadcast 192.168.254.255
gateway 192.168.254.1 dns 192.168.254.3
inet6 fe80::32c6:f7ff:fef4:2f8c%st3 type LINK_LOCAL
ap: <UP,esp32-F42F8C,CH:1,OPEN,STA:0> (DHCPS,AUTOUP)
ether 30:C6:F7:F4:2F:8D
inet 192.168.4.1 netmask 255.255.255.0 broadcast 192.168.4.255
gateway 192.168.4.1 dns 0.0.0.0
inet6 fe80::32c6:f7ff:fef4:2f8d%ap2 type LINK_LOCAL
*eth0: <UP,100M,FULL_DUPLEX,AUTO,ADDR:0x1> (DHCPC,GARP,IP_MOD)
ether 32:C6:F7:F4:2F:8C
inet 192.168.254.22 netmask 255.255.255.0 broadcast 192.168.254.255
gateway 192.168.254.1 dns 192.168.254.3
inet6 …
```
=> feat(net): Add support for esp_netif flags

libraries/WebServer/examples/UploadHugeFile/README.md, libraries/WebServer/examples/UploadHugeFile/UploadHugeFile.ino, libraries/WebServer/src/Parsing.cpp, libraries/WebServer/src/WebServer.cpp, libraries/WebServer/src/WebServer.h, libraries/WebServer/src/detail/RequestHandler.h, libraries/WebServer/src/detail/RequestHandlersImpl.h
In scenarios where the request body size exceeds the available RAM, the ESP fails to allocate sufficient memory to process the request in one go.
Now, when the "Content-Type" of the request is "application/octet-stream", it will attempt to call the "ufn" function of the handler, similar to how it handles multipart requests.
**Code Example:**
```cpp
server.on(uri, HTTP_PUT, finalCallback, [](){
HTTPRaw raw = server.raw();
if (raw.status == RAW_START) {
...
} else if (raw.status == RAW_WRITE) {
...
} else if (raw.status == RAW_END) {
...
}
});
```
=> Handle large octet-stream

libraries/SD/src/sd_diskio.cpp
This PR fixes SPI SD card thread-safe issue.
Tested with SPI TFT and SD card on ESP32.
Closes #9438
=> fix(sd): AquireSPI lock in sdcard_uninit

libraries/SD/src/sd_diskio.cpp
This PR fixes SPI SD card thread-safe issue.
=> Backport for v2.x : fix(sd): AquireSPI lock in sdcard_uninit

libraries/NetworkClientSecure/src/ssl_client.cpp
Update ssl_client.cpp to support IPv6 addresses. The change is similar to the code in NetworkClient.cpp, checking the family of the passed in address and configure the socket and socket address accordingly, for either IPv6 or IPv4 as specified in the address.
Tested with M5Stack Core 2, using the following PlatformIO configuration and the test app from https://github.com/sgryphon/iot-demo-build/tree/main/m5stack/m5unified_wifi_https
```
platform = https://github.com/sgryphon/platform-espressif32.git#sgryphon/add-esp32-arduino-libs
platform_packages = 
platformio/framework-arduinoespressif32-libs @ https://github.com/sgryphon/esp32-arduino-libs.git#sgryphon/test-fix-ipv6-lwip-and-config
platformio/framework-arduinoespressif32 @ https://github.com/sgryphon/arduino-esp32.git#sgryphon/sslclien …
```
=> fix(tls): Enable IPv6 support in ssl_client connect

libraries/USB/src/USBHIDKeyboard.cpp
Fixes key modifier bitmap when using `USBHIDKeyboard::pressRaw(uint8_t k)` and `USBHIDKeyboard::releaseRaw(uint8_t k)`.
The modifiers are marked in a bitmap in the HID Report Descriptor. 
```
Bit:        7   6   5   4   3   2   1   0
+---+---+---+---+---+---+---+---+
Byte 0    | RG| RA| RS| RC| LG| LA| LS| LC|  Modifier bits (LC=Left Control, LS= Left Shift, etc)
+---+---+---+---+---+---+---+---+
Byte 1    |        Reserved byte          |
+---+---+---+---+---+---+---+---+
Byte 2    |        Key 1                  |
+---+---+---+---+---+---+---+---+
Byte 3    |        Key 2                  |
+---+---+---+---+---+---+---+---+
Byte 4    |        Key 3                  |
+---+---+---+---+---+---+---+---+
Byte 5    |        Key 4                  |
+---+---+---+---+---+---+---+---+
Byte 6 …
```
=> fix: USB HID Keyboard raw report

libraries/Ethernet/src/ETH.cpp
-----------
With Olimex POE board and latest Core3, …
=> fix(ethernet): move event listener earlier to avoid missing event `ETH_CONNECTED`

libraries/WebServer/examples/UploadHugeFile/README.md, libraries/WebServer/examples/UploadHugeFile/UploadHugeFile.ino, libraries/WebServer/src/Parsing.cpp, libraries/WebServer/src/WebServer.cpp, libraries/WebServer/src/WebServer.h, libraries/WebServer/src/detail/RequestHandler.h, libraries/WebServer/src/detail/RequestHandlersImpl.h
In scenarios where the request body size exceeds the available RAM, the ESP fails to allocate sufficient memory to process the request in one go.
Now, when the "Content-Type" of the request is "application/octet-stream", it will attempt to call the "ufn" function of the handler, similar to how it handles multipart requests.
**Code Example:**
```cpp
server.on(uri, HTTP_PUT, finalCallback, [](){
HTTPRaw raw = server.raw();
if (raw.status == RAW_START) {
...
} else if (raw.status == RAW_WRITE) {
...
} else if (raw.status == RAW_END) {
...
}
});
```
=> Handle large octet-stream (master branch)

libraries/PPP/src/ppp.c
when no PPP support is enabled.
@me-no-dev
=> LWIP_PPP: Fix compilation 

libraries/Network/src/NetworkManager.cpp
On top of the IPv6 change to use `getaddrinfo()`, this implements a fix for IPv6-only networks by checking if we have an IPv6 public scope address, and if we do then check IPv6 first.  If there is no IPv6-address, or we are on an IPv4-only network, then the change has no effect.
By checking IPv6 first when available, it allows devices to work across all network types -- IPv4-only, IPv6-only, and dual stack, connecting to all destination types -- IPv4-only, IPv6-only, and dual-stack servers.
Previously, while IPv6-only to IPv6-only worked, trying to connect from IPv6-only to dual stack (including DNS64) did not work, as the IPv4 address was always returned (and unreachable).
Note that this change does not do much unless IPv6 is enabled (Libs change): it will simply change the dual-stack …
=> Fix IPv6-only DNS by checking IPv6 first if have a public scope address

docs/en/migration_guides/2.x_to_3.0.rst
Add note to the migration guide about default pin changes for UART. Also fix some formatting issues.
=> feat(doc): Add note about default pin changes to migration guide

tests/touch/touch.ino
Some tests are failing due to the reading of the touch pad being lower than the test allows.
This PR changes the test value to allow for more variance.
CI HIL Tests.
=> ci(touch_test): Change released test value for ESP32

.github/workflows/publishlib.yml, .github/workflows/publishsizes.yml
This PR adds a new workflow `Sizes Results`, which is used for printing the results to the PR as a GitHub-bot.
Also fixes External libs Results workflow to not need the event-file, which is causing issues. 
Tested on my fork.
=> [CI] Add Sizes Results workflow + fix of External lib results

package/package_esp32_index.template.json
```
lib-builder: feature/ppp_modem_support 3e386d3
esp-idf: c432c692fa
arduino: feature/ppp_after_linter eed6c578
tinyusb: master e54023d76
espressif__esp-dl:
espressif__esp-dsp: 1.4.12
espressif__esp-nn: 1.0.2
espressif__esp-sr: 1.7.0
espressif__esp-tflite-micro: 1.2.0
espressif__esp-zboss-lib: 1.2.3
espressif__esp-zigbee-lib: 1.2.3
espressif__esp32-camera:
espressif__esp_diagnostics: 1.1.0
espressif__esp_insights: 1.1.0
espressif__esp_modem: 1.1.0
espressif__esp_rainmaker: 1.1.0
espressif__esp_schedule: 1.1.1
espressif__esp_secure_cert_mgr: 2.4.1
espressif__json_generator: 1.1.2
espressif__mdns: 1.3.0
espressif__qrcode: 0.1.0~2 …
```
=> IDF c432c692fa

cores/esp32/esp32-hal-adc.c, cores/esp32/esp32-hal-adc.h, docs/en/api/adc.rst, libraries/ESP32/examples/AnalogReadContinuous/AnalogReadContinuous.ino, tests/periman/periman.ino
Fixed typo in adc_continuous_data typedef
A simple typo adjustment. It's impact is more clarity when developing. Less distraction.
Tested on ESP32-S3 while using ADC Continuous Mode to read off 4 pins at a time continuously while utilizing ISR after each conversion. Very close scenario to the example scenario.
It's just a typo.
=> Fixed typo for adc_continuous_data typedef in esp32-hal-adc.h/.c

.github/workflows/lib.yml
Add concurrency groups to external libs testing to avoid CI hogging.
CI
=> ci(libs): Add concurrency group to external libs test

.github/scripts/on-release.sh
Last few release JSONs were broken. We are halting their auto-upload until the issues are fixed. JSONs will be manually vetted and uploaded to gh-pages
=> fix(release): Temporary halt JSON uploads on release, until generator is fixed

libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h
in Ethernet library adds MAC address parameter for internal  beginSPI and `friend class EthernetClass` to access it.
Meant as support for potential Arduino API compatibility layer.
this replaces PR https://github.com/espressif/arduino-esp32/pull/9522
=> Ethernet - MAC address parameter for beginSPI

cores/esp32/esp32-hal-uart.c, cores/esp32/esp32-hal-uart.h
Changed the parameter types of `rx_buffer_size` and `tx_buffer_size` in the incoming parameters of the `uartBegin` function from `uint16_t` to `uint32_t`, which solved 2 issues:
- When setting a tx / rx buffer larger than 65535 bytes, the function returns normally without warning, but the actual buffer is not the same as the one set by the user.
- Be able to use tx / rx buffer which larger than 65535 bytes.
- Arduino IDE 2.3.2 Linux_64
- ESP32S3
The `uart_driver_install` function accepts incoming tx / rx buffer size parameters of type `int`: https://github.com/espressif/esp-idf/blob/636ff35b52f10e1a804a3760a5bd94e68f4b1b71/components/esp_driver_uart/include/driver/uart.h#L113
=> Fix hal-uart truncated tx/rx buffer size (uint16_t -> uint32_t)

cores/esp32/HardwareSerial.cpp
Changes from Warning to Verbose UART event warnings in order to make debugging easier, specially with UART BREAK.
Affected Events: BREAK, parity error, frame error.
CI Only.
Fix #9551
=> Change log level of UART events

cores/esp32/HWCDC.cpp, cores/esp32/HWCDC.h
Ports many changes, fixes and improvements made in 2.0.15:
- correct use of timeout
- avoids problems with CDC ISR not reading data
- fixes problems with transmiting many bytes to USB Host
- changes how USB SOF and CDC connection is detected
- improves flushing TX data, forcing a FIFO policy when overfow is detected
TBD 
Fixes #9545
=> feat (hwcdc): ports changes made in 2.0.15

docs/en/migration_guides/2.x_to_3.0.rst
Add section in the migration guide for build system and add note about the "Extra Flags" change.
Closes #9562 
Closes #9566
=> docs(flags): Add build system breaking changes to migration guide

Kconfig.projbuild
Fixes: https://github.com/espressif/arduino-esp32/issues/9556
=> fix(config): Fix wrong names in Kconfig that cause Network and NetworkClientSecure to fail

libraries/WebServer/src/Parsing.cpp
defines constant array as to strings as static const so that it moves from RAM to Flash
I have tested this using Arduino-esp32 core v2.0.16 running FluidNC - http://wiki.fluidnc.com/
This should be cherry-picked into the v2.0.x branch
=> fix(RAM): define HTTP_METHOD_STR as static const to save RAM

.github/scripts/tests_run.sh, .github/workflows/hil.yml, .github/workflows/wokwi.yml, tests/validation/touch/touch.ino
Fix uploading artifacts when not existing for Testing workflow.
Added SOC skip files to test that should skip.
=> ci(hil): Touch skip file when platform is skipped

libraries/EEPROM/src/EEPROM.cpp, libraries/EEPROM/src/EEPROM.h
-----------
Added new function "bool isDirty()" to EEPROM.h and EEPROM.cpp
In Deep-Sleep sensor EUTs where data is initially stored in rtc-memory, before being intermittently transferred to EEPROM, it is very useful to know if the EEPROM is dirty [function “EEPROM.isDirty()”], so that if so you can transfer the rtc-memory-data into the EEPROM before doing an “EEPROM.commit()”.
See https://github.com/espressif/arduino-esp32/issues/9589
I have tested my Pull Request on Arduino-esp32 (github as at 10May24) with ESP32 and ModeMCU-32S Board with this scenario.
Closes https://github.com/espressif/arduino-esp32/issues/9589
=> Arduino core for the esp32 - Add new function "bool isDirty()" to EEPROM.h and EEPROM.cpp

variants/Geekble_ESP32C3/pins_arduino.h
I2C pin are relocated for arduino nano compatability
Tested with I2C ADC Modules.
https://github.com/SooDragon/GeekbleMini-ESP32C3
=> fix: I2C pin are relocated for arduino nano compatability

libraries/BLE/src/BLEAdvertising.h
-----------
Fix minor spelling mistake in setScanFilter Parameter. 
Issue is only in .h file, not .cpp file
No tests changed
no links relevant
=> BLEAdvertising.h: Fix spelling mistake in setScanFilter parameter

variants/esp32-gateway/variant.cpp
Hello guys,
Olimex employee here. We received feedback from customers about some noise in Olimex ESP32-GATEWAY design. We did own tests and confirmed there is some noise coming from the GPIO pin we use to feed the clock to the Ethernet. This is GPIO17. It appears all GPIO strength is set to the maximum level 3 - 20mA. Reducing the Ethernet clock GPIO signal strength reduces the noise a lot. There is no benefit for Ethernet clock GPIO to be at max strength for our boards with Ethernet. Reducing the strength of that pin has only benefits for our ESP32-GATEWAY design.
The addition applies only to ESP32-GATEWAY in the folder of its variant we've added a cpp file with GPIO_DRIVE_CAP_0 for GPIO17. Let me know if something is not done properly.
Thanks for your work.
=> Reduced GPIO17 (Ethernet clock GPIO) signal strength to reduce noise. 

cores/esp32/IPAddress.h
Fixes: https://github.com/espressif/arduino-esp32/issues/9630
=> fix(net): Add back the friend classes required for Ethernet.h to work

cores/esp32/esp32-hal-uart.c
Fixes a log that uses a NULL pointer.
CI only.
Fix #9634
=> Fixes log with NULL ptr

libraries/NetworkClientSecure/src/NetworkClientSecure.cpp, libraries/NetworkClientSecure/src/NetworkClientSecure.h, libraries/NetworkClientSecure/src/ssl_client.cpp, libraries/NetworkClientSecure/src/ssl_client.h
The PR has 3 fixes for NetworkClientSecure
1) buffer to store the peeked byte is moved into the shared objects to be shared between NetworkClientSecure copies
2) last error code is moved into the shared objects to be available in all copies
3) NetworkClientSecure::_timeout shadowed NetworkClient::_timeout and then NetworkClient::setConnectionTimeout didn't set the timeout for NetworkClientSecure
test (to test the last error change port to 80)
```
#include <WiFi.h>
#include <WiFiClientSecure.h>
const char *ssid = "yourssid";
const char *password = "yourpasswd";
const char* server = "example.com";
WiFiClientSecure connect() {
WiFiClientSecure client;
client.setInsecure();
Serial.println("Starting connection to server...");
if (client.connect(server, 443)) {
Serial.println("connected to …
```
=> NetworkClientSecure - copyability improvements and _timeout shadowing fixed

libraries/WiFi/src/STA.cpp, libraries/WiFi/src/WiFiSTA.cpp, libraries/WiFi/src/WiFiSTA.h
Fixes: https://github.com/espressif/arduino-esp32/issues/7915
=> Add support for specifying a WPA2 EAP-TTLS phase 2 method to WiFi.begin

boards.txt, libraries/ESP32/examples/Zigbee/Zigbee_Light_Bulb/README.md, libraries/ESP32/examples/Zigbee/Zigbee_Light_Bulb/Zigbee_Light_Bulb.ino, libraries/ESP32/examples/Zigbee/Zigbee_Light_Switch/README.md, libraries/ESP32/examples/Zigbee/Zigbee_Light_Switch/Zigbee_Light_Switch.ino, libraries/ESP32/examples/Zigbee/Zigbee_Temperature_Sensor/README.md, libraries/ESP32/examples/Zigbee/Zigbee_Temperature_Sensor/Zigbee_Temperature_Sensor.ino, libraries/ESP32/examples/Zigbee/Zigbee_Thermostat/README.md, libraries/ESP32/examples/Zigbee/Zigbee_Thermostat/Zigbee_Thermostat.ino
This PR fixes existing Zigbee examples as there were several changes in the `esp-zigbee-sdk` and also removes Zigbee trace which is not included in the build anymore.
=> Zigbee examples update

libraries/Ethernet/src/ETH.cpp
This is to ensure that stack events are called before ours, because callbacks are called in order of attaching
=> fix(eth): Attach ETH events at the correct place

libraries/Ethernet/src/ETH.h
This PR enables ETH_SPI_SUPPORTS_NO_IRQ to support connection by only 4 wires (SCK, MISO, MOSI and SS) with IRQ and RESET being set as -1
=> feat(eth): Enable the possibility to use SPI ETH with only 4 wires

libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h
Fixes: https://github.com/espressif/arduino-esp32/issues/9655
=> fix(eth): Fix ETH.end()

cores/esp32/HWCDC.cpp, cores/esp32/USBCDC.cpp, cores/esp32/esp32-hal-uart.c, libraries/ESP32/examples/HWCDC_Events/HWCDC_Events.ino
This PR is a backport of #9628
- Fixes HW CDC uploading issue using the HWSerial/JTAG port.
- Changes SOF detection from ISR to Timer routine instead 
- Uses correct logging functions in order to separate UART from USB CDC, always closing one or the other whenever one of them is selected using `setDebugOutput(bool)` method.
- Fixes a warning about `%ld` versus `%d` in the `HWCDC_Events.ino` example. 
Tested for ESP32-S3 and ESP32-C3 using the `HWCDC_Events.ino` example.
Tested also for ESP32-S3, ESP32-C3 and ESP32-S2 for chekcing that the `log_XX()` functions work correctly.
Fix #9646 
Fix #9580
=> feat(hwcdc): Fixes HWCDC fw uploading

boards.txt
Recent debug support commits added the `programmer.default` entry for the Nano ESP32 on 2.0.x releases.
Setting that parameter has unfortunately multiple effects:
- sets the tick by default in the Tools->Programmer menu in the IDE (which was the reason for the added line), but also...
- forces the CLI to use the specified programmer _every time an upload is attempted_ (which is confusing users, since they don't get the DFU upload they expect).
For this reason, it is better to remove the `programmer.default` setting from the board definition and let the user choose the programmer in the IDE menus, as it was before.
Behavior observed on latest Arduino IDE and CLI.
Arduino forum thread: https://forum.arduino.cc/t/arduino-cli-and-nano-esp32-cant-upload/
Same PR for main branch: #9666
=> Nano ESP32: delete `programmer.default` entry (on 2.0.x)

boards.txt
Recent debug support commits added the `programmer.default` entry for the Nano ESP32 on main branch.
Setting that parameter has unfortunately multiple effects:
- sets the tick by default in the Tools->Programmer menu in the IDE (which was the reason for the added line), but also...
- forces the CLI to use the specified programmer _every time an upload is attempted_ (which is confusing users, since they don't get the DFU upload they expect).
For this reason, it is better to remove the `programmer.default` setting from the board definition and let the user choose the programmer in the IDE menus, as it was before.
Behavior observed on latest Arduino IDE and CLI.
Arduino forum thread: https://forum.arduino.cc/t/arduino-cli-and-nano-esp32-cant-upload/
Same PR for `releases/v2.x`: #9665
=>  Nano ESP32: delete `programmer.default` entry (on main) 

Kconfig.projbuild
Fix selective compilation to include LittleFS library when checked in menu.
*This entire section above can be deleted if …
=> Update Kconfig.projbuild to fix LittleFS selective compilation

docs/en/api/ledc.rst
Small fix in the API documentation. The function `ledcWrite` returns a boolean, not void. 
The documentation already states that:
"This function will return true if setting duty is successful. If false is returned, error occurs and duty was not set." 
I've double checked that in the header file (cores/esp32/esp32-hal-ledc.h). The return value is indeed a boolean.
However, the function signature was inconsistent with this behavior:
`void ledcWrite(uint8_t pin, uint32_t duty);`
The signature was corrected in this patch:
`bool ledcWrite(uint8_t pin, uint32_t duty);`
=> docs(ledc.rst):Fixed outdated function signature (ledcWrite)

cores/esp32/esp32-hal-adc.c
This PR fixes ADC Continuous channel number limit for S2/S3, where there are 10 channels per ADC peripheral.
Credits to @victorfleischauer
Tested on esp32-s3
Closes #9676
=> fix(adc): Remove masking for ADC channel number

cores/esp32/esp32-hal-log.h
The ESP-IDF logging library has some nice features such as log forwarding. esp32-hal-log.h has long supported the `USE_ESP_IDF_LOG` macro, but due to subsequent changes, it requires a global `TAG` preprocessor macro to be defined. The macro name is too generic and just having a sane default would be preferable.
This PR changes the default tag macro name to `ARDUHAL_ESP_LOG_TAG` and, if it's not defined, sets it to `"ARDUINO"`.
I wasn't able to build arduino-esp32 master. Instead, I copied the file to Arduino-ESP32 Core v2.0.16 as provided by PlatformIO's `framework-arduinoespressif32` framework package. Test hardware was SH-ESP32 and HALMET (compatible with esp32 devkit devices).
With the change applied, logging works as expected both when `USE_IDF_LOG` is set and when it isn't.
Please …
=> fix(esp-hal-log):Provide a default TAG name for USE_ESP_IDF_LOG logging macro

.github/scripts/merge_packages.py
Use packaging.version instead of the deprecated distutils.version
=> fix(release): Update merge_package.py

.github/scripts/tests_run.sh, .github/workflows/hil.yml, .github/workflows/wokwi.yml
Fix Wokwi infrastructure issues by self hosting its CLI server.
Tested in local fork
=> ci(wokwi): Self host Wokwi CLI server

idf_component.yml
Fixes the issue, where the component is shown as compatible with ESP-IDF 5.2, while in fact isn't.
cc: @igrr
=> fix(IDF): Define max IDF version for the component

.github/workflows/lib.json
Add library "ZACwire" to External libraries compilation test
=> ci(external_libs): Add ZACwire to External libraries compilation test

libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h, libraries/Network/src/NetworkInterface.cpp, libraries/PPP/src/PPP.cpp, libraries/WiFi/src/AP.cpp, libraries/WiFi/src/STA.cpp
Unregister IP events only if all other netifs are stopped.
cc: @JAndrassy
=> fix(net): Don't unregister events if there are interfaces still open

.github/scripts/find_new_boards.sh, boards.txt
Adds a hidden board with the default VID/PID of USB CDC/JTAG in order to always show that in IDE when ESP32 CDC/JTAG device is connected and removes all other mentions of that VID/PID
=> fix(boards): Remove duplicate VID/PID from boards.txt and add default CDC/JTAG board

.github/scripts/on-release.sh, platform.txt
Although Windows generally supports the use of the POSIX compliant slash (`/`) path separator in addition to the Windows native backslash (`\`) separator, in the specific use case where a path is present in a native command executed via an argument to `cmd /c` in a platform command pattern, it is mandatory to use backslash path separators.
Previously, a slash path separator was used in the `tools.esp32-arduino-libs.path` (non-release value) and `compiler.sdk.path` platform properties, which were referenced in a `copy` command in the `cmd /c` argument part of the platform's `recipe.hooks.objcopy.postobjcopy.2.pattern.windows` command pattern. This caused compilation to fail with a "`The syntax of the command is incorrect.`" error under the following conditions:
- The compilation is …
=> feat(tools):Use Windows native path separator in ESP_SR model copy command pattern

variants/arduino_nano_nora/dfu_callbacks.cpp
I don't know what hack that is including cpp files, but without this PR every build for this board fails with core 3. linker can't find `bytes2hex` from HEXBuilder.
I just unpacked my new Nano ESP32. I wonder why nobody cares about this board with core 3.
=> fix(variant): Arduino Nano ESP32 variant fix for core 3

cores/esp32/IPAddress.cpp
This PR fixes #9724 and has been tested with the little sample below in the project where the bug report originated from:
https://github.com/mathieucarbou/ESPAsyncWebServer/blob/main/examples/Filters/Filters.ino
=> fix(net): Fix IPv4 address construction from ip_addr_t and comparison (#9724)

libraries/WiFi/src/WiFiScan.cpp, libraries/WiFi/src/WiFiScan.h
Also increases the default timeout for the cases where BT and WiFi are both on.
Fixes: https://github.com/espressif/arduino-esp32/issues/9736
=> Allow setting scan timeout in milliseconds

.github/workflows/publishsizes-2.x.yml
This PR adds a Sizes test workflow with manual trigger, to compare sizes of master agains 2.X branch.
=> ci(sizes):  Sites test between master and 2.x branch

boards.txt
This PR adds Zigbee menu and Zigbee partitions to all C6/H2 boards.
Closes #9746
Closes #9700
=> feat(boards): Add Zigbee menu for all C6/H2 boards

cores/esp32/esp32-hal-tinyusb.c
Required for the latest ESP-IDF release/v5.1
=> feat(usb): Support the new USB IDF API

CMakeLists.txt
=> feat(idf): Require esp_psram when as component

CMakeLists.txt, idf_component.yml
Included in Arduino's public headers
Fixes: https://github.com/espressif/esp-idf/issues/13899
=> fix(idf): Require MDNS as public

docs/en/esp-idf_component.rst
Improve IDF as component documentation to be less confusing and more descriptive.
=> docs(component): Improve Arduino as component documentation

libraries/NetworkClientSecure/src/NetworkClientSecure.cpp, libraries/NetworkClientSecure/src/NetworkClientSecure.h
Loading Ca Cert/Certificate or Private Key from stream was leaking memory, due to buffers not being freed.
Fixes: #9636
=> fix(ssl): Fix load stream memory leak

boards.txt
fix: Changed Board name to describe board more clearly
Checked under Arduino IDE 2.3.2
board name appears correctly in board list 
https://github.com/SooDragon/GeekbleMini-ESP32C3
=> fix(3rd party board): Changed Board name to describe board more clearly

.github/scripts/tests_run.sh, .github/workflows/build_tests.yml, .github/workflows/hw.yml, .github/workflows/pre-commit.yml, .github/workflows/push.yml, .github/workflows/qemu.yml, .github/workflows/tests.yml, .github/workflows/wokwi.yml, tests/validation/gpio/ci.json, tools/get.py, tools/pre-commit/requirements.txt
This PR aims to:
- Fix Hardware tests
- Fix cache cleanup
- Properly cache python modules for pre-commit
- Compile as IDF component when libs change
- Re-enable Wokwi cache
=> ci(refactor): Fix workflows and small improvements

tests/validation/wifi/test_wifi.py, tests/validation/wifi/wifi.ino
Add scan to WiFi test
CI and locally
=> ci(wifi): Add scan to wifi test

cores/esp32/Esp.cpp
Backport of https://github.com/espressif/arduino-esp32/pull/9758
Partially fixes: https://github.com/espressif/arduino-esp32/issues/9816
=> fix(esp): Fix getFlashChipMode breaking on S3 and C3 

libraries/SD_MMC/examples/SD2USBMSC/SD2USBMSC.ino, libraries/SD_MMC/examples/SD2USBMSC/ci.json, libraries/SD_MMC/src/SD_MMC.cpp, libraries/SD_MMC/src/SD_MMC.h
Added SD_MMC.ReadRAW and SD_MMC.WriteRAW. Added example to demonstrate USBMSC accessing SDMMC card.
Tested on ESP32-S3 (the only supported platform ATM), v3.0.0
=> feat(sdmmc): Add RAW disk functions

.github/workflows/lib.yml, .github/workflows/push.yml
Allow the workflow to pass if the file has not changed
=> ci(push): Fix sizes upload if there is no changes (2.x)

.github/scripts/on-push.sh, .github/scripts/set_push_chunks.sh, .github/scripts/sketch_utils.sh, .github/scripts/tests_run.sh, .github/workflows/hw.yml, .github/workflows/lib.yml, .github/workflows/publishsizes-2.x.yml, .github/workflows/push.yml, .github/workflows/qemu.yml, .github/workflows/wokwi.yml
Fix issues found in the workflows, including:
- Exit code propagation;
- Proper chunk generation when some libraries are selected;
- Fixed missing HW tests dependencies and cache misses;
CI on my fork
=> fix(ci): Fix issues found in workflows

libraries/Network/src/NetworkClient.cpp, libraries/Network/src/NetworkClient.h
Fixes: https://github.com/espressif/arduino-esp32/issues/9822
Test results are relative and actual speeds will vary based on the environment. 
```cpp
// python3 -m http.server 8080 -d .
const char *fileDownloadUrl = "http://192.168.254.91:8080/esp32-3.0.1.zip";
```
New Method:
```
Download completed!
Total download time: 40.714000 s
Average download speed: 573.149578 Kb/s
```
Old Method:
```
Download completed!
Total download time: 63.890000 s
Average download speed: 365.240443 Kb/s
```
```cpp
const char *fileDownloadUrl = "https://github.com/espressif/arduino-esp32/releases/download/3.0.1/esp32-3.0.1.zip";
```
New Method:
```
Download completed!
Total download time: 80.371000 s
Average download speed: 290.343680 Kb/s
```
Old Method:
```
Download completed!
Total download time: 162.368000 …
```
=> fix(client): Implement readBytes in NetworkClient for faster downloads

libraries/WebServer/src/WebServer.cpp, libraries/WebServer/src/WebServer.h
Added support for removing routes in WebServer library. This PR implements `removeRoute` and `removeHandler` methods to remove any specific route which was added earlier using `on` function of WebServer library. 
I have tested this PR on arduino-esp32 core v2.0.17 with ESP32 (Wemos D1 Mini ESP32 Board)
Update (12-06-2024): Tested with arduino-esp32 core v3.0.1 too. Works well and good.
--
=> Added support for removing routes in WebServer library

libraries/WebServer/examples/Filters/Filters.ino, libraries/WebServer/examples/Filters/ci.json, libraries/WebServer/src/Parsing.cpp, libraries/WebServer/src/WebServer.cpp, libraries/WebServer/src/WebServer.h, libraries/WebServer/src/detail/RequestHandler.h, libraries/WebServer/src/detail/RequestHandlersImpl.h
This PR implements support for `setFilter` in WebServer library, particularly useful for conditional processing of routes based on filter functions set by user.
- `on` methods now return `RequestHandler` which also provides another way for users to remove routes. ( Ref: #9832 )
- Updated `RequestHandler` & `FunctionRequestHandler` class to add `setFilter` function.
- Added 2 default filters: `ON_STA_FILTER` & `ON_AP_FILTER`
I've tested this on arduino-esp32 core v3.0.1 - ESP32 ( Wemos D1 Mini ESP32 board ).
> [!IMPORTANT]
> ~~Potential Bug: @me-no-dev , NetworkClient's `localIP()` method always returns `IPAddress(0,0,0,0)` no matter through which interface the client's request came. This breaks the `ON_STA_FILTER` & `ON_AP_FILTER` filters as we can't detect the right interface …
=> feat: added support for filters in WebServer library

libraries/WebServer/src/WebServer.cpp
`removeRoute` now removes all matching routes instead of just first matching route.
Tested on arduino-esp32 core v3.0.1
--
=> fix: removeRoute should remove all matching routes (WebServer)

libraries/Update/src/Updater.cpp
The check was running before firmware was decrypted, so it fails.
Changes run the check only when unencrypted firmware is being uploaded.
Fixes: https://github.com/espressif/arduino-esp32/issues/9850
=> fix(ota): Magic byte check fails with encrypted firmware

libraries/ArduinoOTA/src/ArduinoOTA.cpp
Previously it was allowed only once before begin() was called
Fixes: https://github.com/espressif/arduino-esp32/issues/8803
=> fix(ota): Allow password and partition change while idle

idf_component.yml
It used to come with IDF 4.x
Fixes: https://github.com/espressif/arduino-esp32/issues/9854
=> feat(uart): Add esp-modbus to the included components

boards.txt, variants/walter/pins_arduino.h
This PR adds board definitions for DPTechnics Walter, a compact IoT development board combining an ESP32-S3 with a Sequans Monarch 2 GM02SP cellular modem.
More information about Walter can be found on its CrowdSupply page:
https://www.crowdsupply.com/dptechnics/walter
=> Add (3rd party board): DPTechnics Walter board support

.github/workflows/boards.yml
Add libs cache to improve performance of boards test.
Tested in CI, run: https://github.com/espressif/arduino-esp32/actions/runs/9548979657
=> ci(boards): Add cache for libs

libraries/HTTPClient/src/HTTPClient.cpp, libraries/HTTPClient/src/HTTPClient.h
Similar to setUserAgent
Closes: https://github.com/espressif/arduino-esp32/issues/9861
=> feat(http): Allow to set Accept-Encoding header

libraries/NetworkClientSecure/src/NetworkClientSecure.cpp, libraries/NetworkClientSecure/src/ssl_client.cpp
=> ClientSecure.available() fix for connection closed by remote socket

libraries/BLE/src/BLEClient.cpp, libraries/BLE/src/BLEClient.h, libraries/BLE/src/BLERemoteCharacteristic.cpp, libraries/BLE/src/BLERemoteCharacteristic.h, libraries/BLE/src/BLERemoteService.cpp, libraries/BLE/src/BLERemoteService.h, libraries/BLE/src/BLEScan.cpp, libraries/BLE/src/BLEScan.h
This PR partially reverts changes done in PR #8724 related to using Arduino `String`,  as a Key, within `std::map<>`.
It replaces Arduino `String` by `std::string` which is a C++ class compatible with `std::map<>` template, that must implement `std::less` in order to allow necesary comparation when inserting `<Key, T>` into the map.
Tested using ESP32, ESP32-S3 and ESP32-C6.
In order to test it, it is possible to use the BLE Client example running in one ESP32 SoC
https://github.com/espressif/arduino-esp32/blob/master/libraries/BLE/examples/Client/Client.ino
The second ESP32 SoC shall run a modified version of the BLE Server that adds a second characteristic in the same service.
Based on the code of https://github.com/espressif/arduino-esp32/blob/master/libraries/BLE/examples/Server/Server …
=> fix(BLE): Arduino String shall not be used within std::map<> 

libraries/HTTPClient/examples/BasicHttpsClient/BasicHttpsClient.ino
The example code was failing with a connection refused error. The hard-coded root certificate was not the one I found on the example URL. I've updated to the new certificate.
I've tested on a ESP32-S3-DevKitC-1 module.
=> fix: Update the root certificate for the BasicHttpsClient example

.github/scripts/install-arduino-core-esp32.sh, .github/workflows/build_py_tools.yml, tools/get.py
- Fix the tools compilation workflows by removing the deprecated ARM64 runner
- Add error message when failing to checkout
- Use `get.exe` for windows compilation test
- Optimize `get.py` and make output easier to read   
Locally and CI
=> ci(tools): Fix tools workflows

libraries/ESP32/examples/Time/SimpleTime/SimpleTime.ino
It is said that `esp_sntp_servermode_dhcp(1);` should be called before STA get's IP, yet the call is made after that had already happened. This PR puts it in the right place: after `WiFi.begin();`
=> fix(time): Fix SimpleTime to also use time servers from DHCP

boards.txt, variants/heltec_wifi_kit_32/pins_arduino.h, variants/heltec_wifi_lora_32/pins_arduino.h
For Heltec WiFi Kit 32 V1:
* Change crystal frequency to 26MHz.
* Add partition scheme menu.
* Delete PSRAM menu.
For Heltec WiFi LoRa 32 V1:
* Change crystal frequency to 26MHz.
* Change flash size to 4MB.
* Add partition scheme menu.
The changes were tested on above-mentioned boards.
I have used these examples:
* ESP32/Serial/Serial_All_CPU_Freqs
* FFat/FFat_Test
* WiFi/WiFiScan
Heltec WiFi Kit 32 V1 schematic: https://resource.heltec.cn/download/WiFi_Kit_32/WIFI_Kit_32_Schematic_diagram_V1.PDF
* The crystal is 26MHz.
* If PSRAM exists, its CE signal would be connected on GPIO16, but the only thing connected on GPIO16 is the OLED display, so that PSRAM does not exist. Moreover, enabling PSRAM results in serial message indicating that PSRAM cannot be detected.
Heltec WiFi LoRa 32 V1 …
=> fix(boards): set XTAL 26MHz for Heltec WiFi & LoRa V1

boards.txt, variants/elecrow_crowpanel_7/pins_arduino.h
-----------
Add variant for Elecrow CrowPanel 7.0"
* feat(esp32): Add variant for Elecrow CrowPanel 7.0"
Variant for https://www.elecrow.com/esp32-display-7-inch-hmi-display-rgb-tft-lcd-touch …
=> Add variant for Elecrow CrowPanel 7.0"

.github/scripts/on-release.sh, cores/esp32/esp_arduino_version.h, package.json, platform.txt
Also enables copy of the jsons to gh-pages
=> fix(version): Update version to 3.0.2

libraries/ESP32/examples/DeepSleep/ExternalWakeUp/ExternalWakeUp.ino
IDF 5.1 has changed the way how RTC IO shall be configured in order to make it work as Wakeup source.
This PR fixes the example to work within Arduino Core 3.0.x that uses IDF 5.1.
Using ESP32  + the example provided. Tested using EXT0 and EXT1.
Closes #9809
=> Deep Sleep Example Fix

libraries/BluetoothSerial/src/BluetoothSerial.cpp
Changed https://github.com/espressif/arduino-esp32/blob/b77b38e40ef3c0f47b4e35c88636f68f56e09004/libraries/BluetoothSerial/src/BluetoothSerial.cpp#L881 to use `delay(2)` instead to reduce the flush time.
Tested the change on Windows. Found the affected file in `C:\Users\<local_machine_name>\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.3\libraries\BluetoothSerial\src`
I used this for testing:
```
#include "BluetoothSerial.h"
#if !defined(CONFIG_BT_ENABLED) || !defined(CONFIG_BLUEDROID_ENABLED)
#error Bluetooth is not enabled! Please run `make menuconfig` to and enable it
#endif
#if !defined(CONFIG_BT_SPP_ENABLED)
#error Serial Bluetooth not available or not enabled. It is only available for the ESP32 chip.
#endif
BluetoothSerial SerialBT;
unsigned long takenTime;
void setup() …
```
=> BluetoothSerial - Reduce bluetooth serial flush delay

libraries/HTTPClient/src/HTTPClient.cpp, libraries/HTTPClient/src/HTTPClient.h
Now it is impossible to use HTTPClient lib without bringing all mbedTLS stuff along, even when no https connections requred.
`HTTPCLIENT_NOSECURE` build flag disables TLS support in HTTPClient library by excluding `NetworkClientSecure.h` header.
This allows linker to strip down mbedTLS lib and certificates bundle, which in turn reduces firmware image for about ~80kib.
Could be handy for the cases when no encrypted http connections required for the sake of saving firmware size.
Tested on all HTTPClient lib examples, firmware image size reduction is about 80kib, RAM reduction is about 600 bytes.
origin:
```
Per-archive contributions to ELF file:
Archive File     DRAM .data & 0.bss IRAM0 .text & 0.vectors ram_st_total Flash .text & .rodata  & flash_total
libmbedcrypto.a         144      85 …
```
=> HTTPClient lib - add HTTPCLIENT_NOSECURE build flag

cores/esp32/esp32-hal-rmt.c
If `neopixelWrite()` is used from different tasks  / isr_callbacks, it may result in a concurrency problem because of many detach/attach calls in sequence, but not in synch.
This commit avoids initializing the neopixel GPIO again, after a first use.
It also improves a lot the response time of `neopixelWrite()`.
It still allows to change RMT pin configuration or pin function correctly.
Tested using ESP32-S3. Please check the code from #9903
Fix #9903
=> feat(rmt): Solve neopixel issue

docs/en/advanced_utils.rst, docs/en/api/i2s.rst
Fixes naming in I2S example to avoid conflicts.
Closes #9914
=> docs(i2s): Fix I2S documentation example

Kconfig.projbuild, libraries/NetworkClientSecure/src/WiFiClientSecure.h, libraries/WebServer/examples/UploadHugeFile/UploadHugeFile.ino, libraries/WiFi/src/WiFi.h, libraries/WiFi/src/WiFiClient.h, libraries/WiFi/src/WiFiServer.h, libraries/WiFi/src/WiFiUdp.h
Deprecates WiFiClient, WiFiServer, WiFiUdp and WiFiClientSecure
Fixes: #9891
=> feat(net): Switch to typedefs for WiFiClient, WiFiServer, WiFiUdp and WiFiClientSecure

libraries/PPP/examples/PPP_Basic/PPP_Basic.ino, libraries/PPP/src/PPP.cpp, libraries/PPP/src/PPP.h
The delay required to reset Simcom modem modules varies significantly across different models, even where they have otherwise identical AT command sets.
Make the reset delay configurable to allow customising this for a specific modem.
5. …
=> PPP: Make modem reset delay configurable

boards.txt
Fixes XIAO C6 board name in boards.txt file
IDE View
Fix #9929
=> fix(boards): boards.txt error

CMakeLists.txt
Fixes IDF builds for H2 and C6 when OpenThread is enabled
=> fix(idf): Require openthread on H2 and C6

libraries/WiFiProv/examples/WiFiProv/WiFiProv.ino
Fixes WiFi Provisioning example to work with the new Network layer.
Adds a `WiFi.begin()` for automatic connection after provisioning or after reading NVS.
Changed the Provisioning mode to BLE in order to avoid a memory releasing problem with ESP32 after provisioning.
Tested with S3 and ESP32 using the example from 
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiProv/examples/WiFiProv/WiFiProv.ino
Fix #9943
=> Fixes WiFiProv.ino

libraries/Network/src/NetworkInterface.cpp
If the interface is already connected, try to enable IPv6 immediately. Otherwise the interface would need to go through disconnect/connect cycle for IPv6 to be enabled.
=> feat(net): Enable IPv6 immediately if already connected

docs/en/api/i2s.rst
Fix of i2s api documentation - example used incorrect method which is not declared.
I have tested example on arduino-esp32 core v3.0.2 with ESP32-S3 Board.
=> fix(docs): Correct i2s.srt api example

cores/esp32/esp32-hal-uart.c
Backport to `release/v2.x` branch
Fixes a problem related to inverting signal polarity back to normal after a previous inversion.
This shall set the correct polarity in Serial.begin().
``` cpp
#include <HardwareSerial.h>
HardwareSerial serial(0);   // use serial(1) for comparison
void setup() {}
void loop() {
serial.begin(115200, SERIAL_8N1, 3, 1, false);
serial.write("hello");
serial.flush();
serial.end();
serial.begin(115200, SERIAL_8N1, 3, 1, true);
serial.write("hello");
serial.flush();
serial.end();
}
```
Fix #9896
=> [release/2.x] fix(uart): Set back Pin signal polarity

docs/en/lib_builder.rst
Add instructions to use the lib-builder UI
=> docs(lib-builder): Add instructions to use the UI

libraries/WebServer/src/Parsing.cpp, libraries/WebServer/src/WebServer.cpp, libraries/WebServer/src/WebServer.h
Fixes: #9990
-----------
See #9990 
In short:
- WebServer::_uploadReadByte() does not keep track of some timeout
- WebServer::handleClient() does only set timeout to client after the function call where it is needed.
=> Fix timeout in WebServer::_uploadReadByte and handleClient() (#9990)

libraries/HTTPClient/src/HTTPClient.cpp
Data read from the client might actually be less than what we requested. Use the proper count when calculating data lengths.
Fixes: https://github.com/espressif/arduino-esp32/issues/9997
=> fix(httpc): Fix data read was less than expected

libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h
Default stack size of 2K might not be enough in some cases. Increase the default to safer 4K and allow setting it to custom value.
Fixes: https://github.com/espressif/arduino-esp32/issues/10001
=> feat(eth): Allow setting the RX task stack size

libraries/FS/src/FS.cpp, libraries/FS/src/FS.h
Fix for error return from position()
PR Issue #9992
Currently FS::position() returns 0 if file is invalid,  this change return (size_t) -1 instead, which is a very large number, to indicate an error 
none
Closes #9992
=> FS library position() to return (size_t) -1 on error

libraries/WiFi/examples/WPS/WPS.ino
Provides a better log of what went wrong when using WPS
=> fix(example): Add better WPS logging

.github/workflows/tests_results.yml, README.md
Fix readme badge for runtime tests by generating it in the results workflow
=> docs(badge): Generate runtime tests badge

docs/en/esp-idf_component.rst
This PR updates the documentation page of using Arduino framework as ESP-IDF component.
=> docs(component): Update to IDF 5.1 and add component manager instructions

boards.txt
The board definition had 460800 as default upload speed, but that is invalid on Windows, so the menu did not show. This change puts 115200 as default, which will make the menu appear
Fixes: https://github.com/espressif/arduino-esp32/issues/9786
=> fix(nodemcu-32s): Fix Upload Speed menu on Windows

boards.txt, variants/lolin_s3_mini_pro/pins_arduino.h, variants/lolin_s3_mini_pro/variant.cpp
Add board support for Add LOLIN S3 Mini Pro based ESP32-S3FH4R2 with 0.85 inch TFT Screen and IMU.
https://www.wemos.cc/en/latest/s3/s3_mini_pro.html
=> add(board): Add LOLIN S3 Mini Pro

boards.txt
change(boards):Add default 16MB partition to esp32wroverkit in file boards.txt
Default 8MB partition is defined for ESP32 Wrover Kit (all versions), but default 16MB partition is not defined
I define 16MB default partition in boards.txt for this board.
ESP32 Wrover Kit (all versions)
Closes #10015
=> change(board): Add default 16MB partition to esp32wroverkit

.github/workflows/tests_results.yml, .github/workflows/tests_wokwi.yml
Fixes possible CI error when the badge files are identical and there is nothing to push.
Also propagates the conclusion status throughout the workflows.
=> ci(tests): Fix conclusion status and badge pushing

libraries/SD_MMC/examples/SDMMC_Test/SDMMC_Test.ino
The setPins() function obviously comes from the SD_MMC lib. Not prepending that lib, this code won't compile.
Uncomment code section and compile code.
I have tested my Pull Request on Arduino-esp32 core v2.0.16 with ESP32-S3-devkitc1 Board.
None. I found that recently by using the example.
=> SDMMC: Fix example code

cores/esp32/esp32-hal-rmt.c
This pull request fixes crashes caused by `rmtDeinit` function by improving how the RMT channel is handled.
- Added `int channel = rmt->channel;` at the beginning of `rmtDeinit`.
- Used `channel` consistently throughout the function, including for mutex operations.
This change mirrors the approach used in the other RMT hal functions such as `rmtLoop`, `rmtWrite`, `rmtWriteBlocking` and others, ensuring consistency across the codebase.
Previously, the line `g_rmt_objects[from].channel = 0;` would set `rmt->channel` to 0 before `RMT_MUTEX_UNLOCK(rmt->channel)` was called. This caused the mutex to always be unlocked with an incorrect 0 as channel number, leading to crashes for channels > 0.
Tested on Lolin32 with Arduino-esp32 core v2.0.16, PlatformIO, VS Code, on Linux.
By calling:
```cpp …
```
=> v2.x: Fix RMT mutex unlock using incorrect channel number in rmtDeinit

docs/en/lib_builder.rst
Add small examples and information to Lib builder docs.
=> docs(lib-builder): Add missing requirements and examples

libraries/PPP/src/PPP.cpp, libraries/PPP/src/PPP.h
- Add Arduino stub functions to access the functionality provided by the underlying ESP-MODEM "esp_modem_get_battery_status" call
- Replaced verbose checks on each Arduino stub function call with a single succint #define for ease of code maintainability.  
Tested on an ESP32-S2 with a SIM7080G modem.  Love the PPP functionality, it just *works*!  Just providing some functional extensibility to functionality that is already present. 
```
testClient("google.com", 80);
Serial.print("RSSI: "); Serial.println(PPP.RSSI());
Serial.print("BtyVolt: "); Serial.println(PPP.getBatteryVoltage());
```
output result
```
[...]
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
Connection Success
RSSI: 18
BtyVolt: 3846
```
showing that the modem VCC power supply is 3.846v.
ESP-MODEM …
=> PPP: add "battery status" read stub functions

libraries/NetworkClientSecure/examples/WiFiClientSecure/WiFiClientSecure.ino
Fixes expired CA root for howmyssl.com (uses LetsEncrypt CA)
tested on wokwi with ESP32-S2
Closes #10062
=> fix(wfcs): Replaced expired certificate for howsmyssl.com

.github/scripts/install-arduino-cli.sh, .github/workflows/tests_hw.yml
Fix current CI errors by:
- Installing windows arduino-cli using the zip file
- Doing sparse checkout in HW tests (For some reason it cant find some folders without it)
CI
=> ci(tests): Fix workflow errors

cores/esp32/esp32-hal-gpio.h
Fixing digitalPinCanOutput() by adding the missing include.
Locally
Closes #10049
=> fix(gpio): add missing include for digitalPinCanOutput()

boards.txt, variants/ws_esp32_s3_matrix/partitions_all_app_4MB.csv, variants/ws_esp32_s3_matrix/partitions_otanofs_4MB.csv, variants/ws_esp32_s3_matrix/pins_arduino.h
Adds support for the Waveshare ESP32-S3-Matrix board. Includes changes to the Rainmaker partitions as per PR #10046 .
Tested using:
- Waveshare ESP32-S3-Matrix dev board
- arduino-esp32 core v3.0.3
- Arduino IDE v2.3.2
- Debian GNU/Linux 12
PR #10046
=> feat(board): add Waveshare ESP32-S3-Matrix

cores/esp32/esp32-hal-timer.c
This PR adds checks for each timer function to avoid crashing if timerBegin failed.
Locally
=> fix(timer): Add check to avoid crashing

cores/esp32/esp32-hal-ledc.c
This PR fixes LEDC channels being not cleared in used_channels on detach, as the bus was still set in the Peripheral Manager causing to always found a pin using the channel. Bus is cleared after successful return from the DetachBus function.
Thanks @nuclearcat for reporting the issue.
Locally
Related #10089
=> fix(ledc): Fix freeing channel if not used anymore

libraries/Network/src/NetworkUdp.cpp
Previously, `NetworkUDP::parsePacket()` would take the time to allocate a 1460 byte buffer to call `recvfrom()` with, immediately freeing it if there was no data read. This is an waste of cycles and provides no benefit.
This change has `parsePacket()` check if there is available data via `ioctl()` with `FIONREAD` first, saving the allocation and thus significantly increasing performance in no data situations.
Tested on Arduino-esp32 core v2.0.3 on an ESP32-C3 dev board (XAIO_ESP32C3) by sending UDP messages from my development machine.
In a near-empty sketch, invoking `parsePacket()` every `loop()` call, I was executing about 20,000 calls per second. After the change, the performance was closer to 35,000 calls/second.
I did not find any related issues. However, as I was making this …
=> fix(lwip): Add early out in `NetworkUDP::parsePacket()` when socket has no data

libraries/NetworkClientSecure/src/NetworkClientSecure.cpp, libraries/NetworkClientSecure/src/NetworkClientSecure.h
Fixes: https://github.com/espressif/arduino-esp32/issues/10099
=> fix(ssl): Add size arg to NetworkClientSecure::setCACertBundle

libraries/ESP_NOW/src/ESP32_NOW.cpp, libraries/ESP_NOW/src/ESP32_NOW.h
This PR fixes ESP-NOW library, where on end() peers were not removed correctly.
Locally with ESP-NOW examples.
Related #10076
=> fix(ESP-NOW): Remove all peers on ESP_NOW.end()

libraries/Ethernet/examples/ETH_WIFI_BRIDGE/ETH_WIFI_BRIDGE.ino, libraries/Ethernet/examples/ETH_WIFI_BRIDGE/ci.json, libraries/PPP/examples/PPP_WIFI_BRIDGE/PPP_WIFI_BRIDGE.ino, libraries/PPP/examples/PPP_WIFI_BRIDGE/ci.json, libraries/WiFi/examples/WiFiExtender/WiFiExtender.ino, libraries/WiFi/examples/WiFiExtender/ci.json
Adds examples of how to use NAPT to share internet through WiFi SoftAP
=> feat(net): Add NAPT examples

libraries/WebServer/examples/WebServer/README.md, libraries/WebServer/examples/WebServer/WebServer.ino
Fixing WebServer example.
* Enable FAT and LittleFS filesystems as configured.
* use new versions of RequestHandler::canHandle and RequestHandler::canUpload (old do not work anymore for uploads)
* Tested with Arduino Nano ESP32
Arduino Nano ESP32 using arduino-esp version 3.0.4
Following the instructions in README
* upload data files
* view files
* DELETE files handler
=> Improving WebServer Example

docs/en/api/preferences.rst, docs/en/tutorials/preferences.rst
Correct the size of the Preferences Float type in the API and Tutorial documentation
Verified by running a sketch that returns the `sizeof()` a `float_t` and a `float` variable.
None
=> docs: correct Float type size in Preferences API and Tutorial documentation

boards.txt, variants/waveshare_esp32_s3_lcd_169/pins_arduino.h, variants/waveshare_esp32_s3_touch_lcd_169/pins_arduino.h
Adding variant for Waveshare ESP32-S3-Touch-LCD-1.69 & ESP32-S3-LCD-1.69 board containing MCU, LCD, RTC, and IMU.
Untested, pin definition is based on information in Waveshare wiki.
Wiki For [ESP32-S3-Touch-LCD-1.69](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-1.69)
Wiki For [ESP32-S3-LCD-1.69](https://www.waveshare.com/wiki/ESP32-S3-LCD-1.69)
Pending USB VID PR: [espressif/usb-pids/pull/169](https://github.com/espressif/usb-pids/pull/169)
=> Added variant for Waveshare ESP32-S3-Touch-LCD-1.69 & ESP32-S3-LCD-1.69 board

libraries/SD/src/sd_diskio.cpp
The destructor of `AcquireSPI`  uses `card` after `card` has been freed.
The issue causes constant crashes for me.
(Sidenote: `s_cards[pdrv]` is accessed before `pdrv` is checked to be valid throughout the file)
Tested on a ESP32-S3 via platformio framework "espidf, arduino".
Introduced in https://github.com/espressif/arduino-esp32/commit/b6ca5a863047469c3a786ae6d4c34a9bce6cf7d3
=> Fix use after free in SD library

cores/esp32/esp32-hal-uart.c
ESP32-S2 and S3 using USB CDC OTG (TinyUSB) won't print any log information. This commit fixes that.
Using ESP32-S2 and S3 with `USB CDC On Boot` enabled and in the case of S3, USB Mode shall be `USB OTG (TinyUSB)`.
Set log level to Verbose.
```cpp
#include <esp_log.h>
#include <chip-debug-report.h> 
void setup() {
neopixelWrite(RGB_BUILTIN, 32, 0, 0); // RED until Serial Monitor is open
Serial.begin();
Serial.setDebugOutput(true);
while (!Serial) delay(100);
printBeforeSetupInfo();
esp_log_level_set("*", ESP_LOG_VERBOSE);
neopixelWrite(RGB_BUILTIN, 0, 16, 0); // Green when Serial Monitor is open
}
void loop() {
Serial.println("This is a Serial.println");
log_e("This is a log_e error");
ESP_LOGE("mainloop", "This is an ESP_LOGE error");
delay(2000);
}
```
Fixes #10121
=> fix(USB): OTG S2 and S3 debug print

docs/en/api/adc.rst
Fixes the documentation. typo. volts->Volts
None
Fix #10124
=> fix(doc): analogReadMilliVolts

libraries/RainMaker/src/RMaker.cpp
This PR addition register a set of RainMaker common events for better debugging (reboot, wifi reset, factory reset and MQTT events).
Tested locally
=> feat(RMaker): Register common events for better debugging

libraries/WiFiProv/src/WiFiProv.cpp
This PR fixes WiFi STA was not starting when already provisioned after device reset.
Tested with RainMaker Switch example
Related #10119
=> fix(wifiprov): Fix starting Wifi when already provisioned

cores/esp32/esp32-hal-uart.c
Problem detected with ESP32 and ESP32-S2 when the baudrate goes to 460600 bps.
REF_TICK (2MHz) seem not to work properly.
Limiting the use of REF_TICK for up to 205 Kbps.
ESP32 / S2.
```cpp
#include <HardwareSerial.h>
HardwareSerial MySerial(1);
const int MySerialRX = 16;
const int MySerialTX = 17;
uint8_t rBuffer[2048]; 
void setup() 
{
MySerial.begin(460800, SERIAL_8N1, MySerialRX, MySerialTX);
}
void loop() 
{
while (MySerial.available() > 0) {
int s = MySerial.readBytes(rBuffer, sizeof(rBuffer));
Serial.write(rBuffer, s);
}
}
```
Fix #10161 
Fix #10117
=> Fix(UART): ESP32 | ESP32-S2 UART Clock Source

.github/workflows/docs_build.yml, .github/workflows/docs_deploy.yml, .github/workflows/push.yml
Remove wildcard from branch triggers.
This will avoid triggering twice for some branches while testing. These branches can be later added to the triggers.
=> ci(branches): Remove wildcard from branch triggers

tools/get.py
This PR aims to fix some issues with not extracting the correct libs when downgrading and upgrading the libs using the script.
For example the issue that @P-R-O-C-H-Y had:
- switch to 2.X branch and run get.py
- now you can successfully use 2.x code
- switch to master and run get.py -> it will skip extraction of everything
- if you restart IDE, try to compile any sketch you will get this error:
`xtensa-esp32s2-elf-g++: error: unrecognized command line option '-std=gnu++2b'; did you mean '-std=gnu++2a'?`
This PR also fixes an issue where the flags required a boolen argument.
Tested using:
=> fix(get.py): Add version checking for installed tools

platform.txt, tools/platformio-build.py
`-Werror=return-type` should help catch potential causes of run-time UB.
See https://github.com/esp8266/Arduino/discussions/8160 for the original issue report.
This flag has been:
- added in esp8266/Arduino for all IDE warning levels in 2021: https://github.com/esp8266/Arduino/pull/8165
- already used in ESP-IDF at its default warning/error setting (-Wall -Werror, https://github.com/espressif/esp-idf/issues/8244#issuecomment-1014690475)
- accepted in principle in arduino-esp32 in https://github.com/esp8266/Arduino/pull/8165#issuecomment-867410223
- submitted in a PR in https://github.com/espressif/arduino-esp32/pull/5321, which was closed
- requested in https://github.com/espressif/arduino-esp32/issues/5867#issuecomment-1937769823
1. Compiled test.ino:
```c++
void setup(){}
void loop(){} …
```
=> change(build): add -Werror=return-type to default C and C++ flags

.github/scripts/tests_run.sh, tests/validation/democfg/test_democfg.py, tests/validation/hello_world/test_hello_world.py, tests/validation/nvs/test_nvs.py
Fix using `expect` (regex) instead of `expect_exact` (string) in tests.
Also check for `WOKWI_CLI_TOKEN` before running Wokwi tests
Tested locally
=> fix(tests): Use proper API and check for required token

boards.txt, variants/heltec_vision_master_e290/pins_arduino.h, variants/heltec_vision_master_e_213/pins_arduino.h, variants/heltec_vision_master_t190/pins_arduino.h
Add the new series of development boards launched by Heltec.
Based on the ESP32-S3R8 chip, it integrates displays with various functions and is paired with LoRa modules as an option, allowing users to choose different options for different situations.
[Vision Master E213](https://heltec.org/project/vision-master-e213/)
[Vision Master E290](https://heltec.org/project/vision-master-e290/)
[Vision Master T190](https://heltec.org/project/vision-master-t190/)
=> feat(board):Add Heltec Vision Master series boards

boards.txt, variants/jczn_2432s028r/partitions_all_app_4MB.csv, variants/jczn_2432s028r/partitions_otanofs_4MB.csv, variants/jczn_2432s028r/pins_arduino.h, variants/jczn_2432s028r/variant.cpp
Add support for the JCZN ESP32-2432S028R,  aka Cheap Yellow Display (CYD), development board.
- Includes two custom partition schemes
- Includes revised naming conventions for Rainmaker 4MB partitions
Tested with the JCZN ESP32-2432S028R board with
- Arduino IDE v2.3.2 using arduino-esp32 core v3.0.4 on Debian-Linux 12.
- Arduino IDE v2.3.2 using arduino-esp32 core v2.0.17 on macOS 14.6.1
None
=> feat(boards): Add ESP32-2432S028R board support

cores/esp32/Esp.cpp
Fixes: https://github.com/espressif/arduino-esp32/issues/10238
=> fix(chip): Return correct ESP32 chip model

libraries/ArduinoOTA/src/ArduinoOTA.cpp
as follow up of changing flush() to clear() in networking with PR https://github.com/espressif/arduino-esp32/pull/9453, there is an  unclear use of `flush()` in ArduinoOTA.
The UDP object in ArduinoOTA is used to receive and send messages in `handle()`. The function _onRx invoked in `handle()` before flush()) reads a message and then sends a response. So it is unclear what the flush() in handle() was meant to do. 
But the library would fail if for some reason _onRx doesn't read the whole incoming message because then all following parsePacket will always return 0 (and this is not a good behavior of the NetworkUDP class).
=> ArduinoOTA - change occurrence of client.flush() to clear()

libraries/WebServer/src/Parsing.cpp
as follow up of changing flush() to clear() in networking with PR https://github.com/espressif/arduino-esp32/pull/9453, there is an unclear use of flush() in WebServer.
in Parsing.cpp the client.flush() is at the end of the processing of the HTTP request. the response is already sent. If the connection is not kept alive for the next request, then it is closed so why clearing it. If the connection is kept alive for the following HTTP request, then clear() could delete beginning of the following request. But characters remaining in the buffer would make the following request invalid too. So for a reused connection the processing of the request should ensure to read until the exact end of the request. I don't know if that is fulfilled.
Anyway client.flush() did clear the receive buffer in …
=> WebServer - change occurrence of client.flush() to clear()

libraries/Network/src/NetworkClient.cpp, libraries/Network/src/NetworkClient.h, libraries/Network/src/NetworkUdp.cpp, libraries/Network/src/NetworkUdp.h
This is a compromise for issues caused by https://github.com/espressif/arduino-esp32/pull/9453
Example output:
```
/var/folders/74/n3f3k71s7lv_snk832kfgjfw0000gn/T/arduino_modified_sketch_265854/WiFiIPv6.ino: In function 'void wifiConnectedLoop()':
/var/folders/74/n3f3k71s7lv_snk832kfgjfw0000gn/T/arduino_modified_sketch_265854/WiFiIPv6.ino:53:20: warning: 'virtual void NetworkUDP::flush()' is deprecated: Use clear() instead. [-Wdeprecated-declarations]
53 |     ntpClient.flush();
|     ~~~~~~~~~~~~~~~^~
In file included from /Users/user/Documents/Arduino/hardware/espressif/esp32/libraries/Network/src/Network.h:14,
from /Users/user/Documents/Arduino/hardware/espressif/esp32/libraries/WiFi/src/WiFiGeneric.h:39,
from /Users/user/Documents/Arduino/hardware/espressif/esp32/libraries/WiFi/src/Wi …
```
=> fix(client): Make flush() call clear() and deprecate it

.gitignore, tools/get.py
Remove old files before extracting new ones to avoid conflicts.
Also add newer toolchain to `gitignore` to make development easier
Locally
=> fix(get.py): Remove existing files before extracting

cores/esp32/esp32-hal-uart.c
IDF 5.3 introduces a new feature `SOC_UART_SUPPORT_SLEEP_RETENTION` that adds a new field to `uart_config_t` called `flags.backup_before_sleep`.
When this field is not set, it causes an error when `HardwareSerial::begin()` is executed.
Tested with ESP32, ESP32-S3, ESP32-C6.
``` cpp
void setup() {
}
void loop() {
Serial.println("Hello World!");
delay(1000);
}
```
None
=> fix(uart): sleep retention

.github/scripts/on-release.sh
Fix the release script to use the libs stored as a release asset.
=> fix(release): Fix release script to use new archive method

.github/scripts/on-release.sh
Run install command directly to avoid installing wrong version based on cache.
Locally
=> fix(release): Fix install test on release

package/package_esp32_index.template.json
```
lib-builder: release/v5.3 958f8b0
esp-idf: release/v5.3 0bbd728196
arduino: release/v3.1.x 8352caff
tinyusb: master 669f341b0
espressif__esp-dsp: 1.5.2
espressif__esp-modbus: 1.0.15
espressif__esp-nn: 1.0.2
espressif__esp-tflite-micro: 1.3.1
espressif__esp-zboss-lib: 1.5.0
espressif__esp-zigbee-lib: 1.5.0
espressif__esp_diagnostics: 1.2.0
espressif__esp_insights: 1.2.0
espressif__esp_modem: 1.1.0
espressif__esp_rainmaker: 1.4.0
espressif__esp_schedule: 1.2.0
espressif__esp_secure_cert_mgr: 2.4.1
espressif__json_generator: 1.1.2
espressif__libsodium: 1.0.20~1
espressif__mdns: 1.4.0
espressif__network_provisioning: 1.0.1
espressif__qrcode: …
```
=> IDF release/v5.3

CMakeLists.txt
Fixes an issue related to `esp_matter` component that defines a path using `ESP32` as folder.
Because Arduino defines `ESP32` to `1`, it causes an expansion error for folder using `ESP32` folder name.
`-DESP32` ==> `#define ESP32 1`
`#define CHIP_PLATFORM_CONFIG_INCLUDE <platform/ESP32/CHIPPlatformConfig.h>` 
will expand to
`#define CHIP_PLATFORM_CONFIG_INCLUDE <platform/1/CHIPPlatformConfig.h>`
Building Arduino + Matter as IDF Component in the same project.
https://github.com/espressif/arduino-esp32/issues/7432#issuecomment-2294706221
=> fix(arduino): changes ESP32 definition in CMakeLists.txt file

libraries/PPP/src/PPP.cpp
Modem will try to switch to CMUX and then back to COMMAND in order to allow communication with the modem.
This does not work on SIM800, so RST pin should always be connected to ensure proper reset is possible on boot.
Fixes: https://github.com/espressif/arduino-esp32/issues/10237
=> fix(ppp): Fix PPP not working after reboot if no RST

.github/scripts/on-push.sh
Make the compilation tests use `ci.json` FQBNs or use the defaults set in `sketch_utils.sh`
Required by #10265
=> ci(push): Use FQBN from ci.json

libraries/HTTPClient/src/HTTPClient.cpp
Following deprecation of flush()
=> fix(http): Replace flush() with clear() in HTTPClient

.github/workflows/docs_deploy.yml, .github/workflows/upload-idf-component.yml
Run documentation build and push to components only when release is successful.
Tested in fork
=> ci(release): Make workflows dependent on release completion

boards.txt
These properties are intended to associate VID/PID pairs with the "Bee" board definitions:
https://arduino.github.io/arduino-cli/dev/platform-specification/#properties-from-pluggable-discovery:~:text=upload_port.vid%20and%20upload_port.pid%20properties
Typos caused incorrect VID and PID values to be associated. The result was that ports with this VID/PID pair were not identified by the Arduino development software as the board model as intended.
This pull request fixes the typos.
Compile for the modified boards using the platform (at 0b8eedea5cf18e2b01f80975197b85f70a36caf3) with this patch applied.
=> fix(boards): Correct typos in port prop. associations for "Bee" boards

idf_component.yml, idf_component_examples/hw_cdc_hello_world/CMakeLists.txt, idf_component_examples/hw_cdc_hello_world/README.md, idf_component_examples/hw_cdc_hello_world/main/CMakeLists.txt, idf_component_examples/hw_cdc_hello_world/main/idf_component.yml, idf_component_examples/hw_cdc_hello_world/main/main.cpp, idf_component_examples/hw_cdc_hello_world/sdkconfig.defaults
Adds a new example for building Arduino project as IDF component using the native HW CDC port.
Tested using ESP32-C3, ESP32-C6 and ESP32-S3 - building it using Arduino as IDF Component.
None
=> Adds HW Serial CDC as IDF component example

boards.txt
The Arduino boards platform framework allows properties of a port to be [associated with a board definition](https://arduino.github.io/arduino-cli/dev/platform-specification/#properties-from-pluggable-discovery:~:text=upload_port.vid%20and%20upload_port.pid%20properties). The Arduino development software will identify a port having the associated properties as that board.
This should only be done for properties that are unique to the ports produced by that board model. In cases where a board model does not produce a port with properties unique to that model, it is irresponsible to associate those properties with the board definition as this will cause other models to be inappropriately identified.
The authors of these board definitions associated them with non-unique USB VID/PID pairs so …
=> fix(boards): Remove port property assoc. for non-unique VID/PID pairs

cores/esp32/chip-debug-report.cpp
It was printed wrongly before. Actual revision is the value divided by 100 in float.
=> fix(report): Print correct chip revision

libraries/WiFi/src/WiFiScan.cpp
new parameters could cause issues if scan is not cleared
fixes: https://github.com/espressif/arduino-esp32/issues/10281
=> fix(scan): Make sure scan struct is cleared before set

.github/scripts/sketch_utils.sh
As FQBN is now read in last step of building sketch, there was empty FQBN in the compilation log for sizes report.
=> fix(ci): Log default FQBN if not passed as argument

cores/esp32/Tone.cpp
Implements  setToneChannel() declared in Arduino.h, but removed when moving from Arduino 2.x to 3.x.
Fixes a Task priority problem in the code. Previous priority was the same of the Arduino Task and it prevents the Tone Queue to be processed before Tone commands are executed.
Tested using ESP32-S3, checking the logs.
``` cpp
void setup() {
setToneChannel(5);
test();
}
void loop() {
}
void test() {
// turn off tone function for pin 8:
noTone(8);
setToneChannel(1);
// play a note on pin 6 for 200 ms:
tone(6, 440, 200);
delay(200);
// turn off tone function for pin 6:
noTone(6);
setToneChannel(2);
// play a note on pin 7 for 500 ms:
tone(7, 494, 500);
delay(500);
// turn off tone function for pin 7:
noTone(7);
setToneChannel(1);
// play a note on pin 8 for 300 ms:
tone(8, 523, 300); …
```
=> Adds setToneChannel() implementation

docs/en/contributing.rst, docs/en/guides/docs_contributing.rst
Add instructions on how to create and run tests.
Fix formatting.
Built locally
Closes #10185
=> docs(contrib): Add instructions on how to test changes

cores/esp32/esp32-hal-i2c.c
Currently code can return before semaphore is given, which can cause the bus to lock. Change makes sure that it's properly given in case of failure.
Fixes: https://github.com/espressif/arduino-esp32/issues/10304
=> fix(i2c): Ensure that semaphore is properly given if init fails

libraries/WiFi/src/WiFiScan.cpp
As it was written, it was possible to leak the scan result array if esp_wifi_scan_get_ap_records() failed. Change will ensure that the array is deleted in that case.
=> fix(scan): Make sure that we do not leak memory if reading the APs fails

.pre-commit-config.yaml, libraries/ESP32/examples/HWCDC_Events/ci.json, libraries/ESP_SR/examples/Basic/ci.json, libraries/OpenThread/examples/COAP/coap_lamp/ci.json, libraries/OpenThread/examples/COAP/coap_switch/ci.json, libraries/OpenThread/examples/SimpleCLI/ci.json, libraries/OpenThread/examples/SimpleNode/ci.json, libraries/OpenThread/examples/SimpleThreadNetwork/ExtendedRouterNode/ci.json, libraries/OpenThread/examples/SimpleThreadNetwork/LeaderNode/ci.json, libraries/OpenThread/examples/SimpleThreadNetwork/RouterNode/ci.json, libraries/OpenThread/examples/ThreadScan/ci.json, libraries/OpenThread/examples/onReceive/ci.json, libraries/SD_MMC/examples/SD2USBMSC/ci.json, tests/performance/psramspeed/ci.json, tests/performance/ramspeed/ci.json, tests/validation/democfg/ci.json, tests/validation/gpio/ci.json, tests/validation/nvs/ci.json, tests/validation/touch/ci.json, tests/validation/wifi/ci.json
Added JSON formatter to pre-commit and apply fixes.
Tested locally
=> feat(pre-commit): Add JSON formatter to pre-commit hooks

cores/esp32/Stream.cpp, cores/esp32/Stream.h
Upstream code contains some fixes
=> fix(api): Update Arduino Stream class

libraries/Network/src/NetworkClient.cpp
See discussion in issue #10288
Fixes: #10288
=> fix(networking): NetworkClientRxBuffer::clear() may not always clear

idf_component.yml
Fixes Arduino Managed Components declaration when building Arduino as IDF component using Windows 11 + IDF 5.1.4.
Error Message:
```
Dependencies lock doesn't exist, solving dependencies.
CMake Error at C:/Espressif/frameworks/esp-idf-v5.1.4/tools/cmake/build.cmake:540 (message):
WARNING: From https://github.com/espressif/arduino-esp32
* [new ref]             refs/pull/10335/head  -> refs/pull/10335/head
* [new ref]             refs/pull/10335/merge -> refs/pull/10335/merge
ERROR: Because espressif/arduino-esp32
(4e9eb35752a36bd4e03739dc7e1c3ac246c49d3c) depends on
espressif/rmaker_common (^1.4.3) which doesn't match any versions,
espressif/arduino-esp32 is forbidden.
So, because project depends on espressif/arduino-esp32
(4e9eb35752a36bd4e03739dc7e1c3ac246c49d3c), version solving failed. …
```
=> fix(arduino): rain maker common version

libraries/WebServer/src/Parsing.cpp, libraries/WebServer/src/WebServer.cpp, libraries/WebServer/src/WebServer.h
A few functions in WebServer does have `String` arguments, which does lead to copying of the strings when calling those functions.
For those where applicable, I changed the function arguments to `const String&`.
Also some functions which do not modify members, were not marked as `const`. Added those too.
=> [WebServer] Mark functions as const + reduce copy of strings

libraries/WiFi/src/WiFiScan.cpp
When there are many AP's seen during a scan, the allocation of `_scanResult` may fail. 
Thus add `(std::nothrow)` to the `new` call.  Without it, the next check for a valid pointer was not even done as the application would already have crashed.
Also it is possible the array was still present before allocating a new one, so we must make sure it is deleted first.
Follow-up of this PR: https://github.com/espressif/arduino-esp32/pull/10312
There is 1 possible known issue left which is not being dealt with by this PR.
Since the `_scanDone()` function is called from a callback from an async scan, in theory it is possible someone is still processing a previous scan result via `_getScanInfoByIndex()`.
However if this does happen, then without this fix we would have had a memory leak for sure.
To …
=> [WiFiScan] Allow allocation in _scanDone() to fail and prevent memory leak

libraries/ESP_NOW/src/ESP32_NOW_Serial.cpp, libraries/ESP_NOW/src/ESP32_NOW_Serial.h
After max retries is met once the ESP_NOW_Serial_Class performs "end()" which removes the peer from ESP_NOW. 
Further messages to and from ESP_NOW_Serial are not received or sent. 
Peer should stay in ESP_NOW to re-establish connection even with data loss. 
This change will "retry and drop" the data piece by piece instead of aborting the connection.
ESP_NOW_Serial "Peer" will not remove itself from ESP_NOW_Peer list when data sent is not received by a peer. ESP_NOW_Serial::end() is still called when ESP_NOW::send() fails.
Tested on a pair of M5Stack Stamp ESP32-C3.
Confirmed that transmission is able to continue after:  disconnecting the Receiving module from power.
Attempting to send data.
Restoring power to Receiving module.
Previously, transmission halts as the cleanup/teardown in …
=> change(esp_now_serial): No teardown on retry limit

libraries/WebServer/examples/WebServer/WebServer.ino, libraries/WebServer/src/detail/RequestHandler.h, libraries/WebServer/src/detail/RequestHandlersImpl.h
Nearly each function of WebServer RequestHandler does copy the String arguments instead of using `const String&`.
N.B. This might break some classes which inherit from `RequestHandler`
=> Reduce copy of Strings in WebServer RequestHandler

boards.txt, variants/waveshare_esp32_s3_touch_amoled_241/pins_arduino.h
I modified waveshare_esp32_touch_amoled_241 to waveshare_esp32_s3_touch_amoled_241 without affecting functionality.
The previous waveshare_esp32_touch_amoled_241 was also submitted by me. If waveshare_esp32_s3_touch_amoled_241 is successfully merged, you can delete the previous waveshare_esp32_touch_amoled_241.
=> fix(variant): Rename waveshare esp32-s3 board.

idf_component_examples/esp_matter_light/README.md
Update [Matter Light README.md](https://github.com/espressif/arduino-esp32/blob/master/idf_component_examples/esp_matter_light/README.md)
Following #10356 but against master branch
-----------
Please …
=> Update Matter Light README.md

cores/esp32/Arduino.h
The `digitalPinToInterrupt()` macro currently remaps the pin number to the GPIO number. This is not necessary, as most users will then use the returned value in `attachInterrupt()` or other similar API functions, which already perform the same remapping.
The first half of the macro (the condition) does indeed require the remapping to ensure the check operates on GPIO numbers.
Fixes #10367 on 2.x (legacy) cores.
See also #10373 for the same fix on 3.x (current) cores.
=> digitalPinToInterrupt: fix double pin remapping on 2.x cores

libraries/DNSServer/examples/CaptivePortal/CaptivePortal.ino, libraries/DNSServer/src/DNSServer.cpp
When running on WiFi-AP mode server's start() method returned true while in fact UDP listening socket was never created
Regression introduced in #8760
Closes #10330
=> fix: DNSServer Lib - improper startup code in WiFi mode

cores/esp32/HardwareSerial.cpp
The pin remapping functions have to be called as early as possible in the begin() function, to immediately convert the input parameters from the user to the GPIO numbers used everywhere in the core. However, there is code that assigns GPIO numbers to `txPin`/`rxPin` _before_ the call to `digitalPinToGPIONumber`.
This issue has always been dormant since the introduction of pin remapping in 9b4622d, but was exposed by the recent UART pin detach support in 2.x, which actually disabled the default Serial0 pins.
Move the pin remapping function calls earlier in the begin() function to fix this issue.
Tested on the Nano ESP32 - `Serial0.begin(115200)` was selecting "random" pins instead of the expected defaults.  
See also #10379 for the same fix on master.
=> fix(HardwareSerial): fix pin remapping in begin() for 2.x

cores/esp32/HardwareSerial.cpp
The pin remapping functions have to be called as early as possible in the `HardwareSerial::begin()` function, to immediately convert the input parameters from the user to the GPIO numbers used everywhere in the core. However, there is code that assigns GPIO numbers to `txPin`/`rxPin` _before_ the call to `digitalPinToGPIONumber`.
This issue has always been dormant since the introduction of pin remapping in 9b4622d, but is evident on 3.x due to the full pinmuxing support that _actually detaches pins_ - disabling the default `Serial0` pins.
Move the pin remapping function calls earlier in the `begin()` function to fix this issue.
Tested on the Nano ESP32 - `Serial0.begin(115200)` was selecting "random" pins instead of the expected defaults.  
See also #10380 for the same fix on 2.x.
=> fix(HardwareSerial): fix pin remapping in begin() on master

cores/esp32/esp32-hal-log.h, cores/esp32/esp32-hal-misc.c, cores/esp32/esp32-hal-psram.c
Makes sure that PSRAM is part of the map before app_main is called.
=> fix(psram): Init PSRAM before app_main to fix mmu_map

libraries/WiFi/examples/WPS/WPS.ino
It causes errors with newer C++ standarts
cc: @SuGlider
=> Fix WPS example config initialization

cores/esp32/esp32-hal-tinyusb.c, libraries/USB/src/USBHID.cpp
Fixes an issue where the keyboard LEDs will not trigger the proper event
Fixes: https://github.com/espressif/arduino-esp32/issues/10296
=> fix(hid): Fix OUTPUT report not received

cores/esp32/esp32-hal-misc.c
OPI PSRAM was not registered as started and was preventing it from working.
=> fix(spiram): Fix OPI PSRAM init

libraries/OpenThread/README.md, libraries/OpenThread/src/OThreadCLI.cpp, libraries/OpenThread/src/OThreadCLI.h
TARGET: 3.0.x and 3.1.x
Fixes FreeRTOS types.
This affects certain ways of building applications using IDF Components.
CI only.
=> Update FreeRTOS Symbols in OThreadCLI

libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h
The ESP32, ESP32-S and ESP32-H series have two I2C interfaces, while the ESP32-C series has only one.
-----------
The `Wire1` object is conditionally compiled and is not available on MCUs that only have a single I2C interface (e.g. MCUs of the ESP32-C series).
I tested my pull request on Arduino-esp32 core v3.1.0 with ESP32, ESP32-S3 and ESP32-C3 board with this scenario.
For the test I modified the [WireScan example](https://github.com/espressif/arduino-esp32/tree/master/libraries/Wire/examples/WireScan) to use the `Wire1` object. On an ESP32-C3 based board the compilation failed which is the expected behaviour and intention of this PR.
[ESP32 Arduino Wire not working](https://community.platformio.org/t/twowire-wire-twowire-1-causing-null-tx-buffer-pointer-error/43584)
=> Wire library: Add conditional compilation for second I2C interface based on SOC_I2C_NUM

.github/scripts/install-platformio-esp32.sh, .github/scripts/sketch_utils.sh, .github/scripts/tests_run.sh, .github/workflows/tests_build.yml, .github/workflows/tests_hw.yml, docs/en/contributing.rst, libraries/ESP32/examples/Camera/CameraWebServer/ci.json, libraries/ESP32/examples/Camera/CameraWebServer/partitions.csv, libraries/RainMaker/examples/RMakerCustom/ci.json, libraries/RainMaker/examples/RMakerCustomAirCooler/ci.json, libraries/RainMaker/examples/RMakerSonoffDualR3/ci.json, libraries/RainMaker/examples/RMakerSwitch/ci.json, libraries/WiFiProv/examples/WiFiProv/ci.json, libraries/Zigbee/examples/Zigbee_Color_Dimmable_Light/ci.json, libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/ci.json, libraries/Zigbee/examples/Zigbee_On_Off_Light/ci.json, libraries/Zigbee/examples/Zigbee_On_Off_Switch/ci.json, libraries/Zigbee/examples/Zigbee_Scan_Networks/ci.json, libraries/Zigbee/examples/Zigbee_Temperature_Sensor/ci.json, libraries/Zigbee/examples/Zigbee_Thermostat/ci.json, platform.txt
- Change the partition used by the CI to the same as Arduino by default
- Fix issues with requirements check
- Add option to append to all FQBNs
CI and Locally
=> ci(compilation): Use default partition and add append to FQBN option

cores/esp32/HardwareSerial.cpp
loop() calls Serial Events functions when those are declared. 
The way it was declared, was forcing to always call avalable() to then call an empty function.
This commit fixes it.
Now when the sketch has no serialEvent() function declared, it won't be executed neither will available().
There are is a performance degradation when calling available() every single time when loop() was executed, whenever Serial.begin() is executed.
It shall be merged to 3.0.x and 3.1.x
``` cpp
uint32_t  Loopcounter = 0;
static uint32_t msTick;      
void setup() 
{
Serial.begin(115200);                     // Setup the serial port to 115200 baud //
msTick = millis(); 
Serial0.begin(115200); // THIS Line starts UART Arduino Driver and also forces to executing serialEventRun() that "eats" CPU time...
}
void …
```
=> feat(uart) 3.1.x Core: fixes serialEventRun() to avoid calling available() if serialEvent() is not declared

cores/esp32/HardwareSerial.cpp
Applies #10428 to Arduino Core 2.0.x
Same as #10428 
Related to #10397
=> fix(uart) 2.0.x Core: fixes serialEventRun() to avoid calling available() if serialEvent() is not declared

tests/validation/psram/ci.json, tests/validation/psram/psram.ino, tests/validation/psram/test_psram.py
Add validation test for PSRAM
CI and Locally
=> test(psram): Add PSRAM test

README.md, package.json
-----------
Updates the Package description to add the P4 in 3.1.0
N/A
N/A
=> fix(arduino): adds ESP32-P4 to the package description

libraries/AsyncUDP/src/AsyncUDP.cpp
Implements and fixes TCPIP Core locking in AsyncUDP when enabled.
AsyncUDP calls Raw LwIP APIs that are not safe to call from other threads without locking. While some raw APIs are being [called by using `tcpip_api_call()`](https://github.com/espressif/arduino-esp32/blob/733373a049d8a06fab00628bcae585550fac6d07/libraries/AsyncUDP/src/AsyncUDP.cpp#L48-L135), other calls are not considering this method, as [[1]](https://github.com/espressif/arduino-esp32/blob/733373a049d8a06fab00628bcae585550fac6d07/libraries/AsyncUDP/src/AsyncUDP.cpp#L31), [[2]](https://github.com/espressif/arduino-esp32/blob/733373a049d8a06fab00628bcae585550fac6d07/libraries/AsyncUDP/src/AsyncUDP.cpp#L476-L481), [[3]](https://github.com/espressif/arduino-esp32/blob/733373a049d8a06fab00628bcae585550fac6d07/libraries/AsyncUD …
=> fix(asyncudp): Fixes and implements tcpip thread locking

cores/esp32/HardwareSerial.cpp, cores/esp32/HardwareSerial.h, cores/esp32/esp32-hal-uart.c
Add missing HP UART 3 and 4 for ESP32-P4
=> fix(uart): Add missing HP UARTs for ESP32-P4

boards.txt, variants/waveshare_esp32_s3_touch_amoled_18/pins_arduino.h
Adding variant for Waveshare ESP32-S3-Touch-AMOLED-1.8 board containing MCU, AMOLED, RTC, and IMU.
Untested,Pre-publisher board definition
processed USB VID PR: [espressif/usb-pids/pull/194](https://github.com/espressif/usb-pids/pull/194)
=> Added variant for Waveshare ESP32-S3-Touch-AMOLED-1.8

idf_component.yml
Current esp_insights version in idf_component.yml (^1.0.1) pulls following versions of required components
`esp_insights : 1.0.1`
`esp_diagnostics: 1.0.2`
`esp_diag_data_store : 1.0.2`
With latest update to esp-insights and its components,  `esp_insights: 1.0.1` is not compatible with `esp_diag_data_store: 1.0.2` which causes compilation errors while building core. 
Updating `esp_insights` version to `1.2.1` fixes the issue. 
Reproduced issue with Arduino-esp32 3.0.5 for  ESP32 S3 and ESPC3 boards. After this change build was successful. 
[Latest Changes to esp-insights](https://github.com/espressif/esp-insights/commit/bbe13d1897b8272dc7bc350bd805e8852722e48d)
=> Update esp-insights version

boards.txt, variants/waveshare_esp32_s3_touch_lcd_4/pins_arduino.h, variants/waveshare_esp32_s3_touch_lcd_43/pins_arduino.h, variants/waveshare_esp32_s3_touch_lcd_43b/pins_arduino.h, variants/waveshare_esp32_s3_touch_lcd_5/pins_arduino.h, variants/waveshare_esp32_s3_touch_lcd_5b/pins_arduino.h, variants/waveshare_esp32_s3_touch_lcd_7/pins_arduino.h
Adding variant for Waveshare ESP32-S3-Touch-LCD-4 & ESP32-S3-Touch-LCD-4.3 & ESP32-S3-Touch-LCD-4.3B & ESP32-S3-Touch-LCD-5 & ESP32-S3-Touch-LCD-5B ESP32-S3-Touch-LCD-7 board
Untested, pin definition is based on information in Waveshare wiki.
Wiki for [ESP32-S3-Touch-LCD-4](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4)
Wiki for [ESP32-S3-Touch-LCD-4.3](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4.3)
Wiki for [ESP32-S3-Touch-LCD-4.3B](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4.3B)
Wiki for [ESP32-S3-Touch-LCD-5](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-5)
Wiki for [ESP32-S3-Touch-LCD-5B](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-5)
Wiki for [ESP32-S3-Touch-LCD-7](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-7)
=> addition(3rd_party_board): Add Waveshare-S3-touch-lcd

boards.txt, variants/atd35s3/pins_arduino.h, variants/ioxesp32c6/pins_arduino.h
This Pull Request add support to three new hardware on the market using ESP32-C6 and ESP32-S3 modules, IOXESP32-C6, ATD3.5-S3. Links to the hardware is provided below
IOXESP32-C6
https://www.artronshop.co.th/product/647/ioxesp32-c6-%E0%B8%9A%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%94-esp32-c6-%E0%B9%80%E0%B8%8A%E0%B8%B7%E0%B9%88%E0%B8%AD%E0%B8%A1%E0%B8%95%E0%B9%88%E0%B8%AD-wifi-6-bluetooth-5-thread-zigbee
ATD3.5-S3
https://www.artronshop.co.th/product/567/atd3-5-s3-%E0%B8%9A%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%94-esp32-s3-%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%88%E0%B8%AD-3-5-%E0%B8%99%E0%B8%B4%E0%B9%89%E0%B8%A7-%E0%B8%97%E0%B8%B1%E0%B8%8A-capacitive
These boards are used by Students, Maker and Engineer in Thailand
I have tested my Pull Request on Arduino-esp32 core v3.0.5 with real …
=> Add IOXESP32-C6 and ATD3.5-S3 board

libraries/ESP32/examples/AnalogOut/LEDCFade/LEDCFade.ino
Fixes print of fade direction in ledcFade example.
Locally
=> fix(example): print correct fade direction

idf_component.yml
Update esp-rainmaker version to 1.5.0 as asked in https://github.com/espressif/arduino-esp32/pull/10456
(New PR targeting `release 3.0.x` as asked [here](https://github.com/espressif/arduino-esp32/pull/10470#issuecomment-2416592275))
=> fix(esp-rainmaker): update esp-rainmaker version to 1.5.0

boards.txt, libraries/Ethernet/examples/ETH_LAN8720/ETH_LAN8720.ino, libraries/Ethernet/examples/ETH_TLK110/ETH_TLK110.ino, libraries/Ethernet/examples/ETH_TLK110/ci.json, libraries/Ethernet/examples/ETH_W5500_Arduino_SPI/ETH_W5500_Arduino_SPI.ino, libraries/Ethernet/examples/ETH_W5500_IDF_SPI/ETH_W5500_IDF_SPI.ino, libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h, variants/esp32p4/pins_arduino.h
Also adds default config to the P4 pins_arduino.h
=> Add RMII Ethernet support for ESP32-P4

platform.txt
Fix sdkconfig copy when using Arduino CLI with board manager.
Locally and fork.
=> fix(build): Fix sdkconfig copy for board manager

.editorconfig, .github/scripts/install-platformio-esp32.sh, .github/scripts/sketch_utils.sh, .github/scripts/tests_run.sh, docs/en/contributing.rst
As we can easily change the flash mode for some sketch to DIO, lets switch the default back to QIO so we match the IDE default.
Also add the `requires_any` field to the JSON so we can match requirements in a OR configuration. This will be useful for sketches that require one option or the other, for example the sketches that require WiFi connectivity needs either `CONFIG_SOC_WIFI_SUPPORTED=y` or `CONFIG_ESP_WIFI_REMOTE_ENABLED=y`.
Also add some QoL improvements.
CI
=> ci(json): Add requires_any field and use QIO by default to match IDE

CMakeLists.txt, cores/esp32/esp32-hal-touch-ng.c, cores/esp32/esp32-hal-touch-ng.h, cores/esp32/esp32-hal-touch.c, cores/esp32/esp32-hal.h, cores/esp32/io_pin_remap.h, libraries/ESP32/examples/DeepSleep/TouchWakeUp/TouchWakeUp.ino, libraries/ESP32/examples/DeepSleep/TouchWakeUp/ci.json, libraries/ESP32/examples/Touch/TouchInterrupt/TouchInterrupt.ino, libraries/ESP32/examples/Touch/TouchInterrupt/ci.json, libraries/ESP32/examples/Touch/TouchRead/ci.json, tests/validation/touch/ci.json, tests/validation/touch/touch.ino
This PR adds support for the new NG Touch Driver, which is currently supports touch V3 (ESP32-P4). There is work in progress for V2 and later for V1 touch versions to be supported by the new touch driver.
The new touch driver is implemented the way, to keep backward compatibility with the old APIs.
To get more features as multiple sampling on different frequencies, we may add/change APIs a bit.
Tested locally on P4, also using the touch HW test.
NOTE: Touch deep sleep wakeup is currently not working, fix is needed on driver side. The implementation should be ready.
NOTE 2: Fix is ready and will be merged to IDF master and v5.3 branch.
=> feat(touch): Support NG touch driver for P4

.github/scripts/tests_matrix.sh, .github/workflows/dangerjs.yml, .github/workflows/tests.yml, .github/workflows/tests_results.yml, .github/workflows/tests_wokwi.yml, tests/performance/coremark/coremark.ino, tests/performance/fibonacci/fibonacci.ino, tests/performance/fibonacci/test_fibonacci.py, tests/performance/psramspeed/ci.json, tests/performance/psramspeed/psramspeed.ino, tests/performance/ramspeed/ramspeed.ino, tests/performance/superpi/superpi.ino, tests/requirements.txt, tests/validation/gpio/test_gpio.py, tests/validation/nvs/test_nvs.py, tests/validation/periman/test_periman.py, tests/validation/psram/ci.json, tests/validation/wifi/test_wifi.py
- Fixes Wokwi test so it will check out the proper base branch where the PR is being merged
- Add logging to some tests
- Fixes debug output of some tests
- Improve fibonacci test
- Remove redundant targets from some tests JSON
- Make DangerJS more permissive and improve some CI messages
- Update `pytest-embedded` to support P4
Local and CI in fork
=> fix(testing): Checkout proper branch for Wokwi tests and small QoL improvements

.pre-commit-config.yaml, CMakeLists.txt, cores/esp32/esp32-hal-tinyusb.c, libraries/Matter/examples/MatterCommissionTest/MatterCommissionTest.ino, libraries/Matter/examples/MatterCommissionTest/ci.json, libraries/Matter/examples/MatterComposedLights/MatterComposedLights.ino, libraries/Matter/examples/MatterComposedLights/ci.json, libraries/Matter/examples/MatterOnOffLight/MatterOnOffLight.ino, libraries/Matter/examples/MatterOnOffLight/ci.json, libraries/Matter/keywords.txt, libraries/Matter/library.properties, libraries/Matter/src/Matter.cpp, libraries/Matter/src/Matter.h, libraries/Matter/src/MatterEndPoint.h, libraries/Matter/src/MatterOnOffLight.cpp, libraries/Matter/src/MatterOnOffLight.h, libraries/USB/src/USBHID.cpp
Implementation of Matter Library for ESP32 Arduino Core.
Matter is implemented over WiFi.
Commissioning is done using the Pairing Code or the QRCode from an URL.
Initial Device implmented is a on/off Light.
The Library allow adding more than one endpoint to a matter node.
ESP32 / ESP32-S2 / ESP32-S3 / ESP32-C3 / ESP32-C6
Testing done using Alexa Echo Dot and the examples from the Matter Library.
=> feat(matter): initial commit with arduino matter lib

.github/scripts/find_new_boards.sh
Changed the way to get the modified lines in boards to make the script work for PRs with more changes to boards.txt file, as the "Patch" in json is missing if there is a lot of lines changed.
Tested script locally.
=> fix(ci): Chnage approach in listing the changed boards

CMakeLists.txt
This is a mandatory depedency of the LittleFS library. Without this fix the library won't compile with idf component manager is disabled.
=> fix(littlefs): Add missing dependency

.github/workflows/push.yml
Add missing `CMakeLists.txt` and variant files to trigger compilation tests.
=> fix(tests): Add missing files to compilation tests

libraries/Zigbee/examples/Zigbee_Color_Dimmable_Light/Zigbee_Color_Dimmable_Light.ino, libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/Zigbee_Color_Dimmer_Switch.ino, libraries/Zigbee/examples/Zigbee_On_Off_Light/Zigbee_On_Off_Light.ino, libraries/Zigbee/examples/Zigbee_Temperature_Sensor/Zigbee_Temperature_Sensor.ino, libraries/Zigbee/examples/Zigbee_Thermostat/Zigbee_Thermostat.ino
Configure `BUTTON_PIN`/`SWITCH_PIN` as an input and enable the internal pull-up resistor.
I am facing a factory reset loop using a Waveshare ESP32-H2-DEV-KIT-N4 board witout enabling pull-up.
I tested this with :
Waveshare ESP32-H2-DEV-KIT-N4 board
ESP32-C6-WROOM-1 board
=> fix(zigbee): Enable the internal pull-up resistor for BUTTON_PIN

.github/workflows/boards.yml
Add fail-fast: false to the boards.yml, so failure of 1 board does not cancel other boards to run.
=> fix(ci): Boards test set fail-fast to false

libraries/ESP_I2S/src/ESP_I2S.cpp
When reading and writing we should use separate variables for what we are sending/receiving and what has actually been sent/received. Failing to do so may cause wrong data on the output
=> fix(i2s): Use separate variables when reading and writing

libraries/BLE/src/BLEAdvertising.cpp
Fix #10511 
Changes in comments only. You should see all AD type codes in the surrounding code provided by the diff.
Impact: improve readability and understanding of the code for future readers (like myself)
None. This is just related to reading of the source code.
Closes #10511 
https://github.com/espressif/arduino-esp32/issues/10511
=> fix(ble): Fixed typos (or copy/paste issues) in comments for AD types in BLEAdvertising

libraries/Ethernet/src/ETH.cpp
When Arduino is used as component, `CONFIG_ETH_RMII_CLK_IN_GPIO` might not be defined, so we set it to const `0` to clear the issue.
Fixes: https://github.com/espressif/arduino-esp32/issues/10440
=> fix(eth): Set default clock in pin value to zero

libraries/Update/src/Update.h, libraries/Update/src/Updater.cpp
I'm using OTA with pre-encrypted bin file.
So it's easy to calculate the MD5 of the encrypted file before send it to device.
Update function at the moment is calculating the MD5 of the decrypted file.
With this commit with
`Update.setMD5(md5, false);`
the check of MD5 will be done of encrypted file. Otherwise it will be calculate of the decrypted file.
I have tested my Pull Request on Arduino-esp32 core v3.0.6 with ESP32
=> Update lib - User can choose if calc MD5 from encrypted or decrypted file

CMakeLists.txt, cores/esp32/Arduino.h, cores/esp32/freertos_stats.cpp, cores/esp32/freertos_stats.h
Example output on ESP32-P4 with WiFi and ETH running:
```
Tasks: 17, Runtime: 151s, Period: 2083447us
Num	            Name	     Load	Prio	 Free	Core	State
8	        loopTask	       0%	   1	 5736	   1	Running
5	           IDLE0	      99%	   0	  684	   0	Ready
6	           IDLE1	      99%	   0	  748	   1	Ready
10	             tiT	       0%	  18	 3664	   0	Blocked
12	  arduino_events	       0%	  19	 2384	   1	Blocked
17	      sdio_write	       0%	  23	 4304	   *	Blocked
1	            ipc0	       0%	  24	  716	   0	Suspended
19	          rpc_tx	       0%	  23	 4240	   *	Blocked
7	         Tmr Svc	       0%	   1	 1708	   *	Blocked
18	          rpc_rx	       0%	  23	 3068	   *	Blocked
3	       esp_timer	       0%	  22	 4292	   0	Suspended
13	         emac_rx	       0%	  15	 3568	   *	Suspended …
```
=> feature(rtos): Add Tasks status print function

cores/esp32/HardwareSerial.cpp, cores/esp32/HardwareSerial.h, tests/validation/uart/uart.ino
ESP32-P4 has UART default pins only for UART0 and UART1.
This PR allows the board definition from pins_arduino.h to define RX2 ... RX4 and TX2 ... TX4 if necessary.
It also solves the issue of begin(baud) with no pins for UART2...4 by just sending an error message and returning doing nothing.
ESP32-P4
``` cpp
void setup(){
// UART parameters shall be visible in the logs using Verbose mode
Serial.println("=============================================");
Serial1.begin(115200); // no error message as there are default pins
Serial.println("=============================================");
Serial2.begin(115200); // it shall send an error because there are no default pins
Serial.println("=============================================");
Serial2.begin(115200, SERIAL_8N1, 14, …
```
=> ESP32-P4 UART Pin Definitions

libraries/ESP32/examples/Serial/OnReceiveError_BREAK_Demo/OnReceiveError_BREAK_Demo.ino
Prints the received byte as HEXA and CHAR in order to allow the user to see why there is 1 extra char (0x00) when BREAK is received.
Targets 3.0.x and 3.1.x
Using P4/S3 with  libraries/ESP32/examples/Serial/OnReceiveError_BREAK_Demo/OnReceiveError_BREAK_Demo.ino
```
================================
Test Case #3 BREAK at END
================================
Testing onReceive for receiving 26 bytes at 9600 baud, using RX FIFO Full = 5.
onReceive is called on both FIFO Full and RX Timeout events.
BREAK event will be sent at the END of the 26 bytes
onReceive Callback:: There are 5 bytes available: {0x41='A' 0x42='B' 0x43='C' 0x44='D' 0x45='E'}
onReceive Callback:: There are 5 bytes available: {0x46='F' 0x47='G' 0x48='H' 0x49='I' 0x4a='J'}
onReceive Callback:: There are 10 bytes available: …
```
=> feat(uart): uart break example improvement

package/package_esp32_index.template.json
=> feat(esptool): Update esptool to v4.8.1

package/package_esp32_index.template.json
On some Windows installations, Board Manager will fail to install the RC2 core, because it could not find esptool for the given OS.
=> fix(bm): Board Manager install will fail on Windows

cores/esp32/esp32-hal-time.c
Calling `configTime` and `configTzTime` crashes with error message: "Required to lock TCPIP core functionality" on Arduino 3.1.0 RC2 following activation of `LWIP_TCPIP_CORE_LOCKING` and `LWIP_CHECK_THREAD_SAFETY` for Matter.
Fixes: https://github.com/espressif/arduino-esp32/issues/10526
=> fix(sntp): Lock / Unlock LWIP if CONFIG_LWIP_TCPIP_CORE_LOCKING is set

.github/scripts/set_push_chunks.sh, .github/workflows/pre-commit.yml, .github/workflows/push.yml, .github/workflows/tests.yml, tests/requirements.txt, tools/pre-commit/requirements.txt
This PR aims to fix a few things with CI:
- Bump `pre-commit` and `pytest-embedded` versions. P4 tests will work as expected after this.
- Make sure that pushes to `release/*` branches will not trigger PR workflows if one is open, only push workflows.
- Make sure that changing libraries' sketches will not trigger runtime tests
- Sometimes `pre-commit` acts funky. Add a manual re-trigger label to force execution until some permanent solution can be found.
- Fix the detection of libs and formatting of the chunk generator script
Tested in fork
=> ci(workflows): General improvements and fixes

idf_component.yml, libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp, libraries/Zigbee/src/ep/ZigbeeThermostat.cpp
Fixes changes on Zigbee 1.6.0 version and keep that version fixed in idf_component.yml
Requires https://github.com/espressif/arduino-esp32/pull/10544
=> fix(zigbee): Fix and bump zigbee version and stay on 1.6.0

tools/get.py
Check if win32 binaries also exist when compiling in win64. Also set the CWD of the script to the file location so it will always extract to the proper place
Locally
=> fix(get.py): Check if win32 tools also exist when running on win64

.github/scripts/tests_run.sh
Depending on the order of actions when running tests locally. Wokwi can execute it's test with an out of date diagram file.
To avoid that we can delete any existing generated diagrams so we ensure that a new one is properly created when executing the tests.
=> fix(wokwi): Delete generated diagram to avoid issues running locally

cores/esp32/IPAddress.cpp
This PR restores the IPv6 zone-id in String representation of IPv6 address as well as parsing. This follows https://github.com/espressif/arduino-esp32/commit/20a28b58bc3fd5ff613e2860d65e0953446f264b that disabled it due to a crash in netif_index_to_name() …
=> fix(IPaddress): IPv6 restore zone id

package/package_esp32_index.template.json, platform.txt
Bump `esptool` version to v4.9.dev1 on branch `release/v3.1.x`.
It includes adding back binaries for macOS x86_64 and fixes for USB resetting on S2 and S3.
#6762
=> fix(esptool): Bump esptool version to 4.9.dev1 on 3.1.x

package/package_esp32_index.template.json, platform.txt, tools/get.py
Bump `esptool` version to v4.9.dev1 on branch `release/v3.0.x`.
It includes adding back binaries for macOS x86_64 and fixes for USB resetting on S2 and S3.
#6762
=> fix(esptool): Bump esptool version to 4.9.dev1 on 3.0.x

libraries/Zigbee/src/ZigbeeEP.cpp, libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp
Remove cluster_role from attribute command structure, as it was removed in the last zigbee-sdk 1.6.0
=> fix(zigbee): Fix removed cluster_role attribute

.github/scripts/sketch_utils.sh, .github/scripts/tests_run.sh
Using the `-k` flag in the pytest command might run more than the selected test. For example using `-k test_psram` will run both `test_psram` and `test_psramspeed`. To fix this we can directly pass the python file for the test.
Also, to help with testing, added a `-d` flag to the compilation process. This will be useful to compile tests with debug logs enabled. For example:
`./.github/scripts/tests_build.sh -s uart -t esp32 -d verbose`
Tested locally
=> fix(tests): Fix wrong selection of tests and add debug flag for testing

CMakeLists.txt, libraries/USB/src/USBHIDKeyboard.cpp, libraries/USB/src/USBHIDKeyboard.h, libraries/USB/src/keyboardLayout/KeyboardLayout.h, libraries/USB/src/keyboardLayout/KeyboardLayout_da_DK.cpp, libraries/USB/src/keyboardLayout/KeyboardLayout_de_DE.cpp, libraries/USB/src/keyboardLayout/KeyboardLayout_en_US.cpp, libraries/USB/src/keyboardLayout/KeyboardLayout_es_ES.cpp, libraries/USB/src/keyboardLayout/KeyboardLayout_fr_FR.cpp, libraries/USB/src/keyboardLayout/KeyboardLayout_hu_HU.cpp, libraries/USB/src/keyboardLayout/KeyboardLayout_it_IT.cpp, libraries/USB/src/keyboardLayout/KeyboardLayout_pt_BR.cpp, libraries/USB/src/keyboardLayout/KeyboardLayout_pt_PT.cpp, libraries/USB/src/keyboardLayout/KeyboardLayout_sv_SE.cpp, libraries/USB/src/keyboardLayout/Keyboard_da_DK.h, libraries/USB/src/keyboardLayout/Keyboard_de_DE.h, libraries/USB/src/keyboardLayout/Keyboard_es_ES.h, libraries/USB/src/keyboardLayout/Keyboard_fr_FR.h, libraries/USB/src/keyboardLayout/Keyboard_hu_HU.h, libraries/USB/src/keyboardLayout/Keyboard_it_IT.h, libraries/USB/src/keyboardLayout/Keyboard_pt_BR.h, libraries/USB/src/keyboardLayout/Keyboard_pt_PT.h, libraries/USB/src/keyboardLayout/Keyboard_sv_SE.h
This PR fixes a problem related to sending just modifier key pressing/releasing (SHIFT/CTRL/ALT).
It also adds the upstream Keyboard Layouts to the library.
Additionally it adds the Brazilian ABNT2 Keyboard Layout.
Tested with ESP32-S3 using a Keyboard Test website.
Configuration: CDC on Boot: Disabled || USB Mode: OTG(TinyUSB)
``` cpp
#include "USB.h"
#include "USBHIDKeyboard.h"
USBHIDKeyboard Keyboard;
const int buttonPin = 0;  // input pin for pushbutton
void setup() {
// make pin 0 an input and turn on the pull-up resistor so it goes high unless
// connected to ground:
pinMode(buttonPin, INPUT_PULLUP);
while (!Serial) delay(100);
Serial.println();
Serial.println("Starting USB Keyboard Device.");
Serial.println();
Keyboard.begin();
USB.begin();
}
void …
```
=> feat(usb_hid_keyboard): Adds Keyboard Layout and Sends reports just for Modifier Keys

libraries/WiFi/src/WiFiSTA.cpp
After 3.0.x (including 3.1.x) the function `WiFiSTAClass::isConnected()` returns when it is connected to the WiFi AP but not necessarily when it has an IP address.
This is a breaking change because 2.0.x only returns true when both, it is connected and it has an IP.
This PR fixes it.
``` cpp
#include <WiFi.h>
const char *SSID = "xxx";
const char *PSK = "xxx";
void setup()
{
while (!Serial)
delay(10);
Serial.println("connecting..");
WiFi.begin(SSID, PSK);
while (!WiFi.isConnected())
delay(10);
Serial.println(WiFi.localIP());
}
void loop()
{
delay(1000);
Serial.println(WiFi.localIP());
}
```
Fix #10580
=> fix(wifi): fixes WiFi.isconnected() to return true when it is connected and it has an IP Addr

cores/esp32/IPAddress.cpp, cores/esp32/IPAddress.h, libraries/AsyncUDP/src/AsyncUDP.cpp, libraries/AsyncUDP/src/AsyncUDP.h, libraries/Ethernet/src/ETH.cpp, libraries/Network/src/NetworkClient.cpp, libraries/Network/src/NetworkEvents.h, libraries/Network/src/NetworkInterface.cpp, libraries/Network/src/NetworkInterface.h, libraries/Network/src/NetworkManager.cpp, libraries/Network/src/NetworkServer.cpp, libraries/Network/src/NetworkUdp.cpp, libraries/NetworkClientSecure/src/ssl_client.cpp, libraries/WiFi/src/AP.cpp, libraries/WiFi/src/STA.cpp, libraries/WiFi/src/WiFiAP.cpp, libraries/WiFi/src/WiFiAP.h, libraries/WiFi/src/WiFiGeneric.cpp, libraries/WiFi/src/WiFiGeneric.h, libraries/WiFi/src/WiFiMulti.cpp, libraries/WiFi/src/WiFiMulti.h, libraries/WiFi/src/WiFiSTA.cpp, libraries/WiFi/src/WiFiSTA.h, libraries/WiFi/src/WiFiScan.h, libraries/WiFi/src/WiFiType.h, libraries/WiFiProv/src/WiFiProv.cpp, libraries/WiFiProv/src/WiFiProv.h
=> fix(net): Allow to compile without IPv6 enabled

CMakeLists.txt, libraries/ArduinoOTA/src/ArduinoOTA.cpp, libraries/ESP_I2S/src/ESP_I2S.cpp, libraries/ESP_I2S/src/ESP_I2S.h, libraries/ESPmDNS/src/ESPmDNS.cpp, libraries/ESPmDNS/src/ESPmDNS.h, libraries/LittleFS/src/LittleFS.cpp, libraries/LittleFS/src/LittleFS.h, libraries/PPP/src/PPP.cpp, libraries/PPP/src/PPP.h, libraries/PPP/src/ppp.c
This adds guards for the rest of the extra components
=> fix(build): Allow Arduino to compile in IDF without components

variants/m5stack_fire/pins_arduino.h
I just ran into this issue. The wrong pin is defined in `pinsArduino.h`.
The correct SS pin for the TF reader is GPIO4.
See the screenshot below from https://github.com/m5stack/m5unified
I have tested my Pull Request on Arduino-esp32 core v3.0.7 with a M5Stack Fire with this scenario
I could not find related issues.
=> fix(M5Stack Fire): Fixed TF reader SS pin value.

boards.txt
Default stays the same, additional option for larger SPIFFS area. Using existing partition CSV.
tested on Adafruit Feather V2
Arduino 2.3.3
ESP32 BSP 3.0.7
=> Feat: Feather V2 and Qt PY larger SPIFFS PartitionScheme

cores/esp32/esp32-hal-cpu.c
=> fix weird formatting, no code change

libraries/Matter/examples/MatterDimmableLight/MatterDimmableLight.ino, libraries/Matter/examples/MatterOnOffLight/MatterOnOffLight.ino
A change to improve the code and the make it clearer to read and understand how Preference are being used in the code.
ESP32-S3 and CI using the example
https://github.com/espressif/arduino-esp32/discussions/10542#discussioncomment-11286224
=> Matter example patch

libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h, libraries/Network/src/NetworkEvents.h, libraries/WiFi/src/WiFiGeneric.h
Currently it is not possible to switch off Ethernet support in IDF and compile Arduino as an component. This PR adds guards to make it possible to compile only with WiFi and no Ethernet.
Follow up from #10597
@me-no-dev
=> Guard ethernet parts to make it possible to use without

libraries/WiFi/src/STA.cpp, libraries/WiFi/src/WiFiSTA.cpp, libraries/WiFi/src/WiFiSTA.h
enable WPA Enterprise code part only if support is there in the compiled Arduino libs.
Follow up of #10609 
@me-no-dev
=> Guard WPA Enterprise support

libraries/Zigbee/examples/Zigbee_Color_Dimmable_Light/Zigbee_Color_Dimmable_Light.ino, libraries/Zigbee/examples/Zigbee_On_Off_Light/Zigbee_On_Off_Light.ino, libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp, libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.h, libraries/Zigbee/src/ep/ZigbeeLight.cpp, libraries/Zigbee/src/ep/ZigbeeLight.h
This PR adds APIs to the light endpoints to enable controlling them by itself.
The status of the Light is updated in the clusters, so the actual state is updated in the Smart home apps.
Tested locally with HomeAssistant.
=> feat(zigbee): Add setLight APIs to manually operate lights

libraries/OpenThread/examples/COAP/coap_lamp/coap_lamp.ino, libraries/OpenThread/examples/COAP/coap_switch/coap_switch.ino, libraries/OpenThread/examples/SimpleCLI/SimpleCLI.ino, libraries/OpenThread/examples/SimpleNode/SimpleNode.ino, libraries/OpenThread/examples/SimpleThreadNetwork/ExtendedRouterNode/ExtendedRouterNode.ino, libraries/OpenThread/examples/SimpleThreadNetwork/LeaderNode/LeaderNode.ino, libraries/OpenThread/examples/SimpleThreadNetwork/RouterNode/RouterNode.ino, libraries/OpenThread/examples/ThreadScan/ThreadScan.ino, libraries/OpenThread/examples/onReceive/onReceive.ino, libraries/OpenThread/src/OThreadCLI.cpp, libraries/OpenThread/src/OThreadCLI.h, libraries/OpenThread/src/OThreadCLI_Util.cpp, libraries/OpenThread/src/OThreadCLI_Util.h
This PR adds License information to OpenThread source code and examples.
None - Just CI.
None.
=> feat(openthread): add license declaration to all soure code and examples

libraries/Matter/examples/MatterMinimum/MatterMinimum.ino, libraries/Matter/examples/MatterMinimum/ci.json
Adds the minimum Matter Accessory example code in order to ilustrate how simple it is to work with the new ESP32 Arduino Matter Library.
ESP32-S3 with the provided example
=> Adds a Minimum Code Matter Example

cores/esp32/esp32-hal-cpu.c
Compile of P4 sketches do fail when log debug is enabled.
@me-no-dev
=> fix compile of P4 caused from missing ")" in debug macro

cores/esp32/esp32-hal-uart.c, libraries/OpenThread/examples/COAP/coap_lamp/coap_lamp.ino, libraries/OpenThread/examples/COAP/coap_switch/coap_switch.ino, libraries/OpenThread/examples/SimpleCLI/SimpleCLI.ino, libraries/OpenThread/examples/SimpleNode/SimpleNode.ino, libraries/OpenThread/examples/SimpleThreadNetwork/ExtendedRouterNode/ExtendedRouterNode.ino, libraries/OpenThread/examples/SimpleThreadNetwork/LeaderNode/LeaderNode.ino, libraries/OpenThread/examples/SimpleThreadNetwork/RouterNode/RouterNode.ino, libraries/OpenThread/examples/ThreadScan/ThreadScan.ino, libraries/OpenThread/examples/onReceive/onReceive.ino, libraries/OpenThread/src/OThreadCLI.cpp, libraries/OpenThread/src/OThreadCLI.h, libraries/OpenThread/src/OThreadCLI_Util.cpp, libraries/OpenThread/src/OThreadCLI_Util.h
ESP32 and ESP32S2 use REF_TICK as UART clock source whenever the baud rate is lower then 250,000.
This is done within `HardwareSerial::begin(uint32_t baud)`
This prevents issues with chaning the APB clock to lower than 40MHz, specially when achieving lower power consumpition.
This PR also fixes it for the `HardwareSerial::updateBaudRate(uint32_t baud)` by checking the target baud rate and adjusting the UART Clock Source that will make it work correctly.
Using this sketch (from the issue report) using ESP32 and ESP32S2
``` cpp
void setup() {
// put your setup code here, to run once:
delay(500);
Serial1.begin(230400);
Serial.printf("%d\n", Serial1.baudRate());
// Clock is now UART_SCLK_REF_TICK
Serial1.updateBaudRate(460800);
Serial.printf("%d\n", Serial1.baudRate()); …
```
=> feat(uart): [IDF5.1] fixes HardwareSerial::updateBaudRate() using a baud rate higher 230400 - checks UART Clock Source

cores/esp32/esp32-hal-uart.c
ESP32 and ESP32S2 use REF_TICK as UART clock source whenever the baud rate is lower then 250,000.
This is done within `HardwareSerial::begin(uint32_t baud)`
This prevents issues with chaning the APB clock to lower than 40MHz, specially when achieving lower power consumpition.
This PR also fixes it for the `HardwareSerial::updateBaudRate(uint32_t baud)` by checking the target baud rate and adjusting the UART Clock Source that will make it work correctly.
Using this sketch (from the issue report) using ESP32 and ESP32S2
``` cpp
void setup() {
// put your setup code here, to run once:
delay(500);
Serial1.begin(230400);
Serial.printf("%d\n", Serial1.baudRate());
// Clock is now UART_SCLK_REF_TICK
Serial1.updateBaudRate(460800);
Serial.printf("%d\n", Serial1.baudRate()); …
```
=> feat(uart): [IDF 5.3] fixes HardwareSerial::updateBaudRate() using a baud rate higher 230400 - checks UART Clock Source

boards.txt, libraries/Zigbee/examples/Zigbee_Color_Dimmable_Light/Zigbee_Color_Dimmable_Light.ino, libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/Zigbee_Color_Dimmer_Switch.ino, libraries/Zigbee/examples/Zigbee_On_Off_Light/Zigbee_On_Off_Light.ino, libraries/Zigbee/examples/Zigbee_On_Off_Switch/Zigbee_On_Off_Switch.ino, libraries/Zigbee/examples/Zigbee_Scan_Networks/Zigbee_Scan_Networks.ino, libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino, libraries/Zigbee/examples/Zigbee_Temperature_Sensor/Zigbee_Temperature_Sensor.ino, libraries/Zigbee/examples/Zigbee_Thermostat/Zigbee_Thermostat.ino, libraries/Zigbee/keywords.txt, libraries/Zigbee/src/ZigbeeCore.cpp, libraries/Zigbee/src/ZigbeeCore.h, libraries/Zigbee/src/ZigbeeEP.cpp, libraries/Zigbee/src/ZigbeeEP.h, libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.h
This PR adds Zigbee.conneted() function and the Zigbee.begin() is now blocking until the Zigbee is started.
Some minor API changes + example updates.
=> fix(zigbee): Add connected(), minor fixes, example update

libraries/Zigbee/keywords.txt, libraries/Zigbee/src/ZigbeeCore.cpp, libraries/Zigbee/src/ZigbeeCore.h
This PR adds a fix, so there is no need to restart the device after commissioning fails.
The Zigbee will try to connect for 30s to the already joined network, if not successful the `Zigbee.begin()` returns `false` meaning a need to device restart.
Also added an API to set the scan duration, used when discovering the networks when trying to join.
By default I set the biggest value 4. It can be set within 1-4. 
Tested locally, no need for device restart at all now.
Always connects / rejoins.
#10612
#10601
=> fix(zigbee): Increase timeout, commision again on failure + setScanDuration

libraries/Matter/examples/WiFiProvWithinMatter/WiFiProvWithinMatter.ino, libraries/Matter/examples/WiFiProvWithinMatter/ci.json
WiFi Prov based on BLE or SoftAP can be used for WiFi Network provisioning within Matter Accessories.
This is an alternative that helps application that don't want to fix any SSID/Password in the code.
This example can be used with an other sort of WiFi Provisioning, including, for instance, WiFi Manager Library.
Tested with ESP32-S3 and the provided example.
=> feat(matter): New example => Wifi Prov within Matter as alternative for wireless network provisioning

CMakeLists.txt, libraries/Matter/examples/MatterSmartButon/MatterSmartButon.ino, libraries/Matter/examples/MatterSmartButon/ci.json, libraries/Matter/keywords.txt, libraries/Matter/src/Matter.h, libraries/Matter/src/MatterEndpoints/MatterGenericSwitch.cpp, libraries/Matter/src/MatterEndpoints/MatterGenericSwitch.h
Adds a new matter endpoint for a generic switch that works as a smart button.
This endpoint is supported by Amazon Alexa and Samsung SmartThings.
This is not cleatr if Google HA has implemented it on their Matter Controllers.
This endpoint can send a `click()` command to the Matter Controller.
It can be programmed to trigger 1 or more actions that will be stored in the Controller (example Alexa Echo Dot).
Tested with ESP32-S3, ESP32-C6 and ESP32 using the provided example.
=> feat(matter): Adds a new Matter Endpoint: Generic Switch (smart button)

libraries/BLE/src/BLECharacteristic.cpp
In various places in BLECharacteristic .cpp, costly operations are performed to prepare debug strings, but those debug strings are never used because the log level doesn't permit it. This PR prevents preparing those debug strings according to the log level.
I've compiled this PR with a large BLE projects involving a chain of 3 BLE devices, using both ESP32-WROOM and ESP32-S3.
=> BLECharacteristic optimization

tests/validation/uart/diagram.esp32.json, tests/validation/uart/uart.ino
Refactors UART test to handle any number of UART peripherals.
Also add a diagram file for esp32 to set the simulation CPU frequency to 40 MHz. Sometimes Wokwi simulation can fail with the default value.
Note that the Wokwi UART test for ESP32 will fail until this PR is merged.
Tested locally and CI.
=> refactor(uart): Refactor UART test to work with any number of UARTs

libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/Zigbee_Color_Dimmer_Switch.ino, libraries/Zigbee/examples/Zigbee_On_Off_Switch/Zigbee_On_Off_Switch.ino, libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino, libraries/Zigbee/src/ZigbeeCore.cpp, libraries/Zigbee/src/ZigbeeCore.h, libraries/Zigbee/src/ZigbeeEP.cpp, libraries/Zigbee/src/ZigbeeEP.h, libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.cpp, libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.h, libraries/Zigbee/src/ep/ZigbeeSwitch.cpp, libraries/Zigbee/src/ep/ZigbeeSwitch.h, libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp, libraries/Zigbee/src/ep/ZigbeeThermostat.cpp
This PR adds new feature/fix to recall bounded devices from the binding table after device reboot, with that also the isBound() will return correct value, as the devices will be found if there were some before rebooting.
Other updates:
- Fixes print of the IEEE address, which had reverted bytes order
- `printBoundDevices()` can now be called with Print parameter, so printing to serial instead of log_i is possible.
- Added missing Zigbee locks, fixing the `assert failed: vPortExitCritical port.c:632 (port_uxCriticalNesting[0] > 0)` error
- Added a cmd timeout 10s for reading manufacturer and model 
- mirror updates on Switch/ColorDimSwitch, so there is now option to send the command also to the endpoint num + ieee (long address) combination.
Tested locally with Switch example + 1 or 3 …
=> feat(Zigbee): Recall bounded devices after reboot + IEEE address option for commands

cores/esp32/esp32-hal-spi.c
This PR backports #9333 into `release/v2.x` branch as per discussion in #9221.
=> Fix spiTransaction not updating clock line immediately (backport of #9333 into v2.x branch)

cores/esp32/Esp.cpp
The ESP.getChipModel() function does not correctly identify the ESP32-U4WDH chip as used in the ESP32-MINI-1 module.
It's currently identified as a ESP32-PICO-D2 chip.
This PR fixes that by changing the name from the PICO-D2 (which was supposedly never mass produced) to the ESP32-U4WDH chip.
This closes https://github.com/espressif/arduino-esp32/issues/10683
=> fix(esp32): ESP32-U4WDH chip detection by ESP.getChipModel()

CMakeLists.txt, libraries/Matter/examples/MatterHumiditySensor/MatterHumiditySensor.ino, libraries/Matter/examples/MatterHumiditySensor/ci.json, libraries/Matter/keywords.txt, libraries/Matter/src/Matter.h, libraries/Matter/src/MatterEndpoints/MatterHumiditySensor.cpp, libraries/Matter/src/MatterEndpoints/MatterHumiditySensor.h
Adds a new Matter Endpoint: Humidity Sensor.
This endpoint stores Relative Humidity (percent) information.
ESP32-C6 and ESP32-S3 using the provided example
=> feat(Matter): Adds New Matter Humidity Sensor Endpoint

CMakeLists.txt, libraries/Matter/examples/MatterPressureSensor/MatterPressureSensor.ino, libraries/Matter/examples/MatterPressureSensor/ci.json, libraries/Matter/keywords.txt, libraries/Matter/src/Matter.h, libraries/Matter/src/MatterEndpoints/MatterPressureSensor.cpp, libraries/Matter/src/MatterEndpoints/MatterPressureSensor.h
Adds a Pressure Sensor Matter Endpoint.
It work like all other sensors by reporting to the Matter Controller the pressure read by the device.
Tested with [Home Assistant + Matter Plugin](https://www.home-assistant.io/)
**Note:** This endpoint is not supported by some Matter Providers, such as Amazon Alexa and Apple HomeKit
ESP32-C6 using the provided example
=> feat(matter): adds a Pressure Sensor Matter Endpoint

libraries/SD_MMC/src/SD_MMC.cpp
This PR removed unnecessary check for define `BOARD_HAS_SDMMC`, which is causing that SDMMC can't be used if a board variant don't have this defined. No other SoC is affected by this PR.
Tested with SDMMC example on ESP32-Wrover-kit
Close #10709
=> fix(SDMMC): Remove need for BOARD_HAS_SDMMC for esp32

libraries/Zigbee/examples/Zigbee_Color_Dimmable_Light/Zigbee_Color_Dimmable_Light.ino, libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/Zigbee_Color_Dimmer_Switch.ino, libraries/Zigbee/examples/Zigbee_On_Off_Light/Zigbee_On_Off_Light.ino, libraries/Zigbee/examples/Zigbee_On_Off_Switch/Zigbee_On_Off_Switch.ino, libraries/Zigbee/examples/Zigbee_Scan_Networks/Zigbee_Scan_Networks.ino, libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino, libraries/Zigbee/examples/Zigbee_Temperature_Sensor/Zigbee_Temperature_Sensor.ino, libraries/Zigbee/examples/Zigbee_Thermostat/Zigbee_Thermostat.ino, libraries/Zigbee/src/ZigbeeCore.cpp, libraries/Zigbee/src/ZigbeeCore.h
=> fix(zigbee): Fix rejoin issue for battery powered devices

boards.txt, variants/yb_esp32s3_amp_v2/pins_arduino.h, variants/yb_esp32s3_amp_v3/pins_arduino.h
New boards YB-ESP32-S3-AMP-V2 and YB-ESP32-S3-AMP-V3 added to board list.
Builds successfully tested with both boards on actual Arduino-esp32 core revision.
Closes: https://github.com/espressif/arduino-esp32/issues/10656
Board info: https://github.com/yellobyte/ESP32-DevBoards-Getting-Started/tree/main/boards/YB-ESP32-S3-AMP
=> feat(board): Add custom boards YB-ESP32-S3-AMP-V2 & YB-ESP32-S3-AMP-V3

libraries/RainMaker/examples/RMakerSwitch/RMakerSwitch.ino, libraries/WiFiProv/src/WiFiProv.cpp, libraries/WiFiProv/src/WiFiProv.h
Split provisioning into two parts for better synchronization.
The user node association (cloud_user_assoc) endpoint failed to register in the provisioning workflow because provisioning began before the endpoint creation.
=> fix: Split provisioning into two parts for better synchronization

libraries/ESP32/examples/AnalogOut/LEDCFade/LEDCFade.ino, libraries/ESP32/examples/DeepSleep/SmoothBlink_ULP_Code/SmoothBlink_ULP_Code.ino, libraries/ESP32/examples/FreeRTOS/Mutex/Mutex.ino, libraries/ESP32/examples/FreeRTOS/Queue/Queue.ino, libraries/ESP32/examples/FreeRTOS/Semaphore/Semaphore.ino, libraries/ESP32/examples/GPIO/FunctionalInterrupt/FunctionalInterrupt.ino, libraries/ESP32/examples/MacAddress/GetMacAddress/GetMacAddress.ino, libraries/ESP32/examples/Serial/RS485_Echo_Demo/RS485_Echo_Demo.ino, libraries/ESP32/examples/Utilities/HEXBuilder/HEXBuilder.ino, libraries/ESP32/examples/Utilities/MD5Builder/MD5Builder.ino, libraries/ESP32/examples/Utilities/SHA1Builder/SHA1Builder.ino, libraries/ESP_I2S/examples/ES8388_loopback/ES8388_loopback.ino, libraries/ESP_I2S/examples/Record_to_WAV/Record_to_WAV.ino, libraries/ESP_NOW/examples/ESP_NOW_Broadcast_Master/ESP_NOW_Broadcast_Master.ino, libraries/ESP_NOW/examples/ESP_NOW_Broadcast_Slave/ESP_NOW_Broadcast_Slave.ino, libraries/ESP_NOW/examples/ESP_NOW_Network/ESP_NOW_Network.ino, libraries/SD/examples/SD_Test/SD_Test.ino, libraries/WebServer/examples/HttpAuthCallback/HttpAuthCallback.ino, libraries/WebServer/examples/HttpAuthCallbackInline/HttpAuthCallbackInline.ino, libraries/WebServer/examples/HttpBasicAuthSHA1/HttpBasicAuthSHA1.ino, libraries/WebServer/examples/HttpBasicAuthSHA1orBearerToken/HttpBasicAuthSHA1orBearerToken.ino, libraries/WebServer/examples/MultiHomedServers/MultiHomedServers.ino, libraries/WiFi/examples/WiFiClient/WiFiClient.ino
A problem with `while(!Serial){}` was detected when using USB CDC and DEBUG Level active.
This PR removes it from all examples.
CI Only
None.
=> feat(arduino): remove all while(not serial) in examples

CMakeLists.txt, libraries/Zigbee/examples/Zigbee_CarbonDioxide_Sensor/README.md, libraries/Zigbee/examples/Zigbee_CarbonDioxide_Sensor/Zigbee_CarbonDioxide_Sensor.ino, libraries/Zigbee/examples/Zigbee_CarbonDioxide_Sensor/ci.json, libraries/Zigbee/examples/Zigbee_Occupancy_Sensor/README.md, libraries/Zigbee/examples/Zigbee_Occupancy_Sensor/Zigbee_Occupancy_Sensor.ino, libraries/Zigbee/examples/Zigbee_Occupancy_Sensor/ci.json, libraries/Zigbee/examples/Zigbee_Pressure_Flow_Sensor/README.md, libraries/Zigbee/examples/Zigbee_Pressure_Flow_Sensor/Zigbee_Pressure_Flow_Sensor.ino, libraries/Zigbee/examples/Zigbee_Pressure_Flow_Sensor/ci.json, libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/README.md, libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino, libraries/Zigbee/keywords.txt, libraries/Zigbee/src/Zigbee.h, libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.cpp, libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.h, libraries/Zigbee/src/ep/ZigbeeFlowSensor.cpp, libraries/Zigbee/src/ep/ZigbeeFlowSensor.h, libraries/Zigbee/src/ep/ZigbeeOccupancySensor.cpp, libraries/Zigbee/src/ep/ZigbeeOccupancySensor.h, libraries/Zigbee/src/ep/ZigbeePressureSensor.cpp, libraries/Zigbee/src/ep/ZigbeePressureSensor.h, libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp, libraries/Zigbee/src/ep/ZigbeeTempSensor.h
This PR adds 4 new endpoint types:
- Pressure sensor
- Flow sensor
- Occupancy sensor
- Carbon dioxide (CO2)
There are 3 new examples: `Pressure+Flow sensor`, `Occupancy sensor`, `Carbon dioxide sensor`
+ Some minor enhancements.
Tested using C6 + HomeAssistant
Closes #10684
=> feat(zigbee): Add pressure, flow, ccupancy and carbon dioxide sensor

libraries/WebServer/src/Parsing.cpp
Cap size of last chunk in raw read in WebServer
Currently, the raw read would time out if the content length is not a multiple of HTTP_RAW_BUFLEN, as it tries to read HTTP_RAW_BUFLEN bytes even if the last chunk should actually contain less.
That introduces a five second delay before the final raw call to the handler is performed.
By capping the size to the amount of remaining bytes, this delay is removed.
Tested on an ESP32C3 using a modified [UploadHugeFile example](https://github.com/espressif/arduino-esp32/tree/fb6e977aa8437e0a487a629c3ecad97f794f5508/libraries/WebServer/examples/UploadHugeFile), and curl uploading any file with a size not multiple of 1436.
None
=> Cap size of last chunk in raw read in WebServer

CMakeLists.txt, libraries/Zigbee/examples/Zigbee_Dimmable_Light/README.md, libraries/Zigbee/examples/Zigbee_Dimmable_Light/Zigbee_Dimmable_Light.ino, libraries/Zigbee/examples/Zigbee_Dimmable_Light/ci.json, libraries/Zigbee/src/Zigbee.h, libraries/Zigbee/src/ep/ZigbeeDimmableLight.cpp, libraries/Zigbee/src/ep/ZigbeeDimmableLight.h
This PR adds a Zigbee endpoint for a normal dimmable light. (So no colors or white-temperature change)
I based it on the "color dimmable light" example.
Unfortunately this endpoint type is not in the ESP Zigbee library by default.
So I had to make my own "esp_zb_dimmable_light_clusters_create" function.
It appears to be functioning good, but please do a proper check if I figured it out correctly.
I've tested this with Home Assistant.
The Arduino applications runs on a ESP32-C6 with Arduino-esp32 core on "master" branch.
I'm looking forward to your feedback 😃
=> Zigbee: Add dimmable light endpoint class 

libraries/ESP32/examples/Timer/RepeatTimer/RepeatTimer.ino
The digitalRead of an INPUT pin is LOW, which stops the timer right after start. 
Setting it to INPUT_PULLUP will fix it.
It aims to make repeat timer example work out of the box on some of the popular S3 boards.
Tested on ESP32-S3 with Arduino-esp32 core v3.0.7 using Arduino 2.3.4
https://www.amazon.com/dp/B0C9H7Y66W
=> Use INPUT_PULLUP instead of INPUT

cores/esp32/esp32-hal-cpu.c
Fix error when log level is debug or greater. APLL is present in P4 but is not yet supported in the current libs.
Locally
=> fix(clk_src): Fix error as APLL is not yet supported for P4

libraries/Network/src/NetworkClient.h
Fixes: #10736
-----------
Please describe your …
=> [NetworkClient] Init members of NetworkClient

boards.txt, variants/yb_esp32s3_eth/pins_arduino.h
-----------
New board YB-ESP32-S3-ETH added to board list.
- Builds successfully tested with this board on actual Arduino-esp32 core revision.
- Verified that the defined pins correspond to the correct hardware pins on the board.
- Pre-commit check on changed …
=> feat(board): Add custom board YB-ESP32-S3-ETH

.github/workflows/tests_results.yml, README.md
- Edit info in `README.md` to reflect latest release
- Standardize badges styles and text
- Use `shields.io` badges for better customization.
=> fix(readme): Update readme and fix badges

CMakeLists.txt, libraries/WebServer/examples/Middleware/Middleware.ino, libraries/WebServer/examples/Middleware/ci.json, libraries/WebServer/src/Middlewares.h, libraries/WebServer/src/Parsing.cpp, libraries/WebServer/src/WebServer.cpp, libraries/WebServer/src/WebServer.h, libraries/WebServer/src/detail/RequestHandler.h, libraries/WebServer/src/detail/RequestHandlersImpl.h, libraries/WebServer/src/middleware/AuthenticationMiddleware.cpp, libraries/WebServer/src/middleware/CorsMiddleware.cpp, libraries/WebServer/src/middleware/LoggingMiddleware.cpp, libraries/WebServer/src/middleware/Middleware.h, libraries/WebServer/src/middleware/MiddlewareChain.cpp
For history, please see: https://github.com/espressif/arduino-esp32/pull/10186
-------
This PR improves WebServer with the following additions:
- Add Middleware support (aka Expressif) with some built-in middlewares like cors, authc and logging (curl-like)
- Add ability to collect all incoming request headers
- Added response code and info on server
=> feat(webserver): Middleware with default middleware for cors, authc, curl-like logging 

.github/workflows/upload-idf-component.yml
This is meant to provide us a way to re-release a component if issue is found.
=> ci: Allow push to the component registry from a given git ref

libraries/Matter/examples/MatterTemperatureSensor/MatterTemperatureSensor.ino, libraries/Matter/src/MatterEndpoints/MatterTemperatureSensor.cpp, libraries/Matter/src/MatterEndpoints/MatterTemperatureSensor.h
Matter specification says that all temperatures are measured in Celsius.
This PR fixes all places where this information was open and makes sure that the code and commentaries are clear about it.
CI Only
related to PR #7432
=> feat(matter): Changes Matter Temperature Sensor to report Celsius

.github/workflows/dangerjs.yml
DangerJS options were not being applied because settings were passed as `env`. Also added links to CLA and Contribution Guides.
Fork
=> ci(dangerjs): Fix and update settings

cores/esp32/Client.h, libraries/Network/src/NetworkClient.h
Should fix https://github.com/espressif/arduino-esp32/issues/2755#issuecomment-2547632462
=> Restore Arduino Client API

libraries/Matter/src/MatterEndPoint.h, libraries/Matter/src/MatterEndpoints/MatterColorLight.cpp, libraries/Matter/src/MatterEndpoints/MatterColorTemperatureLight.cpp, libraries/Matter/src/MatterEndpoints/MatterDimmableLight.cpp, libraries/Matter/src/MatterEndpoints/MatterEnhancedColorLight.cpp, libraries/Matter/src/MatterEndpoints/MatterOnOffLight.cpp
When compiling an Arduino project that uses the Matter library (v3.1.0) together with M5Unified (v0.2.2) on M5Stack Atom, I encounter a compilation error caused by an ambiguous reference to attribute_t. It appears that the Matter library defines attribute_t in esp_matter_core.h, and M5Unified (via M5GFX) also declares attribute_t as an enum in enum.hpp.
This PR fixes this issue by forcing the namespace `esp_matter::` into `attribute_t` matter type name.
Using M5Stack Libraries:
``` cpp
#include <M5Unified.h>
#include <Matter.h>
void setup() {
M5.begin();
Matter.begin();
// ...
}
void loop() {
M5.update();
// ...
}
```
Fixes #10804
=> feat(matter): adds esp_matter:: namespace to attribute_t

libraries/AsyncUDP/src/AsyncUDP.cpp
fixes: https://github.com/espressif/arduino-esp32/issues/10758
=> fix(udp): Add missing LwIP locks to init multicast

boards.txt, variants/adafruit_sparklemotion_esp32/pins_arduino.h, variants/adafruit_sparklemotionmini_esp32/pins_arduino.h
new adafruit WLED-friendly dev boards coming soon :)
tested against my hardware, doesn't affect anyone else
https://www.adafruit.com/product/6100
=> Add two more Adafruit Boards (Sparkle Motion & Sparkle Motion mini)

CMakeLists.txt, cores/esp32/esp32-hal-i2c-slave.c, idf_component.yml
With these changes, Arduino core can be used with IDF v5.4
=> feat(idf): Add support for IDF v5.4

libraries/Zigbee/src/ZigbeeCore.cpp, libraries/Zigbee/src/ZigbeeCore.h, libraries/Zigbee/src/ZigbeeEP.cpp, libraries/Zigbee/src/ZigbeeEP.h, libraries/Zigbee/src/ZigbeeHandlers.cpp, libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.cpp, libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.h, libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.h, libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.h, libraries/Zigbee/src/ep/ZigbeeDimmableLight.h, libraries/Zigbee/src/ep/ZigbeeFlowSensor.h, libraries/Zigbee/src/ep/ZigbeeLight.h, libraries/Zigbee/src/ep/ZigbeeOccupancySensor.h, libraries/Zigbee/src/ep/ZigbeePressureSensor.h, libraries/Zigbee/src/ep/ZigbeeSwitch.h, libraries/Zigbee/src/ep/ZigbeeTempSensor.h, libraries/Zigbee/src/ep/ZigbeeThermostat.h
This PR fixes:
- CO2 sensor delta value in reporting to be correct. (float deltas will be supported in upcoming esp-zigbee-sdk version 1.6.2)
- Fixed undeclared destructors for all EPs -> declared empty destructors as they are not used.
- Added returns in Zigbee Handlers to avoid processing empty or failed messages.
=> fix(zigbee): Fixes in handlers, destructors and co2 sensor delta reporting

libraries/ESP_I2S/src/ESP_I2S.cpp
This PR fixes error `[esp32-hal-periman.c:122] perimanSetPinBus(): Invalid pin: 255`, when some of the pins are not used (-1) but the bus clear was called anyway, so it was marked as error Invalid pin.
Closes #10828
=> fix(i2s): Check if pin is used before clearing bus

libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h
Support for JL1101 and other IEEE 802.3 compatible ethernet phys
=> feat(eth): Add support for generic IEEE 802.3 driver

libraries/ESP32/examples/Camera/CameraWebServer/app_httpd.cpp
The code provides fixes incorrect FPS calculation issue. The last_frame variable needs to be updated on each iteration, Immediately after computing the FPS of previous.
Before this commit - the last frame was being updated only once at the beginning of stream_handler function. The fps and avg_frame_time computation were completely wrong. This commit fixes the computation.
This commit - updates last_frame  variable on each iteration. results is correct fps calculation.
I have tested my Pull Request on latest Arduino-esp32 core with ESP32-CAM (CAMERA_MODEL_AI_THINKER) with Core Debug Level - Verbose
[Please provide links to related issue, PRs etc.](https://github.com/espressif/arduino-esp32/issues/10920)
Closes 1 issue ( #10920  )
=> fix(logging): incorrect FPS logging

tests/validation/uart/uart.ino
-----------
ESP32-S2 UART CI Baud rate test case fails.
Wrong pins were used for baud rate detection test case, therefore no data was reaching UART1 RX FIFO from UART0 TX loopback.
Tested with all SoC (ESP32/S2/S3/C3/C6/H2/P4) using https://github.com/espressif/arduino-esp32/blob/master/tests/validation/uart/uart.ino sketch.
None
=> FIX [UART]: ESP32-S2 UART baud rate detection CI  test case

libraries/README.md
Adding ESP-SR to the documentation
-----------
Please …
=> Update README.md to add ESP-SR

CMakeLists.txt, libraries/Zigbee/examples/Zigbee_Contact_Switch/README.md, libraries/Zigbee/examples/Zigbee_Contact_Switch/Zigbee_Contact_Switch.ino, libraries/Zigbee/examples/Zigbee_Contact_Switch/ci.json, libraries/Zigbee/src/Zigbee.h, libraries/Zigbee/src/ZigbeeEP.h, libraries/Zigbee/src/ZigbeeHandlers.cpp, libraries/Zigbee/src/ep/ZigbeeContactSwitch.cpp, libraries/Zigbee/src/ep/ZigbeeContactSwitch.h, libraries/Zigbee/src/ep/ZigbeeDoorWindowHandle.cpp, libraries/Zigbee/src/ep/ZigbeeDoorWindowHandle.h
This PR adds 2 new endpoints, both using IAS Zone cluster:
- Contact Switch (open/close states)
- Door/Window Handle (open/close/tilted)
also added an example for the contact switch, as this type is supported by the HomeAssistant.
Tested using ESP32-C6 connecting to the Zigbee network running under HomeAssistant.
Closes #10870
=> feat(zigbee): Add IAS Zone endpoints (Contact Switch + Door/Window Handle)

libraries/RainMaker/examples/RMakerCustomAirCooler/ci.json, libraries/RainMaker/examples/RMakerSonoffDualR3/ci.json
Examples are causing IRAM to be overrun
=> fix(ci): Disable some RainMaker examples on ESP32

libraries/Network/src/NetworkInterface.cpp
ESP32-P4 was not receiving the interface events.
=> fix(wifi): Make sure that esp-hosted events are propagated

cores/esp32/USBCDC.cpp, cores/esp32/esp32-hal-tinyusb.c, cores/esp32/esp32-hal-tinyusb.h
Adds proper support for running multiple CDC ports at once. Currently targeted to support no more than two at the same time. By default, Arduino supports only one, but with some changes to the lib-builder, support for two can be added.
Lib-builder: https://github.com/espressif/esp32-arduino-lib-builder/pull/275
Fixes: https://github.com/espressif/arduino-esp32/issues/10936
=> feat(cdc): Add support for two CDC ports at once

libraries/Zigbee/examples/Zigbee_OTA_Client/README.md, libraries/Zigbee/examples/Zigbee_OTA_Client/Zigbee_OTA_Client.ino, libraries/Zigbee/examples/Zigbee_OTA_Client/ci.json, libraries/Zigbee/src/ZigbeeEP.cpp, libraries/Zigbee/src/ZigbeeEP.h, libraries/Zigbee/src/ZigbeeHandlers.cpp
This PR adds support for Zigbee OTA Client cluster.
To add Client cluster to the endpoint, add `zbDevice.addOTAClient()` before adding the endpoint to the Zigbee Class.
The first 3 parameters are required and should be defined in your application, so you can control them when releasing a new updated version.
```cpp
addOTAClient(uint32_t file_version, uint32_t downloaded_file_ver, uint16_t hw_version, uint16_t manufacturer = 0x1001, uint16_t image_type = 0x1011, uint8_t max_data_size = 223);
```
Added an simple OTA Client example to demonstrate how to use the OTA update.
For creating the OTA binary file (update file), you will need to get a [python script from the esp-zigbee-sdk](https://github.com/espressif/esp-zigbee-sdk/blob/main/tools/image_builder_tool/image_builder_tool.py).
The OTA …
=> feat(zigbee): Add OTA client cluster support

libraries/Zigbee/src/ZigbeeEP.h, libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp, libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.h, libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.cpp
This PR adds support for HSV color commands.
Tested XY color, please @ilker-aktuna test the HSV colors.
Closes #10669
=> feat(zigbee): Support HSV color commands for RGB light endpoint

boards.txt, variants/huidu_hd_wf2/pins_arduino.h, variants/huidu_hd_wf4/pins_arduino.h
Followup #10779
- fixed flash mode to 'dio'
- removed psram flags
- corrected gpio mapping defines
=> feat(board): Update 3rd party board Huidu HD-WF2/HD-WF4

cores/esp32/WString.cpp
See: https://github.com/espressif/arduino-esp32/issues/10971#issuecomment-2660859418
Fixes: #10971
=> Fix crash in String when using nullptr (#10971)

.github/workflows/push.yml, CMakeLists.txt, cores/esp32/esp32-hal-i2c-ng.c, cores/esp32/esp32-hal-i2c-slave.c, cores/esp32/esp32-hal-i2c.c, idf_component.yml, libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h, libraries/Wire/src/Wire.cpp, libraries/Wire/src/Wire.h, variants/esp32c6/pins_arduino.h
This PR holds the changes necessary to prepare v3.2.0 on top of ESP-IDF v5.4
=> Arduino 3.2.0 based on ESP-IDF v5.4

.github/scripts/on-push.sh, .github/scripts/sketch_utils.sh, .github/workflows/push.yml, boards.txt, package/package_esp32_index.template.json
```
lib-builder: release/v5.5 47c4ca4
esp-idf: master 0f0068fff3
arduino: release/v3.3.x f46725e8
tinyusb: master 2d7d1070f
espressif__esp-dsp: 1.5.2
espressif__esp-modbus: 1.0.17
espressif__esp-nn: 1.1.0
espressif__esp-serial-flasher: 0.0.11
espressif__esp-tflite-micro: 1.3.3
espressif__esp-zboss-lib: 1.6.0
espressif__esp-zigbee-lib: 1.6.0
espressif__esp_diagnostics: 1.0.2
espressif__esp_insights: 1.0.1
espressif__esp_modem: 1.3.0
espressif__esp_rainmaker: 1.5.0
espressif__esp_rcp_update: 1.2.0
espressif__esp_schedule: 1.2.0
espressif__esp_secure_cert_mgr: 2.5.0
espressif__json_generator: 1.1.2
espressif__libsodium: 1.0.20~2 …
```
=> IDF master

package/package_esp32_index.template.json
```
lib-builder: master 3225f04
esp-idf: release/v5.4 e37d33cc1c
arduino: master 783271b6
tinyusb: master 9d2fd6c4a
espressif__esp-dsp: 1.5.2
espressif__esp-modbus: 1.0.17
espressif__esp-nn: 1.1.0
espressif__esp-serial-flasher: 0.0.11
espressif__esp-tflite-micro: 1.3.3~1
espressif__esp-zboss-lib: 1.6.3
espressif__esp-zigbee-lib: 1.6.3
espressif__esp_diagnostics: 1.0.2
espressif__esp_insights: 1.0.1
espressif__esp_modem: 1.3.0
espressif__esp_rainmaker: 1.5.0
espressif__esp_rcp_update: 1.2.0
espressif__esp_schedule: 1.2.0
espressif__esp_secure_cert_mgr: 2.5.0
espressif__json_generator: 1.1.2
espressif__libsodium: 1.0.20~2
espressif__mdns: …
```
=> IDF release/v5.4

cores/esp32/HardwareSerial.cpp, cores/esp32/HardwareSerial.h, cores/esp32/esp32-hal-uart.c, cores/esp32/esp32-hal-uart.h
Adds support for ESP32-C6 and ESP32-P4 to use the LP UART peripheral as a possible `HardwareSerial` port.
ESP32-C6 has now a total of 3 `HardwareSerial` devices: 2 HP UART ports, `Serial0` and `Serial1` plus a LP UART port `Serial2`
ESP32-P4 has now a total of 6 `HardwareSerial` devices: 5 HP UART ports, `Serial0` to `Serial4` plus a LP UART port `Serial5`
ESP32-P4 can set any pin for being used as `Serial5` RX/TX/CTS/RTX pins.
ESP32-C6 must use fixed pins for `Serial2`: RX(4), TX(5), RTS(2), CTS(3)
LP UART port can't be used for logging using `log_x()`
LP UART is not elegible for setting loopbacks to other UART peripheral (no GPIO Matrix Signal)
Using ESP32-C6 and ESP32P4
``` cpp
// Use Serial2 for the ESP32-C6 and Serial5 for the ESP32-P4
#define LP_SERIAL Serial2
void setup() { …
```
=> feat(LP_UART): Implements the ESP32-C6/ESP32-P4 Low Power UART as a possible HardwareSerial port

variants/Geekble_ESP32C3/pins_arduino.h
Update pins_arduino.h
ADC1 no longer supported and removed from Analog pin list
=> fix(board): Update pins_arduino.h for Geekble_ESP32C3

variants/um_feathers3/pins_arduino.h
5. [X] Please **confirm option to "Allow edits and access to secrets by maintainers"** when opening a Pull Request
-----------
Please describe your proposed Pull …
=> fix(board): Update feathers3 wire1 pin definition

boards.txt, variants/Geekble_Nano_ESP32S3/pins_arduino.h
1. add new board
2. https://cafe.naver.com/geekbleofficial/18197
3. https://github.com/SooDragon/Geekble-nano-ESP32S3
A new Dev board for ESP32-S3
It's simple,Easy to use, comparable with Arduino Nano and Arduino Nano ESP32
It's targeted South Korean market to introduce ESP32-S3 to Korean makers
Tested with 
- Arduino IDE 2.3.4 
- Arduino IDE 1.8.19
- Arduino-esp32 core 3.1.1
- Arduino dev boards with ESP32-S3
https://github.com/SooDragon/Geekble-nano-ESP32S3
=> feat(boards): Add Geekble-nano-ESP32S3

libraries/Zigbee/src/ep/ZigbeePressureSensor.cpp
-----------
Fixed calling a temperature cluster …
=> fix(zigbee): use correct pressure cluster function in setTolerance

libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.cpp
-----------
Fixed calling a temperature cluster …
=>  fix(zigbee): use correct carbon dioxide cluster function in setTolerance

cores/esp32/Esp.cpp
fix wrong flash base address for the c5
@me-no-dev
=> c5 flash base address is 0x2000

cores/esp32/esp32-hal-misc.c
My project uses Arduino as an ESP-IDF component with esp-nimble-cpp to provide BLE functionality
I'm seeing compile errors when trying to build my project for the ESP32-P4 because of missing `esp_bt.h` and (as a result) not defined `esp_bt_controller_mem_release` and `ESP_BT_MODE_BTDM`.
As far as I can see `cores/esp32/esp32-hal-misc.c` is the only place where inclusion of `esp_bt.h` is not guarded by `#if SOC_BT_SUPPORTED`
This PR fixes these errors.
I have tested compilation of my Pull Request on Arduino-esp32 core v3.1.3 with ESP32-P4 Board with this scenario
None
=> fix(bt): Compile error on ESP32-P4

idf_component.yml
Recent version of ESP MATTER v1.4 needs newer versions of ESP INSIGHTS and DIAGNOTICS.
This PR updates the Managed Components version.
Using ESP LIB BUILDER
Related to https://github.com/espressif/esp32-arduino-lib-builder/pull/280
=> feat(matter): necessary changes to insights version for esp_matter

libraries/Zigbee/src/ep/ZigbeeAnalog.cpp
Fix to a copy-paste error that causes a Guru Meditation crash with Zigbee Analog Example.
Tested on ESP32C6 and ESP32H2, compiled using both VS Code with Arduino Community extension and Arduino IDE V1.8.19
This will close [#11044](https://github.com/espressif/arduino-esp32/issues/11044)
=> fix(zigbee): Fixed Guru Meditation crash with Zigbee Analog example

libraries/Ethernet/src/ETH.cpp
This pull request includes changes to the `ETHClass::begin` method in the `libraries/Ethernet/src/ETH.cpp` file. The main purpose of these changes is to improve the initialization process of the Ethernet MAC and PHY by storing the created instances in class member variables instead of local variables.
Initialization improvements:
* Changed the `mac` variable to a class member variable `_mac` and updated the error handling to use `_mac`.
* Changed the `phy` variable to a class member variable `_phy` and updated the error handling to use `_phy`.
* Updated the switch cases for different PHY types to assign the new PHY instances to `_phy` instead of `phy`.
* Modified the `eth_config` initialization to use the class member variables `_mac` and `_phy` instead of the local variables `mac` and …
=> fix(eth): Fix RMII Ethernet not being able to be restarted

libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h
This pull request introduces several new methods and modifications to the `ETHClass` in the Ethernet library to enhance its functionality. The primary changes include adding methods to set duplex mode, auto-negotiation, and link speed, as well as updating the return type of the `linkSpeed` method.
* Added `setFullDuplex` method to allow setting the duplex mode of the Ethernet connection.
* Added `setAutoNegotiation` method to enable or disable auto-negotiation on the Ethernet connection.
* Added `setLinkSpeed` method to set the link speed of the Ethernet connection.
* Updated `linkSpeed` method to return `uint16_t` instead of `uint8_t` for better compatibility with link speed values.
* Updated `ETH.h` to declare the new methods and modify the return type of `linkSpeed`.
fixes: …
=> feat(eth): Add setters for negotiation, speed and duplex modes

libraries/Zigbee/src/ep/ZigbeeAnalog.cpp
This PR fixes a wrong attributeID in the setAnalogInputReporting in Analog EP.
Related #11044
=> fix(zigbee): Use correct attributeID in setAnalogInputReporting

libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino, libraries/Zigbee/src/ep/ZigbeeAnalog.cpp, libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.cpp, libraries/Zigbee/src/ep/ZigbeeFlowSensor.cpp, libraries/Zigbee/src/ep/ZigbeeOccupancySensor.cpp, libraries/Zigbee/src/ep/ZigbeePressureSensor.cpp, libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp
This PR fixes Zigbee report() functions for many sensor endpoints in the latest Arduino core versions where esp-zigbee-sdk 1.6.3 is used. 
Tested using CarbonDioxide and TempHum Sleepy examples within HA.
=> fix(zigbee): Add manuf_code to report attribute commands

libraries/Matter/src/MatterEndpoints/MatterColorLight.h, libraries/Matter/src/MatterEndpoints/MatterEnhancedColorLight.h
A Maintainance PR to remove a few compilation warning messages:
libraries\Matter\src/MatterEndpoints/MatterEnhancedColorLight.h:94:30: warning: missing initializer for member 'HsvColor_t::s' [-Wmissing-field-initializers]
libraries\Matter\src/MatterEndpoints/MatterEnhancedColorLight.h:94:30: warning: missing initializer for member 'HsvColor_t::v' [-Wmissing-field-initializers]
libraries\Matter\src/MatterEndpoints/MatterColorLight.h:70:30: warning: missing initializer for member 'HsvColor_t::s' [-Wmissing-field-initializers]
libraries\Matter\src/MatterEndpoints/MatterColorLight.h:70:30: warning: missing initializer for member 'HsvColor_t::v' [-Wmissing-field-initializers]
CI only
None
=> fix(matter): removes a few matter 1.4 / IDF 5.4 compilation warning messages 

libraries/Matter/examples/MatterColorLight/MatterColorLight.ino, libraries/Matter/examples/MatterDimmableLight/MatterDimmableLight.ino, libraries/Matter/examples/MatterEnhancedColorLight/MatterEnhancedColorLight.ino, libraries/Matter/examples/MatterFan/MatterFan.ino, libraries/Matter/examples/MatterTemperatureLight/MatterTemperatureLight.ino
When no RGB LED is used, a regular LED is used, in the examples, to demonstrate Light Brightness or the Fan Motor Power. 
The regular LED is driven with `analogWrite()` and set OFF with `digitalWrite(pin, LOW)`. In order to set it OFF, it is necessary to set the pin to Digital Mode OUTPUT, otherwise an error will be displayed in the UART console. 
Using ESP32.
None
=> fix(matter): examples must set pin to Digital Mode after analogWrite() and before digitalWrite()

libraries/Network/src/NetworkClient.cpp
Fixes a simple macro name conflict warning message:
IDF 5.3+ declares:
``` cpp
#define IN6_IS_ADDR_V4MAPPED(a)     ip6_addr_isipv4mappedipv6((ip6_addr_t*)(a))
#define ip6_addr_isipv4mappedipv6(ip6addr) (((ip6addr)->addr[0] == 0) && ((ip6addr)->addr[1] == 0) && (((ip6addr)->addr[2]) == PP_HTONL(0x0000FFFFUL)))
```
`libraries/Network/src/NetworkClient.cpp` declares:
``` cpp
#define _IN6_IS_ADDR_V4MAPPED(a) ((((__const uint32_t *)(a))[0] == 0) && (((__const uint32_t *)(a))[1] == 0) && (((__const uint32_t *)(a))[2] == htonl(0xffff)))
```
Therefore, both should be the same.
```
\libraries\Network\src\NetworkClient.cpp:26:9: warning: "IN6_IS_ADDR_V4MAPPED" redefined
26 | #define IN6_IS_ADDR_V4MAPPED(a) ((((__const uint32_t *)(a))[0] == 0) && (((__const uint32_t *)(a))[1] == 0) && (((__const …
```
=> fix(network): fixes a macro name conflict warning

libraries/WiFi/examples/WiFiScan/WiFiScan.ino, libraries/WiFi/src/WiFiGeneric.cpp, libraries/WiFi/src/WiFiGeneric.h
This pull request includes changes to the WiFi library to add support for scanning WiFi networks in both 2.4GHz and 5GHz bands. The most important changes include updating the example sketch to demonstrate scanning for both bands, adding new methods to control WiFi band modes, and ensuring compatibility with chips that support 5GHz WiFi.
Enhancements to WiFi scanning:
* [`libraries/WiFi/examples/WiFiScan/WiFiScan.ino`](diffhunk://#diff-afcdb9d9488c384bf9f65155df1a3fe577e93dab466a11211246e3d7c46b4268L2-L21): Updated the example sketch to perform separate scans for 2.4GHz and 5GHz bands if supported by the chip. [[1]](diffhunk://#diff-afcdb9d9488c384bf9f65155df1a3fe577e93dab466a11211246e3d7c46b4268L2-L21) [[2]](diffhunk://#diff-afcdb9d9488c384bf9f65155df1a3fe577e93dab466a11211246e3d7c46b4268 …
=> feat(wifi): Add support for 2.4GHz and 5GHz band switching

tests/validation/i2c_master/i2c_master.ino
Check for changed values rather than a specific range to avoid tests failing due to inconsistent Wokwi timing.
CI
=> test(i2c): Do not use delta as Wokwi timing can be inconsistent

.github/scripts/set_push_chunks.sh, .github/workflows/build_py_tools.yml, .github/workflows/pre-commit.yml, .github/workflows/push.yml
Replace compromised `changed-files` with native solutions
CI, local and fork.
Closes #11127
=> ci(actions): Replace changed-files

cores/esp32/esp32-hal-uart.c, cores/esp32/esp32-hal-uart.h
UART RX Timeout value may change depending on the UART Clock Source, Baudrate and the SoC running it.
This PR brings more clarity to the ` HardwareSerial::setRxTimeout(uint8_t symbols_timeout)` function in order to validate the requested timeout and also log proper error message if necessary.
Tested with ESP32, ESP32-S2 and ESP32-S3.
``` cpp
void setup() {
Serial.setRxTimeout(10);  // shall fail and log an error with ESP32
Serial.begin(256000);
Serial.setRxTimeout(10);  // shall work correctly with ESP32
}
```
Related to #11132
=>  fix(uart): uart rx timeout validation with proper log message

.github/workflows/lib.json
Fix ESPAsyncWebServer URL and examples
CI
=> fix(ext_lib): Fix ESPAsyncWebServer URL and examples

variants/esp32s3usbotg/pins_arduino.h
esp32s3usbotg/pins_arduino.h:5:1: note: 'bool' is defined in header '<stdbool.h>'; did you forget to '#include <stdbool.h>'?
4 | #include <stdint.h>
+++ |+#include <stdbool.h>
5 |
This is a sample error from compilation of all ESP32>USB examples when targeting the ESP32-S3 with OTG board.
Adding the dependency directly in the arduino project does not mitigate the issue :(
The only fix I managed to find is to edit it directly in the pin definitions header
P.S.: a previous pull was created for the base esp32 board, but it was suggested to be requested for merge on the variant itself
=> Fix(esp32s3usbotg) stdbool dependency in pins_arduino.h

libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h, libraries/PPP/src/PPP.cpp, libraries/PPP/src/PPP.h, libraries/WiFi/src/AP.cpp, libraries/WiFi/src/STA.cpp, libraries/WiFi/src/WiFiAP.h, libraries/WiFi/src/WiFiSTA.h
This pull request includes several changes aimed at improving event handling for network interfaces in the Ethernet, PPP, and WiFi libraries. The most important changes involve adding and managing event handles to ensure proper event registration and deregistration.
* `libraries/Ethernet/src/ETH.cpp` and `libraries/Ethernet/src/ETH.h`: Added `_eth_connected_event_handle` to handle Ethernet connection events. Updated methods to use this handle for event registration and removal. [[1]](diffhunk://#diff-ac446ab01e7ad1e517b6da5f710759cf9f867d668175edc0f988aa032a0f8c94L139-R139) [[2]](diffhunk://#diff-ac446ab01e7ad1e517b6da5f710759cf9f867d668175edc0f988aa032a0f8c94L362-R362) [[3]](diffhunk://#diff-ac446ab01e7ad1e517b6da5f710759cf9f867d668175edc0f988aa032a0f8c94L852-R852) …
=> fix(net): Use network_event_handle_t for internal callbacks

libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h
This pull request includes several changes to the `ETHClass` in the `libraries/Ethernet/src/ETH.cpp` and `libraries/Ethernet/src/ETH.h` files. The changes primarily focus on adding support for configuring Ethernet settings such as full duplex mode, link speed, and auto-negotiation, as well as ensuring these settings are properly managed during the Ethernet initialization and shutdown processes.
* Added new member variables `_eth_started`, `_link_speed`, `_full_duplex`, and `_auto_negotiation` to the `ETHClass` to store Ethernet configuration settings.
* Implemented new methods `setFullDuplex`, `setLinkSpeed`, and `setAutoNegotiation` to allow configuration of Ethernet settings before calling `ETH.begin()`. Each method includes validation to ensure settings are applied correctly. …
=> fix(eth): Set the ETH properties at the correct time

boards.txt
[xiao_esp32s3_plus ](https://wiki.seeedstudio.com/xiao_esp32s3_getting_started/#specification)supports 16M flash, but currently only 8M is available. 16M flash option needs to be added;
=> fix: Add 16M flash option for xiao_esp32_s3_plus 

.github/scripts/set_push_chunks.sh, .github/workflows/allboards.yml, .github/workflows/boards.yml, .github/workflows/build_py_tools.yml, .github/workflows/dangerjs.yml, .github/workflows/docs_build.yml, .github/workflows/docs_deploy.yml, .github/workflows/gh-pages.yml, .github/workflows/lib.yml, .github/workflows/pre-commit-status.yml, .github/workflows/pre-commit.yml, .github/workflows/publishlib.yml, .github/workflows/publishsizes-2.x.yml, .github/workflows/publishsizes.yml, .github/workflows/push.yml, .github/workflows/release.yml, .github/workflows/tests.yml, .github/workflows/tests_build.yml, .github/workflows/tests_hw.yml, .github/workflows/tests_qemu.yml, .github/workflows/tests_results.yml, .github/workflows/tests_wokwi.yml, .github/workflows/upload-idf-component.yml
To avoid supply chain attacks, lock actions used in workflows to commit hash rather than tag.
Also improve readability of files.
=> ci(workflows): Lock actions to commits and improve readability

variants/lolin_c3_mini/pins_arduino.h, variants/lolin_c3_pico/pins_arduino.h
Based on https://www.wemos.cc/en/latest/c3/c3_pico.html there were a few pin setting errors for the Lolin-C3-Pico board.
It also fixes the RGB Pin of the Lolin-C3-Mini board, as defned in https://www.wemos.cc/en/latest/c3/c3_mini.html
CI only
https://github.com/espressif/arduino-esp32/discussions/11184
=> fix(arduino_pins): fixes Lolin-C3-Pico and C3-Mini RGB LED pin + C3-Pico SPI SCK pin definition

libraries/WiFi/src/WiFiScan.cpp
Rework of https://github.com/espressif/arduino-esp32/pull/11075
This pull request focuses on memory management improvements and code simplification in the `WiFiScan.cpp` file. The most important changes include replacing `delete[]` with `free()`, using `calloc()` instead of `new`, and simplifying the scan completion check.
Memory management improvements:
* Replaced `delete[]` with `free()` and set the pointer to `NULL` in the `_scanDone` and `scanDelete` methods to prevent potential memory leaks. [[1]](diffhunk://#diff-bace60178f098d80f1b271ad8ffff33f935644dfad66894478bf3a5969dc7b57L121-L135) [[2]](diffhunk://#diff-bace60178f098d80f1b271ad8ffff33f935644dfad66894478bf3a5969dc7b57R176-R181)
* Replaced `new` with `calloc()` for allocating memory for `WiFiScanClass::_scanResult` to ensure the …
=> fix(wifi_scan): Fix some edge cases where WiFi Scan may fail

libraries/Zigbee/src/ZigbeeEP.cpp, libraries/Zigbee/src/ZigbeeEP.h
Just a general review of memory allocation routines and changing `string` variable name to avoid using reserved words.
CI only
https://github.com/espressif/arduino-esp32/pull/11196
=> fix(zigbeeEP): review of names and memory allocation

libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino, libraries/Zigbee/src/ZigbeeEP.cpp, libraries/Zigbee/src/ZigbeeEP.h
This pull request includes updates to the Zigbee Power Config Cluster adding a battery voltage functionality. The most important changes involve adding support for setting and reporting battery voltage in addition to battery percentage.
Enhancements to battery management:
* [`libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino`](diffhunk://#diff-762711ae43f701c312429d935f897759698c0a5687a95b96d8185f72aecc23b9L88-R90): Updated the `setup` function to include setting battery voltage along with battery percentage.
* [`libraries/Zigbee/src/ZigbeeEP.cpp`](diffhunk://#diff-d6ef64ae3bc8bc786fd05ea9a9a601e2710d012542ef08033c3b2e42285bc750L71-R71): Modified the `setPowerSource` method to accept battery voltage as an additional parameter and added a new method …
=> feat(zigbee): Add battery voltage attribute support

libraries/ESP32/examples/RMT/RMTLoopback/RMTLoopback.ino
The way RMT loopback example was done, it had a sync problem that caused the result to do not match.
Low level signal was sent first and then the high level, therefore, it would only detect the second signal (high) after a delay in nanoseconds. This delay would cause the received signal to be shifted by one RMT symbol.
Output of the original example:
```
Got 30 RMT symbols
000e8001=8001000e 000d8001=8002000d 000b8002=8003000c 000a8004=8004000b 
00098005=8005000a 00088006=80060009 00078007=80070008 00068008=80080007 
```
With this refactoring/fix, RMT symbols start with High Level and the output matches the received RMT symbols.
This PR makes the example easier for understanding as well as the RMT symbol will better match.
```
Got 32 RMT symbols
0001800e=0001800e 0002800d=0002800d …
```
=> refactor(rmt): refactored RMT loopback example

cores/esp32/USB.cpp
Using ESP32-S2 with USB CDC enabled and arduino-cli with all warnings set, there is a warning message error:
```
arduino15/packages/esp32/hardware/esp32/3.1.1/cores/esp32/USB.cpp:102:28: note: 'p' declared here 102 
arduino_usb_event_data_t p; 
In function 'esp_err_t arduino_usb_event_post(esp_event_base_t, int32_t, void*, size_t, TickType_t)', inlined from 'void tud_umount_cb()'
```
ESP32-S2 with Arduino CDC on Boot enbaled using Arduino CLI with all warnings activated.
`arduino-cli compile -b esp32:esp32:esp32s2:CDCOnBoot=cdc,UploadMode=cdc,PSRAM=enabled --build-path ./build --build-property upload.maximum_size=4063232 --build-property compiler.optimization_flags=-O2 --warnings all`
Fixes #11162
=> fix(usb): uninitilized variable warning message

cores/esp32/esp32-hal-misc.c
instead of only BT. follow up of  #11214
Without the Arduino Lib Builder has compile error.
=> check for `CONFIG_BT_BLUEDROID_ENABLED` in esp32-hal-misc.c

libraries/WiFi/src/WiFiGeneric.cpp
This pull request includes changes to the `WiFiGenericClass::mode` method in the `WiFiGeneric.cpp` file. The changes involve updating the data type of the `current_protocol` variable and modifying the way its address is passed to the `esp_wifi_get_protocol` function. This is required, because `esp_wifi_get_protocol` sets more than one byte in the provided return mask.
Data type and casting updates:
* Changed the data type of `current_protocol` from `uint8_t` to `uint32_t` to accommodate a wider range of values.
* Updated the `esp_wifi_get_protocol` function calls to cast the address of `current_protocol` to `uint8_t*` to match the expected parameter type. [[1]](diffhunk://#diff-0aa87997f6f48b5397f969144b34ce0ad4da8e173aee854c1cf2e1bf69ecf3aaL605-R607) …
=> fix(wifi): Workaround bug in esp_wifi_get_protocol()

cores/esp32/esp32-hal-uart.c
C5 fails to compile when trying to build a firmware. Can't test if the fix is correct since not having a C5. If correct fix for #11254
@SuGlider
=> fix(esp32c5): Add proper RTC clock source to uartSetClockSource

cores/esp32/esp32-hal-gpio.c
This pull request includes a minor fix to the `__digitalRead` function in the `esp32-hal-gpio.c` file. The change ensures that the `log_w` warning message properly includes the pin number in its output.
* [`cores/esp32/esp32-hal-gpio.c`](diffhunk://#diff-cc07ee5f3d34f8f2648dff856f751f53c9b84477993e8e6adb0f8291d897cc09L188-R188): Updated the `log_w` function call in `__digitalRead` to include the `pin` parameter, ensuring the warning message displays the pin number correctly.
Closes #11265
=> fix(gpio): Fix GPIO warning message

.github/ISSUE_TEMPLATE/Feature-request.yml, .github/ISSUE_TEMPLATE/Issue-report.yml, docs/en/contributing.rst
This pull request introduces updates to enforce English as the standard language for communication in feature requests, issue reports, and contributions. These changes aim to ensure effective communication and streamline the review process.
* [`.github/ISSUE_TEMPLATE/Feature-request.yml`](diffhunk://#diff-3aef908cff5059f17d2d3fbd10c8c765ca45f639b1372129208b9f243c664950R8): Added a note specifying that feature requests must be written in English. Requests in other languages will be closed with a request to rewrite them in English.
* [`.github/ISSUE_TEMPLATE/Issue-report.yml`](diffhunk://#diff-fcb00a2d209e968ab371bf32541d29831b5d7fe3a070fbc9c04cd0a91b7f22d6R8): Added a similar note for issue reports, requiring them to be submitted in English for effective processing.
* …
=> docs(language): Enforce English on contributions and issues

cores/esp32/esp32-hal-i2c-slave.c
in actual IDF branch master. fix for https://github.com/espressif/esp32-arduino-lib-builder/actions/runs/14554194455/job/40828960172
replaces #11270
@me-no-dev
=> i2c_ll_enable_arbitration(i2c->dev, true)

cores/esp32/esp32-hal-ledc.c
IDF 5.3 has included a new field to `ledc_timer_config_t`, `bool deconfigure`.
IDF 5.3 included a new field to `ledc_channel_config_t`, `ledc_sleep_mode_t sleep_mode`.
IDF 5.4 included a new filed to `ledc_channel_config_t`, `unsigned int flags.output_invert`
None of those were initiated in the code. This PR set them all to `0` to make sure that these fields are correctly initiated.
CI only
None
=> feat(ledc): clear all fields added to ledc struct in IDF 5.4

libraries/ESP32/examples/Serial/RxTimeout_Demo/RxTimeout_Demo.ino
Rx Timeout example was not working correctly using ESP32 and ESP32-S2 due to default selection of REF_TICK as UART Clock Source. REF_TICK limits RX Timeout to 1.
This PR adds the necessary call to `HardwareSerial::setClockSource()` in order to make it work properly. 
Tested using the example code of this PR.
ESP32 | ESP32-S2 | ESP32-C3 | ESP32-C6 | ESP32-S3 | ESP32-H2
```
ets Jul 29 2019 12:21:46
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4888
load:0x40078000,len:16516
load:0x40080400,len:4
load:0x40080404,len:3476
entry 0x400805b4
[     8][I][esp32-hal-psram.c:102] psramAddToHeap(): PSRAM added to the heap. …
```
=> feat(uart): sets correct ESP32/S2 clock source for the example

.github/scripts/on-release.sh
This pull request enhances the release script (`.github/scripts/on-release.sh`) to support generating and handling package JSON files for a Chinese mirror (`dl.espressif.cn`). The changes ensure compatibility with the Chinese mirror by adding new JSON files, modifying commands, and updating upload logic.
* Added new variables `PACKAGE_JSON_DEV_CN` and `PACKAGE_JSON_REL_CN` to handle Chinese mirror-specific package JSON files.
* Updated the `sed` command to replace URLs for the Chinese mirror (`github.com` → `dl.espressif.cn/github_assets`) while generating the Chinese-specific JSON files.
* Modified the `merge_package_json` logic to include merging of Chinese mirror-specific JSON files during release preparation.
* Added a note that package JSONs for the Chinese mirror are not tested …
=> ci(release): Add package JSON with chinese mirrors

boards.txt, variants/lilygo_tlora_pager/pins_arduino.h, variants/lilygo_twatch_s3/pins_arduino.h, variants/lilygo_twatch_ultra/pins_arduino.h
Change the T-Watch-S3-Ultra and T-LoRa-Pager pin usage
Adjust the ArduinoIDE partition selection order
Add two types of Radio types for easy selection
=> Update LilyGo T-Watch-S3-Ultra and T-LoRa-Pager variants

libraries/ESP32/examples/RMT/RMT_LED_Blink/RMT_LED_Blink.ino
This example crashes when running with the ESP32 because it doesn't support `SOC_RMT_SUPPORT_TX_LOOP_AUTO_STOP` feature. All other SoC were running the example correctly.
The timming was also incorrect becuase it was sending one RMT Symbol less.
This PR fixes the example to run with no crashes for all the SoC supported by Arduino Core 3.2.x+
It also fixes the blink timming as verified by a logic analizer. 
Tested using the example with ESP32, S2, S3, C3 and C6.
Closes #11281
=> feat(rmt): fixes example to run correctly within IDF 5.x

cores/esp32/esp32-hal-spi.c, cores/esp32/esp32-hal-spi.h, libraries/SPI/src/SPI.cpp, libraries/SPI/src/SPI.h
This PR adds the ability to invert the logic level of the Hardware Slave Select (SS) pin for ESP32 SPI buses (HSPI/VSPI). This is critical for compatibility with hardware that expects active-high SS signals.
Backward Compatibility:
No breaking changes: Existing code using setHwCs() will default to invert_out=false (original behavior)
No Software SS Impact: Only affects hardware-controlled SS pins.
Isolation: Changes to one SPI bus (e.g., HSPI) do not affect others (e.g., VSPI).
Usage Example:
SPIClass *hspi = NULL;
setup(){
hspi = new SPIClass(HSPI);
hspi->begin();
hspi->setSSInvert(true);  // Set before setHwCs();
hspi->setHwCs(true); 
hspi->beginTransaction(SPISettings(SPI_CLOCK, MSBFIRST, SPI_MODE2));
}
I have tested my Pull Request on Arduino-esp32 core v3.1.3 with ESP32-S3 Board. …
=> New SPI invert hardware SS function in hall-spi and SPI library

docs/en/installing.rst, docs/en/troubleshooting.rst
This pull request updates the documentation to provide alternative download links for users in China, addressing potential issues with slow or unstable connections to GitHub. The changes include adding references to the Jihulab mirror in the installation and troubleshooting guides.
* [`docs/en/installing.rst`](diffhunk://#diff-782bceb21b15a86ce2e11bf1c50c1fb6495417df8e671a687a56e185d166d36fR13-R17): Added a note and alternative repository link (`https://jihulab.com/esp-mirror/espressif/arduino-esp32.git`) for users in China experiencing slow download speeds. Also included stable and development release JSON file links for the Arduino IDE Boards Manager. [[1]](diffhunk://#diff-782bceb21b15a86ce2e11bf1c50c1fb6495417df8e671a687a56e185d166d36fR13-R17) …
=> docs(mirror): Add Chinese mirror links

cores/esp32/esp32-hal-spi.c
Add missing value to spi struct for `ss_invert`.
Fixes #11297
=> fix(spi): Add missing initializer for ss_invert

boards.txt, variants/um_edges3_d/pins_arduino.h, variants/um_squixl/pins_arduino.h
Added support for 2 of my new boards: SQUiXL and EdgeS3[D]
Both ESP32-S3 boards.
Thanks :)
=> Added new Unexpected Maker SQUiXL and EDGES3[D] boards.

libraries/Zigbee/examples/Zigbee_On_Off_MultiSwitch/README.md, libraries/Zigbee/examples/Zigbee_On_Off_MultiSwitch/Zigbee_On_Off_MultiSwitch.ino, libraries/Zigbee/examples/Zigbee_On_Off_MultiSwitch/ci.json, libraries/Zigbee/src/ZigbeeCore.cpp, libraries/Zigbee/src/ZigbeeCore.h, libraries/Zigbee/src/ZigbeeEP.cpp, libraries/Zigbee/src/ZigbeeEP.h, libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.cpp, libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.h, libraries/Zigbee/src/ep/ZigbeeSwitch.cpp, libraries/Zigbee/src/ep/ZigbeeSwitch.h, libraries/Zigbee/src/ep/ZigbeeThermostat.cpp, libraries/Zigbee/src/ep/ZigbeeThermostat.h
* Implemented the `Zigbee_On_Off_MultiSwitch.ino` sketch, which includes:
- Configuration and control of up to three Zigbee lights.
- Persistent storage of light configurations in NVS.
- Serial command handling for light control, network management, and factory reset.
* Added a new APS data indication handler to process bind/unbind requests and update the bound devices list dynamically. [[1]](diffhunk://#diff-e68938a8f36a9907b33d5cee511b0fd240f5059d04c677259c963617479fe86eR45) [[2]](diffhunk://#diff-e68938a8f36a9907b33d5cee511b0fd240f5059d04c677259c963617479fe86eR439-R460)
* Introduced a `closeNetwork` method to complement the existing `openNetwork` method, allowing for better network management.
* Enhanced the Zigbee application signal handler to handle device updates for routers and …
=> feat(zigbee): Remove static variables, improve binding, new example

CMakeLists.txt, libraries/Zigbee/examples/Zigbee_Analog_Input_Output/Zigbee_Analog_Input_Output.ino, libraries/Zigbee/examples/Zigbee_Binary_Input/README.md, libraries/Zigbee/examples/Zigbee_Binary_Input/Zigbee_Binary_Input.ino, libraries/Zigbee/examples/Zigbee_Binary_Input/ci.json, libraries/Zigbee/src/Zigbee.h, libraries/Zigbee/src/ep/ZigbeeAnalog.cpp, libraries/Zigbee/src/ep/ZigbeeAnalog.h, libraries/Zigbee/src/ep/ZigbeeBinary.cpp, libraries/Zigbee/src/ep/ZigbeeBinary.h
This PR adds support for Zigbee Binary Input EP + example.
Also adds `description` and `application_type` attributes for Analog EP class. Those 2 new attributes are mandatory for ZHA for the device to be shown correctly.
Tested using included examples and HA with a ZHA dev branch as the AnalogInput+BinaryInput changes are pending for the 2025.5.2 version mostly.
=> feat(zigbee): Add support for Binary input EP + Analog EP extension

cores/esp32/esp32-hal-bt.c
by this change it is possible to remove all not necessary BT include pathes. Why does this matter? The build system SCons which is used for pioarduino does not support @file in CPPPATH. This is a problem for Windows since command line limit is reached for big projects. The current approach to solve compile issues is to move the include files from CPPPATH to ASFLAGS and CCFLAGS and using with -iprefix. This approach generates a heavy performance decrease in compiling. To solve i am implementing a solution to keep the original correct way providing the includes via CPPPATH and remove the not needed includes. This works quiet well. Especially BT has a lot of includes, in most cases just removing this includes does solve Windows compile errors.
BUT currently removing the Bluetooth includes is …
=> make BT core code execution conditional from include esp_bt.h

idf_component.yml
generates weird compile issues when compiling Arduino as an component of IDF when using pioarduino. No impact on Arduino Core since no C2 precompiled libs are provided.
Trying to use wifi-provisioning with the C2 is always a bad idea keeping the low resources from the C2 in mind.
@me-no-dev as discussed in Discord
=> C2: Disable network provisioning

libraries/Zigbee/examples/Zigbee_Analog_Input_Output/Zigbee_Analog_Input_Output.ino, libraries/Zigbee/examples/Zigbee_Analog_Input_Output/ci.json, libraries/Zigbee/keywords.txt, libraries/Zigbee/src/ep/ZigbeeAnalog.cpp, libraries/Zigbee/src/ep/ZigbeeAnalog.h
This pull request introduces updates to the Zigbee library, focusing on enhancing support for analog output functionality. 
New methods added:
```cpp
bool setAnalogOutput(float analog);
float getAnalogOutput();
bool reportAnalogOutput();
```
Tested with ESP32-C6 and the `Zigbee_Analog_Input_Output` example connecting to the HomeAssistant.
=> feat(zigbee): Add method to set/get/report analog output

idf_component.yml, libraries/Zigbee/examples/Zigbee_On_Off_MultiSwitch/ci.json, libraries/Zigbee/examples/Zigbee_Power_Outlet/Zigbee_Power_Outlet.ino, libraries/Zigbee/examples/Zigbee_Power_Outlet/ci.json
This pull request includes updates to Zigbee-related dependencies and configuration files to ensure compatibility with newer library versions and streamline build requirements.
* [`idf_component.yml`](diffhunk://#diff-1c3f4b2cdd6cc6d2fd1051a9943c18b0467e1c9790d979f5515803670e2ee490L57-R62): Updated `espressif/esp-zboss-lib` to version `1.6.4` for compatibility with `esp-zigbee-lib` version `1.6.5`. Updated `espressif/esp-zigbee-lib` to version `1.6.5`. These changes ensure compatibility between Zigbee libraries.
Tested Zigbee compilation on ESP32-C6 and tested Analog example on ESP32-C5, that successfully connects to HA Zigbee network.
=> feat(zigbee): Update to esp-zigbee-sdk 1.6.5 and fix ci.json files

boards.txt
fix: Add PSRAM Option for Geekble nano
Description of Change
we noticed that Geekble nano users need PSRAM option.
So enabled Geekble nano's PSRAM option in board.txt files
Tests scenarios
Tested under Arduino IDE v2.3.6, Arduino-esp32 core v3.2.0 with Geekble nano
Related links
=> fix: Add PSRAM Option for Geekble nano

.github/workflows/build_py_tools.yml, .github/workflows/push.yml, cores/esp32/esp32-hal-i2c-slave.c
the change allows to compile Arduino branch release/v3.1.x as an component of IDF 5.3. with actual branch release/v5.3.
The change is backwards compatible to the released version since there is IDF < 5.3.3 used
=> Backport: changes to compile v3.1.x as component of IDF branch release/v5.3

.github/workflows/publishsizes.yml
This pull request includes a refinement to the artifact processing logic in the `publishsizes.yml` fixing this workflow. The changes ensure that only specific artifacts (`pr_number` and `pr_cli_compile_*`) are processed.
=> fix(ci): Process only needed files in publish sizes

cores/esp32/esp32-hal-ledc.c, cores/esp32/esp32-hal-ledc.h
This pull request introduces enhancements to the LEDC (LED Controller) functionality by adding helper functions for timer management, improving channel attachment logic, and extending the `ledc_channel_handle_t` structure. The changes aim to streamline timer allocation and deconfiguration, improve frequency and resolution matching, and provide better resource management.
Tested using customized ledc example on C6 -> 4 LEDC Timers and checked on oscilloscope.
```
int brightness = 0;  // how bright the LED is
int fadeAmount = 5;  // how many points to fade the LED by
void setup() {
// 2 pins same channel - same timer
ledcAttachChannel(4, 5000, 8, 0);
ledcAttachChannel(5, 5000, 8, 0);
// 3 pins with new timer
ledcAttach(0, 10000, 10);
ledcAttach(1, 50000, 8);
ledcAttach(2, 5000, 10);
// …
```
=> feat(ledc): Improve timer management with frequency/resolution matching

.github/scripts/on-release.sh, .github/scripts/release_append_cn.py, docs/en/installing.rst
This pull request makes updates to the `.github/scripts/on-release.sh` script to improve consistency in URL handling and correct an issue in the upload logic for Chinese-specific pages. These changes ensure proper substitution of URLs and accurate references during the upload process.
Keeping it as draft until assets like this are available:
https://dl.espressif.cn/github_assets/earlephilhower/esp-quick-toolchain/releases/download/3.0.0-gnu12/aarch64-linux-gnu.mklittlefs-c41e51a.200706.tar.gz
* Updated the `sed` command to simplify and generalize the substitution of `github.com` URLs with `dl.espressif.cn/github_assets` by removing the hardcoded `espressif` path segment. This change applies to both development and release package JSON files. …
=> fix(release): Replace all assets with chinese mirrors

cores/esp32/esp32-hal-tinyusb.c
Solves issue #11245 through the [workaround suggested by nitz](https://github.com/espressif/arduino-esp32/issues/11245#issuecomment-2842952196).
I have tested the proposed changes with a [senseBox MCU ESP32S2](https://github.com/espressif/arduino-esp32/tree/master/variants/sensebox_mcu_esp32s2) and another microcontroller with an ESP32S3 with the following script:
```cpp
void setup() {
}
void loop() {
Serial.println("hello");
delay(500);
}
```
Closes #11245.
=> remove weak function declaration of tud_msc_is_writable_cb to fix simultaneous CDC and MSC

cores/esp32/esp32-hal-spi.h, libraries/SPI/src/SPI.cpp, libraries/SPI/src/SPI.h
This pull request is modifying the `SPIClass::begin` method to return a `bool` for better error handling. These updates enhance compatibility with newer ESP32 variants and provide clearer feedback on initialization success.
Closes #8192
=> feat(spi): Add return values to SPI begin + comments on SPI buses

libraries/OpenThread/src/OThread.cpp
5. [X] Please **confirm option to "Allow edits and access to secrets by maintainers"** when opening a Pull Request
-----------
Add RLOC16 in …
=> feat(openthread): Add RLOC16 in otPrintNetworkInformation()

docs/en/guides/core_compatibility.rst
https://docs.espressif.com/projects/arduino-esp32/en/latest/guides/core_compatibility.html
*This entire section above can …
=> fix(docs): correct code block indentation in core_compatibility.rst

.github/scripts/package_esptool.sh, package/package_esp32_index.template.json, platform.txt
Backport of https://github.com/espressif/arduino-esp32/commit/89ff4653286206be29fe49e3c333f14065801616 for v3.2.x
Closes #11482
=> feat(esptool): Upgrade to esptool v5

libraries/DNSServer/library.properties, libraries/DNSServer/src/DNSServer.cpp, libraries/DNSServer/src/DNSServer.h
The code solves two bugs:
- BUG 1: When trouble shooting a dnsserver with the 'dig' (one of the main DNS troubleshooting tools) the server doesn't answer because it doesn't handle EDNS (OPT records in the additional section).
That has been fixed, the additional section in the query can safely be ignored.
(mostly change around line 123)
- BUG 2: The code also returns an A record when the QUERY Type not 'A' (or 'ANY').
This has been fixed too. For an A and ANY query type the server returns an A record.
(mostly change around line 114)
The code continues to return a 'SERVFAIL' when no match with QNAME occurs. However, with the fix of bug 2 we created a proper 'No Data' response, (RFC2308 2.2) for queries that have a match for the name, but not for the type. The function …
=> Proper EDNS handling and cleaner NOERROR response in DNSSERVER

cores/esp32/esp32-hal-uart.c
IDF 5.4.1 has added a new function called uart_release_pin() that is called whenever new pins are set or when uart driver is deleted.
This has a side effect that causes RX pin to never work again with the loopback function. Other changes also have removed some GPIO setup that was necessary for the GPIO loopback mode work.
This PR forces a full RX Pin setup in order to make it work in GPIO Matrix with Loopback TX Signal
CI Only
CI error
=> feat(uart): fixes loopback function after IDF changes

cores/esp32/esp32-hal-uart.c
This PR fixes the effect of the IDF 5.4  commit https://github.com/espressif/esp-idf/commit/60f5828a4a790d4481aaf7c69eac72e3af1079fe that breaks any Arduino sketch that fails reading UART
Nothing is printed into Serial Monitor, event when data is sent.
Sketch
``` cpp
void setup() {
Serial.begin(115200); // using UART0 - open Serial Monitor to send data to Serial
}
void loop() {
// just echo back what is sent to Serial
if (Serial.available()) {
Serial.write((char) Serial.read());
}
}
```
Tested using CI and UART test Cases.
Closes #11498
=> feat(uart): fixes pin attach for any IDF 5.x

cores/esp32/esp32-hal-uart.c
IDF 5.5 has deprecated `gpio_iomux_in()` and `gpio_iomux_ou()` functions.
Therefore it is necessary to update the UART `_uartTrySetIomuxPin()` function to follow the new API.
CI Only
None - Internal.
=> fix(uart): idf 5.5 new gpio_iomux_* functions

docs/conf_common.py, docs/en/contributing.rst, docs/en/esp-idf_component.rst, docs/en/guides/docs_contributing.rst, docs/en/index.rst, docs/en/lib_builder.rst, docs/requirements.txt
This pull request introduces several updates to the documentation system, focusing on adding variable substitution support, improving documentation processes, and updating dependency requirements. The most significant changes include enabling dynamic version substitution in documentation, updating links for better compatibility, and enhancing contributor guidance.
* Added `rst_prolog` in `docs/conf_common.py` to enable variable substitution for `|version|` and `|idf_version|` throughout the documentation. This allows dynamic updates of version information.
* Included the `sphinx_substitution_extensions` extension in `docs/conf_common.py` to support the new substitution functionality. This extension allows for more flexibility when compared to the default Sphinx substitution (for example …
=> fix(docs): Fix links and versions

libraries/ESP_NOW/examples/ESP_NOW_Broadcast_Master/ESP_NOW_Broadcast_Master.ino, libraries/ESP_NOW/examples/ESP_NOW_Broadcast_Slave/ESP_NOW_Broadcast_Slave.ino, libraries/ESP_NOW/examples/ESP_NOW_Network/ESP_NOW_Network.ino, libraries/ESP_NOW/examples/ESP_NOW_Serial/ESP_NOW_Serial.ino, libraries/ESP_NOW/src/ESP32_NOW.cpp, libraries/ESP_NOW/src/ESP32_NOW.h, libraries/ESP_NOW/src/ESP32_NOW_Serial.cpp
Add support for ESP-NOW v2.0 data sizes.
Tested locally
Closes [#11261](https://github.com/espressif/arduino-esp32/issues/11261)
=> feat(esp_now): Add support for ESP NOW V2

cores/esp32/WString.cpp
If oldLen is truncated to uint16_t, appending to a String that is longer than 65535 bytes will create a broken String.
=> Fix appending to Strings longer than 64k

tools/pioarduino-build.py
by doing this it is possible to use custom bootloader which does not fit in the fixed (too small) partition.
Fixes question https://community.platformio.org/t/modify-esp32s3-partition-table-offset-in-a-simple-way-using-framework-arduino/47909
=> pioarduino only: make adresses for partitions.bin and boot_app0.bin configureable

libraries/HTTPUpdateServer/src/HTTPUpdateServer.h, libraries/Update/examples/OTAWebUpdater/OTAWebUpdater.ino, libraries/WebServer/examples/WebUpdate/WebUpdate.ino
Closes: https://github.com/espressif/arduino-esp32/security/advisories/GHSA-9vfw-wx65-c872
=> fix(csrf): Fix SCRF vulnerability in OTA examples and libraries

libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp
The Zigbee standard requires color saturation in the range of 0-254, but `espRgbColorToHsvColor` returns saturations in the range of 0-255. As referenced in #11527 when a full saturation color is set, the following error is received:
```
[  6303][E][ZigbeeColorDimmableLight.cpp:180] setLight(): Failed to set light saturation: 0x87: Invalid value
```
This PR clamps the range of the saturation used in `setLight()` to 0-254 (reducing it to 254 from 255 when full saturation is set), eliminating the "Invalid value" error.
I have tested this change on my XIAO ESP32-C6 
Fixes #11527
=> Update ZigbeeColorDimmableLight to clamp color hue and saturation to 0-254 (Fixes #11527)

package/package_esp32_index.template.json
```
lib-builder: release/v5.5 3cfe5d3
esp-idf: release/v5.5 adb3f2a580
arduino: release/v3.3.x ff3cc813f
tinyusb: master 963971c6a
espressif__eppp_link: 0.3.1
espressif__esp-dsp: 1.7.0
espressif__esp-modbus: 1.0.18
espressif__esp-nn: 1.1.1
espressif__esp-tflite-micro: 1.3.3~1
espressif__esp_hosted: 2.0.13
espressif__esp_modem: 1.4.0
espressif__esp_serial_slave_link: 1.1.0~1
espressif__esp_wifi_remote: 0.13.0
espressif__libsodium: 1.0.20~2
espressif__mdns: 1.8.2
espressif__network_provisioning: 1.0.2
joltwallet__littlefs: 1.20.1
espressif__esp-serial-flasher: 0.0.11
espressif__esp-zboss-lib: 1.6.4
espressif__esp-zigbee-lib: 1.6.5
espressif__esp32-camera:
espressif__esp_delta_ota: 1.1.2
espressif__esp_diag_data_store: 1.0.2 …
```
=> IDF release/v5.5

cores/esp32/esp32-hal-spi.c
This pull request updates the SPI handling for the ESP32P4 target in the `cores/esp32/esp32-hal-spi.c` file. It introduces new logic for enabling and resetting SPI bus clocks specific to ESP32P4 and removes legacy handling for unsupported configurations.
Tested using ESP32-P4 and SD card example. Tested both FSPI and HSPI.
Closes #11398
=> fix(spi): Fix bus clock for ESP32-P4 + remove S2 leftover

boards.txt, variants/rakwireless_rak3112/pins_arduino.h
fix : quad_psram: psram id read error: 0x00ffffff, psram chip not found or not supported, or wrong psram line mode arduino
Configuration updates for `rakwireless_rak3112`:
* Added a new `psram_type` property with the value `opi` to specify the type of PSRAM used.
* Introduced a `memory_type` property that dynamically combines `build.boot` and `build.psram_type` for better memory type management.
* Updated the `menu.PSRAM.enabled` description to "OPI PSRAM" for clarity.
* Add wisblock pin define
=> fix(board): Update PSRAM configuration for RAK3112 to fix PSRAM error

tools/pioarduino-build.py
esptool v5.0.0 needs to be called as esptool not anymore as esptool.py. This PR prepares this change for pioarduino.
PR needs to be merged just before https://github.com/pioarduino/platform-espressif32/pull/209 can be merged.
No changes for ArduinoIDE, the change has only impact for pioarduino
@me-no-dev
=> pioarduino only: fix deprecated warnings caused from esptool v5.0.0

CMakeLists.txt, libraries/Zigbee/examples/Zigbee_Fan_Control/README.md, libraries/Zigbee/examples/Zigbee_Fan_Control/Zigbee_Fan_Control.ino, libraries/Zigbee/examples/Zigbee_Fan_Control/ci.json, libraries/Zigbee/keywords.txt, libraries/Zigbee/src/Zigbee.h, libraries/Zigbee/src/ep/ZigbeeFanControl.cpp, libraries/Zigbee/src/ep/ZigbeeFanControl.h
This pull request introduces a new Zigbee Fan control endpoint + minor updates to keywords.txt.
Tested using HomeAssistant ZHA and ESP32C6 flashed with the new example.
=> feat(zigbee): Add Fan Control endpoint support

.github/workflows/dangerjs.yml
This pull request introduces a minor update to the DangerJS workflow configuration. The change adds a new rule to disable enforcement of `master` as the target branch (as not all PRs target master).
* [`.github/workflows/dangerjs.yml`](diffhunk://#diff-e878c7efb136c2bdcc5ffdc181348b2597cb408c5f8349f67355b8c47b442521R27): Added `rule-target-branch: "false"` to the DangerJS workflow configuration to disable the target branch rule.
=> fix(dangerjs): Disable target branch rule

tools/pioarduino-build.py
since it fixes a lot of issues. related pioarduino PR https://github.com/pioarduino/platform-espressif32/pull/212
@me-no-dev please, by merging i can keep the pioarduino build script code base the same.
=> Backport: pioarduino only change for esptool v5.0.0 support

libraries/ESP32/examples/GPIO/FunctionalInterruptLambda/FunctionalInterruptLambda.ino, libraries/ESP32/examples/GPIO/FunctionalInterruptLambda/README.md
This pull request introduces a comprehensive example for using lambda functions with `FunctionalInterrupt` in ESP32 GPIO interrupt handling. It includes both code and documentation updates to demonstrate advanced debouncing techniques, edge detection, and best practices for interrupt-safe lambda functions.
* Added a complete example in `FunctionalInterruptLambda.ino` showcasing two interrupt handling patterns:
- **CHANGE mode lambda** for dual-edge detection with state-based debouncing and object method integration.
- **FALLING mode lambda** with pointer captures, LED control, and hardware debouncing.
* Created a detailed `README.md` explaining:
- The hardware setup and interrupt behavior on ESP32.
- Lambda function patterns, debouncing strategies, and best practices for safe ISR …
=> feat(gpio): new functional interrupt lambda example

.github/workflows/push.yml, cores/esp32/esp32-hal-uart.c, libraries/ESP_NOW/src/ESP32_NOW.cpp, libraries/Network/src/NetworkClient.cpp, libraries/WiFi/examples/WiFiScan/WiFiScan.ino, libraries/WiFi/src/AP.cpp, libraries/WiFi/src/WiFiAP.h, libraries/WiFi/src/WiFiGeneric.cpp, libraries/WiFi/src/WiFiGeneric.h
Fix https://github.com/espressif/arduino-esp32/pull/10884#discussion_r2215402096
The code doesn't compile with IDF 5.3
CI
https://github.com/espressif/arduino-esp32/pull/10884#discussion_r2215402096
=> fix(build): make core compatible with IDF 5.3

libraries/Zigbee/src/ZigbeeCore.cpp
Replace `ESP_ERROR_CHECK` with proper error handling to prevent system crashes when `esp_zb_bdb_start_top_level_commissioning()` returns `ESP_FAIL` due to invalid commissioning state (can be in progress). This allows the existing retry mechanism to continue working while providing better error logging instead of assertion failures.
Same way its now done in esp-zigbee-sdk examples:
```cpp
static void bdb_start_top_level_commissioning_cb(uint8_t mode_mask)
{
ESP_RETURN_ON_FALSE(esp_zb_bdb_start_top_level_commissioning(mode_mask) == ESP_OK, , TAG, "Failed to start Zigbee commissioning");
}
```
Tested using some Zigbee example with rebooting many times.
Closes #11554
=> fix(zigbee): Replace assert with error log to solve immediate crash

docs/en/zigbee/ep_fan_control.rst, docs/en/zigbee/zigbee_core.rst, docs/en/zigbee/zigbee_ep.rst
This pull request adds documentation updates to the Zigbee library, including a new `ZigbeeFanControl` class and enhanced callback functionality for default response handling.
=> feat(docs): Updaze Zigbee docs with latest changes

cores/esp32/ColorFormat.c, cores/esp32/ColorFormat.h, libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp
This pull request introduces changes to improve color conversion functionality and refactors related code for clarity and flexibility. The most significant updates include adding an optional scaling parameter to the `espXYToRgbColor` function, modifying its usage across the codebase, and updating the header file to reflect these changes.
Before:
RED color on max level (100%) - RGB(68,0,0)
After fix:
RED color on max level (100%) - RGB(255,0,0)
Tested using ColorDimmableLight example
Closes #11619
=> fix(zigbee): Fix RGB color calculation

.github/ISSUE_TEMPLATE/config.yml
Revomed the issue template since it was redundant. As it was agreed with the team to remove it.
=> feat(github): remove ESP32 forum from issue template

.github/ISSUE_TEMPLATE/Issue-report.yml
To include and make the "Type" of the issue mandatory.
This way the users would need to select the type of the issue. This will allow the bot to perform more accurately in managing the backlog as well as the engineers. 
This change was discussed with the team and agreed.
=> feat(github): Update template type

idf_component.yml
New version of `esp-zigbee-sdk` 1.6.6 got released today. This PR updates the version in `idf_component.yml` so it will be picked for next libs build. This version brings the Binary and Multistate support and more.
Related #11609 
Related #11560
=> feat(zigbee): Update ESP-ZIGBEE-SDK to 1.6.6

.github/ISSUE_TEMPLATE/Issue-report.yml
There was a wrong indentation in the previous change that caused discrepancy.  
Here is the updated correct code.
=> fix(github-template): indentation

boards.txt, variants/XIAO_ESP32C5/pins_arduino.h
feat(esp32): Added a new device from Seeed: Xiao ESP32C5)
=> feat(esp32): Added a new device(xiao esp32c5)

variants/lilygo_t3_s3_sx127x/pins_arduino.h
There were two definitions of LORA_BUSY generating a lot of unneccessary warnings.
-----------
The file contains two definitions of LORA_BUSY - one as 33, and the other as ```
#define LORA_BUSY LORA_DIO1
``` 
Where DIO1 is also defined as 33.  
This causes lots of un-useful warning messages from the duplicated definition. 
Tested on my Lilygo T3 S3, with this change 
Not applicable -  no issue posted.
=> variant lilyho_t3_s3_sx127x duplicates LORA_BUSY - deleting one of them

variants/m5stack_atoms3/pins_arduino.h
-----------
Setting the proper RGB led pin in the …
=> fix(esp32:m5stack_atoms3) : Update pins_arduino.h of variant m5stack_atoms3 with correct LED_BUILTIN value matching GPIO #35

libraries/ESP_NOW/library.properties
Change category of ESP_NOW from "Sensor", which is not a valid category, to "Communication", since ESP_NOW enables communications.
here are the valid categories
+ Display
+ Communication
+ Signal Input/Output
+ Sensors
+ Device Control
+ Timing
+ Data Storage
+ Data Processing
+ Other
In the arduino app, to use a category,
1.  Sketch
2. Include Library
3. Manage Libraries
4. Topic dropdown menu
5. select a category
see here for valid categories at the time of this commit
https://github.com/arduino/arduino-cli/blob/b6ddb5ad8397309b1c37745344b455406f085d0d/internal/arduino/libraries/libraries.go#L38
=> fix: Use correct category for ESP_NOW

idf_component.yml
This pull request updates the Zigbee-related dependencies to newer versions for improved compatibility. The changes ensure that `esp-zboss-lib` and `esp-zigbee-lib` are aligned with their latest compatible releases.
Dependency updates:
* Updated `esp-zboss-lib` version requirement to be compatible with `esp-zigbee-lib` 1.6.7 in `idf_component.yml`.
* Updated `esp-zigbee-lib` version from 1.6.6 to 1.6.7 in `idf_component.yml`.
Will be tested with new libs when build.
=> feat(zigbee): Update esp-zigbee-lib to 1.6.7

.github/scripts/sketch_utils.sh, docs/en/contributing.rst
This pull request enhances the automation for building Arduino sketches by introducing support for installing required libraries specified in a `ci.json` file. It adds a new `install_libs` function to the build scripts, ensures libraries are installed before building sketches, and updates the documentation to describe this new feature.
I have tested multiple scenarios of library installations from `ci.json` files on various ESP32 boards in CI.
Link to my GitHub Actions workflow: [link](https://github.com/JakubAndrysek/arduino-esp32/actions/runs/17262216498/job/48986151555?pr=6)
=> Add function to handle library installation from ci.json

idf_component.yml, libraries/ESP_SR/src/ESP_SR.cpp, libraries/ESP_SR/src/ESP_SR.h, libraries/ESP_SR/src/esp32-hal-sr.c, libraries/ESP_SR/src/esp32-hal-sr.h
This pull request updates the ESP Speech Recognition (`ESP_SR`) component to support the ESP32P4 target and upgrades the underlying `esp-sr` dependency version. The main changes ensure that speech recognition features are now available for both ESP32S3 and ESP32P4 platforms when WakeNet or MultiNet are enabled.
**Platform and Dependency Updates:**
* Updated the `espressif/esp-sr` dependency version from `^1.4.2` to `^2.1.5` in `idf_component.yml`, and expanded its rules to include the ESP32P4 target.
**Platform Support Expansion:**
* Modified preprocessor conditionals in `ESP_SR.cpp`, `ESP_SR.h`, `esp32-hal-sr.c`, and `esp32-hal-sr.h` to include both `CONFIG_IDF_TARGET_ESP32S3` and `CONFIG_IDF_TARGET_ESP32P4`, enabling speech recognition features for ESP32P4. …
=> feat(sr): Update ESP-SR to 2.x and enable it for ESP32-P4

.github/workflows/pre-commit.yml, .pre-commit-config.yaml
This pull request improves tracking of pending pre-commit fixes by adding and removing tags when manual fixes are required.
Tested in fork: https://github.com/lucasssvaz/arduino-esp32/pull/53
=> ci(pre-commit): Add label if manual fixes are required

libraries/Zigbee/src/ZigbeeCore.cpp
Improvements to scan management and thread safety:
* Added a check to prevent initiating a new scan if one is already in progress, logging a warning and returning early in `ZigbeeCore::scanNetworks` (`ZigbeeCore.cpp`).
* Wrapped the scan request call with `esp_zb_lock_acquire` and `esp_zb_lock_release` to ensure thread safety when starting a Zigbee network scan (`ZigbeeCore.cpp`).
Tested using the ScanNetworks example.
Closes #10879
=> fix(zigbee): Add lock in scanNetworks to avoid race condition

cores/esp32/esp32-hal-misc.c
@me-no-dev 
to fix error in pioarduino compile when `lib_ignore = BLE` is used. Furthermore this aligns with check in line 28.
No functional change in Arduino code.
The setting `lib_ignore` can be used to speed up build compile times, since only libs which are really used are compiled
and all not needed include paths are removed (helps Windows users, with path length limit)
RMT Blink Example with `lib_ignore` set for BLE and Wifi (manually added this patch)
```
Converting RMTWriteNeoPixel.ino
[ComponentManager] Ignored library: esp_wifi (4 entries)
[ComponentManager] Ignored library: bt (37 entries)
[ComponentManager] Updated build file (41 total removals)
[ComponentManager] Processed 2 ignored libraries
[ComponentManager] Session completed with 4 changes
LDF: Library Dependency Finder -> …
```
=> Add header check for esp_bt.h in esp32-hal-misc.c

.github/workflows/pre-commit-status.yml, .github/workflows/pre-commit.yml
This PR aims to fix the pre-commit tagging to work in forks by executing the tagging in a workflow with higher permissions.
Tested in fork
=> fix(pre-commit): Make tagging work for forks

.flake8, .github/pytools/Sign-File.ps1, .github/scripts/get_affected.py, .github/scripts/merge_packages.py, libraries/ArduinoOTA/examples/BasicOTA/BasicOTA.ino, libraries/ArduinoOTA/src/ArduinoOTA.cpp, libraries/ArduinoOTA/src/ArduinoOTA.h, libraries/WiFi/examples/WiFiUDPClient/udp_server.py, tools/espota.py, tools/get.py
This pull request fixes issues reported by CodeQL. Mostly files which are not closed if an exception occurs.
Requires #11676
=> fix(python): Fixes for Python code scanning alerts

cores/esp32/WString.cpp
Function `float String::toFloat(void) const` returns a `double`.
This causes the warning:
`warning: conversion from 'double' to 'float' may change value [-Wfloat-conversion]`
when compiled with option `-Wfloat-conversion`
Statically cast return value to `float`.
Code compiles without warning when change made.
None
=> fix(esp32): float conversion warning in String::toFloat

boards.txt, variants/m5stack_tab5/pins_arduino.h
-----------
Add variant for [M5Tab5](https://docs.m5stack.com/en/core/Tab5)
I have tested my Pull Request on Arduino-esp32 core with M5Tab5 (ESP32-P4).
Closes #11831
=> feat(variants): Add variant for M5Tab5

libraries/WiFi/src/WiFiScan.cpp
If WiFi has been started via Arduino API, but the WiFi scan is started via IDF API, `WiFiScanClass::_scanDone` is still called from 
the event callback and reads out the scan result.
Arduino-esp32 core v 3.2.1, ESP32-C3
=> Fix (WiFi): Do not steal scan results

cores/esp32/esp32-hal-i2c-slave.c
In function `i2c_slave_gpio_mode` an inner loop variable `a` shadows an outer loop variable `a`.
This causes the warning:
`warning: declaration of 'a' shadows a previous local [-Wshadow]`
when compiled with option`-Wshadow`.
Renamed variable `a` in inner loop to `b`.
Code compiles without warning when change made.
None
=> fix(esp32): Compiler warning - loop variable `a` shadows previous instance of `a` in function `i2c_slave_gpio_mode`

idf_component.yml, libraries/Ethernet/src/ETH.cpp, libraries/Ethernet/src/ETH.h
This pull request adds support for the LAN867x Ethernet PHY to the ESP32 platform. The changes include updating dependencies, conditionally enabling code for the new PHY, and integrating it into the Ethernet library's initialization and configuration logic.
**LAN867x PHY Support Integration:**
* Added `espressif/lan867x` as a dependency in `idf_component.yml`, limited to ESP32 and ESP32P4 targets.
* Defined `ETH_PHY_LAN867X_SUPPORTED` macro in `ETH.h` when `esp_eth_phy_lan867x.h` is available, enabling conditional compilation for LAN867x support.
* Added `ETH_PHY_LAN867X` to the `eth_phy_type_t` enum, making it selectable as a PHY type.
* Included `esp_eth_phy_lan867x.h` and added case handling for `ETH_PHY_LAN867X` in the Ethernet initialization logic, allowing the library to instantiate …
=> feat(eth): Add support for LAN867X ETH PHY

boards.txt, variants/mant1s/pins_arduino.h
Add new board Silicognition ManT1S: https://www.crowdsupply.com/silicognition/mant1s
- Add board configuration to `boards.txt`.
- Add pin definitions and T1S Ethernet config  to `variants/mant1s`.
This requires LAN867x support so depends on #11843, which is not in any release.  So it was tested on `master` on a prototype ManT1S rev 4.  Works as expected with unmodified ETH_LAN8720 example, since `pins_arduino.h` defines `ETH_PHY_MDC` correctly for the ManT1S the config block on top of the example is ignored and uses the correct Ethernet definitions from `pins_arduino.h` instead.
Depends on #11843 and library built with the LAN867x supports this adds.
=> feat(board): add support for Silicognition ManT1S

.github/scripts/update-version.sh
This pull request updates the version management script to ensure the issue template reflects the latest Arduino version. The main change is an automated update to the version listed in the issue report template, helping users report issues against the correct version.
Updates to issue template automation:
* [`.github/scripts/update-version.sh`](diffhunk://#diff-7c948b013f7ac77e61b6d313b97808fa90203751180f55e9e372e792aee386d7R37-R40): Added a step to automatically update the Arduino version in `.github/ISSUE_TEMPLATE/issue-report.yml` using `sed`, ensuring the template always references the latest version.
=> change(script): Update the issue template when version changed

tools/espota.py
This pull request updates the `espota.py` tool to add support for authenticating with devices that use an older, insecure MD5-based challenge/response protocol, improving compatibility with legacy firmware. The main changes include introducing a new `--md5-target` option, updating the authentication flow to handle both MD5 and SHA256 mechanisms, and adjusting the argument parsing and function signatures accordingly.
It will first try with SHA authentication and if it fails it will try again with MD5 for backwards compatibility.
**Authentication protocol updates:**
* Added a new `--md5-target` (`-m`) command-line flag to indicate that the target device uses MD5-based authentication, for compatibility with old firmware.
* Modified the `serve` function and its call sites to accept an …
=> fix(ota): Add legacy option for devices using MD5 authentication

boards.txt
This removes the unused menu for flash size in 4D Systems MIPI LCDs. Products will release with 32MB flash only.
Tested by modifying v3.3.1
N/A
=> fix(menu): remove unused flash size option for 4D Systems MIPI LCDs

boards.txt
This pull request addresses a missing board definition for the Twin AIoT module in the boards.txt file, resolving a critical upload error. This change is to solve the error we received in the twinaiot module that we added in the [previous PR](https://github.com/espressif/arduino-esp32/pull/11755). 
**Problem Description**
When attempting to upload a sketch to the Twin AIoT board, the build and upload process failed due to a missing line in the board's configuration file. The specific error message received was:
No such command '{upload.flags}'
This error was caused by the absence of the upload.flags and upload.extra_flags parameters in the Twin AIoT Module definition. The Arduino IDE's build system, which uses the platform.txt template, was unable to correctly format the esptool.py …
=> fix: Add upload flags to boards.txt for Twin AIoT Module to resolve upload error

boards.txt
This is a simple typo fix for the FoBE Quill ESP32S3 Mesh in boards.txt. There were two identical "fobe_quill_esp32s3_mesh.vid.1" entries and the second one was obviously meant to be called "pid", not "vid".
Because of this typo in boards.txt Arduino IDE v1.8.19 was failing to detect any COM port.
I'm using Arduino IDE v1.8.19 on Windows 10. I updated ESP32 Core from v3.3.0 to v3.3.1 via the board manager. After restaring Arduino IDE it was no longer detecting any COM ports. Tools -> Port option was greyed out even though a board was connected and was detected by windows device manager. The board itself doesn't matter, the problem isn't even ESP32-related, the IDE just fails to detect any board. I tried launching the arduino_debug.exe and it showed the following error in the terminal:
``` …
```
=> fix(board): Fix pid parameter for FoBE Quill ESP32S3 Mesh in boards.txt

cores/esp32/esp32-hal-gpio.c, cores/esp32/esp32-hal-touch-ng.c, cores/esp32/esp32-hal-touch.c
This pull request adds the display of the pin number when an incorrect pin is specified and removes duplicated log lines across multiple functions.  
These changes improve debugging clarity.
Previously, functions like touchRead() would log "No touch pad on selected pin!" when an invalid pin was specified, but the log did not include the actual pin number.
This made it harder to identify which pin caused the issue during debugging.
* Removed duplicated log_e("No touch pad on selected pin!") calls from multiple functions.
* Centralized the error log inside digitalPinToTouchChannel().
* Extended the error message to include the pin number for better debugging context.
* Added log_e() in digitalPinToTouchChannel() when no touch sensor is available on the chip.
This change has been tested on …
=> Refactor touch pad error logging
